import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";
import ShareBar from "@/components/ShareBar";

export const metadata: Metadata = {
  title: "Gerador de Placa Mercosul para Testes: Algoritmo e Validação",
  description: "Aprenda a gerar e validar placas no formato Mercosul (LLLNLNN) para testes de software — código TypeScript, regex, integração com Jest e export SQL prontos para uso.",
  openGraph: {
    title: "Gerador de Placa Mercosul para Testes: Algoritmo e Validação",
    description: "Aprenda a gerar e validar placas no formato Mercosul (LLLNLNN) para testes de software — código TypeScript, regex, integração com Jest e export SQL prontos para uso.",
    type: "article",
    images: ["/api/og?title=Gerador%20de%20Placa%20Mercosul%20para%20Testes%3A%20Algoritmo%20e%20Valida%C3%A7%C3%A3o&subtitle=Aprenda%20a%20gerar%20e%20validar%20placas%20no%20formato%20Mercosul%20(LLLNLNN)%20para%20testes%20de%20software%20%E2%80%94%20c%C3%B3digo%20TypeScript%2C%20regex%2C%20integra%C3%A7%C3%A3o%20com%20Jest%20e%20exp&category=TUTORIAIS"],
  },
  alternates: { canonical: "/blog/gerador-placa-mercosul-teste-software" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Gerador de Placa Mercosul para Testes: Algoritmo e Validação" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Gerador de Placa Mercosul para Testes: Algoritmo e Validação
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>04 de maio de 2026</time>
            <span>·</span>
            <span>11 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">Placas Mercosul seguem um padrão determinístico introduzido no Brasil em 2018. Isso significa que gerar placas válidas para testes não é difícil — mas gerar placas que passem por todos os validadores de um sistema real exige conhecer as restrições exatas do Denatran.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O formato Mercosul tem estrutura determinística — e isso facilita a geração</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Padrão ABC1D23: três letras, um dígito, uma letra, dois dígitos</h3>
          <p className="mb-4">O padrão Mercosul para carros de passeio segue <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[A-Z]&#123;3&#125;[0-9][A-Z][0-9]&#123;2&#125;</code>, sete caracteres sem hífen. A posição 5 (índice 4) é o diferenciador entre o formato antigo e o novo: se for letra, é Mercosul. Se for dígito, é placa antiga.</p>
          <p className="mb-4">Exemplos válidos: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">BRA2E19</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ABC1D23</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">XYZ9K00</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Motos seguem variante ABC1D2 (seis caracteres)</h3>
          <p className="mb-4">Motos têm apenas seis caracteres: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[A-Z]&#123;3&#125;[0-9][A-Z][0-9]</code>. A lógica de geração é idêntica, com o bloco numérico final tendo apenas um dígito em vez de dois.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que o Denatran excluiu certas letras (I, O, Q) do bloco alfabético</h3>
          <p className="mb-4">O Denatran excluiu <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">I</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">O</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Q</code> dos blocos alfabéticos para evitar confusão visual com os dígitos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">1</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0/Q</code> em fontes condensadas. Essa exclusão se aplica tanto às três primeiras letras quanto à letra na posição 5. O alfabeto efetivo tem 23 letras.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Restrições reais que o algoritmo precisa respeitar</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Sequências proibidas: palavras obscenas e siglas de órgãos públicos (Resolução Contran nº 752/2018)</h3>
          <p className="mb-4">A Resolução Contran nº 752/2018 define que o Denatran mantém uma lista interna de combinações proibidas. Não há publicação oficial completa da lista, mas o princípio é claro: o bloco inicial de três letras não pode formar palavras de baixo calão ou siglas sensíveis. Para um gerador de testes, basta uma blocklist mínima:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"const BLOCKED_PREFIXES = new Set([\n  'SSP', 'PRF', 'DPF', 'PGR', 'STF', 'STJ', 'CNJ',\n]);"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O segundo bloco tem exatamente um caractere alfabético na posição 5</h3>
          <p className="mb-4">Essa é a restrição que define o formato Mercosul. O regex completo do segundo bloco é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[0-9][A-HJ-NPR-Z][0-9]&#123;1,2&#125;</code>. A classe <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[A-HJ-NPR-Z]</code> já exclui <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">I</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">O</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Q</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferença entre geração aleatória e geração progressiva (como o Detran sequencia)</h3>
          <p className="mb-4">O Detran emite placas sequencialmente por UF. Para testes, geração aleatória é suficiente e mais simples. Geração progressiva só faz sentido se o sistema testado valida sequências ou prefixos regionais específicos.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Implementação do gerador em TypeScript</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">generateMercosulPlate()</code> pura e sem dependências externas</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"const ALPHA = 'ABCDEFGHJKLMNPRSTUVWXYZ'; // 23 letras, sem I, O, Q\nconst DIGITS = '0123456789';\n\nfunction randomChar(str: string): string {\n  return str[Math.floor(Math.random() * str.length)];\n}\n\nconst BLOCKED_PREFIXES = new Set([\n  'SSP', 'PRF', 'DPF', 'PGR', 'STF', 'STJ', 'CNJ',\n]);\n\nexport function generateMercosulPlate(\n  options: { format?: 'car' | 'moto' } = {}\n): string {\n  const { format = 'car' } = options;\n\n  let prefix: string;\n  do {\n    prefix = randomChar(ALPHA) + randomChar(ALPHA) + randomChar(ALPHA);\n  } while (BLOCKED_PREFIXES.has(prefix));\n\n  const digit1  = randomChar(DIGITS);\n  const letter  = randomChar(ALPHA);\n  const suffix  = format === 'moto'\n    ? randomChar(DIGITS)\n    : randomChar(DIGITS) + randomChar(DIGITS);\n\n  return `${prefix}${digit1}${letter}${suffix}`;\n}\n\nexport function formatPlate(plate: string, hyphen = false): string {\n  if (!hyphen) return plate;\n  return `${plate.slice(0, 3)}-${plate.slice(3)}`;\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Gerando o bloco alfabético inicial com exclusão de I, O, Q</h3>
          <p className="mb-4">A constante <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ALPHA</code> com 23 letras resolve isso diretamente. O loop <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">do...while</code> descarta prefixos bloqueados antes de retornar — na prática, o loop raramente itera mais de uma vez, dado o espaço de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">23³ = 12.167</code> combinações possíveis.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Gerando a parte numérica com posição 5 variável A–Z (exceto I, O, Q)</h3>
          <p className="mb-4">O mesmo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ALPHA</code> cobre a posição 5. Não há pesos ou distribuições específicas documentadas publicamente para essa posição, então distribuição uniforme é a abordagem correta para testes.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Validação via regex e função de checagem</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regex definitivo para placas Mercosul e antigas no mesmo validador</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Formato</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Regex</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Exemplo</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">Mercosul carro</td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">^[A-Z]&#123;3&#125;\d[A-HJ-NPR-Z]\d&#123;2&#125;$</code></td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">BRA2E19</code></td></tr><tr className="border-b border-border"><td className="px-3 py-2">Mercosul moto</td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">^[A-Z]&#123;3&#125;\d[A-HJ-NPR-Z]\d$</code></td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">BRA2E1</code></td></tr><tr className="border-b border-border"><td className="px-3 py-2">Placa antiga</td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">^[A-Z]&#123;3&#125;\d&#123;4&#125;$</code></td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ABC1234</code></td></tr></tbody></table></div>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validatePlate(plate: string)</code> com retorno tipado</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"type PlateFormat = 'mercosul' | 'antiga' | 'moto' | 'invalid';\n\nconst PATTERNS: Record<Exclude<PlateFormat, 'invalid'>, RegExp> = {\n  mercosul: /^[A-Z]{3}\\d[A-HJ-NPR-Z]\\d{2}$/,\n  moto:     /^[A-Z]{3}\\d[A-HJ-NPR-Z]\\d$/,\n  antiga:   /^[A-Z]{3}\\d{4}$/,\n};\n\nexport function validatePlate(\n  plate: string\n): { valid: boolean; format: PlateFormat } {\n  const normalized = plate.toUpperCase().replace(/[\\s-]/g, '');\n\n  for (const [format, regex] of Object.entries(PATTERNS)) {\n    if (regex.test(normalized)) {\n      return { valid: true, format: format as PlateFormat };\n    }\n  }\n  return { valid: false, format: 'invalid' };\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Casos de borda: placas com espaço, lowercase, hífen inconsistente</h3>
          <p className="mb-4">A normalização <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">toUpperCase().replace(/[\s-]/g, '')</code> cobre os três casos. Placas recebidas de formulários raramente chegam no formato canônico, e a função acima absorve todas as variações comuns.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Dados de veículo correlacionados para testes mais realistas</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Associar placa a UF de emplacamento (prefixo de três letras tem distribuição regional real)</h3>
          <p className="mb-4">O Denatran distribui faixas de prefixo por UF. A tabela abaixo é uma aproximação suficiente para testes:</p>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">UF</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Faixa de prefixo</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">SP</td><td className="px-3 py-2">AAA–AZZ</td></tr><tr className="border-b border-border"><td className="px-3 py-2">RJ</td><td className="px-3 py-2">BAA–BZZ</td></tr><tr className="border-b border-border"><td className="px-3 py-2">MG</td><td className="px-3 py-2">CAA–CZZ</td></tr><tr className="border-b border-border"><td className="px-3 py-2">RS</td><td className="px-3 py-2">DAA–DZZ</td></tr><tr className="border-b border-border"><td className="px-3 py-2">PR</td><td className="px-3 py-2">EAA–EZZ</td></tr></tbody></table></div>
          <p className="mb-4">Use um mapa de prefixo inicial por UF em vez de tentar replicar a tabela exata do Detran — para testes, correlação aproximada é suficiente.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Combinar com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">generatePerson()</code> para simular proprietário</h3>
          <p className="mb-4">Use o <Link href="/gerador-pessoa" className="text-primary hover:underline">gerador de pessoa</Link> do FakeForge para gerar nome, CPF e endereço do titular em um único objeto. O <Link href="/gerador-cep" className="text-primary hover:underline">gerador de CEP correlacionado com a UF</Link> torna o fixture ainda mais realista:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import { generateMercosulPlate, generateRenavam } from './plate';\nimport { generatePerson } from './person'; // FakeForge\n\nfunction createVehicleOwner() {\n  return {\n    plate:   generateMercosulPlate(),\n    renavam: generateRenavam(),\n    owner:   generatePerson(),\n  };\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Gerar RENAVAM fake com dígito verificador correto (mod 11)</h3>
          <p className="mb-4">O RENAVAM tem 11 dígitos. Os 10 primeiros são a base numérica; o último é o dígito verificador calculado por mod 11 com pesos específicos:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"export function generateRenavam(): string {\n  const base = Array.from({ length: 10 }, () =>\n    Math.floor(Math.random() * 10)\n  );\n\n  const weights = [3, 2, 9, 8, 7, 6, 5, 4, 3, 2];\n  const sum = base.reduce((acc, d, i) => acc + d * weights[i], 0);\n  const remainder = sum % 11;\n  const digit = remainder < 2 ? 0 : 11 - remainder;\n\n  return [...base, digit].join('');\n}"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Integração com frameworks de teste</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Factory com Vitest: criando fixtures de frota em massa</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import { describe, it, expect } from 'vitest';\nimport { generateMercosulPlate, validatePlate } from './plate';\nimport { generateRenavam } from './renavam';\n\nfunction createVehicleFixture(count: number) {\n  return Array.from({ length: count }, () => ({\n    plate:   generateMercosulPlate(),\n    renavam: generateRenavam(),\n  }));\n}\n\ndescribe('Vehicle fixtures', () => {\n  it('generates 100 valid Mercosul plates', () => {\n    const fleet = createVehicleFixture(100);\n    for (const { plate } of fleet) {\n      expect(validatePlate(plate).format).toBe('mercosul');\n    }\n  });\n});"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Usando a API REST do FakeForge como seed remoto em pipelines de CI</h3>
          <p className="mb-4">A <Link href="/docs" className="text-primary hover:underline">API REST do FakeForge</Link> suporta geração em lote via query params:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=placa&quantity=50&format=csv\""}</code></pre>
          <p className="mb-4">O <Link href="/pricing" className="text-primary hover:underline">plano Dev (R$29/mês)</Link> remove o limite de 100 chamadas/dia, adequado para pipelines que rodam a cada push.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Snapshot testing: por que fixar a semente do RNG evita falsos positivos</h3>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">DICA: Substitua <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Math.random</code> por um PRNG seedável (ex: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">seedrandom</code> via npm) nos testes de snapshot. Em produção, use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Math.random</code> normalmente. Isso garante que o mesmo seed sempre produz os mesmos fixtures, eliminando falsos positivos por aleatoriedade.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Cobertura de cenários negativos é obrigatória</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Placas antigas (ABC1234) que sistemas legados ainda aceitam</h3>
          <p className="mb-4">Sistemas de frota com mais de dez anos provavelmente têm registros no formato antigo. Gere placas antigas explicitamente para testar código legado:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function generateOldPlate(): string {\n  const prefix = Array.from({ length: 3 }, () => randomChar(ALPHA)).join('');\n  const nums   = Array.from({ length: 4 }, () => randomChar(DIGITS)).join('');\n  return `${prefix}${nums}`;\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Placas de coleção, diplomáticas e de teste (série ZZZ) — quando incluir</h3>
          <p className="mb-4">Placas diplomáticas (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">DDI-0001</code>), de coleção e da série ZZZ são casos especiais que a maioria dos sistemas rejeita. Inclua-as na suite de testes negativos, não nos fixtures de dados válidos.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Fuzzing: gerando strings inválidas intencionais para testar boundary conditions</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"const FUZZ_CASES = [\n  '',\n  'ABC',\n  'I00A111',    // I no bloco inicial — inválido\n  'ABC O123',   // espaço e O proibido\n  'ABC1D2',     // moto sem validação explícita de formato\n  '!!!1A23',\n];\n\nfor (const plate of FUZZ_CASES) {\n  const result = validatePlate(plate);\n  console.assert(result.format === 'invalid', `Esperado inválido: ${plate}`);\n}"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">LGPD e dados de veículo: o que é pessoal e o que não é</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Placa sozinha não identifica pessoa — mas placa + CPF + endereço forma dataset sensível (LGPD Art. 5º, I)</h3>
          <p className="mb-4">Uma placa isolada não é dado pessoal segundo a LGPD Art. 5º, I (Lei 13.709/2018 — <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">texto integral</a>). Ela não identifica nem torna identificável uma pessoa natural diretamente. A combinação placa + <Link href="/gerador-cpf" className="text-primary hover:underline">CPF</Link> + endereço + nome, no entanto, forma um conjunto identificador que se enquadra na definição de dado pessoal.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">AVISO: Bancos de dados de teste que combinam dados reais de veículos com dados reais de pessoas — mesmo obtidos de fontes públicas — constituem tratamento de dados pessoais sem base legal clara. Use dados sintéticos em todas as camadas do pipeline de testes.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Banco de dados de testes com dados reais de veículos: risco jurídico e alternativa segura</h3>
          <p className="mb-4">Usar dumps de sistemas reais em ambiente de teste expõe a empresa ao Art. 46 da LGPD (obrigação de adotar medidas de segurança adequadas). A alternativa é gerar fixtures sintéticos com correlações realistas. Combine <Link href="/gerador-pessoa" className="text-primary hover:underline">gerador de pessoa</Link> e <Link href="/gerador-cnpj" className="text-primary hover:underline">gerador de CNPJ</Link> para montar frotas de pessoa física e jurídica sem nenhum dado real.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferença entre dado anonimizado e dado pseudonimizado no contexto de frota (LGPD Art. 12)</h3>
          <p className="mb-4">O LGPD Art. 12 define dado anonimizado como aquele que não pode ser revertido por "meio técnico razoável e disponível". Dado pseudonimizado — ex: CPF substituído por UUID, mas mapeável internamente — ainda é dado pessoal. Dados gerados sinteticamente são anonimizados por construção, sem custo adicional de processo.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Performance ao gerar grandes volumes</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Geração de 10.000 placas únicas sem colisão: estratégia de Set vs. filtro probabilístico</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"export function generateUniquePlates(count: number): string[] {\n  const seen = new Set<string>();\n  while (seen.size < count) {\n    seen.add(generateMercosulPlate());\n  }\n  return [...seen];\n}"}</code></pre>
          <p className="mb-4">O espaço de placas Mercosul válidas é aproximadamente <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">23³ × 10 × 23 × 10² ≈ 280 milhões</code>. Com 10.000 placas, a probabilidade de colisão é desprezível. Um <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Set</code> simples é suficiente; filtro de Bloom só vale para volumes acima de 1 milhão.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Paralelismo com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Promise.all</code> e limites práticos de memória</h3>
          <p className="mb-4">Para volumes acima de 100.000, a geração síncrona em loop é mais eficiente do que <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Promise.all</code> — o overhead de microtask supera qualquer ganho de paralelismo em operações CPU-bound. Quebre em chunks e libere o event loop entre eles:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"async function generatePlatesInChunks(\n  total: number,\n  chunkSize = 10_000\n): Promise<string[]> {\n  const results: string[] = [];\n  for (let i = 0; i < total; i += chunkSize) {\n    const chunk = generateUniquePlates(Math.min(chunkSize, total - i));\n    results.push(...chunk);\n    await new Promise(r => setImmediate(r));\n  }\n  return results;\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Export em CSV e SQL com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE veiculo</code> pronto para carga</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"CREATE TABLE veiculo (\n  id         SERIAL PRIMARY KEY,\n  placa      CHAR(7)     NOT NULL,\n  renavam    CHAR(11)    NOT NULL,\n  uf         CHAR(2)     NOT NULL,\n  created_at TIMESTAMP   DEFAULT NOW()\n);\n\nINSERT INTO veiculo (placa, renavam, uf) VALUES\n  ('BRA2E19', '12345678901', 'SP'),\n  ('XYZ9K00', '98765432109', 'RJ');"}</code></pre>
          <p className="mb-4">O export SQL da <Link href="/docs" className="text-primary hover:underline">API REST do FakeForge</Link> gera o <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE</code> automaticamente com base no tipo solicitado.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Implemente <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">generateMercosulPlate()</code> com o alfabeto de 23 letras (sem <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">I</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">O</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Q</code>) e uma blocklist mínima de prefixos proibidos — o loop <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">do...while</code> descarta conflitos sem custo perceptível.</li><li>Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validatePlate()</code> com suporte a Mercosul, moto e formato antigo; normalize case e hífens antes de aplicar qualquer regex.</li><li>Gere RENAVAM com dígito verificador mod 11 para fixtures de sistema de frota que precisam passar por validadores de documento.</li><li>Combine placa com <Link href="/gerador-pessoa" className="text-primary hover:underline">gerador de pessoa</Link> e <Link href="/gerador-cep" className="text-primary hover:underline">CEP por UF</Link> para dados correlacionados que passam por validadores de negócio, não apenas de formato.</li><li>Nunca use dados reais de veículos em ambiente de teste — a combinação com CPF e endereço forma dataset sujeito à LGPD Art. 5º, I, independentemente da fonte dos dados.</li><li>Próximo passo: adicionar CRV fake com número de registro, data de expedição e órgão emissor para testes de sistemas de documentação de frota completa.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Como gerar placa com prefixo d" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como gerar placa com prefixo de UF específica sem hardcodear toda a tabela do Detran?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Mapeie UF à primeira letra do prefixo (SP→A, RJ→B, MG→C). Aleatorize as outras duas do ALPHA válido. Exemplo: `const p1 = ufMap[uf]; const p23 = randomChar(ALPHA) + randomChar(ALPHA); prefix = p1 + p23;` Não é sequencial como Detran real, mas passa validadores de correlação regional.</p>
            </details>
            <details key="RENAVAM usa o mesmo algoritmo " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">RENAVAM usa o mesmo algoritmo mod 11 do CPF?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não. RENAVAM usa 10 pesos (3,2,9,8,7,6,5,4,3,2); CPF usa dois módulos com 9 e 8 pesos. Cálculo final diverge: RENAVAM `remainder &lt; 2 ? 0 : 11 - remainder`, CPF sempre `11 - remainder`. Reutilizar código de CPF gera dígitos inválidos.</p>
            </details>
            <details key="Gerar 100 mil placas únicas co" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Gerar 100 mil placas únicas com Set causa garbage collection lag perceptível?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não. 100k placas em Set ~0.04% do espaço válido (280M); colisões são raras. GC lag é imperceptível. Acima de 500k, chunking com `setImmediate()` reduz picos de memória. Teste em seu ambiente se for gerar milhões.</p>
            </details>
            <details key="Meu validador legado rejeita p" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Meu validador legado rejeita placas Mercosul — devo gerar antigas em produção?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não force Mercosul em sistema que não suporta. Em testes, mantenha suites separadas: `testMercosulSupport()` usa `generateMercosulPlate()`, `testLegacyCompatibility()` usa `generateOldPlate()`. A migração do validador é responsabilidade da arquitetura, não do gerador.</p>
            </details>
            <details key="Qual blocklist mínima protege " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Qual blocklist mínima protege contra rejeição em APIs de seguro ou Detran?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">SSP, PRF, DPF, PGR, STF, STJ, CNJ cobrem siglas de órgãos públicos (Resolução Contran 752/2018). Adicione palavrões se testar input real. APIs de terceiros podem ter listas maiores — solicite ao provedor ou use whitelist de prefixos conhecidos da UF ao invés de blocklist.</p>
            </details>
          </div>
        </section>
        <ShareBar title={"Gerador de Placa Mercosul para Testes: Algoritmo e Validação"} path="/blog/gerador-placa-mercosul-teste-software" />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Como gerar placa com prefixo de UF específica sem hardcodear toda a tabela do Detran?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Mapeie UF à primeira letra do prefixo (SP→A, RJ→B, MG→C). Aleatorize as outras duas do ALPHA válido. Exemplo: `const p1 = ufMap[uf]; const p23 = randomChar(ALPHA) + randomChar(ALPHA); prefix = p1 + p23;` Não é sequencial como Detran real, mas passa validadores de correlação regional.\"}},{\"@type\":\"Question\",\"name\":\"RENAVAM usa o mesmo algoritmo mod 11 do CPF?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não. RENAVAM usa 10 pesos (3,2,9,8,7,6,5,4,3,2); CPF usa dois módulos com 9 e 8 pesos. Cálculo final diverge: RENAVAM `remainder < 2 ? 0 : 11 - remainder`, CPF sempre `11 - remainder`. Reutilizar código de CPF gera dígitos inválidos.\"}},{\"@type\":\"Question\",\"name\":\"Gerar 100 mil placas únicas com Set causa garbage collection lag perceptível?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não. 100k placas em Set ~0.04% do espaço válido (280M); colisões são raras. GC lag é imperceptível. Acima de 500k, chunking com `setImmediate()` reduz picos de memória. Teste em seu ambiente se for gerar milhões.\"}},{\"@type\":\"Question\",\"name\":\"Meu validador legado rejeita placas Mercosul — devo gerar antigas em produção?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não force Mercosul em sistema que não suporta. Em testes, mantenha suites separadas: `testMercosulSupport()` usa `generateMercosulPlate()`, `testLegacyCompatibility()` usa `generateOldPlate()`. A migração do validador é responsabilidade da arquitetura, não do gerador.\"}},{\"@type\":\"Question\",\"name\":\"Qual blocklist mínima protege contra rejeição em APIs de seguro ou Detran?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"SSP, PRF, DPF, PGR, STF, STJ, CNJ cobrem siglas de órgãos públicos (Resolução Contran 752/2018). Adicione palavrões se testar input real. APIs de terceiros podem ter listas maiores — solicite ao provedor ou use whitelist de prefixos conhecidos da UF ao invés de blocklist.\"}}]}",
        }}
      />
    </PageShell>
  );
}
