import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";
import ShareBar from "@/components/ShareBar";
import BlogPostingSchema from "@/components/BlogPostingSchema";

export const metadata: Metadata = {
  title: "Validar CPF em Java Spring Boot: algoritmo mod-11 e JUnit",
  description: "Implemente validação de CPF em Java com algoritmo mod-11 do zero, integre ao Spring Boot via Bean Validation e cubra edge cases com JUnit 5.",
  openGraph: {
    title: "Validar CPF em Java Spring Boot: algoritmo mod-11 e JUnit",
    description: "Implemente validação de CPF em Java com algoritmo mod-11 do zero, integre ao Spring Boot via Bean Validation e cubra edge cases com JUnit 5.",
    type: "article",
    images: ["/api/og?title=Validar%20CPF%20em%20Java%20Spring%20Boot%3A%20algoritmo%20mod-11%20e%20JUnit&subtitle=Implemente%20valida%C3%A7%C3%A3o%20de%20CPF%20em%20Java%20com%20algoritmo%20mod-11%20do%20zero%2C%20integre%20ao%20Spring%20Boot%20via%20Bean%20Validation%20e%20cubra%20edge%20cases%20com%20JUnit%205.&category=TUTORIAIS"],
  },
  alternates: { canonical: "/blog/validar-cpf-java-spring-boot-algoritmo-mod11-junit" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Validar CPF em Java Spring Boot: algoritmo mod-11 e JUnit" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Validar CPF em Java Spring Boot: algoritmo mod-11 e JUnit
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>03 de junho de 2026</time>
            <span>·</span>
            <span>12 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">A Receita Federal define o CPF como uma sequência de 11 dígitos onde os dois últimos são verificadores calculados por mod-11. Qualquer validação que não reimplemente esse cálculo falha em produção quando recebe CPFs mascarados, strings Unicode ou sequências repetidas. Este tutorial cobre o algoritmo completo, a integração com Bean Validation no Spring Boot e a cobertura de testes com JUnit 5.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O algoritmo mod-11 do CPF: como a Receita Federal calcula os dígitos verificadores</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura de um CPF: 9 dígitos base + 2 verificadores</h3>
          <p className="mb-4">Um CPF tem formato <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">NNN.NNN.NNN-DD</code>, onde os 9 primeiros dígitos são o número base e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">DD</code> são os dois dígitos verificadores. A validação acontece em dois passos independentes, cada um gerando um verificador.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Primeiro dígito: pesos de 10 a 2</h3>
          <p className="mb-4">Multiplique cada um dos 9 dígitos base pelos pesos de 10 a 2 (em ordem). Some os produtos. Calcule <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto = soma % 11</code>. Se <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto &lt; 2</code>, o primeiro verificador é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>. Caso contrário, é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - resto</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Segundo dígito: pesos de 11 a 2 (inclui o primeiro verificador)</h3>
          <p className="mb-4">Repita o processo usando os 9 dígitos base mais o primeiro verificador já calculado, com pesos de 11 a 2. O segundo verificador segue a mesma regra do resto.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regra do resto menor que 2 (resultado = 0)</h3>
          <p className="mb-4">Essa regra existe porque a Receita Federal optou por representar restos 0 e 1 como o dígito <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>, evitando verificadores negativos ou em dois dígitos. É a fonte mais comum de bugs em implementações de terceiros.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">CPFs com todos os dígitos iguais: inválidos por definição, não pelo mod-11</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code> passa no algoritmo matemático. A Receita Federal os rejeita por definição administrativa. Seu código precisa checar isso explicitamente antes de rodar o mod-11.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Implementando o validador CPF puro em Java (sem frameworks)</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Método <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">isValidCpf(String cpf)</code>: limpeza, tamanho, dígitos iguais, dois loops</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-java">{"public final class CpfValidator {\n\n    private CpfValidator() {}\n\n    public static boolean isValidCpf(String cpf) {\n        if (cpf == null) return false;\n\n        String digits = cpf.replaceAll(\"[^0-9]\", \"\");\n\n        if (digits.length() != 11) return false;\n\n        // Rejeita sequências uniformes (000...000, 111...111, etc.)\n        if (digits.chars().distinct().count() == 1) return false;\n\n        return checkDigit(digits, 10) && checkDigit(digits, 11);\n    }\n\n    private static boolean checkDigit(String digits, int weight) {\n        int sum = 0;\n        int limit = weight - 1; // 9 ou 10 dígitos a processar\n        for (int i = 0; i < limit; i++) {\n            sum += Character.getNumericValue(digits.charAt(i)) * (weight - i);\n        }\n        int remainder = sum % 11;\n        int expected = (remainder < 2) ? 0 : 11 - remainder;\n        return expected == Character.getNumericValue(digits.charAt(limit));\n    }\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Tratando entradas com máscara (000.000.000-00) e sem máscara</h3>
          <p className="mb-4">O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">replaceAll("[^0-9]", "")</code> remove pontos, traços e qualquer outro caractere não numérico antes de qualquer cálculo. Isso cobre CPFs mascarados e não mascarados sem lógica extra.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que não usar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Long.parseLong</code> para CPF (zero à esquerda)</h3>
          <p className="mb-4">CPFs iniciados em zero, como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">001.234.567-89</code>, perdem o zero se convertidos para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">long</code>. Trabalhe sempre com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">String</code> e acesse cada caractere individualmente via <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">charAt</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">getNumericValue</code>.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Cobertura de testes com JUnit 5 antes de integrar ao Spring</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Partições de equivalência: válidos, inválidos, nulos, vazios, mascarados</h3>
          <p className="mb-4">Antes de qualquer integração, o algoritmo puro precisa passar em todas as partições de equivalência. Não há valor em subir o Spring para testar uma função que só recebe <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">String</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">CPFs "famosos" de teste</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">444.444.444-44</code> é inválido (sequência uniforme). Para testes, use CPFs gerados deterministicamente. O <Link href="/gerador-cpf" className="text-primary hover:underline">gerador de CPF do FakeForge</Link> gera CPFs válidos que você pode usar como fixtures confiáveis.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Anotação <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@ParameterizedTest</code> com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@CsvSource</code> para 12 casos em 8 linhas</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-java">{"import org.junit.jupiter.params.ParameterizedTest;\nimport org.junit.jupiter.params.provider.CsvSource;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass CpfValidatorTest {\n\n    @ParameterizedTest\n    @CsvSource({\n        \"529.982.247-25, true\",   // CPF válido com máscara\n        \"52998224725,    true\",   // CPF válido sem máscara\n        \"111.111.111-11, false\",  // sequência uniforme\n        \"000.000.000-00, false\",  // todos zeros\n        \"123.456.789-09, false\",  // dígito verificador errado\n        \"529.982.247-26, false\",  // último dígito errado por 1\n        \",               false\",  // null (CSV trata como null)\n        \"'',             false\",  // string vazia\n        \"529.982.247,    false\",  // 10 dígitos apenas\n        \"5299822472599,  false\",  // 13 dígitos\n        \"529.982.247-2A, false\",  // letra no verificador\n        \"529 982 247 25, true\"    // espaços como separador\n    })\n    void validaCpf(String cpf, boolean expected) {\n        assertEquals(expected, CpfValidator.isValidCpf(cpf));\n    }\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Gerador de CPF de teste: <Link href="/gerador-cpf" className="text-primary hover:underline">/gerador-cpf</Link> como fonte de fixtures confiáveis</h3>
          <p className="mb-4">Para fixtures em quantidade, use a API REST do FakeForge:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=cpf&quantity=20&format=json\""}</code></pre>
          <p className="mb-4">Os CPFs retornados passam no algoritmo mod-11. Você pode validar que o seu próprio <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">isValidCpf</code> concorda com a geração, criando um teste de sanidade cruzado.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Criando a anotação <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@CPF</code> personalizada com Bean Validation</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Dependência <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">jakarta.validation-api</code> no <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pom.xml</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-xml">{"<dependency>\n    <groupId>jakarta.validation</groupId>\n    <artifactId>jakarta.validation-api</artifactId>\n    <version>3.0.2</version>\n</dependency>\n<!-- Hibernate Validator como implementação (já incluído via Spring Boot Starter Web) -->"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Interface <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@CPF</code> e classe <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CpfValidator</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-java">{"import jakarta.validation.Constraint;\nimport jakarta.validation.Payload;\nimport java.lang.annotation.*;\n\n@Documented\n@Constraint(validatedBy = CpfConstraintValidator.class)\n@Target({ElementType.FIELD, ElementType.PARAMETER})\n@Retention(RetentionPolicy.RUNTIME)\npublic @interface CPF {\n    String message() default \"{br.com.suaapp.validation.cpf}\";\n    Class<?>[] groups() default {};\n    Class<? extends Payload>[] payload() default {};\n}"}</code></pre>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-java">{"import jakarta.validation.ConstraintValidator;\nimport jakarta.validation.ConstraintValidatorContext;\n\npublic class CpfConstraintValidator implements ConstraintValidator<CPF, String> {\n\n    @Override\n    public boolean isValid(String value, ConstraintValidatorContext ctx) {\n        if (value == null || value.isBlank()) return false;\n        return CpfValidator.isValidCpf(value);\n    }\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Retornando mensagens de erro localizadas via <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">messages.properties</code></h3>
          <p className="mb-4">Crie <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">src/main/resources/ValidationMessages.properties</code>:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-">{"br.com.suaapp.validation.cpf=CPF invalido. Informe um CPF com 11 digitos validos."}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">DICA:</strong> Nomeie a chave com o pacote completo da aplicação para evitar colisão com outras dependências que usem o mesmo arquivo de mensagens.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Integrando a anotação ao Spring Boot: DTO, Controller e tratamento de erros</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">DTO, Controller e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@ControllerAdvice</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-java">{"// DTO\npublic record CadastroRequest(\n    @CPF\n    @NotBlank\n    String cpf,\n\n    @NotBlank\n    String nome\n) {}\n\n// Controller\n@RestController\n@RequestMapping(\"/api/cadastro\")\npublic class CadastroController {\n\n    @PostMapping\n    public ResponseEntity<Void> cadastrar(@Valid @RequestBody CadastroRequest req) {\n        // processamento\n        return ResponseEntity.ok().build();\n    }\n}\n\n// ControllerAdvice\n@RestControllerAdvice\npublic class ValidationAdvice {\n\n    @ExceptionHandler(MethodArgumentNotValidException.class)\n    @ResponseStatus(HttpStatus.UNPROCESSABLE_ENTITY)\n    public Map<String, Object> handleValidation(MethodArgumentNotValidException ex) {\n        List<Map<String, String>> errors = ex.getBindingResult()\n            .getFieldErrors()\n            .stream()\n            .map(fe -> Map.of(\n                \"campo\", fe.getField(),\n                \"mensagem\", fe.getDefaultMessage()\n            ))\n            .toList();\n\n        return Map.of(\n            \"status\", 422,\n            \"erros\", errors\n        );\n    }\n}"}</code></pre>
          <p className="mb-4">O payload de erro retorna HTTP 422 com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">campo</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">mensagem</code>, compatível com a maioria dos clientes frontend sem acoplamento ao formato de exceção do Spring.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Testando a integração com MockMvc</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@WebMvcTest</code> vs <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@SpringBootTest</code>: qual usar para validação</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@WebMvcTest</code> carrega apenas a camada web (controllers, filters, advice). Para testar se a anotação <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@CPF</code> dispara a mensagem certa e o status correto, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@WebMvcTest</code> é suficiente e mais rápido que <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@SpringBootTest</code>.</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-java">{"@WebMvcTest(CadastroController.class)\nclass CadastroControllerTest {\n\n    @Autowired\n    MockMvc mvc;\n\n    @Autowired\n    ObjectMapper mapper;\n\n    @Test\n    void cpfInvalido_retorna422() throws Exception {\n        var body = Map.of(\"cpf\", \"111.111.111-11\", \"nome\", \"Teste\");\n\n        mvc.perform(post(\"/api/cadastro\")\n                .contentType(MediaType.APPLICATION_JSON)\n                .content(mapper.writeValueAsString(body)))\n            .andExpect(status().isUnprocessableEntity())\n            .andExpect(jsonPath(\"$.erros[0].campo\").value(\"cpf\"));\n    }\n\n    @Test\n    void cpfValido_retorna200() throws Exception {\n        var body = Map.of(\"cpf\", \"529.982.247-25\", \"nome\", \"Joao\");\n\n        mvc.perform(post(\"/api/cadastro\")\n                .contentType(MediaType.APPLICATION_JSON)\n                .content(mapper.writeValueAsString(body)))\n            .andExpect(status().isOk());\n    }\n\n    @Test\n    void cpfComSqlInjection_retorna422SemException() throws Exception {\n        var body = Map.of(\"cpf\", \"'; DROP TABLE usuarios; --\", \"nome\", \"Hack\");\n\n        mvc.perform(post(\"/api/cadastro\")\n                .contentType(MediaType.APPLICATION_JSON)\n                .content(mapper.writeValueAsString(body)))\n            .andExpect(status().isUnprocessableEntity());\n    }\n}"}</code></pre>
          <p className="mb-4">O teste de SQL injection confirma que strings maliciosas não geram exceção inesperada: o <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">replaceAll("[^0-9]", "")</code> reduz a string a dígitos antes de qualquer cálculo.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Edge cases que quebram implementações ingênuas</h2>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Entrada</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Comportamento esperado</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Motivo</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">000.000.000-00</code></td><td className="px-3 py-2">inválido</td><td className="px-3 py-2">Todos zeros, regra administrativa</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code> até <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">999.999.999-99</code></td><td className="px-3 py-2">inválido</td><td className="px-3 py-2">Sequências uniformes</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">529.982.247-25</code></td><td className="px-3 py-2">válido</td><td className="px-3 py-2">Passa nos dois verificadores</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">\u0030\u0031\u0032...</code></td><td className="px-3 py-2">depende</td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Character.isDigit</code> aceita dígitos Unicode</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">529 982 247 25</code></td><td className="px-3 py-2">válido ou rejeitar</td><td className="px-3 py-2">Decisão de negócio, documentar antes do deploy</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">529.982.247-2A</code></td><td className="px-3 py-2">inválido</td><td className="px-3 py-2">Letra no campo numérico</td></tr></tbody></table></div>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">AVISO:</strong> <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Character.isDigit</code> retorna <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">true</code> para dígitos de outros scripts Unicode (árabe-indic, devanágari). O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">replaceAll("[^0-9]", "")</code> usa apenas ASCII <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0-9</code>, então é seguro. Não substitua por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Character.isDigit</code> sem adicionar um filtro de range.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Performance: quando a validação vira gargalo</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O algoritmo é O(1) por CPF</h3>
          <p className="mb-4">Dois loops de tamanho fixo (9 e 10 iterações). O gargalo em endpoints de lote não é a matemática: é o parsing de JSON e a alocação de strings.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cache com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ConcurrentHashMap</code> para CPFs repetidos em lote</h3>
          <p className="mb-4">Em cadastros de lote onde o mesmo CPF aparece várias vezes:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-java">{"private static final Map<String, Boolean> CACHE =\n    new ConcurrentHashMap<>(1024);\n\npublic static boolean isValidCpfCached(String cpf) {\n    return CACHE.computeIfAbsent(cpf, CpfValidator::isValidCpf);\n}"}</code></pre>
          <p className="mb-4">Limite o tamanho do cache com Caffeine ou Guava em produção para evitar crescimento ilimitado.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Benchmark com JMH</h3>
          <p className="mb-4">Em hardware moderno, o algoritmo puro sem cache atinge facilmente 2 milhões de validações por segundo em single-thread. O custo real em produção é o overhead de serialização e rede, não o mod-11.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Validação server-side não substitui dados de teste válidos</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que usar CPFs reais em testes é risco LGPD</h3>
          <p className="mb-4">A LGPD Art. 46 (<a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">Lei 13.709/2018</a>) exige que dados pessoais sejam protegidos por medidas técnicas e administrativas. CPFs reais em repositórios, logs de teste ou bancos de desenvolvimento violam esse princípio mesmo que o titular tenha consentido para outra finalidade (LGPD Art. 7º, III).</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Gerando CPFs válidos deterministicamente no setup do JUnit com seed fixo</h3>
          <p className="mb-4">Para suítes determinísticas sem dependência de rede, implemente um gerador com seed fixo:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-java">{"@BeforeAll\nstatic void geraFixtures() {\n    // Gerador determinístico com seed fixo para reprodutibilidade\n    Random rng = new Random(42L);\n    fixtures = IntStream.range(0, 50)\n        .mapToObj(i -> gerarCpfAleatorio(rng))\n        .filter(CpfValidator::isValidCpf)\n        .toList();\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><Link href="/docs" className="text-primary hover:underline">/api/generate?type=cpf&amp;quantity=50&amp;format=json</Link> como fonte de fixtures</h3>
          <p className="mb-4">Para fixtures em CI/CD sem lógica de geração no código de teste:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=cpf&quantity=50&format=json\" \\\n  -H \"x-api-key: SUA_CHAVE\""}</code></pre>
          <p className="mb-4">O <Link href="/pricing" className="text-primary hover:underline">plano Dev (R$29/mês)</Link> cobre 10.000 chamadas diárias, suficiente para pipelines de CI com múltiplos jobs paralelos.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Validando que os fixtures do FakeForge passam no seu próprio <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">isValidCpf</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-java">{"@Test\nvoid fixturesFakeForgePassamNaValidacaoLocal() {\n    fixtures.forEach(cpf ->\n        assertTrue(CpfValidator.isValidCpf(cpf),\n            \"CPF do FakeForge falhou na validacao local: \" + cpf)\n    );\n}"}</code></pre>
          <p className="mb-4">Esse teste cria um contrato bidirecional: se a <Link href="/docs" className="text-primary hover:underline">API do FakeForge</Link> e o seu algoritmo discordarem, o teste falha imediatamente.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">CNPJ segue a mesma lógica: reutilizando a estrutura</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferenças: 14 dígitos, pesos diferentes, dois loops distintos</h3>
          <p className="mb-4">O CNPJ usa pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[5,4,3,2,9,8,7,6,5,4,3,2]</code> no primeiro loop e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[6,5,4,3,2,9,8,7,6,5,4,3,2]</code> no segundo. A estrutura do método <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">checkDigit</code> é reutilizável: basta parametrizar os pesos como array.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">CNPJ Alfanumérico a partir de 01/07/2026</h3>
          <p className="mb-4">A Receita Federal publicou em 2024 a extensão do CNPJ para aceitar letras nas posições 1 a 12. O algoritmo mod-11 permanece, mas <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Character.getNumericValue</code> já suporta letras A-Z como valores 10-35. Use o <Link href="/gerador-cnpj-alfanumerico" className="text-primary hover:underline">gerador de CNPJ alfanumérico</Link> para fixtures do novo formato antes de ajustar seu validador.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/gerador-cnpj</code> para fixtures do formato atual</h3>
          <p className="mb-4">O <Link href="/gerador-cnpj" className="text-primary hover:underline">gerador de CNPJ</Link> gera CNPJs no formato atual (14 dígitos numéricos) com verificadores corretos, prontos para uso em testes de cadastro de pessoa jurídica.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Implemente <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">isValidCpf</code> com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">replaceAll("[^0-9]", "")</code>, cheque sequências uniformes antes do mod-11 e use dois loops com pesos fixos. Não use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Long.parseLong</code>.</li><li>Cubra as 12 partições de equivalência com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@ParameterizedTest</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@CsvSource</code> antes de subir o Spring.</li><li>Crie a anotação <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@CPF</code> com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ConstraintValidator</code> e configure mensagens em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ValidationMessages.properties</code>. O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@ControllerAdvice</code> deve retornar HTTP 422 com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">campo</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">mensagem</code>.</li><li>Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@WebMvcTest</code> para testar a camada de validação. Inclua o caso de SQL injection para confirmar que o endpoint retorna 422 sem estourar exceção.</li><li>Nunca use CPFs reais em testes. Use o <Link href="/gerador-cpf" className="text-primary hover:underline">gerador de CPF</Link> ou a <Link href="/docs" className="text-primary hover:underline">API REST</Link> para fixtures válidos e LGPD-safe.</li><li>O próximo passo natural é o validador de CNPJ com os mesmos pesos parametrizados e, a partir de julho de 2026, suporte ao <Link href="/gerador-cnpj-alfanumerico" className="text-primary hover:underline">CNPJ alfanumérico</Link>.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Devo validar CPF no frontend (" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Devo validar CPF no frontend (JavaScript) ou apenas no backend?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Frontend acelera UX com feedback imediato, bom para experiência. Implemente o mod-11 em JavaScript para isso. Porém, nunca confie na validação do cliente. Backend sempre revalida. Backend é a fonte da verdade. Qualquer request direto à API bypassa frontend, então validação no cliente é inútil para segurança. Use frontend para UX, backend para segurança.</p>
            </details>
            <details key="Como logar CPFs rejeitados sem" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como logar CPFs rejeitados sem violar LGPD?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Nunca logue o CPF na íntegra em logs. Logue apenas hash SHA-256 ou últimos 2 dígitos. Exemplo: `cpf_last_2: "25", cpf_hash: "abc123...def"`. Assim rastreia rejeições sem expor PII em logs, stack traces ou agregadores. Importante: destrua os hashes após 30 dias (retenção mínima para compliance).</p>
            </details>
            <details key="Preciso cachear validações de " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Preciso cachear validações de CPF em lote com 10K itens?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sem cache, 10K CPFs em ~5ms (2M ops/seg). Gargalo real é I/O de banco. Cache (Caffeine) ajuda se o mesmo CPF aparece 10+ vezes no lote. Comece sem cache, meça latência com `System.nanoTime()`. Se &gt; 50ms, adicione cache com TTL de 5 min. Benchmark real antes de otimizar é a regra.</p>
            </details>
            <details key="Posso reusar a lógica de mod-1" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Posso reusar a lógica de mod-11 para validar RG ou CNH?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">RG não tem algoritmo Federal padrão (varia por estado). CNH usa mod-11 como CPF, mas com 12 dígitos e pesos distintos (DENATRAN define). Parametrize `checkDigit()` para aceitar array de pesos. Documente qual documento usa qual sequência. Use enums: `enum DocType &#123; CPF(9), CNH(12), ...&#125;`. Assim escala sem duplicação.</p>
            </details>
            <details key="Como gerar CPFs válidos para t" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como gerar CPFs válidos para testes sem depender de API externa?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Implemente gerador com seed fixo em `@BeforeAll`: `new Random(42L)` gera mesma sequência toda execução, determinística. Ou chame `/api/generate?type=cpf&amp;quantity=50` antes do suite rodar. Cache a resposta em arquivo `fixtures.json`. Terceira opção: use [/gerador-cpf](/gerador-cpf) para 50 CPFs manualmente, commit no repo (LGPD-safe porque são sintéticos).</p>
            </details>
          </div>
        </section>
        <ShareBar title={"Validar CPF em Java Spring Boot: algoritmo mod-11 e JUnit"} path="/blog/validar-cpf-java-spring-boot-algoritmo-mod11-junit" />
        <BlogPostingSchema
          title={"Validar CPF em Java Spring Boot: algoritmo mod-11 e JUnit"}
          slug="validar-cpf-java-spring-boot-algoritmo-mod11-junit"
          description={"Implemente validação de CPF em Java com algoritmo mod-11 do zero, integre ao Spring Boot via Bean Validation e cubra edge cases com JUnit 5."}
          datePublished="2026-05-26"
          image="https://fakeforge.com.br/api/og?title=Validar%20CPF%20em%20Java%20Spring%20Boot%3A%20algoritmo%20mod-11%20e%20JUnit&subtitle=Implemente%20valida%C3%A7%C3%A3o%20de%20CPF%20em%20Java%20com%20algoritmo%20mod-11%20do%20zero%2C%20integre%20ao%20Spring%20Boot%20via%20Bean%20Validation%20e%20cubra%20edge%20cases%20com%20JUnit%205.&category=TUTORIAIS"
        />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Devo validar CPF no frontend (JavaScript) ou apenas no backend?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Frontend acelera UX com feedback imediato, bom para experiência. Implemente o mod-11 em JavaScript para isso. Porém, nunca confie na validação do cliente. Backend sempre revalida. Backend é a fonte da verdade. Qualquer request direto à API bypassa frontend, então validação no cliente é inútil para segurança. Use frontend para UX, backend para segurança.\"}},{\"@type\":\"Question\",\"name\":\"Como logar CPFs rejeitados sem violar LGPD?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Nunca logue o CPF na íntegra em logs. Logue apenas hash SHA-256 ou últimos 2 dígitos. Exemplo: `cpf_last_2: \\\"25\\\", cpf_hash: \\\"abc123...def\\\"`. Assim rastreia rejeições sem expor PII em logs, stack traces ou agregadores. Importante: destrua os hashes após 30 dias (retenção mínima para compliance).\"}},{\"@type\":\"Question\",\"name\":\"Preciso cachear validações de CPF em lote com 10K itens?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sem cache, 10K CPFs em ~5ms (2M ops/seg). Gargalo real é I/O de banco. Cache (Caffeine) ajuda se o mesmo CPF aparece 10+ vezes no lote. Comece sem cache, meça latência com `System.nanoTime()`. Se > 50ms, adicione cache com TTL de 5 min. Benchmark real antes de otimizar é a regra.\"}},{\"@type\":\"Question\",\"name\":\"Posso reusar a lógica de mod-11 para validar RG ou CNH?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"RG não tem algoritmo Federal padrão (varia por estado). CNH usa mod-11 como CPF, mas com 12 dígitos e pesos distintos (DENATRAN define). Parametrize `checkDigit()` para aceitar array de pesos. Documente qual documento usa qual sequência. Use enums: `enum DocType { CPF(9), CNH(12), ...}`. Assim escala sem duplicação.\"}},{\"@type\":\"Question\",\"name\":\"Como gerar CPFs válidos para testes sem depender de API externa?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Implemente gerador com seed fixo em `@BeforeAll`: `new Random(42L)` gera mesma sequência toda execução, determinística. Ou chame `/api/generate?type=cpf&quantity=50` antes do suite rodar. Cache a resposta em arquivo `fixtures.json`. Terceira opção: use [/gerador-cpf](/gerador-cpf) para 50 CPFs manualmente, commit no repo (LGPD-safe porque são sintéticos).\"}}]}",
        }}
      />
    </PageShell>
  );
}
