import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";

export const metadata: Metadata = {
  title: "Validar CPF em Ruby on Rails: mod-11 e RSpec do zero",
  description: "Implemente validação de CPF em Ruby on Rails com o algoritmo mod-11 completo, testes RSpec cobrindo edge cases e integração com ActiveRecord.",
  openGraph: {
    title: "Validar CPF em Ruby on Rails: mod-11 e RSpec do zero",
    description: "Implemente validação de CPF em Ruby on Rails com o algoritmo mod-11 completo, testes RSpec cobrindo edge cases e integração com ActiveRecord.",
    type: "article",
    images: ["/api/og?title=Validar%20CPF%20em%20Ruby%20on%20Rails%3A%20mod-11%20e%20RSpec%20do%20zero&subtitle=Implemente%20valida%C3%A7%C3%A3o%20de%20CPF%20em%20Ruby%20on%20Rails%20com%20o%20algoritmo%20mod-11%20completo%2C%20testes%20RSpec%20cobrindo%20edge%20cases%20e%20integra%C3%A7%C3%A3o%20com%20ActiveRecord&category=TUTORIAIS"],
  },
  alternates: { canonical: "/blog/validar-cpf-ruby-on-rails-mod-11-rspec" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Validar CPF em Ruby on Rails: mod-11 e RSpec do zero" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Validar CPF em Ruby on Rails: mod-11 e RSpec do zero
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>04 de junho de 2026</time>
            <span>·</span>
            <span>12 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">O CPF tem 11 dígitos e dois dígitos verificadores calculados via módulo 11. Sem entender essa mecânica, qualquer implementação de validação é frágil. Este artigo parte do algoritmo e chega em produção: validator ActiveRecord, testes RSpec completos e coluna criptografada com LGPD em mente.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O algoritmo mod-11 define o que é um CPF válido</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura do CPF: 9 dígitos base + 2 dígitos verificadores</h3>
          <p className="mb-4">Um CPF formatado segue o padrão <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">XXX.XXX.XXX-DD</code>, onde os 9 primeiros dígitos são o número base e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">DD</code> são os dois dígitos verificadores. A Receita Federal define essa estrutura na Instrução Normativa RFB 1.548/2015.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cálculo do primeiro dígito verificador (pesos 10..2)</h3>
          <p className="mb-4">Multiplique cada um dos 9 primeiros dígitos pelos pesos de 10 a 2, em ordem. Some os produtos. Calcule <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto = soma % 11</code>. Se o resto for menor que 2, o primeiro dígito verificador é 0. Caso contrário, é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - resto</code>.</p>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Posição</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">d1</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">d2</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">d3</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">d4</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">d5</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">d6</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">d7</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">d8</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">d9</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">Peso</td><td className="px-3 py-2">10</td><td className="px-3 py-2">9</td><td className="px-3 py-2">8</td><td className="px-3 py-2">7</td><td className="px-3 py-2">6</td><td className="px-3 py-2">5</td><td className="px-3 py-2">4</td><td className="px-3 py-2">3</td><td className="px-3 py-2">2</td></tr></tbody></table></div>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cálculo do segundo dígito verificador (pesos 11..2)</h3>
          <p className="mb-4">O segundo dígito usa os 9 dígitos base mais o primeiro verificador, com pesos de 11 a 2. A mesma regra do resto se aplica: resto menor que 2 resulta em 0, caso contrário <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - resto</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regra de rejeição: CPFs com todos os dígitos iguais</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">000.000.000-00</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code> e variantes passam no cálculo mod-11 matematicamente, mas são rejeitados pela Receita Federal como inválidos. Seu validador precisa checar isso antes de calcular os dígitos verificadores.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Implementação em Ruby puro antes de tocar no Rails</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Método <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">valid_cpf?(cpf)</code> sem dependências externas</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"def valid_cpf?(cpf)\n  digits = cpf.to_s.gsub(/\\D/, '')\n\n  return false unless digits.length == 11\n  return false if digits.chars.uniq.length == 1\n\n  calc_digit = lambda do |slice, weight_start|\n    sum = slice.chars.each_with_index.sum do |d, i|\n      d.to_i * (weight_start - i)\n    end\n    remainder = sum % 11\n    remainder < 2 ? 0 : 11 - remainder\n  end\n\n  first  = calc_digit.call(digits[0..8], 10)\n  second = calc_digit.call(digits[0..9], 11)\n\n  digits[9].to_i == first && digits[10].to_i == second\nend"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Normalização da entrada: strip, remover pontuação, garantir 11 chars</h3>
          <p className="mb-4">A linha <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">digits = cpf.to_s.gsub(/\D/, '')</code> cobre todos os casos: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">nil</code> vira string vazia, pontuação é removida, espaços também. <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">to_s</code> evita <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">NoMethodError</code> sem precisar tratar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">nil</code> separadamente.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Retorno explícito de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">true</code>/<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">false</code> sem exceptions no caminho feliz</h3>
          <p className="mb-4">O método retorna <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">false</code> para entradas inválidas, nunca levanta exceção. Exceptions ficam reservadas para erros inesperados de sistema. Validação de formato é fluxo normal, não excepcional.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Cobertura com RSpec: casos que derrubam implementações ingênuas</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">CPFs inválidos: dígito errado, sequência repetida, tamanho errado</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"RSpec.describe '#valid_cpf?' do\n  shared_examples 'rejeita cpf invalido' do |cpf|\n    it \"rejeita #{cpf.inspect}\" do\n      expect(valid_cpf?(cpf)).to be false\n    end\n  end\n\n  context 'entradas validas' do\n    it 'aceita CPF com pontuacao' do\n      expect(valid_cpf?('529.982.247-25')).to be true\n    end\n\n    it 'aceita CPF sem pontuacao' do\n      expect(valid_cpf?('52998224725')).to be true\n    end\n  end\n\n  context 'sequencias repetidas' do\n    %w[00000000000 11111111111 99999999999].each do |cpf|\n      include_examples 'rejeita cpf invalido', cpf\n    end\n  end\n\n  context 'digito verificador errado' do\n    include_examples 'rejeita cpf invalido', '529.982.247-26'\n  end\n\n  context 'tamanho errado' do\n    include_examples 'rejeita cpf invalido', '5299822472'\n    include_examples 'rejeita cpf invalido', '529982247250'\n  end\n\n  context 'entradas sujas' do\n    include_examples 'rejeita cpf invalido', nil\n    include_examples 'rejeita cpf invalido', ''\n    include_examples 'rejeita cpf invalido', '   '\n    include_examples 'rejeita cpf invalido', '123.456.789-09'\n  end\nend"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">shared_examples</code> para reutilizar em validadores futuros</h3>
          <p className="mb-4">O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">shared_examples 'rejeita cpf invalido'</code> pode ser incluído no spec do validador de CNPJ quando você implementar <Link href="/validar-cnpj" className="text-primary hover:underline">validação de CNPJ</Link>. A estrutura mod-11 é a mesma, só os pesos mudam.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Integrar o validador como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ActiveModel::EachValidator</code></h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Criar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">app/validators/cpf_validator.rb</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"class CpfValidator < ActiveModel::EachValidator\n  def validate_each(record, attribute, value)\n    return if valid_cpf?(value)\n\n    record.errors.add(attribute, :invalid_cpf)\n  end\n\n  private\n\n  def valid_cpf?(cpf)\n    digits = cpf.to_s.gsub(/\\D/, '')\n    return false unless digits.length == 11\n    return false if digits.chars.uniq.length == 1\n\n    calc_digit = lambda do |slice, weight_start|\n      sum = slice.chars.each_with_index.sum { |d, i| d.to_i * (weight_start - i) }\n      remainder = sum % 11\n      remainder < 2 ? 0 : 11 - remainder\n    end\n\n    first  = calc_digit.call(digits[0..8], 10)\n    second = calc_digit.call(digits[0..9], 11)\n    digits[9].to_i == first && digits[10].to_i == second\n  end\nend"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Usar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validates :cpf, cpf: true</code> no model</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"class User < ApplicationRecord\n  validates :cpf, presence: true, cpf: true\nend"}</code></pre>
          <p className="mb-4">Rails infere <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CpfValidator</code> a partir do símbolo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">:cpf</code>. Não precisa de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">require</code> explícito se o arquivo estiver em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">app/validators/</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Mensagem de erro localizada via <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">config/locales/pt-BR.yml</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-yaml">{"pt-BR:\n  errors:\n    messages:\n      invalid_cpf: \"não é um CPF válido\"\n  activerecord:\n    attributes:\n      user:\n        cpf: \"CPF\""}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Testar o validator no nível de model com RSpec + FactoryBot</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Factory com CPF válido gerado sinteticamente</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"FactoryBot.define do\n  factory :user do\n    name  { Faker::Name.name }\n    email { Faker::Internet.email }\n    cpf   { CpfFactory.generate }\n  end\nend"}</code></pre>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CpfFactory.generate</code> é implementado na seção de geração sintética abaixo. Não dependa de dados externos ou serviços em factories.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Teste de persistência: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">create(:user, cpf: cpf_invalido)</code> deve falhar</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"RSpec.describe User, type: :model do\n  it 'é invalido com CPF incorreto' do\n    user = build(:user, cpf: '111.111.111-11')\n    expect(user).not_to be_valid\n    expect(user.errors[:cpf]).to include('não é um CPF válido')\n  end\n\n  it 'nao persiste com CPF invalido' do\n    expect { create(:user, cpf: '000.000.000-00') }.to raise_error(ActiveRecord::RecordInvalid)\n  end\n\n  it 'persiste com CPF valido' do\n    expect { create(:user) }.not_to raise_error\n  end\nend"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Sanitização e normalização no before_validation</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">before_validation :normalize_cpf</code> remove a máscara antes de validar</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"class User < ApplicationRecord\n  before_validation :normalize_cpf\n  validates :cpf, presence: true, cpf: true\n\n  private\n\n  def normalize_cpf\n    self.cpf = cpf.to_s.gsub(/\\D/, '') if cpf.present?\n  end\nend"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Armazenar apenas os 11 dígitos no banco (sem pontuação)</h3>
          <p className="mb-4">Armazenar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">52998224725</code> em vez de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">529.982.247-25</code> simplifica consultas SQL, índices e comparações. A formatação é responsabilidade da camada de apresentação.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Apresentar formatado na view com helper <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cpf_format</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"module ApplicationHelper\n  def cpf_format(raw)\n    return '' if raw.blank?\n    digits = raw.gsub(/\\D/, '')\n    return raw unless digits.length == 11\n    \"#{digits[0..2]}.#{digits[3..5]}.#{digits[6..8]}-#{digits[9..10]}\"\n  end\nend"}</code></pre>
          <p className="mb-4">Na view: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">&lt;%= cpf_format(user.cpf) %&gt;</code>.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Unicidade e índice no banco de dados</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Migration com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">add_index :users, :cpf, unique: true</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"class AddUniqueIndexToUsersCpf < ActiveRecord::Migration[7.2]\n  def change\n    add_index :users, :cpf, unique: true\n  end\nend"}</code></pre>
          <p className="mb-4">Sem esse índice, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validates :cpf, uniqueness: true</code> faz um SELECT antes de cada INSERT, o que é lento e sujeito a race conditions em produção.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validates :cpf, uniqueness: true</code> e race conditions</h3>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">AVISO: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validates :cpf, uniqueness: true</code> protege contra duplicatas no nível da aplicação, mas não no banco. Com concorrência, dois processos podem passar pela validação simultaneamente antes de qualquer um persistir. O índice <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">UNIQUE</code> no banco é a única garantia real. Trate <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ActiveRecord::RecordNotUnique</code> no controller.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validates :cpf, uniqueness: &#123; scope: :tenant_id &#125;</code> em apps multi-tenant</h3>
          <p className="mb-4">Em SaaS multi-tenant, o mesmo CPF pode existir em tenants diferentes. O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">scope</code> garante unicidade dentro de um tenant. O índice correspondente fica em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">add_index :users, [:cpf, :tenant_id], unique: true</code>.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Considerações LGPD ao armazenar CPF</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">CPF é dado pessoal sob LGPD Art. 5º, I</h3>
          <p className="mb-4">O CPF identifica uma pessoa natural de forma direta. Isso o classifica como dado pessoal na <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">Lei 13.709/2018 (LGPD)</a>, Art. 5º, I. O tratamento exige base legal explícita: Art. 7º, V (execução de contrato) ou Art. 7º, IX (legítimo interesse, desde que documentado).</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Criptografar em repouso: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">attr_encrypted</code> ou coluna cifrada no PostgreSQL 16</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"# Gemfile\ngem 'attr_encrypted', '~> 4.0'\n\n# model\nclass User < ApplicationRecord\n  attr_encrypted :cpf,\n                 key: Rails.application.credentials.cpf_encryption_key,\n                 encode: true,\n                 encode_iv: true\nend"}</code></pre>
          <p className="mb-4">PostgreSQL 16 também suporta colunas <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">bytea</code> com criptografia via <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pgcrypto</code>. A escolha depende de onde você prefere gerenciar chaves.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Nunca logar CPF em texto plano</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"# config/application.rb\nconfig.filter_parameters += [:cpf, :cpf_confirmacao]"}</code></pre>
          <p className="mb-4">Isso garante que o CPF apareça como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[FILTERED]</code> nos logs do Rails. Revise também qualquer gem de APM (Datadog, New Relic, Sentry) que capture parâmetros de request.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Gerar CPFs sintéticos para o ambiente de testes</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que não usar CPFs reais em fixtures</h3>
          <p className="mb-4">Usar CPFs reais em seeds, factories ou commits de teste viola o princípio de minimização de dados da <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 6º, III</a>. Além disso, repositórios públicos com dados pessoais reais expõem a empresa a notificações da ANPD.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Implementar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CpfFactory.generate</code> em Ruby</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"module CpfFactory\n  def self.generate\n    base = Array.new(9) { rand(0..9) }\n\n    calc = lambda do |digits, weight_start|\n      sum = digits.each_with_index.sum { |d, i| d * (weight_start - i) }\n      remainder = sum % 11\n      remainder < 2 ? 0 : 11 - remainder\n    end\n\n    first  = calc.call(base, 10)\n    second = calc.call(base + [first], 11)\n\n    (base + [first, second]).join\n  end\nend"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Alternativa via API REST do FakeForge</h3>
          <p className="mb-4">Para gerar lotes maiores sem escrever código, use o endpoint da <Link href="/docs" className="text-primary hover:underline">API do FakeForge</Link>:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=cpf&quantity=50&format=json\""}</code></pre>
          <p className="mb-4">A resposta inclui 50 CPFs válidos prontos para seeds ou fixtures. O <Link href="/gerador-cpf" className="text-primary hover:underline">gerador de CPF</Link> na interface web cobre casos de uso manuais durante o desenvolvimento.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">DICA: Se você precisar de CPFs correlacionados com nomes, endereços e e-mails para um seed mais realista, o tipo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pessoa</code> retorna todos esses campos em um único objeto coerente. Confira o <Link href="/gerador-pessoa" className="text-primary hover:underline">gerador de pessoa</Link> para ver a estrutura de saída.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Benchmark: validação em lote sem degradar a requisição</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Custo de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">valid_cpf?</code> é O(1) -- seguro em callbacks</h3>
          <p className="mb-4">O algoritmo faz exatamente 20 multiplicações e 2 divisões, independente da entrada. A validação fica abaixo de 1 microssegundo por chamada em hardware moderno. Usar em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">before_validation</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validate</code> não introduz latência mensurável em requisições web normais.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quando mover validação para job: importação CSV com 10k+ registros</h3>
          <p className="mb-4">Se você importa planilhas de clientes com dezenas de milhares de linhas, valide fora da requisição HTTP. Processe em um <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ActiveJob</code>, retorne um relatório de erros assíncrono e evite timeouts do Puma.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Padrão com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Dry::Validation</code> para pipelines mais complexos</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ruby">{"require 'dry-validation'\n\nclass UserContract < Dry::Validation::Contract\n  params do\n    required(:cpf).filled(:string)\n  end\n\n  rule(:cpf) do\n    key.failure('não é um CPF válido') unless valid_cpf?(values[:cpf])\n  end\nend"}</code></pre>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Dry::Validation</code> separa contratos de dados dos models ActiveRecord, o que facilita reuso em workers, importadores e APIs externas que não passam pelo fluxo Rails MVC.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Implemente <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">valid_cpf?</code> em Ruby puro sem gems: normalize com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">gsub(/\D/, '')</code>, rejeite sequências repetidas e calcule os dois dígitos verificadores via mod-11 com os pesos corretos.</li><li>Crie <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">app/validators/cpf_validator.rb</code> herdando de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ActiveModel::EachValidator</code>, use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validates :cpf, cpf: true</code> no model e adicione <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">before_validation :normalize_cpf</code> para remover pontuação antes de validar.</li><li>Coloque <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">add_index :users, :cpf, unique: true</code> na migration e trate <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ActiveRecord::RecordNotUnique</code> no controller. A validação do Rails não previne race conditions, o índice previne.</li><li>Configure <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">config.filter_parameters += [:cpf]</code> e documente a base legal (LGPD Art. 7º, V ou IX) antes de ir para produção. Considere criptografia em repouso com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">attr_encrypted</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pgcrypto</code>.</li><li>Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CpfFactory.generate</code> ou a <Link href="/docs" className="text-primary hover:underline">API do FakeForge</Link> para fixtures sintéticas. Nunca use CPFs reais em código de teste -- isso viola LGPD Art. 6º, III e expõe o repositório.</li><li>O próximo passo natural é aplicar a mesma estrutura para <Link href="/validar-cnpj" className="text-primary hover:underline">validar CNPJ</Link>: o algoritmo mod-11 é idêntico, com dois ciclos de pesos em vez de um.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Como capturar e comunicar erro" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como capturar e comunicar erro quando um CPF duplicado é enviado?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Use `rescue ActiveRecord::RecordNotUnique` no controller. O índice `UNIQUE` levanta essa exceção antes do Rails acabar a transação. Retorne HTTP 422 com mensagem clara: `&#123; error: "CPF já cadastrado" &#125;`. Isso protege contra race conditions onde dois requests simultâneos passam pela validação Rails mas só um consegue persistir.</p>
            </details>
            <details key="Tenho 100k usuários sem valida" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Tenho 100k usuários sem validação. Como adiciono validação de CPF sem quebrar?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Crie uma migration que executa `UPDATE users SET cpf = TRIM(cpf)` e remove duplicatas mantendo o registro mais antigo. Depois adicione o validador com `validates :cpf, cpf: true, allow_blank: true`. Rode em background job para não travar. Monitore erros, corrija CPFs malformados manualmente, depois mude para `allow_blank: false`.</p>
            </details>
            <details key="Na API, devo sempre normalizar" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Na API, devo sempre normalizar CPF ou deixar o cliente fazer?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Normalize no servidor via `before_validation`. Clientes sempre enviam formatos sujos: pontos, hífens, espaços. Tratá-los no model garante consistência independente da origem (API, form web, import CSV). Armazene normalizado no banco. Na view/resposta JSON, formate com helper: `cpf_format(user.cpf)`.</p>
            </details>
            <details key="Posso usar o mesmo CpfValidato" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Posso usar o mesmo CpfValidator em User, Customer e Supplier?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sim. O validador é agnóstico ao model — só testa o formato do CPF. Se cada model tem `validates :cpf, cpf: true`, reutiliza `CpfValidator` automaticamente. Para lógica mais específica (ex: scoped por tenant), deixe no model com `before_validation`. O validator fica simples, focado no algoritmo mod-11.</p>
            </details>
            <details key="Validar CPF contra o servidor " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Validar CPF contra o servidor da Receita Federal depois de passar na validação local?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não faça rotineiramente — a Receita Federal não expõe API pública de validação. CPFs válidos localmente (mod-11 + rejeição de sequências repetidas) são suficientes para testes. Para onboarding real com compliance, integre com serviços third-party como Serpro ou Brunnsys, mas fora do ciclo de requisição HTTP. Cache o resultado por 24h.</p>
            </details>
          </div>
        </section>
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Como capturar e comunicar erro quando um CPF duplicado é enviado?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Use `rescue ActiveRecord::RecordNotUnique` no controller. O índice `UNIQUE` levanta essa exceção antes do Rails acabar a transação. Retorne HTTP 422 com mensagem clara: `{ error: \\\"CPF já cadastrado\\\" }`. Isso protege contra race conditions onde dois requests simultâneos passam pela validação Rails mas só um consegue persistir.\"}},{\"@type\":\"Question\",\"name\":\"Tenho 100k usuários sem validação. Como adiciono validação de CPF sem quebrar?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Crie uma migration que executa `UPDATE users SET cpf = TRIM(cpf)` e remove duplicatas mantendo o registro mais antigo. Depois adicione o validador com `validates :cpf, cpf: true, allow_blank: true`. Rode em background job para não travar. Monitore erros, corrija CPFs malformados manualmente, depois mude para `allow_blank: false`.\"}},{\"@type\":\"Question\",\"name\":\"Na API, devo sempre normalizar CPF ou deixar o cliente fazer?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Normalize no servidor via `before_validation`. Clientes sempre enviam formatos sujos: pontos, hífens, espaços. Tratá-los no model garante consistência independente da origem (API, form web, import CSV). Armazene normalizado no banco. Na view/resposta JSON, formate com helper: `cpf_format(user.cpf)`.\"}},{\"@type\":\"Question\",\"name\":\"Posso usar o mesmo CpfValidator em User, Customer e Supplier?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sim. O validador é agnóstico ao model — só testa o formato do CPF. Se cada model tem `validates :cpf, cpf: true`, reutiliza `CpfValidator` automaticamente. Para lógica mais específica (ex: scoped por tenant), deixe no model com `before_validation`. O validator fica simples, focado no algoritmo mod-11.\"}},{\"@type\":\"Question\",\"name\":\"Validar CPF contra o servidor da Receita Federal depois de passar na validação local?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não faça rotineiramente — a Receita Federal não expõe API pública de validação. CPFs válidos localmente (mod-11 + rejeição de sequências repetidas) são suficientes para testes. Para onboarding real com compliance, integre com serviços third-party como Serpro ou Brunnsys, mas fora do ciclo de requisição HTTP. Cache o resultado por 24h.\"}}]}",
        }}
      />
    </PageShell>
  );
}
