import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";

export const metadata: Metadata = {
  title: "Validar CNH em JavaScript: algoritmo DENATRAN passo a passo",
  description: "Implemente do zero o algoritmo oficial de validação de CNH em JavaScript e TypeScript, com cálculo dos dois dígitos verificadores e casos de borda cobertos.",
  openGraph: {
    title: "Validar CNH em JavaScript: algoritmo DENATRAN passo a passo",
    description: "Implemente do zero o algoritmo oficial de validação de CNH em JavaScript e TypeScript, com cálculo dos dois dígitos verificadores e casos de borda cobertos.",
    type: "article",
  },
  alternates: { canonical: "/blog/validar-cnh-javascript-algoritmo-denatran" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Validar CNH em JavaScript: algoritmo DENATRAN passo a passo" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Validar CNH em JavaScript: algoritmo DENATRAN passo a passo
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>25 de maio de 2026</time>
            <span>·</span>
            <span>12 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">O número de registro da CNH é tratado por muitos sistemas como texto livre. Isso deixa passar documentos inválidos, fantasmas ou digitados errado. A validação correta exige reproduzir o algoritmo que o DENATRAN (hoje SENATRAN) usa para gerar os dois dígitos verificadores. Este artigo mostra o algoritmo passo a passo e uma implementação TypeScript pronta para produção.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O número de registro da CNH tem estrutura definida por norma DENATRAN</h2>
          <p className="mb-4">O DENATRAN estabeleceu o formato do número de registro na Portaria 1.606/1998, depois consolidado em resoluções do CONTRAN. A estrutura é fixa: 11 dígitos numéricos, sem letras, sem pontuação obrigatória no campo de banco de dados.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que é o RENACH e por que ele importa para validação</h3>
          <p className="mb-4">O RENACH (Registro Nacional de Carteiras de Habilitação) unifica os dados de habilitação de todos os estados. Cada registro recebe um identificador composto pelo código de UF (dois caracteres) seguido de 9 dígitos numéricos. O número que aparece no campo "Número de Registro" da CNH física corresponde apenas à parte numérica do RENACH, sem o prefixo de UF. Para validar o segundo dígito verificador com precisão, o estado emissor precisa ser conhecido. Quando o sistema armazena apenas os 11 dígitos, é possível validar o primeiro verificador com certeza e o segundo condicionalmente.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Composição dos 11 dígitos: prefixo de UF, sequencial e dois dígitos verificadores</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-">{"Posições:  0  1  2  3  4  5  6  7  8   9   10\nConteúdo: [d0 d1 d2 d3 d4 d5 d6 d7 d8  D1  D2]\n           \\_________base 9 dígitos_______/ DV1 DV2"}</code></pre>
          <p className="mb-4">Posições 0–8 formam a base numérica atribuída pelo DETRAN estadual. D1 é o primeiro dígito verificador e D2 o segundo. O índice do estado emissor (DSC — Dígito de Segurança de Controle) varia de 1 (AC) a 27 (TO) e participa do cálculo de D2.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferença entre número de registro, espelho e código de segurança</h3>
          <p className="mb-4">O número de registro (11 dígitos) é o identificador primário. O número de espelho identifica a emissão física da CNH — pode mudar quando o documento é reimpresso sem alteração do RENACH. O código de segurança é um token de consulta no portal SENATRAN, sem algoritmo público de verificação. Para validação de formulários e APIs, só o número de registro interessa.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O algoritmo oficial usa mod-11 em duas passagens sequenciais</h2>
          <p className="mb-4">O mod-11 é o mesmo padrão do <Link href="/gerador-cpf" className="text-primary hover:underline">CPF</Link> e do <Link href="/gerador-cnpj" className="text-primary hover:underline">CNPJ</Link>: soma ponderada dos dígitos, divisão por 11, e o resto determina o verificador. A CNH aplica duas passagens sobre os mesmos 9 dígitos base, com pesos diferentes.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Passagem 1: pesos 2 a 10 sobre os 9 primeiros dígitos</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Posição</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Peso</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Produto</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">0</td><td className="px-3 py-2">2</td><td className="px-3 py-2">d0 × 2</td></tr><tr className="border-b border-border"><td className="px-3 py-2">1</td><td className="px-3 py-2">3</td><td className="px-3 py-2">d1 × 3</td></tr><tr className="border-b border-border"><td className="px-3 py-2">2</td><td className="px-3 py-2">4</td><td className="px-3 py-2">d2 × 4</td></tr><tr className="border-b border-border"><td className="px-3 py-2">3</td><td className="px-3 py-2">5</td><td className="px-3 py-2">d3 × 5</td></tr><tr className="border-b border-border"><td className="px-3 py-2">4</td><td className="px-3 py-2">6</td><td className="px-3 py-2">d4 × 6</td></tr><tr className="border-b border-border"><td className="px-3 py-2">5</td><td className="px-3 py-2">7</td><td className="px-3 py-2">d5 × 7</td></tr><tr className="border-b border-border"><td className="px-3 py-2">6</td><td className="px-3 py-2">8</td><td className="px-3 py-2">d6 × 8</td></tr><tr className="border-b border-border"><td className="px-3 py-2">7</td><td className="px-3 py-2">9</td><td className="px-3 py-2">d7 × 9</td></tr><tr className="border-b border-border"><td className="px-3 py-2">8</td><td className="px-3 py-2">10</td><td className="px-3 py-2">d8 × 10</td></tr></tbody></table></div>
          <p className="mb-4">Soma todos os produtos. Calcula <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">rem = soma % 11</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regras de resto: quando o DSC (Dígito de Segurança de Controle) é zero</h3>
          <p className="mb-4">Se <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">rem &lt; 2</code> (resto 0 ou 1), D1 = <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>. Caso contrário, D1 = <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - rem</code>. O resultado sempre cabe em um dígito — não há caso especial de "10" nessa passagem.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Passagem 2: pesos 2 a 11 incluindo o primeiro dígito verificador</h3>
          <p className="mb-4">A segunda passagem usa os 9 dígitos base mais D1, com pesos 2 a 11: posições 0–8 recebem pesos 2–10 (idênticos à passagem 1), e D1 recebe peso 11. O DSC do estado emissor é somado ao total antes do mod-11.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como o estado emissor afeta o segundo cálculo (DSC ≥ 10)</h3>
          <p className="mb-4">O índice de estado vai de 1 a 27. Quando <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">(total + DSC) % 11</code> produz <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - rem = 10</code>, o resultado é ajustado para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>, evitando um verificador de dois dígitos. Estados com DSC ≥ 10 (a partir de MA=10) têm maior probabilidade de acionar esse ajuste.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Implementação do primeiro dígito verificador em TypeScript</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcPrimeiroDV(digits: string): number</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function calcPrimeiroDV(digits: string): number {\n  let sum = 0;\n  for (let i = 0; i < 9; i++) {\n    sum += Number(digits[i]) * (2 + i); // pesos 2, 3, ..., 10\n  }\n  const rem = sum % 11;\n  return rem < 2 ? 0 : 11 - rem;\n}"}</code></pre>
          <p className="mb-4">A função recebe uma string de exatamente 9 caracteres numéricos. Validação de entrada fica na função principal.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Tratamento do caso em que o resto é 0 ou 1</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">rem &lt; 2</code> cobre os dois casos de uma vez. Diferente do CPF, a CNH não distingue entre resto 0 e resto 1 — ambos colapsam para zero. A expressão ternária é suficiente.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Testes unitários com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">assert</code> puro, sem framework</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import assert from \"node:assert/strict\";\n\nassert.strictEqual(calcPrimeiroDV(\"000000000\"), 0); // rem=0 → D1=0\nassert.strictEqual(calcPrimeiroDV(\"111111111\"), 11 - (99 % 11)); // rem calculado\nconsole.log(\"calcPrimeiroDV: OK\");"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Implementação do segundo dígito verificador em TypeScript</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcSegundoDV(digits: string, primeiroDV: number, dsc: number): number</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function calcSegundoDV(\n  digits: string,\n  primeiroDV: number,\n  dsc: number\n): number {\n  let sum = 0;\n  for (let i = 0; i < 9; i++) {\n    sum += Number(digits[i]) * (2 + i); // pesos 2..10\n  }\n  sum += primeiroDV * 11; // peso 11 para D1\n\n  const rem = (sum + dsc) % 11;\n  if (rem < 2) return 0;\n  const result = 11 - rem;\n  return result >= 10 ? 0 : result;\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regra especial quando DSC atinge 10 ou 11</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">rem</code> pode valer 0 a 10 (resultado do mod-11). Quando <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">rem = 1</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - rem = 10</code> — um valor inválido como dígito único. O guard <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">result &gt;= 10 ? 0 : result</code> garante que nunca se retorna dois dígitos. Estados com DSC alto deslocam o módulo para essa faixa com mais frequência.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como o índice do estado (posição 1 do RENACH) entra no cálculo</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"const UF_DSC: Record<string, number> = {\n  AC:  1, AL:  2, AM:  3, AP:  4, BA:  5,\n  CE:  6, DF:  7, ES:  8, GO:  9, MA: 10,\n  MG: 11, MS: 12, MT: 13, PA: 14, PB: 15,\n  PE: 16, PI: 17, PR: 18, RJ: 19, RN: 20,\n  RO: 21, RR: 22, RS: 23, SC: 24, SE: 25,\n  SP: 26, TO: 27,\n};"}</code></pre>
          <p className="mb-4">Quando o UF não está disponível, passe <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">dsc = 0</code> e valide apenas D1. A maioria dos formulários coleta o estado, então o UF geralmente está disponível como contexto.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Função principal <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validarCNH</code> com todos os guards de entrada</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Rejeitar strings não numéricas e comprimento diferente de 11</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function stripMask(input: string): string {\n  return input.replace(/\\D/g, \"\");\n}\n\nfunction validarCNH(\n  input: string,\n  uf?: string\n): { valido: boolean; motivo?: string } {\n  const cnh = stripMask(input);\n\n  if (cnh.length !== 11) {\n    return { valido: false, motivo: \"Comprimento inválido\" };\n  }\n\n  const TRIVIAIS = Array.from({ length: 10 }, (_, i) => String(i).repeat(11));\n  if (TRIVIAIS.includes(cnh)) {\n    return { valido: false, motivo: \"Sequência trivial\" };\n  }\n\n  const base = cnh.slice(0, 9);\n  const d1Informado = Number(cnh[9]);\n  const d2Informado = Number(cnh[10]);\n\n  const d1Calculado = calcPrimeiroDV(base);\n  if (d1Informado !== d1Calculado) {\n    return { valido: false, motivo: \"Primeiro dígito verificador inválido\" };\n  }\n\n  if (uf) {\n    const dsc = UF_DSC[uf.toUpperCase()] ?? 0;\n    const d2Calculado = calcSegundoDV(base, d1Calculado, dsc);\n    if (d2Informado !== d2Calculado) {\n      return { valido: false, motivo: \"Segundo dígito verificador inválido\" };\n    }\n  }\n\n  return { valido: true };\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Rejeitar sequências triviais (00000000000 a 99999999999 repetidos)</h3>
          <p className="mb-4">O array <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">TRIVIAIS</code> cobre todas as CNHs formadas por um único dígito repetido. Esse guard é crítico: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">00000000000</code> passa pelo algoritmo mod-11 (soma zero, rem zero, D1 zero, D2 zero), mas não representa um registro real.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Retornar objeto estruturado <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">&#123; valido: boolean; motivo?: string &#125;</code></h3>
          <p className="mb-4">O campo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">motivo</code> aparece apenas quando <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">valido: false</code>. O chamador diferencia "D1 errado" de "comprimento incorreto" sem depender de exceções ou comparar strings de erro.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Casos de borda que quebram implementações ingênuas</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">CNHs com prefixo de estado 0 (emissões antigas)</h3>
          <p className="mb-4">Emissões anteriores à padronização do RENACH usavam <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code> como primeiro dígito da parte numérica. O cálculo de D1 é idêntico — a fórmula não muda. A confusão aparece ao tentar inferir o estado a partir do número sem o prefixo de UF. A solução é sempre armazenar o UF junto ao número de registro.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Segundo verificador resultando em 10 antes do ajuste</h3>
          <p className="mb-4">Se <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - rem = 10</code>, a função retorna <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>. Implementações que retornam <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">10</code> diretamente falharão ao comparar com o dígito armazenado na CNH real. O guard <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">result &gt;= 10 ? 0 : result</code> previne isso de forma explícita.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Entrada com máscara (pontos, hífens, espaços)</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">stripMask</code> remove qualquer caractere não numérico antes de processar. Isso aceita <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"012.345.678-90"</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"012 345 678 90"</code> sem erro. A verificação de comprimento ocorre após o strip.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">DICA: Aplique <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">stripMask</code> antes de qualquer verificação de formato. Sistemas legados frequentemente persistem CNHs formatadas, e isso quebra validações que assumem entrada limpa.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Suite de testes com CNHs reais e inválidas conhecidas</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Tabela de vetores de teste (número, esperado, motivo)</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">CNH</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">UF</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Esperado</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Motivo</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">00000000000</code></td><td className="px-3 py-2">SP</td><td className="px-3 py-2">inválida</td><td className="px-3 py-2">Sequência trivial</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">1234567890</code></td><td className="px-3 py-2">SP</td><td className="px-3 py-2">inválida</td><td className="px-3 py-2">Comprimento 10, não 11</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">1234567890X</code></td><td className="px-3 py-2">RJ</td><td className="px-3 py-2">inválida</td><td className="px-3 py-2">Caractere não numérico</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">12345678901</code></td><td className="px-3 py-2">SP</td><td className="px-3 py-2">inválida</td><td className="px-3 py-2">D1 provavelmente incorreto</td></tr><tr className="border-b border-border"><td className="px-3 py-2">(gerado em /gerador-cnh)</td><td className="px-3 py-2">SP</td><td className="px-3 py-2">válida</td><td className="px-3 py-2">Gerado pelo algoritmo</td></tr></tbody></table></div>
          <p className="mb-4">Para vetores com resultado "válida" confirmado, use o <Link href="/gerador-cnh" className="text-primary hover:underline">gerador de CNH</Link>. Os números são fictícios: não correspondem a nenhum habilitado real e são seguros para fixtures e seeds de banco.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como gerar CNHs válidas para testes sem expor dados reais</h3>
          <p className="mb-4">O <Link href="/gerador-cnh" className="text-primary hover:underline">gerador de CNH do FakeForge</Link> aplica o mesmo algoritmo DENATRAN descrito neste artigo. Use os números gerados em dados de teste, mocks de API e seeds de desenvolvimento. Eles não passam em consultas ao portal SENATRAN — são inválidos no mundo real, válidos em formato.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Executar os testes com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">node --test</code> nativo (Node 20+)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// cnh.test.ts\nimport { test } from \"node:test\";\nimport assert from \"node:assert/strict\";\nimport { validarCNH } from \"./cnh.js\";\n\ntest(\"rejeita sequência trivial\", () => {\n  assert.deepEqual(validarCNH(\"00000000000\"), {\n    valido: false,\n    motivo: \"Sequência trivial\",\n  });\n});\n\ntest(\"rejeita comprimento errado\", () => {\n  assert.deepEqual(validarCNH(\"1234567890\"), {\n    valido: false,\n    motivo: \"Comprimento inválido\",\n  });\n});"}</code></pre>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"# TypeScript direto com tsx (Node 20+)\nnode --import tsx --test cnh.test.ts"}</code></pre>
          <p className="mb-4">O runner nativo do Node 20 não exige Jest, Vitest ou Mocha.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Integrar a validação em formulários React e em APIs Next.js</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Hook <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">useCNH</code> com debounce para campo controlado</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import { useState, useEffect } from \"react\";\nimport { validarCNH } from \"@/lib/validators/cnh\";\n\nexport function useCNH(uf?: string) {\n  const [valor, setValor] = useState(\"\");\n  const [resultado, setResultado] = useState<{\n    valido: boolean;\n    motivo?: string;\n  } | null>(null);\n\n  useEffect(() => {\n    const timer = setTimeout(() => {\n      if (stripMask(valor).length >= 11) {\n        setResultado(validarCNH(valor, uf));\n      } else {\n        setResultado(null);\n      }\n    }, 400);\n    return () => clearTimeout(timer);\n  }, [valor, uf]);\n\n  return { valor, setValor, resultado };\n}"}</code></pre>
          <p className="mb-4">O debounce de 400ms evita revalidar a cada tecla. O resultado zera enquanto o campo tem menos de 11 dígitos.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Validação no route handler <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/api/validate/cnh</code> com retorno padronizado</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// src/app/api/validate/cnh/route.ts\nimport { NextRequest, NextResponse } from \"next/server\";\nimport { validarCNH } from \"@/lib/validators/cnh\";\n\nexport function GET(req: NextRequest) {\n  const numero = req.nextUrl.searchParams.get(\"numero\") ?? \"\";\n  const uf = req.nextUrl.searchParams.get(\"uf\") ?? undefined;\n\n  const resultado = validarCNH(numero, uf);\n  return NextResponse.json(resultado, { status: resultado.valido ? 200 : 422 });\n}"}</code></pre>
          <p className="mb-4">Status 422 (Unprocessable Entity) sinaliza que a entrada chegou íntegra mas falhou na validação. Siga o mesmo padrão do <Link href="/validar-cpf" className="text-primary hover:underline">validador de CPF</Link> e do <Link href="/validar-cnpj" className="text-primary hover:underline">validador de CNPJ</Link> para consistência de contrato.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Reutilizar a mesma lógica no cliente e no servidor sem duplicação</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validarCNH</code> em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@/lib/validators/cnh.ts</code> é uma função pura sem dependências de browser ou Node.js. Importar no hook e no route handler é suficiente — não há necessidade de serializar via fetch para validação síncrona no cliente.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Considerações LGPD para sistemas que coletam número de CNH</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">CNH é dado pessoal sob LGPD Art. 5º, I — exige base legal (Art. 7º, IX)</h3>
          <p className="mb-4">O número de registro da CNH identifica uma pessoa física de forma direta (<a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 5º, I</a>). Coletar e armazenar esse dado exige base legal explícita. A mais comum para marketplaces e sistemas B2B é execução de contrato ou legítimo interesse (<a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 7º, IX</a>), com balancing test documentado.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">AVISO: Armazenar o número de CNH "por precaução" sem finalidade específica viola o princípio da necessidade (LGPD Art. 6º, III). Se o sistema só precisa confirmar que o usuário tem habilitação, armazene um booleano ou a data de validade, não o número completo.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Princípio da minimização: validar no frontend, nunca armazenar se não for necessário</h3>
          <p className="mb-4">A validação de formato não exige persistência. Valide no frontend com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">useCNH</code>, confirme no backend com o route handler, e persista o número apenas se ele for necessário para a finalidade declarada ao titular.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferença entre validar formato e cruzar com base DENATRAN/RENACH real</h3>
          <p className="mb-4">Este algoritmo confirma que os dígitos verificadores são matematicamente corretos. Não confirma que a CNH existe no cadastro SENATRAN, que a habilitação está ativa, nem que os dados pertencem ao usuário logado. Para confirmação real, é necessário acesso à API do SENATRAN (restrita a conveniados). O algoritmo aqui descarta entradas obviamente inválidas sem custo de I/O.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>O número de registro da CNH tem 11 dígitos: 9 de base e 2 verificadores calculados com mod-11 em duas passagens sequenciais.</li><li>Primeiro verificador usa pesos 2–10 sobre os 9 dígitos base; qualquer resto menor que 2 produz zero.</li><li>Segundo verificador usa pesos 2–11 (incluindo D1) mais o índice DSC do estado emissor; resultado ≥ 10 vira zero.</li><li><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validarCNH(input, uf?)</code> retorna <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">&#123; valido: boolean; motivo?: string &#125;</code> — o mesmo contrato serve no hook React e no route handler Next.js, sem duplicação.</li><li>Rejeite sequências triviais explicitamente: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">00000000000</code> passa pelo mod-11 por construção e precisa de guard dedicado.</li><li>Para gerar CNHs fictícias válidas em fixtures e seeds de banco, use o <Link href="/gerador-cnh" className="text-primary hover:underline">gerador de CNH</Link>. Para padrões análogos em outros documentos, veja <Link href="/gerador-cpf" className="text-primary hover:underline">CPF</Link>, <Link href="/gerador-cnpj" className="text-primary hover:underline">CNPJ</Link> e <Link href="/gerador-pis" className="text-primary hover:underline">PIS/PASEP</Link>.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Se não tenho o UF disponível n" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Se não tenho o UF disponível no formulário, consigo validar a CNH parcialmente?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sim. Passe `uf: undefined` e valide apenas D1. Funciona, mas é menos seguro — D2 fica inconcluso. Se o formulário coleta endereço ou estado, capture-o antes de validar. Sem UF, você rejeita a maioria das entradas inválidas, mas passa em alguns casos que SENATRAN recusaria.</p>
            </details>
            <details key="Gerei uma CNH no seu site, pas" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Gerei uma CNH no seu site, passei pra meu código e falhou. Como debugo?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Confirme que `stripMask` removeu máscara. Verifique que pesos em `calcPrimeiroDV` são 2–10 e em `calcSegundoDV` são 2–11 mais peso 11 para D1. Reproduza manualmente: base (9 dígitos) + D1 + D2, aplique mod-11, compare com o informado. Diferença apontará erro no algoritmo.</p>
            </details>
            <details key="Validar 1 milhão de CNHs é cus" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Validar 1 milhão de CNHs é custoso? Preciso cache?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não. Mod-11 é O(1) — 9 multiplicações por validação. 1 milhão em ~50ms em Node.js puro. Sem cache necessário. Se precisar mais velocidade, paralelizar com Worker Threads. CPU-bound, não I/O-bound.</p>
            </details>
            <details key="Existe uma API pública e gratu" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Existe uma API pública e gratuita de SENATRAN para confirmar se a CNH é real?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não. SENATRAN restringe acesso a conveniados (bancos, seguradoras, licenciados). Este algoritmo valida apenas formato matemático, não existência. Para produção com usuários reais, negocie convênio direto com SENATRAN ou delegue a parceiro credenciado.</p>
            </details>
            <details key="Por que o estado não está embu" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Por que o estado não está embutido nos 11 dígitos se ele é necessário para calcular D2?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">O RENACH completo é UF+11 dígitos (ex: SP000000001). A CNH impressa mostra só os 11 numéricos — norma DENATRAN separou propositalmente. O estado é contexto da emissão, não identificador impresso. Por isso deve vir de outro campo do formulário ou contexto.</p>
            </details>
          </div>
        </section>
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Se não tenho o UF disponível no formulário, consigo validar a CNH parcialmente?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sim. Passe `uf: undefined` e valide apenas D1. Funciona, mas é menos seguro — D2 fica inconcluso. Se o formulário coleta endereço ou estado, capture-o antes de validar. Sem UF, você rejeita a maioria das entradas inválidas, mas passa em alguns casos que SENATRAN recusaria.\"}},{\"@type\":\"Question\",\"name\":\"Gerei uma CNH no seu site, passei pra meu código e falhou. Como debugo?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Confirme que `stripMask` removeu máscara. Verifique que pesos em `calcPrimeiroDV` são 2–10 e em `calcSegundoDV` são 2–11 mais peso 11 para D1. Reproduza manualmente: base (9 dígitos) + D1 + D2, aplique mod-11, compare com o informado. Diferença apontará erro no algoritmo.\"}},{\"@type\":\"Question\",\"name\":\"Validar 1 milhão de CNHs é custoso? Preciso cache?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não. Mod-11 é O(1) — 9 multiplicações por validação. 1 milhão em ~50ms em Node.js puro. Sem cache necessário. Se precisar mais velocidade, paralelizar com Worker Threads. CPU-bound, não I/O-bound.\"}},{\"@type\":\"Question\",\"name\":\"Existe uma API pública e gratuita de SENATRAN para confirmar se a CNH é real?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não. SENATRAN restringe acesso a conveniados (bancos, seguradoras, licenciados). Este algoritmo valida apenas formato matemático, não existência. Para produção com usuários reais, negocie convênio direto com SENATRAN ou delegue a parceiro credenciado.\"}},{\"@type\":\"Question\",\"name\":\"Por que o estado não está embutido nos 11 dígitos se ele é necessário para calcular D2?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"O RENACH completo é UF+11 dígitos (ex: SP000000001). A CNH impressa mostra só os 11 numéricos — norma DENATRAN separou propositalmente. O estado é contexto da emissão, não identificador impresso. Por isso deve vir de outro campo do formulário ou contexto.\"}}]}",
        }}
      />
    </PageShell>
  );
}
