import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";

export const metadata: Metadata = {
  title: "Conta bancária fake para testes: Bradesco, Itaú e Nubank",
  description: "Gere contas bancárias fictícias com agência, número e dígito verificador válidos para Bradesco, Itaú, Nubank e mais 14 bancos. Grátis, LGPD-safe.",
  openGraph: {
    title: "Conta bancária fake para testes: Bradesco, Itaú e Nubank",
    description: "Gere contas bancárias fictícias com agência, número e dígito verificador válidos para Bradesco, Itaú, Nubank e mais 14 bancos. Grátis, LGPD-safe.",
    type: "article",
  },
  alternates: { canonical: "/blog/conta-bancaria-fake-bradesco-itau-nubank-testes" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Conta bancária fake para testes: Bradesco, Itaú e Nubank" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Conta bancária fake para testes: Bradesco, Itaú e Nubank
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>26 de maio de 2026</time>
            <span>·</span>
            <span>9 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">Testar um fluxo de pagamento sem conta bancária válida em formato significa errar no DV e perder horas depurando uma validação que não deveria existir. Este artigo mostra como gerar contas bancárias fictícias com agência, número e dígito verificador corretos para Bradesco, Itaú, Nubank e mais 14 bancos, usando a <Link href="/docs" className="text-primary hover:underline">API FakeForge</Link> ou a interface web.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O que é uma conta bancária fake e quando você precisa de uma</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferença entre dado fake e dado falso</h3>
          <p className="mb-4">Dado fake é gerado sinteticamente para ter o formato correto, sem corresponder a nenhum titular real. Dado falso é um dado real adulterado ou usado fora do contexto original. A distinção importa porque dado falso pode ter origem ilícita. Dado fake, quando gerado por ferramenta que não usa base de pessoas reais, não coloca ninguém em risco e não viola a LGPD.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Casos de uso legítimos</h3>
          <p className="mb-4">Os mais comuns no dia a dia:</p>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Fixtures em testes de integração que validam o dígito verificador antes de persistir.</li><li>Seeds de banco de dados para ambiente de desenvolvimento e staging.</li><li>Demos de produto sem exposição de dados reais de clientes.</li><li>Pipelines de CI/CD que precisam de dados bancários no schema sem depender de produção.</li><li>Payloads de exemplo em documentação de API interna.</li></ul>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que a conta precisa ter para ser útil</h3>
          <p className="mb-4">Número de conta gerado aleatoriamente sem DV válido falha na primeira chamada ao backend. Para ser útil em testes, a conta precisa ter: código COMPE do banco, número de agência no formato do banco, número de conta no formato do banco, dígito verificador correto pelo algoritmo do banco. Sem isso, o teste valida o caminho feliz de uma entrada que nunca ocorreria em produção.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Estrutura de uma conta bancária brasileira</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Composição: COMPE, agência, conta, dígito verificador</h3>
          <p className="mb-4">O COMPE (Catálogo de Identificadores de Participantes do SPB) é o código de três dígitos que identifica o banco. A agência tem quatro dígitos em quase todos os bancos, podendo ter um DV próprio. A conta tem entre cinco e oito dígitos dependendo do banco, seguida de um DV. O Banco Central publica a lista COMPE atualizada em bcb.gov.br.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como o dígito verificador é calculado</h3>
          <p className="mb-4">A maioria dos bancos usa módulo 11, mas com variações no conjunto de pesos, no tratamento de resultado 0, 1 ou igual ao módulo. Itaú usa pesos 2 a 9 aplicados da direita para esquerda, soma reduzida módulo 10. Bradesco usa módulo 11 com DV separado para agência e conta. Nubank delega para a estrutura Pagar.me e usa agência fixa 0001 sem DV de agência. Não existe um algoritmo único para todos os bancos brasileiros.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que gerar sem validar o DV quebra testes</h3>
          <p className="mb-4">Um campo de formulário ou endpoint que recebe dados bancários geralmente valida o DV antes de gravar. Se o dado fake não passa nessa validação, o teste falha por motivo errado. O erro aponta para o payload do teste, não para a lógica que você quer exercitar. Gerar dados com DV correto elimina esse ruído.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Principais bancos e seus formatos de conta</h2>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Banco</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Código COMPE</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Agência</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">DV Agência</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Conta</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">DV Conta</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">Banco do Brasil</td><td className="px-3 py-2">001</td><td className="px-3 py-2">4 dígitos</td><td className="px-3 py-2">1 dígito</td><td className="px-3 py-2">8 dígitos</td><td className="px-3 py-2">1 dígito</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Bradesco</td><td className="px-3 py-2">237</td><td className="px-3 py-2">4 dígitos</td><td className="px-3 py-2">1 dígito</td><td className="px-3 py-2">7 dígitos</td><td className="px-3 py-2">1 dígito</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Itaú</td><td className="px-3 py-2">341</td><td className="px-3 py-2">4 dígitos</td><td className="px-3 py-2">sem DV</td><td className="px-3 py-2">5 dígitos</td><td className="px-3 py-2">1 dígito</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Caixa Econômica</td><td className="px-3 py-2">104</td><td className="px-3 py-2">4 dígitos</td><td className="px-3 py-2">1 dígito</td><td className="px-3 py-2">11 dígitos</td><td className="px-3 py-2">1 dígito</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Santander</td><td className="px-3 py-2">033</td><td className="px-3 py-2">4 dígitos</td><td className="px-3 py-2">1 dígito</td><td className="px-3 py-2">8 dígitos</td><td className="px-3 py-2">1 dígito</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Nubank</td><td className="px-3 py-2">260</td><td className="px-3 py-2">0001 (fixo)</td><td className="px-3 py-2">sem DV</td><td className="px-3 py-2">7 dígitos</td><td className="px-3 py-2">1 dígito</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Inter</td><td className="px-3 py-2">077</td><td className="px-3 py-2">4 dígitos</td><td className="px-3 py-2">sem DV</td><td className="px-3 py-2">7 dígitos</td><td className="px-3 py-2">1 dígito</td></tr><tr className="border-b border-border"><td className="px-3 py-2">C6 Bank</td><td className="px-3 py-2">336</td><td className="px-3 py-2">0001 (fixo)</td><td className="px-3 py-2">sem DV</td><td className="px-3 py-2">7 dígitos</td><td className="px-3 py-2">1 dígito</td></tr></tbody></table></div>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Bradesco (banco 237)</h3>
          <p className="mb-4">Agência com quatro dígitos numéricos mais um DV calculado por módulo 7. Conta com sete dígitos mais um DV calculado por módulo 11. Valores 0 e 1 como resto do módulo 11 resultam em DV "0" na maioria das implementações. Bradesco é o banco com maior variação em sistemas legados, por isso o formato exato depende do sistema de destino.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Itaú (banco 341)</h3>
          <p className="mb-4">Agência com quatro dígitos sem DV. Conta com cinco dígitos mais um DV calculado por módulo 10 com pesos alternados 2 e 1. É o formato mais simples entre os grandes bancos.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Nubank (banco 260)</h3>
          <p className="mb-4">Conta corrente digital com agência fixa 0001. Não há DV de agência. O DV de conta usa módulo 11 com pesos 2 a 9. Por ter agência fixa, é o banco mais fácil de gerar manualmente, mas o DV de conta ainda precisa ser calculado corretamente.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Outros bancos cobertos</h3>
          <p className="mb-4">Caixa Econômica (104) tem o formato mais longo, com 11 dígitos de conta. Banco do Brasil (001) tem 8 dígitos de conta. Inter (077) e C6 (336) seguem estrutura digital com agências reduzidas. O <Link href="/gerador-conta-bancaria" className="text-primary hover:underline">gerador de conta bancária</Link> cobre todos esses formatos com DV válido.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Gerando contas bancárias fake com a API FakeForge</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Endpoint e parâmetros</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=conta-bancaria&quantity=5&format=json\""}</code></pre>
          <p className="mb-4">Substitua <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=json</code> por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=csv</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code> para outros formatos. O parâmetro <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">quantity</code> aceita até 10.000 itens por chamada. Para gerar apenas contas Nubank, adicione <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">bank=260</code> (campo em roadmap, verificar disponibilidade em <Link href="/docs" className="text-primary hover:underline">/docs</Link>).</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Resposta JSON</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"interface BankAccount {\n  bank: string;        // \"Nubank\"\n  bankCode: string;    // \"260\"\n  agency: string;      // \"0001\"\n  agencyDigit: string; // \"\" (quando sem DV)\n  account: string;     // \"1234567\"\n  accountDigit: string;// \"9\"\n  type: \"corrente\" | \"poupanca\";\n}\n\ninterface GenerateResponse {\n  _meta: {\n    source: string;\n    url: string;\n    generated_at: string;\n    license: string;\n  };\n  type: string;\n  quantity: number;\n  data: BankAccount[];\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Export CSV para seed scripts</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=conta-bancaria&quantity=100&format=csv\" \\\n  -o contas_teste.csv"}</code></pre>
          <p className="mb-4">O arquivo inclui cabeçalho com os nomes das colunas. Importa diretamente em scripts de seed com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">COPY</code> no PostgreSQL ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">LOAD DATA INFILE</code> no MySQL.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Export SQL com CREATE TABLE</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"-- Generated by FakeForge BR -- free Brazilian test data\n-- https://fakeforge.com.br\n-- Generated at: 2026-05-26T14:23:51Z\n-- License: CC0 (public domain test data)\n\nCREATE TABLE IF NOT EXISTS bank_accounts (\n  id SERIAL PRIMARY KEY,\n  bank VARCHAR(100) NOT NULL,\n  bank_code CHAR(3) NOT NULL,\n  agency VARCHAR(4) NOT NULL,\n  agency_digit VARCHAR(1),\n  account VARCHAR(11) NOT NULL,\n  account_digit CHAR(1) NOT NULL,\n  type VARCHAR(10) NOT NULL\n);\n\nINSERT INTO bank_accounts (bank, bank_code, agency, agency_digit, account, account_digit, type)\nVALUES\n  ('Bradesco', '237', '3142', '5', '9876543', '2', 'corrente'),\n  ('Nubank', '260', '0001', '', '4521876', '3', 'corrente'),\n  ('Itaú', '341', '7823', '', '45123', '7', 'poupanca');"}</code></pre>
          <p className="mb-4">O export SQL do FakeForge gera <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE</code> compatível com PostgreSQL e MySQL. Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code> no endpoint.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Gerando contas via web sem escrever código</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Selecionando banco específico vs. banco aleatório</h3>
          <p className="mb-4">Na interface do <Link href="/gerador-conta-bancaria" className="text-primary hover:underline">gerador de conta bancária</Link>, o seletor de tipo permite escolher um banco específico ou manter a opção aleatória. Para demonstrações, escolher um banco específico evita confusão com o cliente que reconhece apenas o logo do banco habitual dele.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Copiando item por item ou exportando lote</h3>
          <p className="mb-4">Cada resultado tem botão de cópia individual. Para lotes maiores, os botões de export no topo geram o arquivo no formato selecionado. O lote máximo pela interface web é 50 itens. Para volumes maiores, use a API.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Usando como fixture em Postman ou Insomnia</h3>
          <p className="mb-4">Gere 10 contas em JSON, copie o array <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">data</code> e cole como body de uma collection do Postman. Ou use a URL do endpoint diretamente em um pré-script de request para gerar dados frescos a cada execução.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Gerando contas bancárias fake em TypeScript</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Fetch com tipagem</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import type { BankAccount, GenerateResponse } from \"./types/fakeforge\";\n\nasync function fetchFakeBankAccounts(quantity = 10): Promise<BankAccount[]> {\n  const url = new URL(\"https://fakeforge.com.br/api/generate\");\n  url.searchParams.set(\"type\", \"conta-bancaria\");\n  url.searchParams.set(\"quantity\", String(quantity));\n  url.searchParams.set(\"format\", \"json\");\n\n  const res = await fetch(url.toString());\n  if (!res.ok) throw new Error(`FakeForge HTTP ${res.status}`);\n\n  const body: GenerateResponse = await res.json();\n  return body.data;\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Setup de fixture em Jest</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import { fetchFakeBankAccounts } from \"../helpers/fakeforge\";\nimport type { BankAccount } from \"../types/fakeforge\";\n\ndescribe(\"BankAccountService\", () => {\n  let accounts: BankAccount[];\n\n  beforeAll(async () => {\n    accounts = await fetchFakeBankAccounts(20);\n  });\n\n  it(\"aceita conta Nubank com agência 0001\", () => {\n    const nubank = accounts.find((a) => a.bankCode === \"260\");\n    expect(nubank).toBeDefined();\n    expect(nubank?.agency).toBe(\"0001\");\n  });\n\n  it(\"rejeita conta com DV inválido\", () => {\n    const invalid = { ...accounts[0], accountDigit: \"X\" };\n    expect(() => BankAccountService.validate(invalid)).toThrow();\n  });\n});"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">DICA:</strong> Chame <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">fetchFakeBankAccounts</code> em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">beforeAll</code>, não em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">beforeEach</code>. Uma chamada por suite economiza o limite de 100 chamadas/dia do plano gratuito.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Gerando contas bancárias fake em Python</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Chamada com httpx e conversão para DataFrame</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"import httpx\nimport pandas as pd\n\ndef fetch_bank_accounts(quantity: int = 50) -> pd.DataFrame:\n    url = \"https://fakeforge.com.br/api/generate\"\n    params = {\"type\": \"conta-bancaria\", \"quantity\": quantity, \"format\": \"json\"}\n\n    with httpx.Client(timeout=10) as client:\n        res = client.get(url, params=params)\n        res.raise_for_status()\n\n    data = res.json()[\"data\"]\n    return pd.DataFrame(data)\n\ndf = fetch_bank_accounts(100)\nprint(df.head())"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Salvando CSV com encoding UTF-8-BOM para Excel</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"df.to_csv(\n    \"contas_fake.csv\",\n    index=False,\n    encoding=\"utf-8-sig\",  # BOM garante leitura correta no Excel PT-BR\n)"}</code></pre>
          <p className="mb-4">O encoding <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">utf-8-sig</code> (UTF-8 com BOM) evita que o Excel interprete acentos como caracteres corrompidos em Windows. Pandas e outros consumidores Python ignoram o BOM sem problemas.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Boas práticas LGPD ao usar dados fictícios em testes</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que dados reais violam a LGPD Art. 7º, IX</h3>
          <p className="mb-4">A <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 7º, IX</a> exige base legal para todo tratamento de dados pessoais. Testes de software não se enquadram em nenhuma das bases legais listadas quando o ambiente de teste não tem as mesmas salvaguardas do ambiente de produção. Usar conta bancária real de um cliente em um banco de dados de desenvolvimento que o estagiário acessa é tratamento sem base legal.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Segregação de ambientes como controle técnico</h3>
          <p className="mb-4">A <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 46</a> exige medidas técnicas e administrativas para proteger dados pessoais. Segregar ambientes e usar dados fictícios em dev e staging é um controle técnico documentável. Quando a ANPD analisa um incidente, a ausência desse controle agrava a avaliação.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como documentar o uso</h3>
          <p className="mb-4">Na política de privacidade ou no registro de operações de tratamento, inclua: "Ambientes de desenvolvimento e teste utilizam exclusivamente dados fictícios gerados sinteticamente. Nenhum dado pessoal de titulares é replicado fora do ambiente de produção." Essa linha fecha a lacuna quando um auditor pergunta o que acontece com dados de clientes fora de produção.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Comparando abordagens</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Implementação manual</h3>
          <p className="mb-4">Implementar o cálculo de DV manualmente é a fonte mais comum de bugs silenciosos. O módulo 11 com tratamento de resto 0 e 1 varia por banco. Bradesco e Itaú têm regras diferentes para o mesmo algoritmo base. A maioria das implementações encontradas em Stack Overflow e GitHub Gist tem pelo menos um caso de borda errado.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Faker.js e Faker (Python)</h3>
          <p className="mb-4">Faker.js gera números de conta no formato norte-americano (routing number + account number). Não há suporte a COMPE, agência brasileira ou DV calculado por algoritmo bancário nacional. Faker em Python tem situação equivalente. Ambas as bibliotecas são ótimas para dados genéricos, mas não cobrem o formato bancário brasileiro com DV válido. A <Link href="/comparacao/fakeforge-vs-alternativas" className="text-primary hover:underline">comparação detalhada está em /comparacao/fakeforge-vs-alternativas</Link>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">FakeForge</h3>
          <p className="mb-4">Uma chamada à API retorna banco, código COMPE, agência, DV de agência, conta e DV de conta em um único objeto consistente. Os campos são correlacionados: o <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">bankCode</code> corresponde ao <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">bank</code>, o DV foi calculado pelo algoritmo correto para aquele banco. Não há pós-processamento necessário para usar nos testes.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Limites e o que a conta fake não substitui</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Não é uma conta real</h3>
          <p className="mb-4">Uma conta fake não tem titularidade no SPB. Não funciona para TED, PIX ou qualquer operação que o Banco Central processa contra a base de contas cadastradas. Usar uma conta fake em uma transação real resulta em rejeição imediata pela instituição financeira recebedora.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">AVISO:</strong> Nunca use dados fictícios em campos de formulários de instituições financeiras reais, mesmo para "testar" um endpoint de produção. Isso pode ser interpretado como tentativa de fraude independente da intenção.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quando usar sandbox oficial</h3>
          <p className="mb-4">Para testes de integração que chegam até a API do banco (open banking, PIX real, TED), use o sandbox oficial. Bradesco tem o Bradesco Sandbox em developers.bradesco.com.br. Itaú tem o Itaú Developer Portal em developer.itau.com.br. O BACEN mantém o PIX Homologação para instituições participantes. Esses ambientes exigem credencial e aprovação do banco, mas são necessários quando o teste precisa de uma resposta real da infraestrutura bancária.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quando a conta fake é suficiente</h3>
          <p className="mb-4">Conta fake cobre todo cenário onde o sistema sendo testado valida o formato e o DV sem chamar nenhuma API externa. Formulários de cadastro, validações de backend, seeds de banco de dados, fixtures de testes unitários e de integração que mocam a chamada ao banco: esses cenários não precisam de sandbox. Conta fake é a escolha correta para 90% dos casos de teste que envolvem dados bancários.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Use <Link href="/gerador-conta-bancaria" className="text-primary hover:underline">dados fictícios de conta bancária</Link> em todos os ambientes fora de produção para cumprir LGPD Art. 7º, IX sem precisar anonimizar base real.</li><li>Confira o código COMPE e o algoritmo de DV antes de implementar manualmente: cada banco tem variação no módulo 11.</li><li>Para seeds em TypeScript, chame a API em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">beforeAll</code> e reutilize o lote na suite inteira para não consumir o limite de 100 chamadas/dia do plano gratuito.</li><li>Para pipelines de dados em Python, use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">utf-8-sig</code> ao salvar CSV para evitar problema de encoding no Excel PT-BR.</li><li>Quando o teste precisa de resposta real da infraestrutura bancária, use o sandbox oficial do banco, não conta fake.</li><li>Para o mesmo titular fictício, combine <Link href="/gerador-conta-bancaria" className="text-primary hover:underline">conta bancária</Link> com <Link href="/gerador-cpf" className="text-primary hover:underline">CPF fake</Link>, <Link href="/gerador-pix" className="text-primary hover:underline">chave PIX</Link> e <Link href="/gerador-pessoa" className="text-primary hover:underline">dados completos de pessoa</Link> em uma única chamada à API usando múltiplos tipos. O <Link href="/pricing" className="text-primary hover:underline">plano Dev (R$29/mês)</Link> remove o limite de 100 chamadas/dia se o volume de testes exigir.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Como sei se meu backend está r" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como sei se meu backend está realmente validando o DV ou apenas aceitando qualquer coisa?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Teste com DV inválido propositalmente para validar que backend rejeita. Gere com FakeForge (DV correto, deve passar) e manualmente com DV errado (deve falhar). Se ambos passam, backend não valida DV — bug. Exemplo: expect(validate(conta)).toBe(true) vs expect(validate(invalidConta)).toBe(false).</p>
            </details>
            <details key="Posso reutilizar a mesma conta" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Posso reutilizar a mesma conta fake em múltiplos testes ou devo gerar uma nova cada vez?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Reutilize para economizar chamadas à API. Contas fake são dados estáticos sem 'sessão'—o mesmo objeto pode ser usado em 100 testes. Coloque em beforeAll, exporte e importe em todos os testes da suite. Evita consumir limite de 100 chamadas/dia do free tier.</p>
            </details>
            <details key="É mais eficiente gerar 100 con" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">É mais eficiente gerar 100 contas em uma chamada ou fazer 100 chamadas de 1 conta cada?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Uma chamada com quantity=100 é mais eficiente: economiza 99 requisições HTTP e roda rápido. Gere uma vez em beforeAll, copie o array na fixture, itere nos testes sem chamar API novamente. Alternativa: salve em .json local versionado para rodar CI/CD offline sem consumir limite diário.</p>
            </details>
            <details key="Como faço testes de integração" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como faço testes de integração com PIX real ou TED se conta fake não funciona no Banco Central?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Use sandbox oficial: Bradesco (developers.bradesco.com.br), Itaú (developer.itau.com.br), BACEN PIX Homologação. Requerem credencial mas validam contra banco real. Conta fake é para formato/DV local, sandbox é para fluxo de dinheiro. Escolha conforme teste exigir resposta real.</p>
            </details>
            <details key="Posso combinar conta bancária " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Posso combinar conta bancária fake com CPF fake e pessoa fake para um titular fictício completo?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sim, é possível. Gere cada tipo separado com quantity=1 e combine os dados: &#123; cpf, conta, pessoa, chave_pix &#125;. Ou use gerador multi-tipo em uma chamada (roadmap futuro). Crie factory que monta titular fictício completo: createFakePerson() =&gt; (&#123; cpf, conta, ...pessoa &#125;). Reutilize em testes de onboarding.</p>
            </details>
          </div>
        </section>
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Como sei se meu backend está realmente validando o DV ou apenas aceitando qualquer coisa?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Teste com DV inválido propositalmente para validar que backend rejeita. Gere com FakeForge (DV correto, deve passar) e manualmente com DV errado (deve falhar). Se ambos passam, backend não valida DV — bug. Exemplo: expect(validate(conta)).toBe(true) vs expect(validate(invalidConta)).toBe(false).\"}},{\"@type\":\"Question\",\"name\":\"Posso reutilizar a mesma conta fake em múltiplos testes ou devo gerar uma nova cada vez?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Reutilize para economizar chamadas à API. Contas fake são dados estáticos sem 'sessão'—o mesmo objeto pode ser usado em 100 testes. Coloque em beforeAll, exporte e importe em todos os testes da suite. Evita consumir limite de 100 chamadas/dia do free tier.\"}},{\"@type\":\"Question\",\"name\":\"É mais eficiente gerar 100 contas em uma chamada ou fazer 100 chamadas de 1 conta cada?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Uma chamada com quantity=100 é mais eficiente: economiza 99 requisições HTTP e roda rápido. Gere uma vez em beforeAll, copie o array na fixture, itere nos testes sem chamar API novamente. Alternativa: salve em .json local versionado para rodar CI/CD offline sem consumir limite diário.\"}},{\"@type\":\"Question\",\"name\":\"Como faço testes de integração com PIX real ou TED se conta fake não funciona no Banco Central?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Use sandbox oficial: Bradesco (developers.bradesco.com.br), Itaú (developer.itau.com.br), BACEN PIX Homologação. Requerem credencial mas validam contra banco real. Conta fake é para formato/DV local, sandbox é para fluxo de dinheiro. Escolha conforme teste exigir resposta real.\"}},{\"@type\":\"Question\",\"name\":\"Posso combinar conta bancária fake com CPF fake e pessoa fake para um titular fictício completo?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sim, é possível. Gere cada tipo separado com quantity=1 e combine os dados: { cpf, conta, pessoa, chave_pix }. Ou use gerador multi-tipo em uma chamada (roadmap futuro). Crie factory que monta titular fictício completo: createFakePerson() => ({ cpf, conta, ...pessoa }). Reutilize em testes de onboarding.\"}}]}",
        }}
      />
    </PageShell>
  );
}
