import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";
import ShareBar from "@/components/ShareBar";
import BlogPostingSchema from "@/components/BlogPostingSchema";

export const metadata: Metadata = {
  title: "QR Code PIX Dinâmico (EMV BR Code) em Node.js",
  description: "Aprenda a gerar QR Code PIX dinâmico no padrão EMV BR Code em Node.js — payload, cálculo CRC16-CCITT, bibliotecas e testes com dados fictícios.",
  openGraph: {
    title: "QR Code PIX Dinâmico (EMV BR Code) em Node.js",
    description: "Aprenda a gerar QR Code PIX dinâmico no padrão EMV BR Code em Node.js — payload, cálculo CRC16-CCITT, bibliotecas e testes com dados fictícios.",
    type: "article",
    images: ["/api/og?title=QR%20Code%20PIX%20Din%C3%A2mico%20(EMV%20BR%20Code)%20em%20Node.js&subtitle=Aprenda%20a%20gerar%20QR%20Code%20PIX%20din%C3%A2mico%20no%20padr%C3%A3o%20EMV%20BR%20Code%20em%20Node.js%20%E2%80%94%20payload%2C%20c%C3%A1lculo%20CRC16-CCITT%2C%20bibliotecas%20e%20testes%20com%20dados%20fict%C3%ADci&category=TUTORIAIS"],
  },
  alternates: { canonical: "/blog/qr-code-pix-dinamico-emv-br-code-nodejs" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="QR Code PIX Dinâmico (EMV BR Code) em Node.js" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            QR Code PIX Dinâmico (EMV BR Code) em Node.js
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>20 de maio de 2026</time>
            <span>·</span>
            <span>14 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">O padrão EMV BR Code, especificado pelo Banco Central na Resolução BCB nº 1 de 2020, define dois modos de operação para QR Codes PIX: estático e dinâmico. A diferença não é cosmética — ela determina quem controla o valor cobrado, como a conciliação acontece e quais dados o app do banco efetivamente lê. Este artigo cobre a implementação completa do modo dinâmico em Node.js: do payload TLV ao CRC16-CCITT, passando pela geração da imagem e pelos testes com dados fictícios.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">PIX dinâmico difere do estático em dois aspectos críticos</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que o Banco Central define como "dinâmico" (Resolução BCB nº 1, 2020)</h3>
          <p className="mb-4">A Resolução BCB nº 1, de 21 de janeiro de 2020, define o PIX dinâmico como a modalidade em que o payload contém uma URL para um endpoint externo (o PSP do recebedor), de onde o app do banco obtém os detalhes da cobrança em tempo real. O QR Code em si não carrega valor nem identificação completa — ele carrega um ponteiro.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que o payload dinâmico exige um endpoint próprio (URL no campo 26)</h3>
          <p className="mb-4">No modo dinâmico, o campo 26 (Merchant Account Information) contém a URL do PSP. Quando o usuário escaneia o código, o app do banco faz um GET nessa URL e recebe um JSON com o valor, o vencimento e os dados do recebedor. Isso permite cobranças com vencimento, descontos condicionais e invalidação após pagamento — funcionalidades impossíveis no modo estático.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quando usar estático vs. dinâmico — regra prática</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Critério</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Estático</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Dinâmico</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">Valor fixo no QR Code</td><td className="px-3 py-2">Sim</td><td className="px-3 py-2">Não (busca na URL)</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Controle de expiração</td><td className="px-3 py-2">Não</td><td className="px-3 py-2">Sim</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Conciliação por TXID</td><td className="px-3 py-2">Limitado</td><td className="px-3 py-2">Completa</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Requer backend próprio</td><td className="px-3 py-2">Não</td><td className="px-3 py-2">Sim</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Caso de uso típico</td><td className="px-3 py-2">Doações, gorjetas</td><td className="px-3 py-2">E-commerce, cobranças</td></tr></tbody></table></div>
          <p className="mb-4">Use dinâmico quando o valor varia, quando você precisa identificar exatamente qual QR Code foi pago, ou quando a cobrança expira.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">A estrutura EMV BR Code campo a campo</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">TLV (Tag-Length-Value) e a hierarquia de IDs do BACEN</h3>
          <p className="mb-4">O payload é uma string ASCII onde cada campo segue o formato <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">IDLLVALUE</code>: dois dígitos de ID, dois dígitos de comprimento e o valor. Um campo pode conter sub-campos no mesmo formato. O BACEN define os IDs de 00 a 85; campos de 26 a 51 são reservados para informações do provedor de pagamento.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Campos obrigatórios: ID 00, 26, 52, 53, 54, 58, 59, 60, 62, 63</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">ID</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Nome</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Exemplo</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">00</td><td className="px-3 py-2">Payload Format Indicator</td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">01</code></td></tr><tr className="border-b border-border"><td className="px-3 py-2">26</td><td className="px-3 py-2">Merchant Account Information</td><td className="px-3 py-2">URL do PSP</td></tr><tr className="border-b border-border"><td className="px-3 py-2">52</td><td className="px-3 py-2">Merchant Category Code</td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0000</code></td></tr><tr className="border-b border-border"><td className="px-3 py-2">53</td><td className="px-3 py-2">Transaction Currency</td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">986</code> (BRL)</td></tr><tr className="border-b border-border"><td className="px-3 py-2">54</td><td className="px-3 py-2">Transaction Amount</td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">10.00</code></td></tr><tr className="border-b border-border"><td className="px-3 py-2">58</td><td className="px-3 py-2">Country Code</td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">BR</code></td></tr><tr className="border-b border-border"><td className="px-3 py-2">59</td><td className="px-3 py-2">Merchant Name</td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">FakeForge Ltda</code></td></tr><tr className="border-b border-border"><td className="px-3 py-2">60</td><td className="px-3 py-2">Merchant City</td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Sao Paulo</code></td></tr><tr className="border-b border-border"><td className="px-3 py-2">62</td><td className="px-3 py-2">Additional Data Field</td><td className="px-3 py-2">TXID</td></tr><tr className="border-b border-border"><td className="px-3 py-2">63</td><td className="px-3 py-2">CRC16</td><td className="px-3 py-2">calculado por último</td></tr></tbody></table></div>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Campo 26 no dinâmico — GUI e URL do PSP</h3>
          <p className="mb-4">O campo 26 contém obrigatoriamente o sub-campo 00 (GUI, sempre <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">br.gov.bcb.pix</code>) e o sub-campo 25 com a URL do seu PSP. No modo estático, o sub-campo 01 teria a chave PIX diretamente. No dinâmico, a URL deve ser HTTPS e responder ao padrão da API Open Finance do BACEN.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Campo 62 (Additional Data) — TXID e sua importância para conciliação</h3>
          <p className="mb-4">O sub-campo 05 do campo 62 é o TXID — identificador único da cobrança. O BACEN exige entre 26 e 35 caracteres alfanuméricos (sem espaços, sem acentos). É esse valor que aparece no extrato do banco e que você usa para confirmar o pagamento sem ambiguidade.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Campo 63 — CRC16-CCITT: como e por que é calculado por último</h3>
          <p className="mb-4">O campo 63 é sempre os últimos 4 caracteres hexadecimais do payload. O cálculo usa CRC16-CCITT (polinômio <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0x1021</code>, valor inicial <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0xFFFF</code>) sobre toda a string que vem antes — incluindo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">6304</code> (o prefixo do próprio campo 63). Se qualquer caractere anterior mudar, o CRC muda. Apps de banco rejeitam payloads com CRC inválido sem mensagem de erro clara.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Configuração do projeto Node.js</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura de pastas e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">package.json</code> mínimo</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"mkdir pix-dinamico && cd pix-dinamico\nnpm init -y\nnpm install qrcode express\nnpm install -D typescript @types/node @types/express ts-node jest @types/jest ts-jest\nnpx tsc --init"}</code></pre>
          <p className="mb-4">Estrutura:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-">{"src/\n  pix/\n    payload.ts   # builder + CRC\n    types.ts     # interfaces TypeScript\n  server.ts      # endpoint Express"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">TypeScript opcional — tipos para o payload dinâmico</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// src/pix/types.ts\nexport interface PixDynamicPayload {\n  /** URL HTTPS do PSP — mantenha abaixo de 77 chars */\n  url: string;\n  /** Valor com 2 casas decimais, ex: \"49.90\" */\n  amount: string;\n  /** Nome do recebedor, max 25 chars, sem acentos */\n  merchantName: string;\n  /** Cidade do recebedor, max 15 chars, sem acentos */\n  merchantCity: string;\n  /** TXID: 26–35 chars alfanuméricos [A-Za-z0-9] */\n  txid: string;\n}"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Implementação do builder de payload EMV BR Code</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">buildField(id, value)</code> — serialização TLV</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// src/pix/payload.ts\n\nfunction buildField(id: string, value: string): string {\n  const len = value.length.toString().padStart(2, \"0\");\n  return `${id}${len}${value}`;\n}"}</code></pre>
          <p className="mb-4">O comprimento é sempre dois dígitos decimais. Campos com valor vazio não devem ser incluídos.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Montagem do payload e cálculo do CRC16-CCITT</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function crc16ccitt(payload: string): string {\n  let crc = 0xffff;\n  for (let i = 0; i < payload.length; i++) {\n    crc ^= payload.charCodeAt(i) << 8;\n    for (let j = 0; j < 8; j++) {\n      crc = crc & 0x8000 ? (crc << 1) ^ 0x1021 : crc << 1;\n    }\n  }\n  return (crc & 0xffff).toString(16).toUpperCase().padStart(4, \"0\");\n}\n\nexport function buildPixQrPayload(options: PixDynamicPayload): string {\n  if (options.txid.length < 26 || options.txid.length > 35) {\n    throw new Error(\"TXID deve ter entre 26 e 35 caracteres.\");\n  }\n\n  const gui      = buildField(\"00\", \"br.gov.bcb.pix\");\n  const pspUrl   = buildField(\"25\", options.url);\n  const mAI      = buildField(\"26\", gui + pspUrl);\n  const addData  = buildField(\"62\", buildField(\"05\", options.txid));\n\n  const withoutCrc = [\n    buildField(\"00\", \"01\"),\n    mAI,\n    buildField(\"52\", \"0000\"),\n    buildField(\"53\", \"986\"),\n    buildField(\"54\", options.amount),\n    buildField(\"58\", \"BR\"),\n    buildField(\"59\", options.merchantName),\n    buildField(\"60\", options.merchantCity),\n    addData,\n    \"6304\",\n  ].join(\"\");\n\n  return withoutCrc + crc16ccitt(withoutCrc);\n}"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">DICA:</strong> O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"6304"</code> já deve estar na string antes do CRC ser calculado. A string <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">withoutCrc</code> termina em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"6304"</code> — o CRC é calculado sobre ela e então concatenado. Inverter essa ordem gera um CRC diferente do esperado pelo app do banco.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Geração da imagem QR Code e entrega ao cliente</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Servindo o QR Code via endpoint Express</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">toDataURL()</code> retorna base64 (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">data:image/png;base64,...</code>), ideal para embutir em HTML ou JSON. <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">toFile()</code> salva em disco — use apenas para caching ou CDN estática.</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// src/server.ts\nimport express from \"express\";\nimport QRCode from \"qrcode\";\nimport { buildPixQrPayload } from \"./pix/payload\";\nimport type { PixDynamicPayload } from \"./pix/types\";\n\nconst app = express();\n\napp.get(\"/pix/qrcode\", async (req, res) => {\n  const options: PixDynamicPayload = {\n    url: \"https://psp.exemplo.com.br/cobv/abc123\",\n    amount: \"49.90\",\n    merchantName: \"FakeForge Ltda\",\n    merchantCity: \"Sao Paulo\",\n    txid: \"FAKEFORGE20240520ABC123DEF\",\n  };\n\n  const payload = buildPixQrPayload(options);\n  const dataUrl = await QRCode.toDataURL(payload, { errorCorrectionLevel: \"M\" });\n\n  res.json({ payload, qrcode: dataUrl });\n});\n\napp.listen(3000);"}</code></pre>
          <p className="mb-4">Para retornar PNG direto, use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">QRCode.toBuffer()</code> com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Content-Type: image/png</code>. Para forçar download, adicione <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Content-Disposition: attachment; filename="pix.png"</code>.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Dados de teste com FakeForge — sem CPF ou CNPJ real</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que nunca usar documentos reais em ambiente de dev (LGPD Art. 46)</h3>
          <p className="mb-4">A <a href="https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 46</a> exige medidas técnicas e administrativas para proteger dados pessoais contra acesso não autorizado. Usar CPF ou CNPJ reais em seeds, logs ou fixtures de teste viola esse princípio — e cria passivo jurídico mesmo sem vazamento confirmado.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Gerando chave PIX fictícia e CNPJ para testes</h3>
          <p className="mb-4">O <Link href="/gerador-pix" className="text-primary hover:underline">gerador de PIX</Link> do FakeForge produz chaves nos quatro formatos suportados pelo BACEN (CPF, CNPJ, e-mail, telefone e EVP). Use o <Link href="/gerador-cnpj" className="text-primary hover:underline">gerador de CNPJ</Link> para o campo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">merchantName</code> e confirme com o <Link href="/validar-cnpj" className="text-primary hover:underline">validador de CNPJ</Link> antes de subir para staging — o algoritmo mod-11 é exigente e um dígito errado causa rejeição silenciosa em alguns PSPs.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Usando a API REST do FakeForge em scripts de seed</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// seed.ts — busca dados fictícios antes de rodar os testes\nasync function getFakePixKey(): Promise<string> {\n  const res = await fetch(\n    \"https://fakeforge.com.br/api/generate?type=pix&quantity=1&format=json\"\n  );\n  const [item] = await res.json();\n  return item.key;\n}\n\nasync function getFakeMerchant(): Promise<{ cnpj: string; name: string }> {\n  const res = await fetch(\n    \"https://fakeforge.com.br/api/generate?type=empresa&quantity=1&format=json\"\n  );\n  const [item] = await res.json();\n  return { cnpj: item.cnpj, name: item.razaoSocial };\n}"}</code></pre>
          <p className="mb-4">Para times com CI/CD intenso, os <Link href="/pricing" className="text-primary hover:underline">planos da API</Link> (Dev R$29/mês ou Team R$79/mês) removem o limite de 100 chamadas/dia. Consulte a <Link href="/docs" className="text-primary hover:underline">documentação</Link> para todos os tipos disponíveis.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Teste do payload — verificação sem depender do app do banco</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Decodificador TLV para debug local</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// tlv-decoder.ts\nexport function decodeTlv(payload: string): Record<string, string> {\n  const result: Record<string, string> = {};\n  let i = 0;\n  while (i < payload.length - 4) {\n    const id  = payload.slice(i, i + 2);\n    const len = parseInt(payload.slice(i + 2, i + 4), 10);\n    result[id] = payload.slice(i + 4, i + 4 + len);\n    i += 4 + len;\n  }\n  return result;\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Teste unitário com Jest — validar CRC e campos obrigatórios</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// pix.test.ts\nimport { buildPixQrPayload } from \"./src/pix/payload\";\n\nconst opts = {\n  url: \"https://psp.exemplo.com.br/cobv/test001\",\n  amount: \"1.00\",\n  merchantName: \"Teste Ltda\",\n  merchantCity: \"Curitiba\",\n  txid: \"TESTETXIDVALIDO26CHARS0001\",\n};\n\ntest(\"payload termina com CRC de 4 chars hex maiúsculos\", () => {\n  const payload = buildPixQrPayload(opts);\n  expect(payload.slice(-4)).toMatch(/^[0-9A-F]{4}$/);\n});\n\ntest(\"payload contém campos 26 e 62\", () => {\n  const payload = buildPixQrPayload(opts);\n  expect(payload).toContain(\"26\");\n  expect(payload).toContain(\"6205\");\n});\n\ntest(\"TXID com 25 chars lança erro\", () => {\n  expect(() =>\n    buildPixQrPayload({ ...opts, txid: \"CURTODEMAIS1234567890ABCDE\" })\n  ).toThrow(\"TXID deve ter entre 26 e 35 caracteres.\");\n});"}</code></pre>
          <p className="mb-4">Para teste de integração, simule a resposta do PSP no campo 26 com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">nock</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">msw</code> — intercepte o GET na URL do campo 26 e retorne o JSON de cobrança esperado pelo padrão BACEN.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Erros comuns e como depurá-los</h2>
          <p className="mb-4"><strong className="text-foreground">CRC incorreto:</strong> verifique se <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">withoutCrc</code> termina em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"6304"</code> antes do cálculo. Acentos em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">merchantName</code> corrompem o CRC — normalize com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">.normalize("NFD").replace(/[\u0300-\u036f]/g, "")</code>. Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">&amp; 0xffff</code> em cada iteração para manter 16 bits.</p>
          <p className="mb-4"><strong className="text-foreground">Campo 54 com formato errado:</strong> o BACEN exige ponto decimal e exatamente duas casas. <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"49,90"</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"49.9"</code> são inválidos. Use sempre <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">amount.toFixed(2)</code>.</p>
          <p className="mb-4"><strong className="text-foreground">URL no campo 26 com mais de 99 caracteres:</strong> o comprimento TLV é limitado a dois dígitos decimais (máximo 99). Uma URL longa demais gera comprimento de três dígitos, corrompendo o payload inteiro. Mantenha a URL abaixo de 77 caracteres para que o campo 26 completo (GUI + URL) caiba nos 99 bytes permitidos.</p>
          <p className="mb-4"><strong className="text-foreground">TXID inválido:</strong> o BACEN aceita apenas <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[A-Za-z0-9]</code>, 26–35 caracteres. UUID sem hífens tem 32 caracteres e atende a regra.</p>
          <p className="mb-4"><strong className="text-foreground">QR Code lido como estático:</strong> verifique se o sub-campo 25 do campo 26 contém uma URL HTTPS (não uma chave PIX), e se o campo 01 (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">initiation method</code>) está ausente — ele é exclusivo do modo estático.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Segurança e boas práticas em produção</h2>
          <p className="mb-4"><strong className="text-foreground">HTTPS obrigatório:</strong> a Resolução BCB nº 1, 2020 exige HTTPS na URL do campo 26. Apps de banco recusam cobranças dinâmicas com URL HTTP sem exceção.</p>
          <p className="mb-4"><strong className="text-foreground">Expiração e invalidação de TXID:</strong> armazene o TXID com status (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pendente</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pago</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">expirado</code>). Quando o PSP confirmar via webhook, marque como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pago</code> e retorne HTTP 422 para leituras subsequentes. Isso previne double spending em falhas de rede.</p>
          <p className="mb-4"><strong className="text-foreground">Rate limiting:</strong> aplique rate limiting por IP no endpoint de geração. Sem isso, um atacante enumera TXIDs e mapeia cobranças em aberto. Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">express-rate-limit</code> com janela de 1 minuto e máximo de 20 requisições por IP.</p>
          <p className="mb-4"><strong className="text-foreground">Logs sem dados pessoais:</strong> a <a href="https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 7º, IX</a> exige base legal para tratar dados pessoais. Logs de aplicação raramente têm controle de acesso adequado — não inclua CPF, CNPJ ou valor de cobrança. Use o TXID opaco para rastreamento.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">AVISO:</strong> Em produção, nunca retorne o payload PIX completo em logs de erro. O TXID exposto permite que atacantes consultem o status da cobrança diretamente no PSP sem autenticação.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>O modo dinâmico exige URL HTTPS no sub-campo 25 do campo 26; o payload não carrega o valor diretamente — o app do banco busca os detalhes no seu backend.</li><li>O CRC16-CCITT é calculado sobre a string completa incluindo o prefixo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">6304</code>; erros de encoding (acentos) e truncamento de 16 bits são as causas mais comuns de falha silenciosa.</li><li>TXID deve ter 26–35 caracteres <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[A-Za-z0-9]</code>; UUID sem hífens (32 chars) atende a regra e simplifica a conciliação por webhook.</li><li>Use o <Link href="/gerador-pix" className="text-primary hover:underline">gerador de PIX</Link> e o <Link href="/gerador-cnpj" className="text-primary hover:underline">gerador de CNPJ</Link> do FakeForge para seeds e fixtures, e valide com o <Link href="/validar-cnpj" className="text-primary hover:underline">validador de CNPJ</Link> antes de usar em staging — nunca use documentos reais em dev (LGPD Art. 46).</li><li>O próximo passo natural é implementar o webhook de confirmação do PSP e usar o TXID para reconciliar pagamentos sem polling no banco de dados da cobrança.</li><li>Referências complementares: spec EMV BR Code v2.1 (site do BACEN), sandbox de homologação do BACEN, e a <Link href="/docs" className="text-primary hover:underline">documentação da API FakeForge</Link> para automação de geração de dados em CI/CD.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Posso reutilizar o mesmo TXID " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Posso reutilizar o mesmo TXID para cobranças diferentes?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não. O TXID é identificador único da cobrança — reutilizar permite que um atacante copie um QR pago e clique novamente. Após confirmação do PSP (webhook), marque como `pago` e rejeite re-escanagens com HTTP 422. Para nova cobrança, gere novo TXID. Use UUID sem hífens (32 chars, valida a regra 26–35 chars) ou prefixo temporal para rastreabilidade.</p>
            </details>
            <details key="QRCode.toDataURL() retorna bas" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">QRCode.toDataURL() retorna base64 e QRCode.toBuffer() retorna PNG binário — qual usar?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Use `toDataURL()` para API JSON (embute no response com `&#123; qrcode: dataUrl &#125;` — cliente desenha uma tag `&lt;img&gt;`). Use `toBuffer()` apenas se servir PNG direto (`Content-Type: image/png`) — útil para download ou CDN estática. DataURL é mais simples, mais lento em conexões lentas; Buffer economiza banda em alta escala.</p>
            </details>
            <details key="Como validar o payload antes d" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como validar o payload antes de gerar o QR sem decodificar manualmente?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Escreva um decodificador TLV que lê o payload e retorna um objeto &#123; '00': '01', '26': '...', ... &#125;. Valide programaticamente: campo 26 contém URL HTTPS? Campo 54 tem format correto (2 decimais)? TXID no campo 62 tem 26–35 chars `[A-Za-z0-9]`? Use Jest com casos edge: TXID=25chars deve falhar, URL com 100 chars deve falhar.</p>
            </details>
            <details key="Se um cliente gerar o QR, depo" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Se um cliente gerar o QR, depois mudar de ideia e quiser um valor diferente, preciso gerar novo QR?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sim. Cada TXID corresponde a uma cobrança imutável no PSP — você não pode renegociar valor no mesmo TXID. Gere novo TXID, novo payload, novo QR. No banco de dados, marque o TXID antigo como `cancelado` ou `expirado` para auditoria. Considere TTL automático (ex: 30 minutos) antes de exigir novo QR.</p>
            </details>
            <details key="O que fazer se meu endpoint do" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">O que fazer se meu endpoint do PSP (campo 26) fica indisponível e o usuário escaneia o QR?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">O app do banco tenta GET na URL e falha. Ele retorna erro `[9999] Erro ao processar sua requisição`. De lado do cliente: implemente circuit breaker no seu PSP (fail-fast, cacheia última resposta válida 5–10s). De lado do servidor: use webhook redundante com Slack/PagerDuty. Estude SLA do seu PSP antes de lançar cobranças em produção.</p>
            </details>
          </div>
        </section>
        <ShareBar title={"QR Code PIX Dinâmico (EMV BR Code) em Node.js"} path="/blog/qr-code-pix-dinamico-emv-br-code-nodejs" />
        <BlogPostingSchema
          title={"QR Code PIX Dinâmico (EMV BR Code) em Node.js"}
          slug="qr-code-pix-dinamico-emv-br-code-nodejs"
          description={"Aprenda a gerar QR Code PIX dinâmico no padrão EMV BR Code em Node.js — payload, cálculo CRC16-CCITT, bibliotecas e testes com dados fictícios."}
          datePublished="2026-05-26"
          image="https://fakeforge.com.br/api/og?title=QR%20Code%20PIX%20Din%C3%A2mico%20(EMV%20BR%20Code)%20em%20Node.js&subtitle=Aprenda%20a%20gerar%20QR%20Code%20PIX%20din%C3%A2mico%20no%20padr%C3%A3o%20EMV%20BR%20Code%20em%20Node.js%20%E2%80%94%20payload%2C%20c%C3%A1lculo%20CRC16-CCITT%2C%20bibliotecas%20e%20testes%20com%20dados%20fict%C3%ADci&category=TUTORIAIS"
        />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Posso reutilizar o mesmo TXID para cobranças diferentes?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não. O TXID é identificador único da cobrança — reutilizar permite que um atacante copie um QR pago e clique novamente. Após confirmação do PSP (webhook), marque como `pago` e rejeite re-escanagens com HTTP 422. Para nova cobrança, gere novo TXID. Use UUID sem hífens (32 chars, valida a regra 26–35 chars) ou prefixo temporal para rastreabilidade.\"}},{\"@type\":\"Question\",\"name\":\"QRCode.toDataURL() retorna base64 e QRCode.toBuffer() retorna PNG binário — qual usar?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Use `toDataURL()` para API JSON (embute no response com `{ qrcode: dataUrl }` — cliente desenha uma tag `<img>`). Use `toBuffer()` apenas se servir PNG direto (`Content-Type: image/png`) — útil para download ou CDN estática. DataURL é mais simples, mais lento em conexões lentas; Buffer economiza banda em alta escala.\"}},{\"@type\":\"Question\",\"name\":\"Como validar o payload antes de gerar o QR sem decodificar manualmente?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Escreva um decodificador TLV que lê o payload e retorna um objeto { '00': '01', '26': '...', ... }. Valide programaticamente: campo 26 contém URL HTTPS? Campo 54 tem format correto (2 decimais)? TXID no campo 62 tem 26–35 chars `[A-Za-z0-9]`? Use Jest com casos edge: TXID=25chars deve falhar, URL com 100 chars deve falhar.\"}},{\"@type\":\"Question\",\"name\":\"Se um cliente gerar o QR, depois mudar de ideia e quiser um valor diferente, preciso gerar novo QR?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sim. Cada TXID corresponde a uma cobrança imutável no PSP — você não pode renegociar valor no mesmo TXID. Gere novo TXID, novo payload, novo QR. No banco de dados, marque o TXID antigo como `cancelado` ou `expirado` para auditoria. Considere TTL automático (ex: 30 minutos) antes de exigir novo QR.\"}},{\"@type\":\"Question\",\"name\":\"O que fazer se meu endpoint do PSP (campo 26) fica indisponível e o usuário escaneia o QR?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"O app do banco tenta GET na URL e falha. Ele retorna erro `[9999] Erro ao processar sua requisição`. De lado do cliente: implemente circuit breaker no seu PSP (fail-fast, cacheia última resposta válida 5–10s). De lado do servidor: use webhook redundante com Slack/PagerDuty. Estude SLA do seu PSP antes de lançar cobranças em produção.\"}}]}",
        }}
      />
    </PageShell>
  );
}
