import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";
import ShareBar from "@/components/ShareBar";
import BlogPostingSchema from "@/components/BlogPostingSchema";

export const metadata: Metadata = {
  title: "Validar CPF em C# .NET: algoritmo mod-11 e xUnit",
  description: "Implemente a validação de CPF em C# do zero com o algoritmo mod-11, trate casos-limite e cubra tudo com xUnit. Código pronto para produção.",
  openGraph: {
    title: "Validar CPF em C# .NET: algoritmo mod-11 e xUnit",
    description: "Implemente a validação de CPF em C# do zero com o algoritmo mod-11, trate casos-limite e cubra tudo com xUnit. Código pronto para produção.",
    type: "article",
    images: ["/api/og?title=Validar%20CPF%20em%20C%23%20.NET%3A%20algoritmo%20mod-11%20e%20xUnit&subtitle=Implemente%20a%20valida%C3%A7%C3%A3o%20de%20CPF%20em%20C%23%20do%20zero%20com%20o%20algoritmo%20mod-11%2C%20trate%20casos-limite%20e%20cubra%20tudo%20com%20xUnit.%20C%C3%B3digo%20pronto%20para%20produ%C3%A7%C3%A3o.&category=TUTORIAIS"],
  },
  alternates: { canonical: "/blog/validar-cpf-csharp-dotnet-mod11-xunit" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Validar CPF em C# .NET: algoritmo mod-11 e xUnit" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Validar CPF em C# .NET: algoritmo mod-11 e xUnit
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>04 de junho de 2026</time>
            <span>·</span>
            <span>12 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">CPF não é só 11 dígitos. Qualquer sistema que aceita entrada do usuário precisa rejeitar sequências como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">000.000.000-00</code>, verificar os dois dígitos verificadores com o algoritmo mod-11 e fazer isso sem alocar memória desnecessária. Este artigo implementa a validação do zero em C# 12 / .NET 8, cobre os casos-limite que a Receita Federal documenta e fecha com uma suite xUnit reproduzível, incluindo seed de CPFs fictícios via <Link href="/docs" className="text-primary hover:underline">API do FakeForge</Link>.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O que o mod-11 faz e por que o CPF depende dele</h2>
          <p className="mb-4">O módulo 11 é uma função de checksum: dado um número inteiro positivo, calcula o resto da divisão por 11 de uma soma ponderada dos dígitos. O resultado, possivelmente ajustado, torna-se o dígito verificador. Qualquer erro de digitação em um único dígito ou transposição de dois dígitos adjacentes produz um resto diferente, e a validação falha.</p>
          <p className="mb-4">A Receita Federal adotou duas rodadas consecutivas de mod-11 para o CPF: a primeira protege os 9 dígitos do corpo com um ponderador decrescente (10 → 2); a segunda protege os 10 dígitos resultantes (corpo + primeiro verificador) com ponderador 11 → 2.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura dos 11 dígitos: 9 de corpo e 2 verificadores</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Posição</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">1</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">2</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">3</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">4</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">5</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">6</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">7</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">8</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">9</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">10</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">11</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">Papel</td><td className="px-3 py-2">corpo</td><td className="px-3 py-2">corpo</td><td className="px-3 py-2">corpo</td><td className="px-3 py-2">corpo</td><td className="px-3 py-2">corpo</td><td className="px-3 py-2">corpo</td><td className="px-3 py-2">corpo</td><td className="px-3 py-2">corpo</td><td className="px-3 py-2">corpo</td><td className="px-3 py-2">1º verificador</td><td className="px-3 py-2">2º verificador</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Peso (1ª rodada)</td><td className="px-3 py-2">10</td><td className="px-3 py-2">9</td><td className="px-3 py-2">8</td><td className="px-3 py-2">7</td><td className="px-3 py-2">6</td><td className="px-3 py-2">5</td><td className="px-3 py-2">4</td><td className="px-3 py-2">3</td><td className="px-3 py-2">2</td><td className="px-3 py-2">—</td><td className="px-3 py-2">—</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Peso (2ª rodada)</td><td className="px-3 py-2">11</td><td className="px-3 py-2">10</td><td className="px-3 py-2">9</td><td className="px-3 py-2">8</td><td className="px-3 py-2">7</td><td className="px-3 py-2">6</td><td className="px-3 py-2">5</td><td className="px-3 py-2">4</td><td className="px-3 py-2">3</td><td className="px-3 py-2">2</td><td className="px-3 py-2">—</td></tr></tbody></table></div>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">As regras de eliminação</h3>
          <p className="mb-4">Antes de qualquer cálculo, dois descartes imediatos:</p>
          <p className="mb-4">1. O CPF deve ter exatamente 11 dígitos numéricos (após remover pontuação). 2. Se todos os 11 dígitos forem iguais (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">000.000.000-00</code> até <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">999.999.999-99</code>), o CPF é inválido. A Receita Federal os reserva para controle interno e eles passariam no cálculo aritmético, o que tornaria a regra de eliminação obrigatória na lógica de negócio.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Algoritmo passo a passo, sem biblioteca externa</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cálculo do primeiro dígito verificador</h3>
          <p className="mb-4">1. Multiplique cada um dos 9 dígitos do corpo pelo peso correspondente (10 a 2). 2. Some os produtos. 3. Multiplique a soma por 10. 4. Calcule o resto da divisão por 11. 5. Se o resto for 10 ou 11, o primeiro verificador é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>; caso contrário, o resto é o verificador.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cálculo do segundo dígito verificador</h3>
          <p className="mb-4">Repita o processo usando os 10 dígitos (corpo + primeiro verificador) com pesos de 11 a 2.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Casos especiais que a Receita Federal documenta</h3>
          <p className="mb-4">As sequências repetidas (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">000...</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111...</code>, ..., <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">999...</code>) satisfazem a aritmética do mod-11 mas são explicitamente inválidas. Isso é documentado no manual de validação da Receita Federal (versão 2019, disponível no portal <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">receita.economia.gov.br</code>). Qualquer implementação que não trate esse caso aceita entradas inválidas silenciosamente.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Implementação em C# — classe CpfValidator</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Sanitização da entrada</h3>
          <p className="mb-4">Pontos e hífens são pontuação opcional. O validador deve aceitar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"529.982.247-25"</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"52998224725"</code> como equivalentes, rejeitar qualquer outro caractere não numérico sem exceção.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Método <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">IsValid(string)</code> e sobrecarga <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ReadOnlySpan&lt;char&gt;</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-csharp">{"public static class CpfValidator\n{\n    public static bool IsValid(string? cpf)\n    {\n        if (cpf is null) return false;\n        return IsValid(cpf.AsSpan());\n    }\n\n    public static bool IsValid(ReadOnlySpan<char> input)\n    {\n        Span<int> digits = stackalloc int[11];\n        int count = 0;\n\n        foreach (char c in input)\n        {\n            if (char.IsAsciiDigit(c))\n            {\n                if (count == 11) return false; // mais de 11 dígitos\n                digits[count++] = c - '0';\n            }\n            else if (c != '.' && c != '-')\n            {\n                return false; // caractere inesperado\n            }\n        }\n\n        if (count != 11) return false;\n\n        // eliminar sequências de dígitos repetidos\n        bool allSame = true;\n        for (int i = 1; i < 11; i++)\n        {\n            if (digits[i] != digits[0]) { allSame = false; break; }\n        }\n        if (allSame) return false;\n\n        // primeiro verificador\n        int sum = 0;\n        for (int i = 0; i < 9; i++)\n            sum += digits[i] * (10 - i);\n        int rem = (sum * 10) % 11;\n        if (rem >= 10) rem = 0;\n        if (rem != digits[9]) return false;\n\n        // segundo verificador\n        sum = 0;\n        for (int i = 0; i < 10; i++)\n            sum += digits[i] * (11 - i);\n        rem = (sum * 10) % 11;\n        if (rem >= 10) rem = 0;\n        return rem == digits[10];\n    }\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Sobrecarga <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ReadOnlySpan&lt;char&gt;</code> para evitar alocação</h3>
          <p className="mb-4">A sobrecarga com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ReadOnlySpan&lt;char&gt;</code> permite passar fatias de strings maiores sem criar substring. <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">stackalloc int[11]</code> aloca os 11 inteiros na stack, evitando pressão no GC. Em cenários de alta throughput (validação em lote via API, por exemplo), a diferença é mensurável.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Formatação e parsing bidirecional</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Formatar string raw como "000.000.000-00"</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-csharp">{"public static class CpfFormatter\n{\n    public static string Format(string raw)\n    {\n        var digits = raw.Where(char.IsAsciiDigit).ToArray();\n        if (digits.Length != 11)\n            throw new ArgumentException(\"CPF deve ter 11 dígitos.\", nameof(raw));\n\n        return $\"{new string(digits[..3])}.{new string(digits[3..6])}.{new string(digits[6..9])}-{new string(digits[9..11])}\";\n    }\n\n    public static string StripMask(string formatted)\n        => new string(formatted.Where(char.IsAsciiDigit).ToArray());\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Parsear string formatada de volta para dígitos</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">StripMask</code> acima cobre o caminho inverso. Para cenários com entrada controlada (banco de dados, payload de API), prefira <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">AsSpan()</code> direto no <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">IsValid</code> para evitar a alocação do <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">char[]</code>.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Testes com xUnit — cobertura completa</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[Theory]</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[InlineData]</code> para CPFs válidos</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-csharp">{"public class CpfValidatorTests\n{\n    [Theory]\n    [InlineData(\"529.982.247-25\")]\n    [InlineData(\"52998224725\")]\n    [InlineData(\"871.048.410-18\")]\n    [InlineData(\"153.509.460-56\")]\n    public void IsValid_RetornaTrue_ParaCpfsValidos(string cpf)\n        => Assert.True(CpfValidator.IsValid(cpf));\n\n    [Theory]\n    [InlineData(\"000.000.000-00\")]  // sequência repetida\n    [InlineData(\"111.111.111-11\")]\n    [InlineData(\"529.982.247-26\")]  // segundo verificador errado\n    [InlineData(\"529.982.247-35\")]  // primeiro verificador errado\n    [InlineData(\"529.982.24\")]      // dígitos insuficientes\n    [InlineData(\"529.982.247-255\")] // dígitos em excesso\n    [InlineData(\"abc.def.ghi-jk\")]  // letras\n    [InlineData(\"\")]\n    [InlineData(null)]\n    public void IsValid_RetornaFalse_ParaCpfsInvalidos(string? cpf)\n        => Assert.False(CpfValidator.IsValid(cpf));\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Testar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ReadOnlySpan&lt;char&gt;</code> separadamente</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-csharp">{"[Fact]\npublic void IsValid_Span_AceitaFatiaDeStringMaior()\n{\n    const string linha = \"CPF: 529.982.247-25 (titular)\";\n    ReadOnlySpan<char> fatia = linha.AsSpan(5, 14); // \"529.982.247-25\"\n    Assert.True(CpfValidator.IsValid(fatia));\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Casos inválidos: sequências repetidas</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-csharp">{"[Theory]\n[InlineData(\"000.000.000-00\")]\n[InlineData(\"111.111.111-11\")]\n[InlineData(\"222.222.222-22\")]\n[InlineData(\"333.333.333-33\")]\n[InlineData(\"444.444.444-44\")]\n[InlineData(\"555.555.555-55\")]\n[InlineData(\"666.666.666-66\")]\n[InlineData(\"777.777.777-77\")]\n[InlineData(\"888.888.888-88\")]\n[InlineData(\"999.999.999-99\")]\npublic void IsValid_RetornaFalse_ParaSequenciasRepetidas(string cpf)\n    => Assert.False(CpfValidator.IsValid(cpf));"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">DICA: use o <Link href="/gerador-cpf" className="text-primary hover:underline">gerador de CPF</Link> para criar rapidamente novos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[InlineData]</code> válidos. Para lotes maiores, a <Link href="/docs" className="text-primary hover:underline">API do FakeForge</Link> retorna até 10.000 CPFs em uma chamada.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Integração com ASP.NET Core — atributo de validação customizado</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Criar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CpfAttribute : ValidationAttribute</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-csharp">{"[AttributeUsage(AttributeTargets.Property | AttributeTargets.Parameter)]\npublic sealed class CpfAttribute : ValidationAttribute\n{\n    protected override ValidationResult? IsValid(object? value, ValidationContext ctx)\n    {\n        var cpf = value as string;\n        if (CpfValidator.IsValid(cpf))\n            return ValidationResult.Success;\n\n        return new ValidationResult(\n            \"CPF informado é inválido.\",\n            new[] { ctx.MemberName ?? string.Empty });\n    }\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Aplicar no model e retornar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ProblemDetails</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-csharp">{"public record CriarContaRequest(\n    [Cpf] string Cpf,\n    string Nome\n);\n\n// No controller, a validação automática do ASP.NET Core\n// devolve ProblemDetails com status 400 quando [ApiController] está presente.\n// Nenhum código adicional necessário no action method."}</code></pre>
          <p className="mb-4">O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[ApiController]</code> já transforma erros de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ModelState</code> em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ProblemDetails</code> (RFC 7807). Nada extra no action.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Integração com FluentValidation</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regra com mensagem em português</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-csharp">{"public class CriarContaValidator : AbstractValidator<CriarContaRequest>\n{\n    public CriarContaValidator()\n    {\n        RuleFor(x => x.Cpf)\n            .NotEmpty().WithMessage(\"CPF é obrigatório.\")\n            .Must(CpfValidator.IsValid).WithMessage(\"CPF informado é inválido.\");\n\n        RuleFor(x => x.Nome)\n            .NotEmpty().WithMessage(\"Nome é obrigatório.\");\n    }\n}"}</code></pre>
          <p className="mb-4">Registre o validator no DI com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">services.AddFluentValidationAutoValidation()</code> (pacote <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">FluentValidation.AspNetCore</code>). O pipeline do ASP.NET Core chama o validator antes do action method, igual ao comportamento do <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[ApiController]</code> com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">DataAnnotations</code>.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Geração de CPFs falsos para os próprios testes</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que não usar CPFs reais em fixtures</h3>
          <p className="mb-4">CPF é dado pessoal direto segundo a <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 5º, I</a>. Inserir CPFs reais em fixtures de teste viola o princípio da minimização (LGPD Art. 6º, III) e pode gerar responsabilidade civil se o repositório for público. Use apenas CPFs gerados sinteticamente.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Chamar a API do FakeForge para gerar CPFs válidos em massa</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-http">{"GET /api/generate?type=cpf&quantity=50&format=json HTTP/1.1\nHost: fakeforge.com.br\nAccept: application/json"}</code></pre>
          <p className="mb-4">Resposta:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-json">{"{\n  \"_meta\": {\n    \"source\": \"FakeForge BR\",\n    \"url\": \"https://fakeforge.com.br\",\n    \"generated_at\": \"2026-06-03T10:00:00Z\",\n    \"license\": \"CC0 (public domain test data)\"\n  },\n  \"type\": \"cpf\",\n  \"quantity\": 50,\n  \"data\": [\n    \"529.982.247-25\",\n    \"871.048.410-18\",\n    \"153.509.460-56\"\n  ]\n}"}</code></pre>
          <p className="mb-4">O campo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">_meta</code> está presente em todas as respostas. O array <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">data</code> contém os CPFs prontos para uso em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[InlineData]</code>. Consulte a <Link href="/docs" className="text-primary hover:underline">referência completa da API</Link> para parâmetros de exportação CSV e SQL.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Seed local com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ICollectionFixture</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-csharp">{"public class CpfFixture\n{\n    // CPFs gerados via FakeForge /api/generate?type=cpf&quantity=10&format=json\n    public static readonly string[] CpfsValidos =\n    [\n        \"529.982.247-25\",\n        \"871.048.410-18\",\n        \"153.509.460-56\",\n        \"017.849.460-18\",\n        \"321.077.940-04\",\n        \"512.364.280-20\",\n        \"643.097.260-97\",\n        \"234.876.140-31\",\n        \"789.432.160-72\",\n        \"098.765.431-06\"\n    ];\n}\n\n[CollectionDefinition(\"Cpf\")]\npublic class CpfCollection : ICollectionFixture<CpfFixture> { }\n\n[Collection(\"Cpf\")]\npublic class CpfFixtureTests\n{\n    [Fact]\n    public void TodosOsCpfsDoSeedSaoValidos()\n    {\n        foreach (var cpf in CpfFixture.CpfsValidos)\n            Assert.True(CpfValidator.IsValid(cpf), $\"Falhou: {cpf}\");\n    }\n}"}</code></pre>
          <p className="mb-4">Regenere o seed periodicamente com a API. Valide online em <Link href="/validar-cpf" className="text-primary hover:underline">/validar-cpf</Link> antes de commitar.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Armadilhas comuns e como evitá-las</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Confundir mod-11 do CPF com mod-11 do CNPJ</h3>
          <p className="mb-4">O CNPJ usa pesos diferentes e duas rodadas com sequências distintas (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">5,4,3,2,9,8,7,6,5,4,3,2</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">6,5,4,3,2,9,8,7,6,5,4,3,2</code>). Copiar a lógica do CPF para o CNPJ e ajustar só o tamanho produz validação silenciosamente errada. Implemente separado. Veja a <Link href="/validar-cnpj" className="text-primary hover:underline">extensão para CNPJ</Link> como próximo passo.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Aceitar CPF com espaços ou letras sem sanitizar</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"529 982 247 25"</code> (espaços no lugar de pontuação) deve falhar porque espaço não é um separador previsto. O código acima rejeita qualquer caractere que não seja dígito, ponto ou hífen. Não expanda essa lista sem um caso de uso concreto.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Não tratar o resto 10 ou 11</h3>
          <p className="mb-4">Quando a soma ponderada multiplicada por 10, dividida por 11, resulta em 10 ou 11, o verificador é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>. Omitir esse ajuste faz o validador rejeitar CPFs válidos cujo dígito verificador é zero. O código usa <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">if (rem &gt;= 10) rem = 0;</code> para cobrir ambos os casos em uma linha.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">AVISO: o PIS/PASEP usa o mesmo algoritmo mod-11, mas com pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">3,2,9,8,7,6,5,4,3,2</code>. Não reaproveite <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CpfValidator</code> para PIS sem adaptar os pesos. Veja <Link href="/gerador-pis" className="text-primary hover:underline">gerador de PIS/PASEP</Link> para referência.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CpfValidator.IsValid</code> implementa as duas rodadas de mod-11 com eliminação de sequências repetidas, sem dependência externa.</li><li>A sobrecarga <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ReadOnlySpan&lt;char&gt;</code> evita alocação de heap; use-a em hot paths.</li><li><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CpfAttribute : ValidationAttribute</code> e a regra FluentValidation integram ao pipeline do ASP.NET Core sem código extra no controller.</li><li>CPF é dado pessoal (LGPD Art. 5º, I): use apenas CPFs sintéticos em fixtures. A <Link href="/docs" className="text-primary hover:underline">API do FakeForge</Link> gera lotes via <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">GET /api/generate?type=cpf&amp;quantity=N</code>.</li><li>O CNPJ usa pesos diferentes; implemente separado. O próximo passo natural é <Link href="/validar-cnpj" className="text-primary hover:underline">/validar-cnpj</Link>.</li><li>Regenere o seed de testes periodicamente e valide em <Link href="/validar-cpf" className="text-primary hover:underline">/validar-cpf</Link> antes de commitar.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Como validar um CPF durante o " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como validar um CPF durante o upload de um arquivo CSV sem falhar na primeira linha inválida?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Processe linha por linha, colecione erros em um array (posição, valor) e só lance exceção ao final. Use `StreamReader` com `IsValid(span)` para não alocar cada linha. Retorne `BadRequest` com lista de linhas rejeitadas para o cliente reprocessar, evitando upload redundante.</p>
            </details>
            <details key="Preciso salvar CPF validado no" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Preciso salvar CPF validado no banco. Qual é a melhor estratégia: armazenar formatado ou sem máscara?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Armazene sem máscara (`CHAR(11)` ou `VARCHAR(11)`). Índices são mais eficientes sem pontuação e buscas não falham por variações de formatação. Formatar é tarefa da view/API response, não do banco. Filtre CPFs formatados no controller antes da query se necessário.</p>
            </details>
            <details key="Posso reutilizar `ReadOnlySpan" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Posso reutilizar `ReadOnlySpan&lt;char&gt;` se extrair a substring de um arquivo grande em stream?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não. `ReadOnlySpan&lt;char&gt;` é válido só enquanto o buffer subjacente vive; próxima leitura descarta a memória anterior. Copie em `string` local ou use `stackalloc int[11]` para armazenar dígitos antes de passar ao `IsValid(span)`. Segurança &gt; micro-otimização aqui.</p>
            </details>
            <details key="O `CpfValidator.IsValid` lança" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">O `CpfValidator.IsValid` lança exceção ou retorna false para entrada null?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Retorna `false` sem exceção. Prático em model binding do ASP.NET Core: null e CPF inválido são capturados em `ModelState` automaticamente, sem try-catch. Use `[Required]` em cima se null é proibido; a validação composta então falha com mensagem clara.</p>
            </details>
            <details key="O CPF gerado via API do FakeFo" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">O CPF gerado via API do FakeForge sempre passa na validação, ou preciso testar cada um?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Todos passam; a API valida internamente antes de retornar. Não teste individual. Valide o endpoint uma vez em smoke test. Para milhões, exporte CSV/SQL e importe direto. Regenere seed de testes periodicamente para evitar viés amostral nos testes de integração.</p>
            </details>
          </div>
        </section>
        <ShareBar title={"Validar CPF em C# .NET: algoritmo mod-11 e xUnit"} path="/blog/validar-cpf-csharp-dotnet-mod11-xunit" />
        <BlogPostingSchema
          title={"Validar CPF em C# .NET: algoritmo mod-11 e xUnit"}
          slug="validar-cpf-csharp-dotnet-mod11-xunit"
          description={"Implemente a validação de CPF em C# do zero com o algoritmo mod-11, trate casos-limite e cubra tudo com xUnit. Código pronto para produção."}
          datePublished="2026-05-26"
          image="https://fakeforge.com.br/api/og?title=Validar%20CPF%20em%20C%23%20.NET%3A%20algoritmo%20mod-11%20e%20xUnit&subtitle=Implemente%20a%20valida%C3%A7%C3%A3o%20de%20CPF%20em%20C%23%20do%20zero%20com%20o%20algoritmo%20mod-11%2C%20trate%20casos-limite%20e%20cubra%20tudo%20com%20xUnit.%20C%C3%B3digo%20pronto%20para%20produ%C3%A7%C3%A3o.&category=TUTORIAIS"
        />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Como validar um CPF durante o upload de um arquivo CSV sem falhar na primeira linha inválida?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Processe linha por linha, colecione erros em um array (posição, valor) e só lance exceção ao final. Use `StreamReader` com `IsValid(span)` para não alocar cada linha. Retorne `BadRequest` com lista de linhas rejeitadas para o cliente reprocessar, evitando upload redundante.\"}},{\"@type\":\"Question\",\"name\":\"Preciso salvar CPF validado no banco. Qual é a melhor estratégia: armazenar formatado ou sem máscara?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Armazene sem máscara (`CHAR(11)` ou `VARCHAR(11)`). Índices são mais eficientes sem pontuação e buscas não falham por variações de formatação. Formatar é tarefa da view/API response, não do banco. Filtre CPFs formatados no controller antes da query se necessário.\"}},{\"@type\":\"Question\",\"name\":\"Posso reutilizar `ReadOnlySpan<char>` se extrair a substring de um arquivo grande em stream?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não. `ReadOnlySpan<char>` é válido só enquanto o buffer subjacente vive; próxima leitura descarta a memória anterior. Copie em `string` local ou use `stackalloc int[11]` para armazenar dígitos antes de passar ao `IsValid(span)`. Segurança > micro-otimização aqui.\"}},{\"@type\":\"Question\",\"name\":\"O `CpfValidator.IsValid` lança exceção ou retorna false para entrada null?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Retorna `false` sem exceção. Prático em model binding do ASP.NET Core: null e CPF inválido são capturados em `ModelState` automaticamente, sem try-catch. Use `[Required]` em cima se null é proibido; a validação composta então falha com mensagem clara.\"}},{\"@type\":\"Question\",\"name\":\"O CPF gerado via API do FakeForge sempre passa na validação, ou preciso testar cada um?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Todos passam; a API valida internamente antes de retornar. Não teste individual. Valide o endpoint uma vez em smoke test. Para milhões, exporte CSV/SQL e importe direto. Regenere seed de testes periodicamente para evitar viés amostral nos testes de integração.\"}}]}",
        }}
      />
    </PageShell>
  );
}
