import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";
import ShareBar from "@/components/ShareBar";

export const metadata: Metadata = {
  title: "Gerador de CPF válido online: como funciona e quando usar",
  description: "Entenda o algoritmo mod-11 do CPF, quando usar dados fictícios em testes e como gerar CPFs válidos sem violar a LGPD.",
  openGraph: {
    title: "Gerador de CPF válido online: como funciona e quando usar",
    description: "Entenda o algoritmo mod-11 do CPF, quando usar dados fictícios em testes e como gerar CPFs válidos sem violar a LGPD.",
    type: "article",
    images: ["/api/og?title=Gerador%20de%20CPF%20v%C3%A1lido%20online%3A%20como%20funciona%20e%20quando%20usar&subtitle=Entenda%20o%20algoritmo%20mod-11%20do%20CPF%2C%20quando%20usar%20dados%20fict%C3%ADcios%20em%20testes%20e%20como%20gerar%20CPFs%20v%C3%A1lidos%20sem%20violar%20a%20LGPD.&category=CONCEITOS"],
  },
  alternates: { canonical: "/blog/gerador-cpf-valido-online-como-funciona" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Conceitos" title="Gerador de CPF válido online: como funciona e quando usar" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Gerador de CPF válido online: como funciona e quando usar
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>04 de junho de 2026</time>
            <span>·</span>
            <span>8 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">O CPF segue uma estrutura matemática determinística. Qualquer ferramenta que entenda essa estrutura pode gerar documentos que passam em qualquer validador de formato, sem jamais tocar em dados reais de cidadãos brasileiros. Esse é o ponto de partida para entender o que um gerador de CPF faz e, principalmente, o que ele não faz.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O CPF tem estrutura matemática verificável</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Anatomia dos 11 dígitos</h3>
          <p className="mb-4">O Cadastro de Pessoas Físicas é composto por 11 dígitos numéricos organizados como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">NNN.NNN.NNN-DD</code>, onde:</p>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Posições 1-9: número de base, atribuído sequencialmente pela Receita Federal</li><li>Posições 10-11: dígitos verificadores calculados a partir dos nove primeiros</li></ul>
          <p className="mb-4">A máscara visual (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">123.456.789-09</code>) é apenas apresentação. O que importa ao validar é a sequência bruta de dígitos: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">12345678909</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cálculo dos dois dígitos verificadores (passo a passo com mod-11)</h3>
          <p className="mb-4">O algoritmo usa aritmética modular com base 11. Para o <strong className="text-foreground">primeiro dígito verificador</strong> (posição 10):</p>
          <p className="mb-4">1. Multiplique os 9 primeiros dígitos pelos pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">10, 9, 8, 7, 6, 5, 4, 3, 2</code>. 2. Some os produtos. 3. Calcule <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto = soma % 11</code>. 4. Se <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto &lt; 2</code>, o primeiro dígito verificador é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>. Caso contrário, é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - resto</code>.</p>
          <p className="mb-4">Para o <strong className="text-foreground">segundo dígito verificador</strong> (posição 11), repita o processo usando os 10 primeiros dígitos (incluindo o verificador recém-calculado) com pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11, 10, 9, 8, 7, 6, 5, 4, 3, 2</code>.</p>
          <p className="mb-4">Exemplo com o CPF <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">529.982.247-25</code>:</p>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Base: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">529982247</code></li><li>Pesos primeiro dígito: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">10→5, 9→2, 8→9, 7→9, 6→8, 5→2, 4→2, 3→4, 2→7</code></li><li>Soma: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">50+18+72+63+48+10+8+12+14 = 295</code></li><li><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">295 % 11 = 9</code> → primeiro dígito = <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - 9 = 2</code> ✓</li><li>Segundo verificador inclui o <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">2</code> calculado com peso <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11</code>: resultado <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">5</code> ✓</li></ul>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que um CPF aleatório quase nunca passa na validação</h3>
          <p className="mb-4">A probabilidade de 9 dígitos aleatórios produzirem verificadores corretos por acaso é de aproximadamente 1 em 100. Gerar números sem o cálculo dos verificadores resulta em rejeição imediata por qualquer biblioteca de validação, incluindo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cpf-check</code> (Node.js) e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">caelum-stella</code> (Java).</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Geradores de CPF calculam os verificadores, não inventam números</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferença entre "CPF válido por formato" e "CPF existente na Receita"</h3>
          <p className="mb-4">Um CPF gerado por software é <strong className="text-foreground">matematicamente válido</strong>, mas <strong className="text-foreground">não pertence a nenhuma pessoa</strong>. A Receita Federal não expõe endpoint público para verificar se um CPF está ativo na base. Ferramentas de consulta de situação cadastral (SERPRO, eCPF) requerem autenticação e retornam dados pessoais reais. Um gerador de CPF não faz consulta à Receita. O dado gerado é fictício e descartável.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Casos excluídos pelo algoritmo (111.111.111-11 e similares)</h3>
          <p className="mb-4">O algoritmo mod-11 exclui sequências onde todos os 9 dígitos de base são iguais. Esses números são tecnicamente inválidos porque os pesos produzem dígitos verificadores inconsistentes. Um gerador correto descarta essas sequências antes de calcular os verificadores.</p>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Sequência</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Motivo da exclusão</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">000.000.000-00</code></td><td className="px-3 py-2">Base zerada, verificadores impossíveis</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code></td><td className="px-3 py-2">Sequência repetida, inválida por convenção</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">999.999.999-99</code></td><td className="px-3 py-2">Idem</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Qualquer <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">NNN.NNN.NNN</code> com dígitos repetidos</td><td className="px-3 py-2">Todos excluídos pelo mesmo critério</td></tr></tbody></table></div>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como a semente aleatória garante distribuição uniforme</h3>
          <p className="mb-4">Bons geradores sorteiam os 9 dígitos de base via <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Math.random()</code> ou equivalente criptograficamente seguro, verificam se a sequência é de dígitos repetidos e, se não for, aplicam o cálculo dos verificadores. O resultado cobre aproximadamente 900 milhões de combinações válidas com distribuição razoavelmente uniforme.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Quando usar CPF fictício em testes é correto e legal</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Ambientes de desenvolvimento e staging (caso de uso central)</h3>
          <p className="mb-4">Qualquer sistema que processe CPF precisa testar fluxos de cadastro, validação de entrada, persistência e consulta. Usar dados fictícios nesses ambientes é a prática correta. O dado nunca existiu, não pertence a ninguém e não pode ser vinculado a uma pessoa natural, o que o exclui da definição de dado pessoal conforme a <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 5º, I</a>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Dados de seed em migrations e fixtures</h3>
          <p className="mb-4">Seed scripts criam estados iniciais para bancos de dados em desenvolvimento. Usar CPFs fictícios nesses scripts é idiomático e elimina dependência de dados reais para configurar o ambiente. Veja como integrar com Prisma na seção sobre a API REST abaixo.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Testes automatizados e pipelines de CI</h3>
          <p className="mb-4">Testes de integração que cobrem validação de CPF, fluxos de onboarding ou regras de negócio dependentes do documento precisam de entradas controladas. CPFs fictícios garantem determinismo: o mesmo valor de entrada sempre produz o mesmo comportamento esperado, sem risco de o dado "expirar" ou mudar de situação cadastral.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Demos, screenshots e materiais de treinamento</h3>
          <p className="mb-4">Manuais de sistema, apresentações internas e materiais de treinamento frequentemente precisam exibir documentos em telas. Usar um CPF fictício elimina o risco de exposição acidental de dados reais em capturas de tela ou gravações.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Quando usar CPF fictício viola a LGPD</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">LGPD Art. 7º, IX e o princípio da necessidade</h3>
          <p className="mb-4">O <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">Art. 7º, IX da LGPD</a> autoriza tratamento de dados pessoais quando necessário para atender interesses legítimos do controlador, desde que não prevaleçam direitos do titular. O princípio da necessidade (Art. 6º, III) exige que apenas os dados estritamente necessários sejam processados. Usar CPF real onde um fictício resolveria viola diretamente esse princípio.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O erro de copiar CPFs reais de produção para dev</h3>
          <p className="mb-4">Copiar dumps de produção para ambientes de desenvolvimento é uma das violações mais comuns e mais silenciosas. O ambiente de dev geralmente tem controles menores: logs mais verbosos, acesso mais amplo, menos monitoramento. Um CPF real nesse ambiente representa tratamento sem finalidade legítima para os dados do titular.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">AVISO:</strong> A ANPD já notificou empresas por compartilhamento indevido de bases de dados entre ambientes. A multa administrativa pode chegar a 2% do faturamento nacional, limitado a R$ 50 milhões por infração (LGPD Art. 52). Substitua dados reais por dados fictícios antes de qualquer cópia para dev ou staging.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Pseudonimização não é anonimização: o que o Art. 13 da LGPD diz</h3>
          <p className="mb-4">O <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">Art. 13 da LGPD</a> define pseudonimização como tratamento pelo qual o dado perde a possibilidade de associação ao titular sem uso de informação adicional mantida separadamente. Mascarar um CPF real (ex: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">*<strong className="text-foreground">.456.789-</strong></code>) não é anonimização: a sequência central ainda permite reidentificação combinada com outros campos. Dados gerados por algoritmo, sem base em registros reais, não têm esse problema.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Checklist antes de subir qualquer base de testes</h3>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>[ ] Nenhum CPF no dump pertence a um usuário real</li><li>[ ] Nenhum nome, email ou telefone é dado pessoal real</li><li>[ ] O ambiente de destino tem controles de acesso equivalentes ao de produção, ou os dados foram substituídos por fictícios</li><li>[ ] O seed script usa CPFs gerados, não copiados</li></ul>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O algoritmo mod-11 implementado em TypeScript</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">generateCPF()</code> do zero</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function generateCPF(): string {\n  const digits = Array.from({ length: 9 }, () => Math.floor(Math.random() * 10));\n\n  if (digits.every((d) => d === digits[0])) return generateCPF();\n\n  const calcVerifier = (base: number[], weight: number): number => {\n    const sum = base.reduce((acc, d, i) => acc + d * (weight - i), 0);\n    const remainder = sum % 11;\n    return remainder < 2 ? 0 : 11 - remainder;\n  };\n\n  const d1 = calcVerifier(digits, 10);\n  const d2 = calcVerifier([...digits, d1], 11);\n\n  return [...digits, d1, d2].join('');\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validateCPF()</code> cobrindo os edge cases</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function validateCPF(raw: string): boolean {\n  const cpf = raw.replace(/\\D/g, '');\n\n  if (cpf.length !== 11) return false;\n  if (/^(\\d)\\1{10}$/.test(cpf)) return false;\n\n  const digits = cpf.split('').map(Number);\n\n  const calcVerifier = (base: number[], weight: number): number => {\n    const sum = base.reduce((acc, d, i) => acc + d * (weight - i), 0);\n    const remainder = sum % 11;\n    return remainder < 2 ? 0 : 11 - remainder;\n  };\n\n  const d1 = calcVerifier(digits.slice(0, 9), 10);\n  const d2 = calcVerifier(digits.slice(0, 10), 11);\n\n  return d1 === digits[9] && d2 === digits[10];\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Teste unitário mínimo para os dois</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import { describe, it, expect } from 'vitest';\n\ndescribe('CPF', () => {\n  it('gera CPF com 11 dígitos numéricos', () => {\n    const cpf = generateCPF();\n    expect(cpf).toHaveLength(11);\n    expect(/^\\d{11}$/.test(cpf)).toBe(true);\n  });\n\n  it('CPF gerado passa na validação em 100 amostras', () => {\n    for (let i = 0; i < 100; i++) {\n      expect(validateCPF(generateCPF())).toBe(true);\n    }\n  });\n\n  it('rejeita sequências repetidas', () => {\n    expect(validateCPF('11111111111')).toBe(false);\n    expect(validateCPF('00000000000')).toBe(false);\n  });\n\n  it('rejeita CPF com tamanho errado', () => {\n    expect(validateCPF('1234567890')).toBe(false);\n    expect(validateCPF('123456789012')).toBe(false);\n  });\n\n  it('aceita CPF com máscara', () => {\n    expect(validateCPF('529.982.247-25')).toBe(true);\n  });\n\n  it('rejeita CPF com verificador errado', () => {\n    expect(validateCPF('529.982.247-26')).toBe(false);\n  });\n});"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Gerar CPF pela API REST sem código de validação próprio</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Chamada GET simples com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">type=cpf&amp;quantity=10</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=cpf&quantity=10&format=json\""}</code></pre>
          <p className="mb-4">A resposta inclui o campo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">_meta</code> com atribuição da fonte, seguido dos dados:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-json">{"{\n  \"_meta\": {\n    \"source\": \"FakeForge BR\",\n    \"url\": \"https://fakeforge.com.br\",\n    \"generated_at\": \"2026-06-04T10:00:00Z\",\n    \"license\": \"CC0\"\n  },\n  \"type\": \"cpf\",\n  \"quantity\": 10,\n  \"data\": [\"52998224725\", \"01234567890\"]\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Exportar lista em JSON, CSV e SQL para fixtures</h3>
          <p className="mb-4">Troque <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=json</code> por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=csv</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code>. O formato SQL retorna um bloco <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE</code> com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">INSERT INTO</code> pronto para colar em migrations. Os parâmetros completos estão em <Link href="/docs" className="text-primary hover:underline">/docs</Link>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Integrar com seed scripts do Prisma ou TypeORM</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import { PrismaClient } from '@prisma/client';\n\nconst prisma = new PrismaClient();\n\nasync function seed() {\n  const response = await fetch(\n    'https://fakeforge.com.br/api/generate?type=cpf&quantity=20&format=json'\n  );\n  const { data: cpfs } = await response.json();\n\n  await prisma.user.createMany({\n    data: cpfs.map((cpf: string, i: number) => ({\n      cpf,\n      name: `Usuário Teste ${i + 1}`,\n      email: `teste${i + 1}@example.com`,\n    })),\n    skipDuplicates: true,\n  });\n\n  await prisma.$disconnect();\n}\n\nseed();"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">DICA:</strong> Para gerar CPF junto com nome, endereço e contato correlacionados, onde o DDD do telefone bate com o estado do CEP, use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">type=pessoa</code>. Veja <Link href="/gerador-pessoa" className="text-primary hover:underline">/gerador-pessoa</Link>.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Ferramentas online: o que avaliar antes de usar</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">HTTPS e ausência de log server-side</h3>
          <p className="mb-4">Qualquer ferramenta que gere dados via formulário web deve operar sobre HTTPS. Mesmo sendo dados fictícios, o contexto de uso pode ser sensível. Prefira ferramentas que declarem explicitamente não registrar inputs do usuário.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Geração client-side vs server-side (implicação de privacidade)</h3>
          <p className="mb-4">Ferramentas que executam a geração inteiramente no navegador (JavaScript puro, sem chamada ao servidor) não enviam nada para infraestrutura externa. Ferramentas que chamam uma API server-side registram ao menos IP e timestamp nos logs do servidor. Para ambientes com políticas de segurança restritivas, isso é um critério relevante.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Suporte a bulk e formatos de exportação</h3>
          <p className="mb-4">Gerar um CPF por vez é ineficiente para seed scripts. Avalie se a ferramenta suporta geração em lote, exportação em CSV e SQL, e se existe API programática. O <Link href="/gerador-cpf" className="text-primary hover:underline">/gerador-cpf</Link> gera até 10.000 itens por chamada com exportação nos três formatos.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Validador de CPF: diferente do gerador, mesmo algoritmo</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quando você precisa validar, não gerar</h3>
          <p className="mb-4">Formulários de cadastro, integrações com sistemas legados e ETLs que recebem CPF como entrada precisam de validação, não de geração. O algoritmo é o mesmo mod-11, aplicado no sentido inverso: receber os 11 dígitos e confirmar se os verificadores batem. Use <Link href="/validar-cpf" className="text-primary hover:underline">/validar-cpf</Link> para verificar CPFs individualmente sem implementar o algoritmo.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como testar o validador com CPFs intencionalmente inválidos</h3>
          <p className="mb-4">Um validador robusto deve rejeitar:</p>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>CPFs com menos ou mais de 11 dígitos</li><li>Sequências com todos os dígitos iguais (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code>)</li><li>CPFs com verificadores incorretos (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">529.982.247-26</code> em vez de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">-25</code>)</li><li>Strings não numéricas após remoção de máscara</li></ul>
          <p className="mb-4">Use os casos acima como suite mínima de testes de regressão para qualquer implementação de validação de CPF.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Erros comuns ao trabalhar com CPF em código</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Comparar string com máscara vs sem máscara</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"529.982.247-25" === "52998224725"</code> retorna <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">false</code>. Normalize sempre antes de comparar: remova pontos, hífen e espaços via <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">replace(/\D/g, '')</code>. Armazene CPF sem máscara no banco. Aplique a máscara apenas na camada de apresentação.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Aceitar CPF com todos os dígitos iguais como válido</h3>
          <p className="mb-4">O regex <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/^(\d)\1&#123;10&#125;$/</code> captura qualquer sequência de 11 dígitos repetidos. Esse teste deve vir antes do cálculo dos verificadores, porque sequências como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code> satisfazem o mod-11 de forma espúria em algumas implementações incompletas.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Não remover pontuação antes de validar</h3>
          <p className="mb-4">Usuários digitam CPF com e sem máscara. Sistemas legados entregam CPF em formatos variados. A primeira linha de qualquer função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validateCPF</code> deve ser <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">const cpf = raw.replace(/\D/g, '')</code>. Qualquer validação feita antes dessa normalização vai gerar falsos negativos para entradas válidas com formatação diferente.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>O CPF é matematicamente verificável via mod-11: qualquer gerador correto calcula os dígitos verificadores com base nos 9 primeiros dígitos, não os sorteia aleatoriamente.</li><li>Dado gerado por algoritmo não é dado pessoal (LGPD Art. 5º, I) e pode ser usado livremente em dev, staging, CI e fixtures, sem necessidade de bases legais adicionais.</li><li>Copiar CPFs reais de produção para ambientes de desenvolvimento viola o princípio da necessidade da LGPD (Art. 6º, III) e expõe a empresa a sanções administrativas de até R$ 50 milhões por infração (Art. 52).</li><li>Pseudonimização parcial (mascaramento) não elimina o risco de reidentificação. Dados gerados por algoritmo, sem origem em registros reais, são a alternativa correta.</li><li>Para gerar CPF no navegador, use <Link href="/gerador-cpf" className="text-primary hover:underline">/gerador-cpf</Link>. Para validar um CPF existente, use <Link href="/validar-cpf" className="text-primary hover:underline">/validar-cpf</Link>. Para integrar via API REST com suporte a JSON, CSV e SQL, consulte <Link href="/docs" className="text-primary hover:underline">/docs</Link>.</li><li>Para gerar CPF junto com nome, endereço, telefone e email correlacionados em uma única chamada, use <Link href="/gerador-pessoa" className="text-primary hover:underline">/gerador-pessoa</Link>.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Preciso validar um CPF do usuá" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Preciso validar um CPF do usuário antes de chamar a API de geração?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">A API de geração já retorna CPFs validados (mod-11 correto). Use a API para gerar ou validar dados de entrada. Se receber CPF do usuário, valide primeiro com /validar-cpf antes de processá-lo, não antes de chamar a geração.</p>
            </details>
            <details key="Como faço para gerar CPFs que " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como faço para gerar CPFs que passem em validadores third-party tipo caelum-stella?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Todos os CPFs gerados pelo algoritmo mod-11 descrito passam em qualquer validador padrão (caelum-stella, cpf-check, nodejs). O ponto crítico é que calculamos os dígitos verificadores corretamente usando pesos mod-11. Compatibilidade com libs third-party está garantida. Use /api/generate com type=cpf e formato desejado.</p>
            </details>
            <details key="Posso usar a mesma seed de CPF" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Posso usar a mesma seed de CPF em testes paralelos sem gerar conflitos?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sim. CPFs gerados não são reais e não têm unicidade obrigatória. Se precisar de valores determinísticos idênticos entre rodadas, considere hardcoding um array de 100 CPFs válidos e distribuir entre jobs paralelos. Isso elimina race conditions no RNG e garante reprodutibilidade.</p>
            </details>
            <details key="Qual é a performance de gerar " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Qual é a performance de gerar 10 mil CPFs por chamada?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">A geração é O(n) linear. Dez mil CPFs respondem em &lt;500ms em conexão padrão. Se necessário maior volume, gere em lote e cachear CSVs/JSON em S3 ou cache. A API limita intencionalmente a 10k por chamada para evitar abuso. Para bulk recorrente, seed em banco local.</p>
            </details>
            <details key="Se uso CPF gerado em staging, " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Se uso CPF gerado em staging, consigo importá-lo em produção?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não recomendado. Dados fictícios devem ficar isolados em ambientes não-produção. Se código de produção tiver validação rígida contra Receita Federal, dados fictícios falharão. Use CPF fictício em dev/staging, dados reais apenas em prod conforme LGPD Art. 7º IX. Nunca misture ciclos.</p>
            </details>
          </div>
        </section>
        <ShareBar title={"Gerador de CPF válido online: como funciona e quando usar"} path="/blog/gerador-cpf-valido-online-como-funciona" />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Preciso validar um CPF do usuário antes de chamar a API de geração?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"A API de geração já retorna CPFs validados (mod-11 correto). Use a API para gerar ou validar dados de entrada. Se receber CPF do usuário, valide primeiro com /validar-cpf antes de processá-lo, não antes de chamar a geração.\"}},{\"@type\":\"Question\",\"name\":\"Como faço para gerar CPFs que passem em validadores third-party tipo caelum-stella?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Todos os CPFs gerados pelo algoritmo mod-11 descrito passam em qualquer validador padrão (caelum-stella, cpf-check, nodejs). O ponto crítico é que calculamos os dígitos verificadores corretamente usando pesos mod-11. Compatibilidade com libs third-party está garantida. Use /api/generate com type=cpf e formato desejado.\"}},{\"@type\":\"Question\",\"name\":\"Posso usar a mesma seed de CPF em testes paralelos sem gerar conflitos?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sim. CPFs gerados não são reais e não têm unicidade obrigatória. Se precisar de valores determinísticos idênticos entre rodadas, considere hardcoding um array de 100 CPFs válidos e distribuir entre jobs paralelos. Isso elimina race conditions no RNG e garante reprodutibilidade.\"}},{\"@type\":\"Question\",\"name\":\"Qual é a performance de gerar 10 mil CPFs por chamada?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"A geração é O(n) linear. Dez mil CPFs respondem em <500ms em conexão padrão. Se necessário maior volume, gere em lote e cachear CSVs/JSON em S3 ou cache. A API limita intencionalmente a 10k por chamada para evitar abuso. Para bulk recorrente, seed em banco local.\"}},{\"@type\":\"Question\",\"name\":\"Se uso CPF gerado em staging, consigo importá-lo em produção?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não recomendado. Dados fictícios devem ficar isolados em ambientes não-produção. Se código de produção tiver validação rígida contra Receita Federal, dados fictícios falharão. Use CPF fictício em dev/staging, dados reais apenas em prod conforme LGPD Art. 7º IX. Nunca misture ciclos.\"}}]}",
        }}
      />
    </PageShell>
  );
}
