import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";
import ShareBar from "@/components/ShareBar";
import BlogPostingSchema from "@/components/BlogPostingSchema";

export const metadata: Metadata = {
  title: "Popular PostgreSQL com dados brasileiros para staging",
  description: "Aprenda a gerar CPF, CNPJ, endereços e PIX válidos e inserir em um banco PostgreSQL de staging com scripts prontos e API REST.",
  openGraph: {
    title: "Popular PostgreSQL com dados brasileiros para staging",
    description: "Aprenda a gerar CPF, CNPJ, endereços e PIX válidos e inserir em um banco PostgreSQL de staging com scripts prontos e API REST.",
    type: "article",
    images: ["/api/og?title=Popular%20PostgreSQL%20com%20dados%20brasileiros%20para%20staging&subtitle=Aprenda%20a%20gerar%20CPF%2C%20CNPJ%2C%20endere%C3%A7os%20e%20PIX%20v%C3%A1lidos%20e%20inserir%20em%20um%20banco%20PostgreSQL%20de%20staging%20com%20scripts%20prontos%20e%20API%20REST.&category=TUTORIAIS"],
  },
  alternates: { canonical: "/blog/popular-postgresql-dados-brasileiros-staging" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Popular PostgreSQL com dados brasileiros para staging" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Popular PostgreSQL com dados brasileiros para staging
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>13 de maio de 2026</time>
            <span>·</span>
            <span>12 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">Usar dados de produção em ambiente de staging é um problema de compliance, não de conveniência. A alternativa prática é popular o banco com dados sintéticos válidos — CPFs que passam no mod-11, CNPJs com dígito verificador correto, endereços onde CEP, cidade e estado são coerentes entre si. Este guia mostra como fazer isso do zero com PostgreSQL, um script TypeScript e a <Link href="/docs" className="text-primary hover:underline">API REST do FakeForge</Link>.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Staging com dados reais é um risco desnecessário</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que a LGPD Art. 7º diz sobre uso de dados pessoais em ambientes de teste</h3>
          <p className="mb-4">A <a href="https://www.planalto.gov.br/ccivil_03/_ato2018-2022/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">Lei Geral de Proteção de Dados (LGPD)</a> exige base legal para cada operação de tratamento de dados pessoais. O Art. 7º lista as hipóteses permitidas; nenhuma delas cobre "copiar CPFs reais para o banco de staging porque é mais fácil". O Art. 46 vai além: exige que o controlador adote medidas técnicas para proteger dados pessoais de acessos não autorizados. Um banco de staging acessível por toda a equipe de desenvolvimento, sem as mesmas proteções do banco de produção, viola esse princípio.</p>
          <p className="mb-4">A sanção administrativa (Art. 52) pode chegar a 2% do faturamento bruto, limitada a R$ 50 milhões por infração. O risco não compensa.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que dados mascarados frequentemente corrompem testes de integração</h3>
          <p className="mb-4">Mascaramento substitui valores reais por valores aleatórios — um CPF vira uma sequência de 11 dígitos sem validade de checksum. Isso quebra:</p>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Validações de frontend que conferem o dígito verificador antes de submeter o formulário</li><li>Integrações com gateways de pagamento que rejeitam CPFs inválidos no sandbox</li><li>Testes de fluxo de emissão de nota fiscal onde o CNPJ precisa ser válido</li></ul>
          <p className="mb-4">O resultado são falsos negativos nos testes: o código está certo, mas o teste falha por causa do dado.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">A alternativa: dados sintéticos válidos que respeitam regras de negócio brasileiras</h3>
          <p className="mb-4">Dados sintéticos gerados com as mesmas regras do dado real — mod-11 para CPF/CNPJ, algoritmo de Luhn para cartões, correlação CEP × DDD × estado — passam em todas as validações sem expor nenhuma pessoa real. É o melhor dos dois mundos: compliance com a LGPD e testes que refletem o comportamento em produção.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O que faz um dado brasileiro "válido" para testes</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Dígitos verificadores: CPF mod-11, CNPJ mod-11, Luhn para cartões</h3>
          <p className="mb-4">CPF e CNPJ usam o algoritmo mod-11 em dois dígitos verificadores. Um CPF gerado aleatoriamente tem cerca de 1% de chance de ser válido por acaso — suficiente para passar em alguns testes, mas garantido para falhar em outros. Geradores que implementam o cálculo correto eliminam essa variância.</p>
          <p className="mb-4">Cartões de crédito usam o algoritmo de Luhn: a soma dos dígitos, com pesos alternados, deve ser divisível por 10. O <Link href="/gerador-cartao" className="text-primary hover:underline">gerador de cartão de crédito</Link> do FakeForge implementa Luhn para Visa, Mastercard, Elo, Hipercard e Amex.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Correlação entre campos: CEP, DDD, estado e cidade precisam bater</h3>
          <p className="mb-4">Um endereço com CEP <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">01310-100</code> (Av. Paulista, São Paulo) e DDD <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">51</code> (Porto Alegre) quebra testes de validação de endereço e cálculo de frete. Dados correlacionados garantem que todos os campos de um registro sejam internamente consistentes.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Dados financeiros: chaves PIX, códigos ISPB/BACEN, agência e conta</h3>
          <p className="mb-4">O BACEN define o ISPB (Identificador de Sistema de Pagamentos Brasileiro) de cada instituição. Uma chave PIX do tipo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">evp</code> tem formato UUID; do tipo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cpf</code>, 11 dígitos; do tipo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">telefone</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">+55</code> seguido de DDD e número; do tipo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">email</code>, formato RFC 5322. Misturar formatos invalida a chave no ambiente de sandbox dos bancos. O <Link href="/gerador-pix" className="text-primary hover:underline">gerador de PIX</Link> cobre os quatro formatos.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Requisitos do ambiente antes de começar</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">PostgreSQL 14+ e extensão pgcrypto (para UUIDs nativos)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"-- Habilitar geração de UUID no banco\nCREATE EXTENSION IF NOT EXISTS pgcrypto;\n\n-- Verificar versão\nSELECT version();\n-- PostgreSQL 14.x ou superior recomendado"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Node.js 18+ ou Python 3.10+ para os scripts de seed</h3>
          <p className="mb-4">O script usa <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">fetch</code> nativo (disponível a partir do Node.js 18 sem flag experimental) e o driver <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">postgres</code> (também conhecido como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">postgres.js</code>). Instale as dependências:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"npm install postgres dotenv"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Variáveis de ambiente e conexão segura ao banco de staging</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"# .env (nunca commitar)\nDATABASE_URL=postgresql://user:senha@staging-host:5432/staging_db?sslmode=require\nFAKEFORGE_API_KEY=ff_live_xxxxxxxxxxxxxxxx"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">AVISO:</strong> Nunca use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">sslmode=disable</code> em staging. Conexões não criptografadas expõem credenciais e dados em trânsito, violando o Art. 46 da LGPD independente de o dado ser sintético ou real.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Gerar os dados com a API FakeForge</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Endpoint GET <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/api/generate</code> — parâmetros <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">type</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">quantity</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format</code></h3>
          <p className="mb-4">A <Link href="/docs" className="text-primary hover:underline">referência completa da API REST</Link> documenta todos os tipos disponíveis. A chamada mais simples:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-">{"GET https://fakeforge.com.br/api/generate?type=pessoa&quantity=100&format=json\nAuthorization: Bearer ff_live_xxxxxxxxxxxxxxxx"}</code></pre>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Parâmetro</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Valores aceitos</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Padrão</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">type</code></td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cpf</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cnpj</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pessoa</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">empresa</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pix</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cartao</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cep</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">conta</code></td><td className="px-3 py-2">obrigatório</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">quantity</code></td><td className="px-3 py-2">1 – 10.000</td><td className="px-3 py-2">1</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format</code></td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">json</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">csv</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">sql</code></td><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">json</code></td></tr></tbody></table></div>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Exportar direto em SQL com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code>: CREATE TABLE já incluído</h3>
          <p className="mb-4">Com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code>, a resposta inclui o <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE IF NOT EXISTS</code> e os <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">INSERT INTO</code> prontos para execução. Útil para ambientes onde você quer importar sem escrever DDL manualmente.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Autenticação com API key e limites de rate (100 chamadas/dia no plano gratuito)</h3>
          <p className="mb-4">O <Link href="/pricing" className="text-primary hover:underline">plano gratuito</Link> permite 100 chamadas por dia. O plano Dev (R$ 29/mês) sobe para 10.000 chamadas/dia. Para um seed de 1.000 pessoas + 500 empresas + 2.000 transações, o plano gratuito não é suficiente — planeje com o plano Dev ou faça cache local do resultado gerado.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Gerar em lote com script TypeScript usando <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">fetch</code> e loop por tipo</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// src/seed/fetchData.ts\nasync function fetchWithRetry(\n  url: string,\n  apiKey: string,\n  retries = 3\n): Promise<unknown[]> {\n  for (let attempt = 1; attempt <= retries; attempt++) {\n    const res = await fetch(url, {\n      headers: { Authorization: `Bearer ${apiKey}` },\n    });\n\n    if (res.status === 429) {\n      const retryAfter = Number(res.headers.get(\"Retry-After\") ?? 60);\n      console.log(`Rate limit atingido. Aguardando ${retryAfter}s...`);\n      await new Promise((r) => setTimeout(r, retryAfter * 1000));\n      continue;\n    }\n\n    if (!res.ok) throw new Error(`HTTP ${res.status}: ${await res.text()}`);\n    const data = await res.json();\n    return data as unknown[];\n  }\n  throw new Error(\"Número máximo de tentativas atingido.\");\n}"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Modelar o schema PostgreSQL para dados brasileiros</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Tipos corretos para CPF (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(11)</code>), CNPJ (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(14)</code>), CEP (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(8)</code>)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"CREATE TABLE pessoas (\n  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n  nome        VARCHAR(120) NOT NULL,\n  cpf         CHAR(11)    NOT NULL UNIQUE,\n  email       VARCHAR(254) NOT NULL,\n  telefone    VARCHAR(15),\n  cep         CHAR(8)     NOT NULL,\n  logradouro  VARCHAR(200),\n  cidade      VARCHAR(100),\n  estado      CHAR(2),\n  criado_em   TIMESTAMPTZ DEFAULT NOW()\n);\n\nCREATE TABLE empresas (\n  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n  razao_social VARCHAR(200) NOT NULL,\n  cnpj        CHAR(14)    NOT NULL UNIQUE,\n  email       VARCHAR(254),\n  cep         CHAR(8),\n  cidade      VARCHAR(100),\n  estado      CHAR(2),\n  criado_em   TIMESTAMPTZ DEFAULT NOW()\n);\n\nCREATE TYPE pix_tipo AS ENUM ('cpf', 'cnpj', 'telefone', 'email', 'evp');\n\nCREATE TABLE transacoes (\n  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n  pessoa_id   UUID        REFERENCES pessoas(id),\n  pix_chave   VARCHAR(77),\n  pix_tipo    pix_tipo,\n  banco_nome  VARCHAR(100),\n  agencia     VARCHAR(10),\n  conta       VARCHAR(20),\n  cartao_numero CHAR(16),\n  cartao_bandeira VARCHAR(20),\n  criado_em   TIMESTAMPTZ DEFAULT NOW()\n);"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Constraints de CHECK para validar formato no banco</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"ALTER TABLE pessoas\n  ADD CONSTRAINT cpf_formato CHECK (cpf ~ '^\\d{11}$'),\n  ADD CONSTRAINT cep_formato CHECK (cep ~ '^\\d{8}$'),\n  ADD CONSTRAINT estado_formato CHECK (estado ~ '^[A-Z]{2}$');\n\nALTER TABLE empresas\n  ADD CONSTRAINT cnpj_formato CHECK (cnpj ~ '^\\d{14}$');"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Script de seed completo em TypeScript</h2>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// src/seed/index.ts\nimport postgres from \"postgres\";\nimport \"dotenv/config\";\n\nconst sql = postgres(process.env.DATABASE_URL!);\nconst API_BASE = \"https://fakeforge.com.br/api/generate\";\nconst API_KEY = process.env.FAKEFORGE_API_KEY!;\n\nasync function fetchData(type: string, quantity: number): Promise<unknown[]> {\n  const url = `${API_BASE}?type=${type}&quantity=${quantity}&format=json`;\n  const res = await fetch(url, {\n    headers: { Authorization: `Bearer ${API_KEY}` },\n  });\n  if (!res.ok) throw new Error(`Erro ao buscar ${type}: HTTP ${res.status}`);\n  return res.json() as Promise<unknown[]>;\n}\n\nasync function seedPessoas() {\n  const pessoas = await fetchData(\"pessoa\", 1000) as Array<{\n    nome: string; cpf: string; email: string; telefone: string;\n    cep: string; logradouro: string; cidade: string; estado: string;\n  }>;\n\n  await sql`\n    INSERT INTO pessoas (nome, cpf, email, telefone, cep, logradouro, cidade, estado)\n    SELECT nome, cpf, email, telefone, cep, logradouro, cidade, estado\n    FROM ${sql(pessoas)}\n    ON CONFLICT (cpf) DO NOTHING\n  `;\n  console.log(`Pessoas inseridas: até ${pessoas.length}`);\n}\n\nasync function seedEmpresas() {\n  const empresas = await fetchData(\"empresa\", 500) as Array<{\n    razao_social: string; cnpj: string; email: string;\n    cep: string; cidade: string; estado: string;\n  }>;\n\n  await sql`\n    INSERT INTO empresas (razao_social, cnpj, email, cep, cidade, estado)\n    SELECT razao_social, cnpj, email, cep, cidade, estado\n    FROM ${sql(empresas)}\n    ON CONFLICT (cnpj) DO NOTHING\n  `;\n  console.log(`Empresas inseridas: até ${empresas.length}`);\n}\n\nasync function seedTransacoes() {\n  const [pix, contas] = await Promise.all([\n    fetchData(\"pix\", 2000),\n    fetchData(\"conta\", 2000),\n  ]);\n\n  // Buscar IDs de pessoas para associar às transações\n  const ids = await sql<{ id: string }[]>`SELECT id FROM pessoas LIMIT 2000`;\n\n  const rows = ids.map((p, i) => ({\n    pessoa_id: p.id,\n    pix_chave: (pix[i] as { chave: string }).chave,\n    pix_tipo: (pix[i] as { tipo: string }).tipo,\n    banco_nome: (contas[i] as { banco: string }).banco,\n    agencia: (contas[i] as { agencia: string }).agencia,\n    conta: (contas[i] as { conta: string }).conta,\n  }));\n\n  await sql`\n    INSERT INTO transacoes (pessoa_id, pix_chave, pix_tipo, banco_nome, agencia, conta)\n    SELECT pessoa_id, pix_chave, pix_tipo::pix_tipo, banco_nome, agencia, conta\n    FROM ${sql(rows)}\n    ON CONFLICT DO NOTHING\n  `;\n  console.log(`Transações inseridas: até ${rows.length}`);\n}\n\nasync function main() {\n  await seedPessoas();\n  await seedEmpresas();\n  await seedTransacoes();\n  await sql.end();\n}\n\nmain().catch((err) => { console.error(err); process.exit(1); });"}</code></pre>
          <p className="mb-4">O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ON CONFLICT DO NOTHING</code> garante idempotência: rodar o script duas vezes não duplica registros.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Usar o export SQL direto do FakeForge</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Baixar o arquivo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">.sql</code> pela UI ou via API com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl -s \\\n  \"https://fakeforge.com.br/api/generate?type=pessoa&quantity=500&format=sql\" \\\n  -H \"Authorization: Bearer $FAKEFORGE_API_KEY\" \\\n  -o seed_pessoas.sql"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Executar com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">psql -f seed.sql</code> ou via migration (Flyway/Liquibase)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"psql \"$DATABASE_URL\" -f seed_pessoas.sql"}</code></pre>
          <p className="mb-4">Para Flyway, salve o arquivo como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">V2__seed_staging.sql</code> no diretório de migrations. O prefixo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">V</code> indica migration versionada; use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">R</code> (repeatable) se quiser reexecutar a cada sprint.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Adaptar o DDL gerado ao schema existente do projeto</h3>
          <p className="mb-4">O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE IF NOT EXISTS</code> gerado pelo FakeForge usa nomes de coluna em português. Se o schema do seu projeto usa inglês, ajuste com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">sed</code> antes de importar ou edite o arquivo manualmente. O DDL gerado é um ponto de partida, não um requisito.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Automatizar o seed em CI/CD</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">GitHub Actions: step de seed antes dos testes de integração</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-yaml">{"# .github/workflows/integration.yml\nname: Integration Tests\n\non: [push, pull_request]\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    services:\n      postgres:\n        image: postgres:16\n        env:\n          POSTGRES_USER: ci\n          POSTGRES_PASSWORD: ci\n          POSTGRES_DB: staging_test\n        options: >-\n          --health-cmd pg_isready\n          --health-interval 10s\n          --health-timeout 5s\n          --health-retries 5\n        ports:\n          - 5432:5432\n\n    steps:\n      - uses: actions/checkout@v4\n\n      - uses: actions/setup-node@v4\n        with:\n          node-version: \"20\"\n\n      - run: npm ci\n\n      - name: Aplicar migrations\n        env:\n          DATABASE_URL: postgresql://ci:ci@localhost:5432/staging_test\n        run: npm run migrate\n\n      - name: Seed com dados sintéticos\n        env:\n          DATABASE_URL: postgresql://ci:ci@localhost:5432/staging_test\n          FAKEFORGE_API_KEY: ${{ secrets.SEED_API_KEY }}\n        run: npx ts-node src/seed/index.ts\n\n      - name: Rodar testes de integração\n        env:\n          DATABASE_URL: postgresql://ci:ci@localhost:5432/staging_test\n        run: npm run test:integration"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">DICA:</strong> Armazene <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">SEED_API_KEY</code> nos GitHub Secrets (Settings → Secrets → Actions). Nunca coloque a key no código ou em arquivos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">.env</code> commitados.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Docker Compose com init script para ambiente local</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-yaml">{"# docker-compose.yml\nservices:\n  db:\n    image: postgres:16\n    environment:\n      POSTGRES_USER: dev\n      POSTGRES_PASSWORD: dev\n      POSTGRES_DB: staging\n    volumes:\n      - ./sql/init:/docker-entrypoint-initdb.d\n    ports:\n      - \"5432:5432\""}</code></pre>
          <p className="mb-4">Coloque os arquivos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">.sql</code> exportados pelo FakeForge em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">./sql/init/</code>. O PostgreSQL executa todos os arquivos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">*.sql</code> nesse diretório na ordem alfabética ao criar o container pela primeira vez.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Validar os dados inseridos no banco</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Query SQL para checar CPFs com dígito verificador inválido</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"-- Retorna CPFs que não passam na verificação de formato básico\n-- (validação completa do mod-11 requer função PL/pgSQL)\nSELECT cpf, nome\nFROM pessoas\nWHERE cpf !~ '^\\d{11}$'\n   OR cpf = repeat(substring(cpf, 1, 1), 11); -- rejeita sequências como '11111111111'"}</code></pre>
          <p className="mb-4">Para validação completa do mod-11 dentro do banco, implemente uma função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">is_cpf_valido(text)</code> em PL/pgSQL ou use o <Link href="/validar-cpf" className="text-primary hover:underline">endpoint <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/validar-cpf</code></Link> em um script de smoke test pós-seed.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Testar correlação CEP × estado com JOIN em tabela de referência</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"-- Prefixos de CEP por estado (amostra)\nCREATE TEMP TABLE cep_estados (prefixo CHAR(2), estado CHAR(2));\nINSERT INTO cep_estados VALUES\n  ('01', 'SP'), ('20', 'RJ'), ('30', 'MG'),\n  ('40', 'BA'), ('60', 'CE'), ('70', 'DF'),\n  ('80', 'PR'), ('90', 'RS');\n\nSELECT p.cpf, p.cep, p.estado, ce.estado AS estado_esperado\nFROM pessoas p\nLEFT JOIN cep_estados ce ON LEFT(p.cep, 2) = ce.prefixo\nWHERE ce.estado IS DISTINCT FROM p.estado\nLIMIT 20;"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Endpoint <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/validar-cpf</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/validar-cnpj</code> para smoke test pós-seed</h3>
          <p className="mb-4">Após o seed, chame os endpoints de <Link href="/validar-cpf" className="text-primary hover:underline">validação de CPF</Link> e <Link href="/validar-cnpj" className="text-primary hover:underline">validação de CNPJ</Link> em uma amostra aleatória para confirmar que os dados gerados são válidos do ponto de vista do mod-11.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Boas práticas de segurança e conformidade LGPD</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Isolar banco de staging na VPC — sem rota pública</h3>
          <p className="mb-4">O banco de staging nunca deve ter endpoint público. Configure security groups (AWS) ou firewall rules (GCP/Azure) para aceitar conexões apenas de dentro da VPC privada. Mesmo dados sintéticos expostos publicamente criam superfície de ataque desnecessária.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Nunca promover dados de staging para produção (LGPD Art. 46)</h3>
          <p className="mb-4">O <a href="https://www.planalto.gov.br/ccivil_03/_ato2018-2022/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">Art. 46 da LGPD</a> exige que o controlador implemente medidas técnicas para proteger dados pessoais. Promover um dump de staging para produção — mesmo com dados sintéticos — cria confusão operacional e pode misturar dados se o processo não for rigoroso. Separe os ambientes por banco, por credencial e por pipeline de deploy.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Rotation automático do seed a cada sprint para evitar fixação de padrões</h3>
          <p className="mb-4">Dados fixos por meses criam memorização involuntária: desenvolvedores decoram CPFs e CNPJs específicos, testes passam por acidente porque assumem valores hardcoded. Automatize o re-seed a cada início de sprint com um job agendado no CI/CD.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li><strong className="text-foreground">Schema primeiro:</strong> defina <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(11)</code> para CPF, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(14)</code> para CNPJ, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(8)</code> para CEP e use constraints de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHECK</code> para garantir formato no banco antes de inserir qualquer dado.</li><li><strong className="text-foreground">API FakeForge:</strong> use o <Link href="/docs" className="text-primary hover:underline">endpoint <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/api/generate</code></Link> com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=json</code> para seed programático ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code> para importação direta via <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">psql -f</code>.</li><li><strong className="text-foreground">Idempotência:</strong> sempre use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ON CONFLICT DO NOTHING</code> nos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">INSERT INTO</code> do script de seed para poder reexecutar sem duplicar registros.</li><li><strong className="text-foreground">CI/CD:</strong> adicione o step de seed como pré-condição dos testes de integração no GitHub Actions, com a API key em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">secrets.SEED_API_KEY</code> e nunca em texto plano.</li><li><strong className="text-foreground">Validação pós-seed:</strong> execute as queries de verificação de formato e correlação CEP × estado, e chame os endpoints <Link href="/validar-cpf" className="text-primary hover:underline">/validar-cpf</Link> e <Link href="/validar-cnpj" className="text-primary hover:underline">/validar-cnpj</Link> em amostra antes de liberar o ambiente para os testes.</li><li><strong className="text-foreground">Compliance:</strong> isole o banco de staging na VPC, nunca promova dados para produção e rotacione o seed a cada sprint — requisitos derivados da LGPD Art. 7º e Art. 46, não apenas boas práticas.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Como reutilizar dados gerados " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como reutilizar dados gerados para economizar rate limit do plano gratuito?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Gere uma única vez com `format=sql`, commit o arquivo no repositório (ou em artifact do CI), e reutilize em todas as pipelines. Ou cache o resultado JSON em S3/GitHub Actions artifacts. Evita chamar a API múltiplas vezes por PR/branch.</p>
            </details>
            <details key="Qual a ordem correta de execuç" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Qual a ordem correta de execução do seed: pessoas → empresas → transações?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Pessoas primeiro (sem foreign keys), depois empresas (FK pessoa), depois transações (FK pessoa+empresa). Use `await Promise.all()` apenas entre jobs independentes. Antes de inserir transações, execute `SELECT id FROM pessoas` no banco para coletar IDs reais e garantir integridade de FK.</p>
            </details>
            <details key="Como garanto que pessoa_id nas" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como garanto que pessoa_id nas transações realmente existe no banco?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não gere UUIDs client-side aleatoriamente. Execute `SELECT id FROM pessoas LIMIT X` no script TypeScript antes de montar os rows de transações. Ou use gerador que retorna relacionamentos já pré-conectados no JSON (pessoa_id + transação). Evita violação de FK.</p>
            </details>
            <details key="Se dados são sintéticos em sta" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Se dados são sintéticos em staging, por que ainda precisam de isolamento LGPD?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sim. LGPD Art. 46 exige proteção para *qualquer* dado estruturado como pessoal, sintético ou não. Implemente VPC privada, nenhum endpoint público, zero credenciais em código, RBAC para acesso. Compliance é sobre *processo* de tratamento, não apenas se valor é factual.</p>
            </details>
            <details key="Qual é a forma recomendada par" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Qual é a forma recomendada para validar CPF mod-11 dentro do PostgreSQL?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Cria função PL/pgSQL com o algoritmo mod-11 completo ou usa trigger BEFORE INSERT para rejeitar inválidos. Mais prático: valida em application-side (TypeScript) antes do INSERT, usando a biblioteca interna do FakeForge; é mais testável, reutilizável e rápido.</p>
            </details>
          </div>
        </section>
        <ShareBar title={"Popular PostgreSQL com dados brasileiros para staging"} path="/blog/popular-postgresql-dados-brasileiros-staging" />
        <BlogPostingSchema
          title={"Popular PostgreSQL com dados brasileiros para staging"}
          slug="popular-postgresql-dados-brasileiros-staging"
          description={"Aprenda a gerar CPF, CNPJ, endereços e PIX válidos e inserir em um banco PostgreSQL de staging com scripts prontos e API REST."}
          datePublished="2026-05-26"
          image="https://fakeforge.com.br/api/og?title=Popular%20PostgreSQL%20com%20dados%20brasileiros%20para%20staging&subtitle=Aprenda%20a%20gerar%20CPF%2C%20CNPJ%2C%20endere%C3%A7os%20e%20PIX%20v%C3%A1lidos%20e%20inserir%20em%20um%20banco%20PostgreSQL%20de%20staging%20com%20scripts%20prontos%20e%20API%20REST.&category=TUTORIAIS"
        />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Como reutilizar dados gerados para economizar rate limit do plano gratuito?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Gere uma única vez com `format=sql`, commit o arquivo no repositório (ou em artifact do CI), e reutilize em todas as pipelines. Ou cache o resultado JSON em S3/GitHub Actions artifacts. Evita chamar a API múltiplas vezes por PR/branch.\"}},{\"@type\":\"Question\",\"name\":\"Qual a ordem correta de execução do seed: pessoas → empresas → transações?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Pessoas primeiro (sem foreign keys), depois empresas (FK pessoa), depois transações (FK pessoa+empresa). Use `await Promise.all()` apenas entre jobs independentes. Antes de inserir transações, execute `SELECT id FROM pessoas` no banco para coletar IDs reais e garantir integridade de FK.\"}},{\"@type\":\"Question\",\"name\":\"Como garanto que pessoa_id nas transações realmente existe no banco?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não gere UUIDs client-side aleatoriamente. Execute `SELECT id FROM pessoas LIMIT X` no script TypeScript antes de montar os rows de transações. Ou use gerador que retorna relacionamentos já pré-conectados no JSON (pessoa_id + transação). Evita violação de FK.\"}},{\"@type\":\"Question\",\"name\":\"Se dados são sintéticos em staging, por que ainda precisam de isolamento LGPD?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sim. LGPD Art. 46 exige proteção para *qualquer* dado estruturado como pessoal, sintético ou não. Implemente VPC privada, nenhum endpoint público, zero credenciais em código, RBAC para acesso. Compliance é sobre *processo* de tratamento, não apenas se valor é factual.\"}},{\"@type\":\"Question\",\"name\":\"Qual é a forma recomendada para validar CPF mod-11 dentro do PostgreSQL?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Cria função PL/pgSQL com o algoritmo mod-11 completo ou usa trigger BEFORE INSERT para rejeitar inválidos. Mais prático: valida em application-side (TypeScript) antes do INSERT, usando a biblioteca interna do FakeForge; é mais testável, reutilizável e rápido.\"}}]}",
        }}
      />
    </PageShell>
  );
}
