import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";
import ShareBar from "@/components/ShareBar";
import BlogPostingSchema from "@/components/BlogPostingSchema";

export const metadata: Metadata = {
  title: "Como mockar CEP no Cypress com dados brasileiros falsos",
  description: "Aprenda a interceptar chamadas de CEP no Cypress e retornar endereços brasileiros falsos e coerentes — sem depender de APIs externas nos seus testes.",
  openGraph: {
    title: "Como mockar CEP no Cypress com dados brasileiros falsos",
    description: "Aprenda a interceptar chamadas de CEP no Cypress e retornar endereços brasileiros falsos e coerentes — sem depender de APIs externas nos seus testes.",
    type: "article",
    images: ["/api/og?title=Como%20mockar%20CEP%20no%20Cypress%20com%20dados%20brasileiros%20falsos&subtitle=Aprenda%20a%20interceptar%20chamadas%20de%20CEP%20no%20Cypress%20e%20retornar%20endere%C3%A7os%20brasileiros%20falsos%20e%20coerentes%20%E2%80%94%20sem%20depender%20de%20APIs%20externas%20nos%20seu&category=TUTORIAIS"],
  },
  alternates: { canonical: "/blog/mockar-cep-cypress-dados-brasileiros-falsos" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Como mockar CEP no Cypress com dados brasileiros falsos" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Como mockar CEP no Cypress com dados brasileiros falsos
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>21 de maio de 2026</time>
            <span>·</span>
            <span>9 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">Testes E2E que dependem de APIs externas quebram. Não é hipótese — é certeza estatística. Se o seu fluxo de checkout, cadastro ou validação de endereço faz uma chamada real para ViaCEP ou BrasilAPI durante o Cypress, você está transferindo a responsabilidade de estabilidade do seu pipeline para um servidor que você não controla. Este guia resolve isso: você vai interceptar essas chamadas, substituí-las por dados brasileiros falsos e coerentes, e manter seus testes verdes independente de qualquer dependência externa.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O problema real: testes E2E quebrando por dependência de CEP externo</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que consultar ViaCEP ou BrasilAPI nos testes é arriscado</h3>
          <p className="mb-4">ViaCEP e BrasilAPI são excelentes para produção. Para testes, são fontes de flakiness. O problema não é a qualidade dos serviços — é a natureza do teste E2E: você precisa de controle total sobre os dados de entrada e saída. Quando o CEP digitado no teste retorna dados diferentes dependendo do dia (endereço atualizado, bairro renomeado, CEP descontinuado), suas assertions falham por motivos que não têm nada a ver com o código que você está testando.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Flakiness causada por rate limit, timeout e dados inconsistentes</h3>
          <p className="mb-4">A BrasilAPI aplica rate limiting. Em pipelines de CI com múltiplos workers rodando testes em paralelo, você vai atingir esse limite. O resultado: requisições com status 429 ou timeout, campos de endereço vazios no DOM, assertions falhando com mensagens que parecem bugs da aplicação mas são só throttling de API. Além disso, CEPs reais mudam. O Correios atualiza sua base regularmente — um CEP que existia ontem pode retornar objeto vazio amanhã.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que significa "mockar" uma API no contexto do Cypress</h3>
          <p className="mb-4">Mockar no Cypress significa interceptar uma requisição HTTP antes que ela saia do browser e devolver uma resposta controlada. O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cy.intercept()</code> age como um proxy no nível do Service Worker do browser de teste: a requisição é capturada, a resposta que você definiu é retornada, e a aplicação nunca chega a tocar a rede real. Para o código da aplicação, a chamada foi feita normalmente.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Anatomia de um endereço brasileiro válido para testes</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Campos obrigatórios: logradouro, bairro, localidade, UF, CEP</h3>
          <p className="mb-4">O formato ViaCEP retorna oito campos. Para testes funcionais, os cinco que importam são:</p>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Campo</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Exemplo</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Usado em</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">logradouro</code></td><td className="px-3 py-2">Rua das Palmeiras</td><td className="px-3 py-2">Input de rua</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">bairro</code></td><td className="px-3 py-2">Vila Madalena</td><td className="px-3 py-2">Input de bairro</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">localidade</code></td><td className="px-3 py-2">São Paulo</td><td className="px-3 py-2">Input de cidade</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">uf</code></td><td className="px-3 py-2">SP</td><td className="px-3 py-2">Select de estado</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cep</code></td><td className="px-3 py-2">01310-100</td><td className="px-3 py-2">Input de CEP</td></tr></tbody></table></div>
          <p className="mb-4">Os demais (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ibge</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">gia</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ddd</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">siafi</code>) raramente afetam lógica de formulário, mas alguns sistemas usam o <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ddd</code> para pré-preencher telefone.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Correlação entre prefixo do CEP e estado (ex: 01xxx–09xxx = SP)</h3>
          <p className="mb-4">CEPs brasileiros seguem faixas por estado definidas pelos Correios. São Paulo ocupa <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">01000-000</code> a <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">09999-999</code>. Rio de Janeiro vai de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">20000-000</code> a <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">28999-999</code>. Um endereço com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cep: "01310-100"</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">uf: "RJ"</code> é geograficamente impossível — e se a sua aplicação valida isso (muitas validam frete, filial regional, ICMS), o teste vai falhar com um falso negativo.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que dados aleatórios sem correlação geram falsos negativos nos testes</h3>
          <p className="mb-4">Gerar CEP e UF de forma independente cria combinações inválidas. A aplicação rejeita o endereço, o teste falha, o dev investiga achando que é bug, descobre que é fixture corrompida, perde tempo. Dados correlacionados — onde CEP, bairro, cidade e UF pertencem à mesma região — eliminam essa categoria de problema.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Gerando endereços brasileiros falsos e coerentes</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Usando o gerador de CEP do FakeForge via interface web</h3>
          <p className="mb-4">O <Link href="/gerador-cep" className="text-primary hover:underline">gerador de CEP do FakeForge</Link> gera endereços completos com correlação garantida entre todos os campos. Para testes pontuais, você pode gerar manualmente, copiar o JSON e salvar como fixture. Para uso em pipeline, a API é mais adequada.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Consumindo a API REST do FakeForge para gerar lotes de endereços</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=cep&quantity=5&format=json\""}</code></pre>
          <p className="mb-4">A <Link href="/docs" className="text-primary hover:underline">API REST do FakeForge</Link> aceita <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">type</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">quantity</code> (máx 10.000) e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format</code> (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">json</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">csv</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">sql</code>). O plano gratuito cobre 100 chamadas/dia — suficiente para a maioria dos pipelines de CI.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura do payload retornado e mapeamento para o formato ViaCEP</h3>
          <p className="mb-4">O FakeForge retorna o seguinte formato por item:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-json">{"{\n  \"cep\": \"04538-132\",\n  \"logradouro\": \"Avenida Brigadeiro Faria Lima\",\n  \"bairro\": \"Itaim Bibi\",\n  \"localidade\": \"São Paulo\",\n  \"uf\": \"SP\",\n  \"ddd\": \"11\"\n}"}</code></pre>
          <p className="mb-4">Isso é idêntico ao formato ViaCEP. Você pode usar o payload diretamente como resposta do intercept sem transformação.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Configurando cy.intercept() para substituir a chamada de CEP</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Sintaxe básica do cy.intercept com fixture estática</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"// cypress/e2e/cadastro.cy.ts\ndescribe('Preenchimento automático de endereço', () => {\n  beforeEach(() => {\n    cy.intercept('GET', '**/viacep.com.br/ws/**', {\n      fixture: 'endereco-sp.json',\n    }).as('buscarCep');\n  });\n\n  it('preenche os campos após digitar CEP', () => {\n    cy.visit('/cadastro');\n    cy.get('[data-testid=\"input-cep\"]').type('01310100');\n    cy.wait('@buscarCep');\n    cy.get('[data-testid=\"input-logradouro\"]').should('have.value', 'Avenida Paulista');\n  });\n});"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Interceptando padrões de URL (glob e regex para qualquer CEP digitado)</h3>
          <p className="mb-4">O glob <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded"><strong className="text-foreground">/viacep.com.br/ws/</strong></code> captura qualquer CEP. Se a aplicação usa BrasilAPI, ajuste:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"// Intercepta qualquer CEP na BrasilAPI\ncy.intercept('GET', '**/brasilapi.com.br/api/cep/v1/**', {\n  fixture: 'endereco-sp.json',\n}).as('buscarCep');\n\n// Ou com regex para cobrir ambas\ncy.intercept('GET', /viacep\\.com\\.br|brasilapi\\.com\\.br/, {\n  fixture: 'endereco-sp.json',\n}).as('buscarCep');"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Respondendo com objeto inline vs fixture salva em cypress/fixtures</h3>
          <p className="mb-4">Fixture salva é melhor para dados fixos reutilizados. Objeto inline é melhor para dados dinâmicos gerados no beforeEach:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"// Objeto inline — útil quando o endereço varia por teste\ncy.intercept('GET', '**/viacep.com.br/ws/**', {\n  statusCode: 200,\n  body: {\n    cep: '04538-132',\n    logradouro: 'Avenida Brigadeiro Faria Lima',\n    bairro: 'Itaim Bibi',\n    localidade: 'São Paulo',\n    uf: 'SP',\n    ddd: '11',\n  },\n}).as('buscarCep');"}</code></pre>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Fixture dinâmica: gerando endereços falsos no beforeEach</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Criando um comando customizado generateFakeAddress</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"// cypress/support/commands.ts\nCypress.Commands.add('generateFakeAddress', () => {\n  return cy.task('gerarEndereco');\n});\n\ndeclare global {\n  namespace Cypress {\n    interface Chainable {\n      generateFakeAddress(): Chainable<ViaCepResponse>;\n    }\n  }\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Chamando a API FakeForge dentro do cy.task</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"// cypress.config.ts\nimport { defineConfig } from 'cypress';\n\nexport default defineConfig({\n  e2e: {\n    setupNodeEvents(on) {\n      on('task', {\n        async gerarEndereco() {\n          const res = await fetch(\n            'https://fakeforge.com.br/api/generate?type=cep&quantity=1&format=json'\n          );\n          const data = await res.json();\n          // A API retorna array — pegar o primeiro item\n          return data[0];\n        },\n      });\n    },\n  },\n});"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">DICA:</strong> O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cy.task</code> roda no processo Node do Cypress (fora do browser), então chamadas <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">fetch</code> nativas funcionam no Node 18+. Para Node 16, substitua por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">https.get</code> ou instale <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">node-fetch</code>.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Vinculando o endereço gerado ao alias e reutilizando nos assertions</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"// cypress/e2e/cadastro.cy.ts\ndescribe('Endereço dinâmico', () => {\n  beforeEach(() => {\n    cy.task('gerarEndereco').then((endereco) => {\n      cy.wrap(endereco).as('enderecoFalso');\n\n      cy.intercept('GET', '**/viacep.com.br/ws/**', {\n        statusCode: 200,\n        body: endereco,\n      }).as('buscarCep');\n    });\n  });\n\n  it('verifica campos preenchidos com dados correlacionados', function () {\n    // Usar function() para acessar this.enderecoFalso\n    cy.visit('/cadastro');\n    cy.get('[data-testid=\"input-cep\"]').type(\n      this.enderecoFalso.cep.replace('-', '')\n    );\n    cy.wait('@buscarCep');\n    cy.get('[data-testid=\"input-logradouro\"]').should(\n      'have.value',\n      this.enderecoFalso.logradouro\n    );\n    cy.get('[data-testid=\"input-uf\"]').should('have.value', this.enderecoFalso.uf);\n  });\n});"}</code></pre>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Testando o fluxo completo de preenchimento automático de endereço</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Digitando o CEP no input e verificando o preenchimento dos campos</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"it('preenche logradouro, bairro, cidade e UF automaticamente', function () {\n  cy.visit('/checkout/endereco');\n  cy.get('[data-testid=\"input-cep\"]').type(\n    this.enderecoFalso.cep.replace('-', '')\n  );\n  cy.wait('@buscarCep');\n\n  cy.get('[data-testid=\"input-logradouro\"]').should(\n    'have.value',\n    this.enderecoFalso.logradouro\n  );\n  cy.get('[data-testid=\"input-bairro\"]').should(\n    'have.value',\n    this.enderecoFalso.bairro\n  );\n  cy.get('[data-testid=\"input-cidade\"]').should(\n    'have.value',\n    this.enderecoFalso.localidade\n  );\n  cy.get('[data-testid=\"select-uf\"]').should('have.value', this.enderecoFalso.uf);\n});"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cobrindo o caso de CEP inválido (mock de erro 404 / objeto vazio)</h3>
          <p className="mb-4">ViaCEP retorna <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">&#123; "erro": true &#125;</code> com status HTTP 200 para CEPs inexistentes — não um 404. Sua aplicação precisa tratar isso, e seu teste precisa cobrir:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"it('exibe mensagem de erro para CEP inválido', () => {\n  cy.intercept('GET', '**/viacep.com.br/ws/**', {\n    statusCode: 200,\n    body: { erro: true },\n  }).as('buscarCepInvalido');\n\n  cy.visit('/checkout/endereco');\n  cy.get('[data-testid=\"input-cep\"]').type('99999999');\n  cy.wait('@buscarCepInvalido');\n  cy.get('[data-testid=\"erro-cep\"]').should('be.visible').and('contain', 'CEP não encontrado');\n});"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">AVISO:</strong> Não mocke CEP inválido como status 404. ViaCEP retorna 200 com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">&#123; erro: true &#125;</code>. Se sua aplicação checa <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">response.ok</code> em vez do campo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">erro</code>, este comportamento específico ficará sem cobertura de teste.</blockquote>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Isolando testes por estado ou região com diferentes fixtures</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura de pastas para fixtures regionais</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-">{"cypress/\n  fixtures/\n    enderecos/\n      endereco-sp.json\n      endereco-rj.json\n      endereco-rs.json\n      endereco-ba.json"}</code></pre>
          <p className="mb-4">Exemplo de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cypress/fixtures/enderecos/endereco-sp.json</code>:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-json">{"{\n  \"cep\": \"01310-100\",\n  \"logradouro\": \"Avenida Paulista\",\n  \"complemento\": \"de 1 a 610 - lado par\",\n  \"bairro\": \"Bela Vista\",\n  \"localidade\": \"São Paulo\",\n  \"uf\": \"SP\",\n  \"ddd\": \"11\"\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Parametrizando testes com cy.each para múltiplos estados</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"const estados = ['sp', 'rj', 'rs', 'ba'];\n\nestados.forEach((uf) => {\n  it(`calcula frete corretamente para ${uf.toUpperCase()}`, () => {\n    cy.intercept('GET', '**/viacep.com.br/ws/**', {\n      fixture: `enderecos/endereco-${uf}.json`,\n    }).as('buscarCep');\n\n    cy.visit('/frete');\n    cy.get('[data-testid=\"input-cep\"]').type('01310100');\n    cy.wait('@buscarCep');\n    cy.get('[data-testid=\"valor-frete\"]').should('be.visible');\n  });\n});"}</code></pre>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Boas práticas para não quebrar o ambiente de staging</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Usando variável de ambiente para ativar mock apenas em CI</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"# .env.ci\nCYPRESS_MOCK_CEP=true"}</code></pre>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"// cypress/e2e/cadastro.cy.ts\nconst mockCep = Cypress.env('MOCK_CEP') === 'true';\n\nbeforeEach(() => {\n  if (mockCep) {\n    cy.intercept('GET', '**/viacep.com.br/ws/**', {\n      fixture: 'enderecos/endereco-sp.json',\n    }).as('buscarCep');\n  }\n});"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Não interceptar em testes de contrato ou smoke tests de integração real</h3>
          <p className="mb-4">Testes de contrato verificam se a API externa ainda retorna o formato esperado. Interceptar esses testes derrota o propósito. Separe por pasta ou tag:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"// Teste de contrato — sem mock\nit('ViaCEP retorna campos esperados', { tags: ['@contrato'] }, () => {\n  cy.request('GET', 'https://viacep.com.br/ws/01310100/json/').then((res) => {\n    expect(res.body).to.have.keys(['cep', 'logradouro', 'bairro', 'localidade', 'uf']);\n  });\n});"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Documentando quais testes usam dados falsos vs dados reais</h3>
          <p className="mb-4">Adicione um comentário de cabeçalho nos arquivos de teste que usam mocks:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"/**\n * DADOS: mock via FakeForge (/api/generate?type=cep)\n * Não roda chamadas reais para ViaCEP.\n * Para testes de contrato, veja: cypress/e2e/contratos/viacep.cy.ts\n */"}</code></pre>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">LGPD e dados de endereço em testes</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">LGPD Art. 7º, IX e o risco de usar endereços reais de usuários em fixtures</h3>
          <p className="mb-4">A <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 7º, IX</a> permite tratamento de dados pessoais apenas quando há base legal. Usar endereços reais de usuários em fixtures de teste — mesmo anonimizados parcialmente — pode caracterizar tratamento sem consentimento e sem base legal adequada. O endereço completo de uma pessoa física é dado pessoal.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que dados gerados (não coletados) eliminam a obrigação de consentimento</h3>
          <p className="mb-4">Dados gerados sinteticamente nunca pertenceram a nenhuma pessoa física. Não há titular. Não há base legal necessária porque não existe dado pessoal. Um CEP falso gerado pelo <Link href="/gerador-cep" className="text-primary hover:underline">FakeForge</Link> com logradouro, bairro e cidade correlacionados é tecnicamente válido para testes e juridicamente neutro para fins da LGPD.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como o FakeForge garante que nenhum dado real é armazenado ou processado</h3>
          <p className="mb-4">O FakeForge não usa bases de dados de pessoas reais. Os geradores são algoritmos determinísticos: CPF via módulo 11, CNPJ via dígitos verificadores, endereços via tabelas de prefixos dos Correios sem consulta externa. Nenhuma requisição à API armazena os dados gerados. Não há log associado a usuário, não há PII em trânsito.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li><strong className="text-foreground">Intercepte sempre em E2E:</strong> Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cy.intercept()</code> para toda chamada de CEP externo — ViaCEP, BrasilAPI ou qualquer outra. Testes E2E não devem depender de disponibilidade de APIs de terceiros.</li><li><strong className="text-foreground">Dados correlacionados evitam falsos negativos:</strong> CEP, bairro, cidade e UF devem ser geograficamente coerentes. Use o <Link href="/gerador-cep" className="text-primary hover:underline">gerador de CEP do FakeForge</Link> ou a <Link href="/docs" className="text-primary hover:underline">API REST</Link> para garantir essa correlação.</li><li><strong className="text-foreground"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cy.task</code> para geração dinâmica:</strong> Chame a API FakeForge no <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cypress.config.ts</code> via <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">task</code> para gerar endereços frescos por suite, evitando fixtures estáticas que ficam defasadas.</li><li><strong className="text-foreground">Trate <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">&#123; erro: true &#125;</code> com status 200:</strong> ViaCEP não retorna 404 para CEP inválido. Cubra este caso explicitamente no mock para garantir que o tratamento de erro da aplicação está coberto.</li><li><strong className="text-foreground">Ative mocks via variável de ambiente:</strong> <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CYPRESS_MOCK_CEP=true</code> no CI e desligado em testes de contrato. Mantenha a separação documentada no cabeçalho dos arquivos de teste.</li><li><strong className="text-foreground">Dados gerados são LGPD-safe:</strong> Substitua qualquer fixture com endereço real de usuário por dados sintéticos. Para <Link href="/gerador-cpf" className="text-primary hover:underline">mockar validação de CPF no fluxo de cadastro</Link>, <Link href="/gerador-cnpj" className="text-primary hover:underline">dados de empresa nos testes de formulário B2B</Link> ou <Link href="/gerador-pix" className="text-primary hover:underline">chaves PIX em fluxos de pagamento</Link>, o mesmo princípio se aplica.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Como mockar duas requisições d" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como mockar duas requisições de CEP diferentes no mesmo teste (endereço de cobrança + entrega)?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Use cy.intercept com callback para diferenciar por padrão de URL. Verifique o query param ou o caminho e retorne a fixture apropriada: cy.intercept('GET', '**/viacep.com.br/**', (req) =&gt; &#123; req.reply((res) =&gt; &#123; res.body = req.url.includes('01310') ? enderecoSP : enderecORJ; &#125;); &#125;).</p>
            </details>
            <details key="O cy.task chamando a API FakeF" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">O cy.task chamando a API FakeForge em cada teste fica lento em CI com paralelo?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sim. Para pipelines com 4+ workers, gere 50 endereços uma vez antes da suite e distribua via fixture JSON carregado de setup. Ou mova o cy.task para um arquivo pluginFile que roda antes de tudo, economizando requisições HTTP repetidas entre testes paralelos.</p>
            </details>
            <details key="Como mockar timeout ou erro 50" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como mockar timeout ou erro 504 da ViaCEP sem chamar de verdade?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">cy.intercept('GET', '**/viacep/**', (req) =&gt; &#123; req.reply((res) =&gt; &#123; res.delay = 15000; res.statusCode = 504; res.body = &#123;&#125;; &#125;); &#125;). Isso simula timeout e erro sem atingir limite real. Essencial para testar fallback e tratamento de erro da aplicação.</p>
            </details>
            <details key="Preciso gerar endereço falso (" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Preciso gerar endereço falso (CEP), CPF e CNPJ válidos no mesmo fluxo de cadastro. Como combinar?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">No beforeEach, chame cy.task para cada tipo via Promise.all: Promise.all([cy.task('gerarEndereco'), cy.task('gerarCPF'), cy.task('gerarCNPJ')]).then(([end, cpf, cnpj]) =&gt; &#123; ... &#125;). Salve em this.dados e reutilize nos intercepts de todas as APIs do fluxo.</p>
            </details>
            <details key="O input CEP tem máscara (00000" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">O input CEP tem máscara (00000-000) mas a requisição HTTP envia sem máscara. Como mockar?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">O cy.intercept intercepta APÓS o JavaScript remover a máscara. Digitar '01310-100' no input, o código remove o hífen e faz a requisição (01310100) — mocke essa requisição sem máscara. Correlação permanece idêntica à mask original.</p>
            </details>
          </div>
        </section>
        <ShareBar title={"Como mockar CEP no Cypress com dados brasileiros falsos"} path="/blog/mockar-cep-cypress-dados-brasileiros-falsos" />
        <BlogPostingSchema
          title={"Como mockar CEP no Cypress com dados brasileiros falsos"}
          slug="mockar-cep-cypress-dados-brasileiros-falsos"
          description={"Aprenda a interceptar chamadas de CEP no Cypress e retornar endereços brasileiros falsos e coerentes — sem depender de APIs externas nos seus testes."}
          datePublished="2026-05-26"
          image="https://fakeforge.com.br/api/og?title=Como%20mockar%20CEP%20no%20Cypress%20com%20dados%20brasileiros%20falsos&subtitle=Aprenda%20a%20interceptar%20chamadas%20de%20CEP%20no%20Cypress%20e%20retornar%20endere%C3%A7os%20brasileiros%20falsos%20e%20coerentes%20%E2%80%94%20sem%20depender%20de%20APIs%20externas%20nos%20seu&category=TUTORIAIS"
        />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Como mockar duas requisições de CEP diferentes no mesmo teste (endereço de cobrança + entrega)?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Use cy.intercept com callback para diferenciar por padrão de URL. Verifique o query param ou o caminho e retorne a fixture apropriada: cy.intercept('GET', '**/viacep.com.br/**', (req) => { req.reply((res) => { res.body = req.url.includes('01310') ? enderecoSP : enderecORJ; }); }).\"}},{\"@type\":\"Question\",\"name\":\"O cy.task chamando a API FakeForge em cada teste fica lento em CI com paralelo?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sim. Para pipelines com 4+ workers, gere 50 endereços uma vez antes da suite e distribua via fixture JSON carregado de setup. Ou mova o cy.task para um arquivo pluginFile que roda antes de tudo, economizando requisições HTTP repetidas entre testes paralelos.\"}},{\"@type\":\"Question\",\"name\":\"Como mockar timeout ou erro 504 da ViaCEP sem chamar de verdade?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"cy.intercept('GET', '**/viacep/**', (req) => { req.reply((res) => { res.delay = 15000; res.statusCode = 504; res.body = {}; }); }). Isso simula timeout e erro sem atingir limite real. Essencial para testar fallback e tratamento de erro da aplicação.\"}},{\"@type\":\"Question\",\"name\":\"Preciso gerar endereço falso (CEP), CPF e CNPJ válidos no mesmo fluxo de cadastro. Como combinar?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"No beforeEach, chame cy.task para cada tipo via Promise.all: Promise.all([cy.task('gerarEndereco'), cy.task('gerarCPF'), cy.task('gerarCNPJ')]).then(([end, cpf, cnpj]) => { ... }). Salve em this.dados e reutilize nos intercepts de todas as APIs do fluxo.\"}},{\"@type\":\"Question\",\"name\":\"O input CEP tem máscara (00000-000) mas a requisição HTTP envia sem máscara. Como mockar?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"O cy.intercept intercepta APÓS o JavaScript remover a máscara. Digitar '01310-100' no input, o código remove o hífen e faz a requisição (01310100) — mocke essa requisição sem máscara. Correlação permanece idêntica à mask original.\"}}]}",
        }}
      />
    </PageShell>
  );
}
