import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";
import ShareBar from "@/components/ShareBar";

export const metadata: Metadata = {
  title: "Documentos Brasileiros: Formatos e Algoritmos de Validação",
  description: "CPF, CNPJ, RG, CIN e CNH: estrutura de dígitos, cálculo de verificação e exemplos de código para validar cada documento em TypeScript.",
  openGraph: {
    title: "Documentos Brasileiros: Formatos e Algoritmos de Validação",
    description: "CPF, CNPJ, RG, CIN e CNH: estrutura de dígitos, cálculo de verificação e exemplos de código para validar cada documento em TypeScript.",
    type: "article",
    images: ["/api/og?title=Documentos%20brasileiros%20para%20devs%3A%20formatos%20e%20algoritmos%20de%20valida%C3%A7%C3%A3o&subtitle=CPF%2C%20CNPJ%2C%20RG%2C%20CIN%20e%20CNH%3A%20estrutura%20de%20d%C3%ADgitos%2C%20c%C3%A1lculo%20de%20verifica%C3%A7%C3%A3o%20e%20exemplos%20de%20c%C3%B3digo%20para%20validar%20cada%20documento%20em%20TypeScript.&category=TUTORIAIS"],
  },
  alternates: { canonical: "/blog/documentos-brasileiros-formatos-algoritmos-validacao" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Documentos brasileiros para devs: formatos e algoritmos de validação" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Documentos brasileiros para devs: formatos e algoritmos de validação
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>02 de junho de 2026</time>
            <span>·</span>
            <span>14 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">Cada documento de identidade brasileiro tem estrutura própria, entidade emissora distinta e, na maioria dos casos, um algoritmo de dígito verificador diferente. Implementar validação correta exige conhecer cada um desses detalhes antes de escrever uma linha de código.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Cada documento tem estrutura própria e algoritmo distinto</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que validação por checksum existe (e por que muitos devs erram)</h3>
          <p className="mb-4">O dígito verificador (DV) detecta erros de digitação: transposição de algarismos, dígito faltante, número inventado. Ele não confirma que o documento foi emitido nem que a pessoa existe — apenas que os números respeitam o cálculo definido pelo órgão emissor.</p>
          <p className="mb-4">O erro mais comum é confundir "passa no checksum" com "documento válido". CPFs zerados (000.000.000-00) e CNPJs com todos os dígitos iguais passam em implementações ingênuas porque o algoritmo não descarta essas sequências por padrão.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Tabela comparativa: tamanho, formato, dígito verificador, entidade emissora</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Documento</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Tamanho</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Formato</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">DVs</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Emitente</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">CPF</td><td className="px-3 py-2">11 dígitos</td><td className="px-3 py-2">NNN.NNN.NNN-DD</td><td className="px-3 py-2">2</td><td className="px-3 py-2">Receita Federal</td></tr><tr className="border-b border-border"><td className="px-3 py-2">CNPJ</td><td className="px-3 py-2">14 chars</td><td className="px-3 py-2">NN.NNN.NNN/EEEE-DD</td><td className="px-3 py-2">2</td><td className="px-3 py-2">Receita Federal</td></tr><tr className="border-b border-border"><td className="px-3 py-2">RG</td><td className="px-3 py-2">variável</td><td className="px-3 py-2">por estado</td><td className="px-3 py-2">0 ou 1</td><td className="px-3 py-2">SSP / DETRAN estadual</td></tr><tr className="border-b border-border"><td className="px-3 py-2">CIN</td><td className="px-3 py-2">12 chars</td><td className="px-3 py-2">UF + 9 dígitos + D</td><td className="px-3 py-2">1</td><td className="px-3 py-2">MJ / SENASP</td></tr><tr className="border-b border-border"><td className="px-3 py-2">CNH</td><td className="px-3 py-2">11 dígitos</td><td className="px-3 py-2">sem máscara pública</td><td className="px-3 py-2">2</td><td className="px-3 py-2">SENATRAN / DETRAN</td></tr></tbody></table></div>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">CPF: onze dígitos e dois módulos 11</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Anatomia do número (região fiscal, sequencial, DVs)</h3>
          <p className="mb-4">O CPF tem 11 dígitos: 9 de base e 2 verificadores. Os três primeiros identificam a região fiscal de inscrição (01-09 = Brasília, 10 = SP). Os dígitos 1-9 formam o número de inscrição; os dígitos 10 e 11 são os DVs calculados em duas rodadas distintas.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Algoritmo passo a passo com pesos [10..2] e [11..2]</h3>
          <p className="mb-4"><strong className="text-foreground">Primeiro DV:</strong> multiplica os 9 primeiros dígitos pelos pesos 10, 9, 8, 7, 6, 5, 4, 3, 2. Soma os produtos. Calcula <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto = soma % 11</code>. Se resto &lt; 2, DV = 0; caso contrário, DV = 11 - resto.</p>
          <p className="mb-4"><strong className="text-foreground">Segundo DV:</strong> usa os 9 dígitos originais mais o primeiro DV, com pesos 11, 10, 9, 8, 7, 6, 5, 4, 3, 2. Mesma regra de resto.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Casos especiais que passam no checksum mas são inválidos (111.111.111-11)</h3>
          <p className="mb-4">Sequências com todos os dígitos iguais (000.000.000-00 até 999.999.999-99) geram DVs matematicamente coerentes, mas a Receita Federal nunca as emite. Qualquer validação deve rejeitar esses onze padrões explicitamente.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Implementação TypeScript completa com casos de teste</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function normalizarDocumento(doc: string): string {\n  return doc.trim().toUpperCase().replace(/[^A-Z0-9]/g, '');\n}\n\nfunction validarCPF(cpf: string): boolean {\n  const s = normalizarDocumento(cpf);\n  if (s.length !== 11 || /^(\\d)\\1{10}$/.test(s)) return false;\n\n  const calcDv = (base: number[]) => {\n    const len = base.length;\n    const soma = base.reduce((acc, d, i) => acc + d * (len + 1 - i), 0);\n    const r = soma % 11;\n    return r < 2 ? 0 : 11 - r;\n  };\n\n  const digits = s.split('').map(Number);\n  const dv1 = calcDv(digits.slice(0, 9));\n  if (dv1 !== digits[9]) return false;\n  const dv2 = calcDv(digits.slice(0, 10));\n  return dv2 === digits[10];\n}\n\nconsole.assert(validarCPF('529.982.247-25') === true);\nconsole.assert(validarCPF('111.111.111-11') === false);\nconsole.assert(validarCPF('000.000.000-00') === false);"}</code></pre>
          <p className="mb-4">Use o <Link href="/validar-cpf" className="text-primary hover:underline">validador de CPF online</Link> para conferir casos limítrofes antes de subir para produção. Para <Link href="/gerador-cpf" className="text-primary hover:underline">gerar CPFs válidos para testes</Link>, o gerador calcula os dois DVs pelo mesmo algoritmo acima.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">CNPJ numérico: quatorze dígitos e pesos cíclicos</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura: raiz, ordem, estabelecimento, DVs</h3>
          <p className="mb-4">O CNPJ tem 14 posições: 8 de raiz (identifica a empresa), 4 de ordem de filial (0001 = matriz) e 2 DVs. Formato mascarado: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">NN.NNN.NNN/EEEE-DD</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Pesos [5,4,3,2,9,8,7,6,5,4,3,2] e segundo ciclo</h3>
          <p className="mb-4">Os 12 primeiros caracteres são multiplicados pelos pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[5,4,3,2,9,8,7,6,5,4,3,2]</code> para o primeiro DV. Para o segundo, os pesos são <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[6,5,4,3,2,9,8,7,6,5,4,3,2]</code>, incluindo o DV anterior. A regra de resto é idêntica à do CPF.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Implementação TypeScript e diferenças para o CPF</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function validarCNPJ(cnpj: string): boolean {\n  const s = normalizarDocumento(cnpj);\n  if (s.length !== 14 || /^(.)\\1{13}$/.test(s)) return false;\n\n  const pesos1 = [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2];\n  const pesos2 = [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2];\n\n  const calcDv = (chars: string[], pesos: number[]) => {\n    const soma = chars.reduce((acc, c, i) => {\n      const v = c >= 'A' ? c.charCodeAt(0) - 55 : Number(c);\n      return acc + v * pesos[i];\n    }, 0);\n    const r = soma % 11;\n    return r < 2 ? 0 : 11 - r;\n  };\n\n  const chars = s.split('');\n  const dv1 = calcDv(chars.slice(0, 12), pesos1);\n  if (dv1 !== Number(chars[12])) return false;\n  const dv2 = calcDv(chars.slice(0, 13), pesos2);\n  return dv2 === Number(chars[13]);\n}"}</code></pre>
          <p className="mb-4">Essa implementação já suporta letras na raiz. Use <Link href="/gerador-cnpj" className="text-primary hover:underline">/gerador-cnpj</Link> para CNPJs numéricos em fixtures e <Link href="/validar-cnpj" className="text-primary hover:underline">/validar-cnpj</Link> para verificação online.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">CNPJ alfanumérico: vigência 01/07/2026 (Receita Federal)</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que muda na estrutura (raiz aceita A-Z0-9, ordem permanece numérica)</h3>
          <p className="mb-4">A partir de 01/07/2026, a Receita Federal passa a emitir CNPJs com letras nos 8 dígitos da raiz (Instrução Normativa RFB 2.229/2024). A parte de ordem (posições 9-12) permanece numérica. Os dois DVs continuam numéricos. Formato futuro: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">B3.QK4.L7/0001-XX</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como o checksum se adapta: valor ASCII de letras, mesmo módulo 11</h3>
          <p className="mb-4">Letras são convertidas pelo valor posicional: A = 10, B = 11, Z = 35, equivalente a <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">charCodeAt(0) - 55</code> para maiúsculas. O módulo 11 não muda. A função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validarCNPJ</code> acima já contempla isso.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Impacto em sistemas legados: regex, máscaras, banco de dados (VARCHAR vs CHAR)</h3>
          <p className="mb-4">Três pontos críticos de migração:</p>
          <p className="mb-4">1. <strong className="text-foreground">Regex</strong> que assume <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">\d&#123;14&#125;</code> rejeita o novo formato. Substituir por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[A-Z0-9]&#123;14&#125;</code> após normalização para maiúsculas. 2. <strong className="text-foreground">Máscara de input</strong> baseada em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">replace(/\D/g, '')</code> descarta letras. Ajustar para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">replace(/[^A-Z0-9]/gi, '')</code>. 3. <strong className="text-foreground">Coluna de banco</strong> tipada como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(14)</code> sem máscara funciona para ambos os formatos, pois letras ASCII também ocupam 1 byte.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">AVISO: Não armazene CNPJ com máscara (pontos, barra, hífen) no banco. Isso quebra índices, duplica espaço e complica queries de JOIN. Normalize antes de persistir.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Snippet de migração para aceitar os dois formatos em paralelo</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function normalizarCNPJ(cnpj: string): string {\n  return cnpj.toUpperCase().replace(/[^A-Z0-9]/g, '');\n}\n\nfunction isCNPJAlfanumerico(cnpj: string): boolean {\n  return /[A-Z]/.test(normalizarCNPJ(cnpj));\n}"}</code></pre>
          <p className="mb-4">Para gerar CNPJs no novo formato, use <Link href="/gerador-cnpj-alfanumerico" className="text-primary hover:underline">/gerador-cnpj-alfanumerico</Link>.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">RG: sem padrão nacional, mas com padrões estaduais</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Mapeamento por estado (SSP-SP, SSP-RJ, SSP-MG, DETRAN-RS)</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">UF</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Formato típico</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">DV</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Emitente</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">SP</td><td className="px-3 py-2">NN.NNN.NNN-D (ou X)</td><td className="px-3 py-2">mod 11</td><td className="px-3 py-2">SSP-SP</td></tr><tr className="border-b border-border"><td className="px-3 py-2">RJ</td><td className="px-3 py-2">NN.NNN.NNN-D</td><td className="px-3 py-2">mod 11</td><td className="px-3 py-2">DETRAN-RJ</td></tr><tr className="border-b border-border"><td className="px-3 py-2">MG</td><td className="px-3 py-2">M-NNN.NNN</td><td className="px-3 py-2">sem DV público</td><td className="px-3 py-2">SSP-MG</td></tr><tr className="border-b border-border"><td className="px-3 py-2">RS</td><td className="px-3 py-2">NNN.NNNNN</td><td className="px-3 py-2">sem DV público</td><td className="px-3 py-2">SSP-RS</td></tr></tbody></table></div>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">SSP-SP: dígito verificador com módulo 11 e letra X</h3>
          <p className="mb-4">O RG de SP tem 8 algarismos base e 1 DV. Pesos de 2 a 9 são aplicados da direita para a esquerda. O DV pode ser numérico ou a letra <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">X</code> quando o resultado do módulo for 10.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que validar RG é diferente: você valida formato, não checksum universal</h3>
          <p className="mb-4">Não existe algoritmo federal para RG. A validação cross-state resume-se a: comprimento dentro do intervalo esperado (6-10 caracteres), caracteres permitidos (dígitos e, em SP, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">X</code> na última posição) e máscara compatível com a UF informada pelo usuário.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estratégia prática: aceitar, mascarar e delegar conferência ao emitente</h3>
          <p className="mb-4">Para formulários, aceite o número informado, aplique a máscara da UF selecionada e nunca reprove por checksum — apenas por caracteres inválidos. Use <Link href="/gerador-rg" className="text-primary hover:underline">/gerador-rg</Link> para gerar RGs no formato SSP-SP em fixtures de teste.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">CIN: o novo documento de identidade nacional (EC 131/2023)</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura definida pelo MJ: letras UF + 9 dígitos + DV</h3>
          <p className="mb-4">A Emenda Constitucional 131/2023 instituiu o CIN (Carteira de Identidade Nacional). O número segue o padrão <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">UF</code> (2 letras) + 9 dígitos + 1 DV, totalizando 12 caracteres. Exemplo: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">SP123456789-4</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Relação com RG: CIN não substitui, coexiste até 2032</h3>
          <p className="mb-4">O RG permanece válido até 28/02/2032. Sistemas que coletam documentos de identidade devem aceitar ambos. Colunas separadas (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cin CHAR(12) NULL</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">rg VARCHAR(20) NULL</code>) são mais simples de migrar do que um campo genérico <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">documento_identidade</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Algoritmo de dígito verificador do CIN</h3>
          <p className="mb-4">O DV é calculado sobre os 9 dígitos centrais com pesos de 2 a 10, da esquerda para a direita. Soma dos produtos, módulo 11. Se resto &lt; 2, DV = 0; caso contrário, DV = 11 - resto. A sigla da UF não entra no cálculo.</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function validarCIN(cin: string): boolean {\n  const s = cin.toUpperCase().replace(/[^A-Z0-9]/g, '');\n  if (!/^[A-Z]{2}\\d{10}$/.test(s)) return false;\n\n  const digits = s.slice(2).split('').map(Number);\n  const soma = digits.slice(0, 9).reduce((acc, d, i) => acc + d * (i + 2), 0);\n  const r = soma % 11;\n  const dv = r < 2 ? 0 : 11 - r;\n  return dv === digits[9];\n}"}</code></pre>
          <p className="mb-4">Use <Link href="/gerador-cin" className="text-primary hover:underline">/gerador-cin</Link> para gerar CINs válidos em seeds de banco de dados.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">CNH: onze dígitos, dois DVs calculados em sequências distintas</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura do Registro Nacional de Condutores Habilitados (RENACH/SENATRAN)</h3>
          <p className="mb-4">A CNH tem 11 dígitos no campo RENACH. Os 9 primeiros são o número base; os dígitos 10 e 11 são DVs calculados em duas etapas com lógicas distintas entre si.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cálculo do primeiro DV: pesos decrescentes 9..1</h3>
          <p className="mb-4">Multiplica os 9 dígitos pelos pesos 9, 8, 7, 6, 5, 4, 3, 2, 1. Soma. Divide por 11. O DV1 é o resto. Se resto = 10, guarda um flag <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">dsc = 2</code>; caso contrário, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">dsc = 0</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cálculo do segundo DV: pesos crescentes 1..9 com DSC condicional</h3>
          <p className="mb-4">Multiplica os mesmos 9 dígitos pelos pesos 1, 2, 3, 4, 5, 6, 7, 8, 9. Soma. Divide por 11. DV2 = resto. Se DV2 &gt;= 10, DV2 = 0. DV1 definitivo = DV1 - dsc; se negativo, DV1 = 0.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Implementação TypeScript com os dois passos encadeados</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function validarCNH(cnh: string): boolean {\n  const s = normalizarDocumento(cnh);\n  if (s.length !== 11 || /^(\\d)\\1{10}$/.test(s)) return false;\n\n  const d = s.split('').map(Number);\n\n  let soma1 = 0;\n  let dsc = 0;\n  for (let i = 0; i < 9; i++) soma1 += d[i] * (9 - i);\n  let dv1 = soma1 % 11;\n  if (dv1 >= 10) { dv1 = 0; dsc = 2; }\n\n  let soma2 = 0;\n  for (let i = 0; i < 9; i++) soma2 += d[i] * (1 + i);\n  let dv2 = soma2 % 11;\n  if (dv2 >= 10) dv2 = 0;\n  dv1 = dv1 - dsc < 0 ? 0 : dv1 - dsc;\n\n  return d[9] === dv1 && d[10] === dv2;\n}"}</code></pre>
          <p className="mb-4">Para <Link href="/gerador-cnh" className="text-primary hover:underline">gerar CNHs com DV correto</Link> em massa, a API REST aceita <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">?type=cnh&amp;quantity=N</code>.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Validação em formulários: onde colocar a lógica</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Client-side (UX rápida) vs server-side (fonte da verdade)</h3>
          <p className="mb-4">Validação no cliente devolve feedback imediato sem latência de rede. Mas JavaScript pode ser contornado. A fonte da verdade é o servidor.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Padrão recomendado: validar sintaxe no cliente, checksum no servidor</h3>
          <p className="mb-4">No cliente: comprimento, máscara, caracteres permitidos. No servidor: checksum completo mais rejeição de sequências inválidas. Essa separação evita round-trips desnecessários sem abrir a verificação de integridade a bypass.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Exemplo de endpoint Next.js reutilizável para múltiplos tipos de documento</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// src/app/api/validate/route.ts\nimport { NextRequest, NextResponse } from 'next/server';\nimport { validarCPF } from '@/lib/validators/cpf';\nimport { validarCNPJ } from '@/lib/validators/cnpj';\nimport { validarCNH } from '@/lib/validators/cnh';\nimport { validarCIN } from '@/lib/validators/cin';\n\nconst validators: Record<string, (v: string) => boolean> = {\n  cpf: validarCPF,\n  cnpj: validarCNPJ,\n  cnh: validarCNH,\n  cin: validarCIN,\n};\n\nexport async function POST(req: NextRequest) {\n  const { type, value } = await req.json();\n  const validate = validators[type];\n  if (!validate) {\n    return NextResponse.json(\n      { valid: false, reason: 'tipo desconhecido' },\n      { status: 400 }\n    );\n  }\n  const valid = validate(value ?? '');\n  return NextResponse.json({ valid, reason: valid ? null : 'checksum inválido' });\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">LGPD Art. 6º, I e Art. 9º: minimização de dados coletados em formulários</h3>
          <p className="mb-4">A <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 6º, I</a> exige finalidade legítima e específica para o tratamento de dados pessoais. O Art. 9º obriga informar ao titular quais dados são coletados e por quê. Na prática: não colete CPF se a funcionalidade não exige verificação de identidade. Campos opcionais devem ser opcionais de verdade.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Geração de dados fictícios para testes (LGPD Art. 12)</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que usar dados sintéticos em vez de CPFs/CNPJs reais em seeds</h3>
          <p className="mb-4">Usar CPFs e CNPJs reais em ambientes de desenvolvimento viola o princípio de minimização e expõe dados de terceiros a quem não deveria tê-los. Um dump de produção com CPFs reais em staging é um incidente de segurança, não um atalho de desenvolvimento.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que a LGPD diz sobre dados anonimizados e pseudonimizados (Art. 12 e Art. 13)</h3>
          <p className="mb-4">O <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">Art. 12 da LGPD</a> define que dados que não podem ser revertidos para identificar o titular não são dados pessoais. Dados sintéticos gerados por algoritmo, sem base em registros reais, se enquadram nessa categoria. O Art. 13 permite uso de dados pseudonimizados para pesquisa, mas com separação do mapeamento de reversão.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">DICA: Documentos gerados pelo FakeForge BR são produzidos por algoritmo sem consulta a nenhuma base da Receita Federal ou SSP. O checksum é válido, mas o número nunca foi emitido. Isso os torna seguros para seeds, testes de carga e fixtures de CI.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como FakeForge BR gera documentos válidos no formato sem usar registros reais</h3>
          <p className="mb-4">Cada gerador sorteia dígitos aleatórios para a parte base, calcula os DVs pelo mesmo algoritmo dos órgãos emissores e rejeita sequências inválidas (todos iguais, CPFs de região inexistente). O resultado passa em qualquer validador de formato.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Integração via API REST: /api/generate?type=cpf&amp;quantity=100&amp;format=json</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=cpf&quantity=100&format=json\""}</code></pre>
          <p className="mb-4">Retorna um array de 100 CPFs prontos para seeds. Substitua <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cpf</code> por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cnpj</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cnh</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cin</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pessoa</code> conforme a necessidade. A documentação completa está em <Link href="/docs" className="text-primary hover:underline">/docs</Link>.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Erros comuns de implementação e como evitá-los</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Armazenar CPF/CNPJ com máscara no banco (coluna VARCHAR vs CHAR sem formatação)</h3>
          <p className="mb-4">Armazenar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"123.456.789-09"</code> em vez de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"12345678909"</code> desperdiça 4 bytes por registro, impede índice eficiente e força tratamento inconsistente em queries de JOIN. Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(11)</code> para CPF e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(14)</code> para CNPJ, sem máscara.</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"CREATE TABLE pessoas (\n  id          SERIAL PRIMARY KEY,\n  cpf         CHAR(11)    UNIQUE NOT NULL,\n  cnpj        CHAR(14)    NULL,\n  rg          VARCHAR(20) NULL,\n  cin         CHAR(12)    NULL,\n  cnh         CHAR(11)    NULL,\n  nome        VARCHAR(200) NOT NULL,\n  criado_em   TIMESTAMPTZ DEFAULT NOW()\n);"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Aceitar "000.000.000-00" e CNPJs zerados (sequências inválidas mesmo com DV correto)</h3>
          <p className="mb-4">Sequências homogêneas geram DVs válidos matematicamente mas nunca são emitidas. O guard <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">if (/^(.)\1&#123;13&#125;$/.test(s)) return false</code> na entrada da função resolve o caso.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regex que rejeita CNPJ alfanumérico antes de validar checksum</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/^\d&#123;14&#125;$/</code> retorna <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">false</code> para CNPJs como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">B3QK4L70001XX</code> a partir de julho de 2026. Atualize para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">^[A-Z0-9]&#123;14&#125;$</code> após normalização para maiúsculas e remoção de máscara.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Não normalizar entrada antes de calcular (espaços, pontos, barras, hífens)</h3>
          <p className="mb-4">Toda função de validação deve começar com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">normalizarDocumento()</code>. Centralizar elimina falsos negativos causados por diferenças de formatação e garante que a mesma lógica funcione para input de formulário, leitura de arquivo CSV e payload de API.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Documento</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Algoritmo</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Casos especiais</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Ferramenta</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">CPF</td><td className="px-3 py-2">Mod 11, pesos 10..2 e 11..2</td><td className="px-3 py-2">Rejeitar 11 sequências homogêneas</td><td className="px-3 py-2"><Link href="/gerador-cpf" className="text-primary hover:underline">/gerador-cpf</Link></td></tr><tr className="border-b border-border"><td className="px-3 py-2">CNPJ (num.)</td><td className="px-3 py-2">Mod 11, pesos cíclicos</td><td className="px-3 py-2">Rejeitar sequências iguais</td><td className="px-3 py-2"><Link href="/gerador-cnpj" className="text-primary hover:underline">/gerador-cnpj</Link></td></tr><tr className="border-b border-border"><td className="px-3 py-2">CNPJ (alfa)</td><td className="px-3 py-2">Idem, charCode para letras</td><td className="px-3 py-2">Atualizar regex e máscara de input</td><td className="px-3 py-2"><Link href="/gerador-cnpj-alfanumerico" className="text-primary hover:underline">/gerador-cnpj-alfanumerico</Link></td></tr><tr className="border-b border-border"><td className="px-3 py-2">RG</td><td className="px-3 py-2">Por UF (SP: mod 11 + X)</td><td className="px-3 py-2">Sem validação cross-state</td><td className="px-3 py-2"><Link href="/gerador-rg" className="text-primary hover:underline">/gerador-rg</Link></td></tr><tr className="border-b border-border"><td className="px-3 py-2">CIN</td><td className="px-3 py-2">Mod 11, pesos 2..10</td><td className="px-3 py-2">Coexiste com RG até 2032</td><td className="px-3 py-2"><Link href="/gerador-cin" className="text-primary hover:underline">/gerador-cin</Link></td></tr><tr className="border-b border-border"><td className="px-3 py-2">CNH</td><td className="px-3 py-2">Dois DVs com pesos e DSC distintos</td><td className="px-3 py-2">Sequências homogêneas são inválidas</td><td className="px-3 py-2"><Link href="/gerador-cnh" className="text-primary hover:underline">/gerador-cnh</Link></td></tr></tbody></table></div>
          <p className="mb-4"><strong className="text-foreground">Próximos passos:</strong></p>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Adicione <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">normalizarDocumento()</code> como pré-processador único em todas as funções de validação existentes no projeto.</li><li>Atualize regex de CNPJ para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[A-Z0-9]&#123;14&#125;</code> antes de julho de 2026.</li><li>Migre colunas de CPF/CNPJ para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(11)</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(14)</code> sem máscara, com índice único.</li><li>Crie colunas <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cin</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">rg</code> separadas para suportar o período de coexistência até 2032.</li><li>Substitua CPFs e CNPJs reais em seeds por dados gerados via <Link href="/docs" className="text-primary hover:underline">API REST do FakeForge</Link>.</li><li>Use <Link href="/gerador-pessoa" className="text-primary hover:underline">/gerador-pessoa</Link> para fixtures completas com todos os documentos correlacionados em um único request.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Como fazer migração de colunas" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como fazer migração de colunas de CPF/CNPJ com máscara (VARCHAR) para CHAR sem máscara em produção sem downtime?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Use trigger que normaliza entrada nova antes do INSERT. Backfill em chunks noturnos com `UPDATE tabela SET cpf = regexp_replace(cpf, '\D', '', 'g') WHERE id BETWEEN x AND y`. Crie índice único novo em paralelo. Após 100% backfill, remova trigger. PostgreSQL suporta isso sem lock de tabela inteira. Dois comandos: ALTER TABLE ADD CONSTRAINT; DROP old_column.</p>
            </details>
            <details key="Como testar validação de CPF e" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como testar validação de CPF em CI/CD sem expor dados reais em logs?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Chame API do FakeForge antes dos testes para gerar CPFs sintéticos determinísticos (use seed fixo). Crie fixture que popula banco de testes em memória. Logs contêm apenas números gerados, nunca reais. Mock de rede não funciona; integração real é mais segura. Limpe dados pós-teste com teardown().</p>
            </details>
            <details key="Se um CPF passa na validação d" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Se um CPF passa na validação de checksum, posso usá-lo para fins de contato ou assumir que é real?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não. Checksum valida apenas formato, não emissão. Dados sintéticos passam no checksum mas nunca foram emitidos. Para LGPD/contato, exija confirmação secundária: email, SMS, OTP. Mantenha coluna `origem` (real | sintético) para auditoria. Recuse contatos baseados em CPF sintético.</p>
            </details>
            <details key="Como fazer rollout de CNPJ alf" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como fazer rollout de CNPJ alfanumérico (julho/2026) sem quebrar validação legada?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Crie função única `validarCNPJUnificado()` que aceita `[A-Z0-9]&#123;14&#125;` após normalizar para maiúsculas. Novo regex é backward-compatible (0-9 já passam). Mantenha coluna CHAR(14) existente. Teste novo validador com dados mixtos antes de deploy. Sem downtime; apenas atualizar função e redeploy.</p>
            </details>
            <details key="Qual é o risco de aceitar e ar" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Qual é o risco de aceitar e armazenar um CPF real que vem de uma API terceira ou webhook?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Vazamento de dados reais de terceiros sem consentimento. LGPD Art. 6º exige finalidade legítima. Alternativa: não armazene, apenas valide checksum, marque como "verificado externamente", guarde hash + últimos 4 dígitos para referência. Se precisar armazenar, obtenha consentimento explícito. Compliance vale o espaço economizado.</p>
            </details>
          </div>
        </section>
        <ShareBar title={"Documentos Brasileiros: Formatos e Algoritmos de Validação"} path="/blog/documentos-brasileiros-formatos-algoritmos-validacao" />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Como fazer migração de colunas de CPF/CNPJ com máscara (VARCHAR) para CHAR sem máscara em produção sem downtime?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Use trigger que normaliza entrada nova antes do INSERT. Backfill em chunks noturnos com `UPDATE tabela SET cpf = regexp_replace(cpf, '\\\\D', '', 'g') WHERE id BETWEEN x AND y`. Crie índice único novo em paralelo. Após 100% backfill, remova trigger. PostgreSQL suporta isso sem lock de tabela inteira. Dois comandos: ALTER TABLE ADD CONSTRAINT; DROP old_column.\"}},{\"@type\":\"Question\",\"name\":\"Como testar validação de CPF em CI/CD sem expor dados reais em logs?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Chame API do FakeForge antes dos testes para gerar CPFs sintéticos determinísticos (use seed fixo). Crie fixture que popula banco de testes em memória. Logs contêm apenas números gerados, nunca reais. Mock de rede não funciona; integração real é mais segura. Limpe dados pós-teste com teardown().\"}},{\"@type\":\"Question\",\"name\":\"Se um CPF passa na validação de checksum, posso usá-lo para fins de contato ou assumir que é real?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não. Checksum valida apenas formato, não emissão. Dados sintéticos passam no checksum mas nunca foram emitidos. Para LGPD/contato, exija confirmação secundária: email, SMS, OTP. Mantenha coluna `origem` (real | sintético) para auditoria. Recuse contatos baseados em CPF sintético.\"}},{\"@type\":\"Question\",\"name\":\"Como fazer rollout de CNPJ alfanumérico (julho/2026) sem quebrar validação legada?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Crie função única `validarCNPJUnificado()` que aceita `[A-Z0-9]{14}` após normalizar para maiúsculas. Novo regex é backward-compatible (0-9 já passam). Mantenha coluna CHAR(14) existente. Teste novo validador com dados mixtos antes de deploy. Sem downtime; apenas atualizar função e redeploy.\"}},{\"@type\":\"Question\",\"name\":\"Qual é o risco de aceitar e armazenar um CPF real que vem de uma API terceira ou webhook?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Vazamento de dados reais de terceiros sem consentimento. LGPD Art. 6º exige finalidade legítima. Alternativa: não armazene, apenas valide checksum, marque como \\\"verificado externamente\\\", guarde hash + últimos 4 dígitos para referência. Se precisar armazenar, obtenha consentimento explícito. Compliance vale o espaço economizado.\"}}]}",
        }}
      />
    </PageShell>
  );
}
