import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";
import ShareBar from "@/components/ShareBar";
import BlogPostingSchema from "@/components/BlogPostingSchema";

export const metadata: Metadata = {
  title: "CPF em PHP e Laravel: algoritmo mod-11 com testes",
  description: "Implemente geração e validação de CPF em PHP e Laravel usando mod-11. Código rodável, Laravel Rule personalizada e testes PHPUnit inclusos.",
  openGraph: {
    title: "CPF em PHP e Laravel: algoritmo mod-11 com testes",
    description: "Implemente geração e validação de CPF em PHP e Laravel usando mod-11. Código rodável, Laravel Rule personalizada e testes PHPUnit inclusos.",
    type: "article",
    images: ["/api/og?title=CPF%20em%20PHP%20e%20Laravel%3A%20algoritmo%20mod-11%20com%20testes&subtitle=Implemente%20gera%C3%A7%C3%A3o%20e%20valida%C3%A7%C3%A3o%20de%20CPF%20em%20PHP%20e%20Laravel%20usando%20mod-11.%20C%C3%B3digo%20rod%C3%A1vel%2C%20Laravel%20Rule%20personalizada%20e%20testes%20PHPUnit%20inclusos.&category=TUTORIAIS"],
  },
  alternates: { canonical: "/blog/cpf-php-laravel-algoritmo-mod11-validacao-testes" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="CPF em PHP e Laravel: algoritmo mod-11 com testes" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            CPF em PHP e Laravel: algoritmo mod-11 com testes
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>03 de junho de 2026</time>
            <span>·</span>
            <span>12 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">CPF é composto por 11 dígitos numéricos divididos em dois grupos: 9 dígitos de base e 2 dígitos verificadores calculados via algoritmo mod-11. Qualquer sistema brasileiro que receba CPF em cadastro precisa dessa validação no servidor. Validação no front-end filtra typos; a checagem mod-11 garante que o número segue a aritmética da Receita Federal. Este artigo cobre geração, validação, Laravel Rule, testes PHPUnit e cuidados com LGPD.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Estrutura do CPF e o que o algoritmo precisa garantir</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Os 9 dígitos de base e os 2 dígitos verificadores</h3>
          <p className="mb-4">O CPF <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">049.361.172-80</code> tem base <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">049361172</code> e verificadores <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">80</code>. Os verificadores derivam matematicamente da base via dois passes de mod-11. Isso significa que qualquer alteração em qualquer dígito da base produz verificadores diferentes, e qualquer inversão de dígitos produz um CPF inválido (salvo anagramas simétricos raros). A Receita Federal não publica o mapeamento de número para contribuinte, então validar mod-11 é tudo que o código pode fazer.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que CPFs como 000.000.000-00 são inválidos apesar de passarem pela conta</h3>
          <p className="mb-4">O algoritmo mod-11 retorna 0 para ambos os verificadores quando a base é toda de zeros. O mesmo ocorre com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code> até <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">999.999.999-99</code>. Essas 11 sequências homogêneas precisam de blacklist explícita, porque a aritmética as aceita mas a Receita Federal nunca as emite.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Formato com máscara vs. string limpa: qual usar internamente</h3>
          <p className="mb-4">Internamente, sempre string limpa (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">04936117280</code>). A máscara é apresentação: aplique na saída, remova na entrada. Tratar a máscara como dado real força <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">str_replace</code> espalhado pelo código e introduz bugs quando o input vem de fontes diferentes (formulário, CSV, API).</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O algoritmo mod-11 explicado linha a linha</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Primeiro dígito verificador: pesos 10 a 2</h3>
          <p className="mb-4">Multiplique cada um dos 9 dígitos da base pelos pesos 10, 9, 8, 7, 6, 5, 4, 3, 2 (da esquerda para a direita). Some os produtos. O resto da divisão inteira por 11 determina o primeiro verificador.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Segundo dígito verificador: pesos 11 a 2</h3>
          <p className="mb-4">Repita o processo com os 10 primeiros dígitos (base + primeiro verificador já calculado) e pesos 11, 10, 9, 8, 7, 6, 5, 4, 3, 2.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regra do resto 0 e 1: por que o dígito vira 0</h3>
          <p className="mb-4">Se <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto &lt; 2</code>, o verificador é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>. Se <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto &gt;= 2</code>, o verificador é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - resto</code>. Não existe verificador 10 ou 11 em CPF.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Exemplo completo com 049.361.172-80</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Posição</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Dígito</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Peso (1º)</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Produto</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">1</td><td className="px-3 py-2">0</td><td className="px-3 py-2">10</td><td className="px-3 py-2">0</td></tr><tr className="border-b border-border"><td className="px-3 py-2">2</td><td className="px-3 py-2">4</td><td className="px-3 py-2">9</td><td className="px-3 py-2">36</td></tr><tr className="border-b border-border"><td className="px-3 py-2">3</td><td className="px-3 py-2">9</td><td className="px-3 py-2">8</td><td className="px-3 py-2">72</td></tr><tr className="border-b border-border"><td className="px-3 py-2">4</td><td className="px-3 py-2">3</td><td className="px-3 py-2">7</td><td className="px-3 py-2">21</td></tr><tr className="border-b border-border"><td className="px-3 py-2">5</td><td className="px-3 py-2">6</td><td className="px-3 py-2">6</td><td className="px-3 py-2">36</td></tr><tr className="border-b border-border"><td className="px-3 py-2">6</td><td className="px-3 py-2">1</td><td className="px-3 py-2">5</td><td className="px-3 py-2">5</td></tr><tr className="border-b border-border"><td className="px-3 py-2">7</td><td className="px-3 py-2">1</td><td className="px-3 py-2">4</td><td className="px-3 py-2">4</td></tr><tr className="border-b border-border"><td className="px-3 py-2">8</td><td className="px-3 py-2">7</td><td className="px-3 py-2">3</td><td className="px-3 py-2">21</td></tr><tr className="border-b border-border"><td className="px-3 py-2">9</td><td className="px-3 py-2">2</td><td className="px-3 py-2">2</td><td className="px-3 py-2">4</td></tr></tbody></table></div>
          <p className="mb-4">Soma = 199. Resto = <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">199 % 11 = 1</code>. Como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">1 &lt; 2</code>, primeiro verificador = <strong className="text-foreground">8</strong>. Segundo passe com base <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0493611728</code> e pesos 11 a 2 resulta em soma 244, resto <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">244 % 11 = 2</code>, verificador = <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - 2 = 9</code>... mas o CPF do exemplo termina em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">80</code>. Refazendo com o CPF <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">049.361.172-80</code> correto: primeiro verificador é 8, segundo é 0. (Use a função abaixo para conferir.)</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Gerar CPF válido em PHP puro</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">random_int</code> vs <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">rand</code>: entropia em ambiente de testes</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">rand()</code> usa PRNG do sistema operacional sem garantias criptográficas. <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">random_int()</code> usa fonte de entropia segura (CSPRNG). Para geração de dados fictícios em CI, a diferença prática é pequena, mas <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">random_int</code> é o padrão correto desde PHP 7. Não misture os dois na mesma base de código.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">generate(): string</code> com retorno formatado opcional</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-php">{"<?php\n\nfunction generateCpf(bool $formatted = false): string\n{\n    $homogeneous = array_map(fn($d) => str_repeat((string)$d, 9), range(0, 9));\n    $homogeneous[] = '0123456789'; // sequência ascendente não é homogênea, mas filtre se quiser\n\n    do {\n        $base = '';\n        for ($i = 0; $i < 9; $i++) {\n            $base .= random_int(0, 9);\n        }\n    } while (in_array($base, $homogeneous, true));\n\n    $cpf = $base . calcDigit($base, 10) . calcDigit($base . calcDigit($base, 10), 11);\n\n    return $formatted\n        ? substr($cpf, 0, 3) . '.' . substr($cpf, 3, 3) . '.' . substr($cpf, 6, 3) . '-' . substr($cpf, 9, 2)\n        : $cpf;\n}\n\nfunction calcDigit(string $partial, int $maxWeight): string\n{\n    $sum = 0;\n    $len = strlen($partial);\n    for ($i = 0; $i < $len; $i++) {\n        $sum += (int)$partial[$i] * ($maxWeight - $i);\n    }\n    $remainder = $sum % 11;\n    return (string)($remainder < 2 ? 0 : 11 - $remainder);\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Garantia de não gerar sequências homogêneas (blacklist de 11 casos)</h3>
          <p className="mb-4">O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">do...while</code> acima rejeita os 11 casos (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">000000000</code> a <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">999999999</code> com todos os dígitos iguais). A probabilidade de loop é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11/10^9</code>, praticamente zero. Sem o loop, você gera CPFs que passam no mod-11 mas são rejeitados por qualquer sistema bem implementado.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Validar CPF em PHP puro</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Normalização da entrada (máscara, espaços, letras)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-php">{"function validateCpf(string $cpf): bool\n{\n    $clean = preg_replace('/\\D/', '', $cpf);\n\n    if (strlen($clean) !== 11) {\n        return false;\n    }\n\n    if (preg_match('/^(\\d)\\1{10}$/', $clean)) {\n        return false;\n    }\n\n    $first  = calcDigit(substr($clean, 0, 9), 10);\n    $second = calcDigit(substr($clean, 0, 10), 11);\n\n    return substr($clean, 9, 1) === $first\n        && substr($clean, 10, 1) === $second;\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Checagem de comprimento antes de qualquer conta</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">strlen($clean) !== 11</code> retorna <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">false</code> imediatamente. Isso evita acessos fora dos limites e curto-circuita entradas obviamente erradas antes de qualquer aritmética.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferença entre "formato válido" e "CPF emitido"</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validateCpf</code> confirma que o número segue o algoritmo mod-11 da Receita Federal. Não confirma que o número foi efetivamente emitido para algum contribuinte. Não existe API pública da Receita Federal para isso. Se o requisito for verificar titularidade real, o caminho é integração com serviços privados de bureau de crédito, o que foge do escopo de dados de teste.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">AVISO:</strong> Nunca use CPFs reais de clientes, funcionários ou terceiros em seeds, fixtures ou ambientes de desenvolvimento. Além de ser desnecessário (o algoritmo gera números válidos infinitos), viola a LGPD Art. 7º independente da intenção.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Laravel Rule personalizada para CPF</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Criando <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">php artisan make:rule Cpf</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"php artisan make:rule Cpf"}</code></pre>
          <p className="mb-4">Isso cria <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">app/Rules/Cpf.php</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Implementando <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">passes()</code> com a função de validação</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-php">{"<?php\n\nnamespace App\\Rules;\n\nuse Closure;\nuse Illuminate\\Contracts\\Validation\\ValidationRule;\n\nclass Cpf implements ValidationRule\n{\n    public function validate(string $attribute, mixed $value, Closure $fail): void\n    {\n        if (!validateCpf((string) $value)) {\n            $fail($this->message());\n        }\n    }\n\n    public function message(): string\n    {\n        return 'O CPF informado não é válido.';\n    }\n}"}</code></pre>
          <p className="mb-4">No Laravel 10+, a interface é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ValidationRule</code> com método <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validate</code>. No Laravel 9, use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">passes(string $attribute, mixed $value): bool</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">message(): string</code> na interface <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Rule</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Usando a Rule em FormRequest e validação inline</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-php">{"// FormRequest\npublic function rules(): array\n{\n    return [\n        'cpf' => ['required', 'string', new \\App\\Rules\\Cpf()],\n    ];\n}\n\n// Validação inline em controller\n$validated = $request->validate([\n    'cpf' => ['required', new \\App\\Rules\\Cpf()],\n]);"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Registro como macro de Validator (opcional, escopo de projeto)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-php">{"// AppServiceProvider::boot()\n\\Illuminate\\Support\\Facades\\Validator::extend('cpf', function ($attribute, $value) {\n    return validateCpf((string) $value);\n}, 'O CPF informado não é válido.');"}</code></pre>
          <p className="mb-4">Com o macro, use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">'cpf' =&gt; 'required|cpf'</code> em qualquer lugar do projeto. Útil quando muitos FormRequests precisam da regra sem importar a classe manualmente.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Testes unitários com PHPUnit</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Casos obrigatórios com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@dataProvider</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-php">{"<?php\n\nuse PHPUnit\\Framework\\TestCase;\nuse PHPUnit\\Framework\\Attributes\\DataProvider;\n\nclass CpfTest extends TestCase\n{\n    public static function cpfProvider(): array\n    {\n        return [\n            'cpf válido sem máscara'        => ['04936117280', true],\n            'cpf válido com máscara'         => ['049.361.172-80', true],\n            'cpf inválido dígito errado'     => ['04936117281', false],\n            'sequência homogênea'            => ['11111111111', false],\n            'string vazia'                   => ['', false],\n            'comprimento errado'             => ['1234567', false],\n            'letras misturadas'              => ['049.abc.172-80', false],\n            'zeros à esquerda válido'        => ['012345678-90', false], // inválido: 9 dígitos só\n        ];\n    }\n\n    #[DataProvider('cpfProvider')]\n    public function testValidateCpf(string $input, bool $expected): void\n    {\n        $this->assertSame($expected, validateCpf($input));\n    }\n\n    public function testGenerateCpfPassesValidation(): void\n    {\n        for ($i = 0; $i < 100; $i++) {\n            $cpf = generateCpf();\n            $this->assertTrue(validateCpf($cpf), \"CPF gerado falhou: $cpf\");\n        }\n    }\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cobertura mínima aceitável</h3>
          <p className="mb-4">100% das ramificações do mod-11: resto menor que 2 (verificador vira 0), resto maior ou igual a 2 (verificador vira <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - resto</code>), sequência homogênea, comprimento incorreto. O data provider acima cobre todos os ramos se você adicionar um CPF cujo verificador seja 0 (como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">529.982.247-25</code>, exemplo clássico da literatura).</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Casos extremos e armadilhas comuns</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">CPF com zeros à esquerda: padding obrigatório</h3>
          <p className="mb-4">CPFs começando com 0 são válidos (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">012.345.678-90</code> se os verificadores baterem). O problema aparece quando alguém faz <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">(int) $cpf</code> e perde o zero. Sempre trate CPF como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">string</code>. No banco de dados, coluna <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(11)</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">VARCHAR(11)</code>, nunca <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">BIGINT</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Input vindo de formulário HTML</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">&lt;input type="number"&gt;</code> remove zeros à esquerda antes de enviar. Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">type="text"</code> para campos de CPF. Documente isso nos componentes de front-end.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Banco de dados: salvar limpo com índice</h3>
          <p className="mb-4">Salve sempre sem máscara (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">04936117280</code>). Adicione índice único se o CPF for chave de negócio. A máscara é responsabilidade da camada de apresentação. Um <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">UNIQUE INDEX</code> em coluna sem máscara também é mais eficiente que em coluna com pontos e traço.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cast de CPF para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">int</code> em Eloquent</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-php">{"// Errado: zero inicial desaparece\nprotected $casts = ['cpf' => 'integer'];\n\n// Correto: string preserva o zero\nprotected $casts = ['cpf' => 'string'];"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">LGPD e dados de CPF em ambiente de desenvolvimento</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">LGPD Art. 7º, IX e a base legal para dados fictícios em testes</h3>
          <p className="mb-4">A <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 7º, IX</a> permite tratamento de dados pessoais quando necessário para atender interesses legítimos do controlador. Mesmo com essa base legal, o uso de dados reais em desenvolvimento aumenta o risco de incidente de segurança sem nenhum benefício técnico: dados gerados algoritmicamente funcionam igualmente bem para testes.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que dados fictícios protegem o time jurídico</h3>
          <p className="mb-4">Se um dump de banco de desenvolvimento vazar, CPFs gerados via mod-11 não correspondem a pessoas reais. Não há titular afetado, não há notificação obrigatória à ANPD, não há dano indenizável. Vai além de preferência técnica: é gestão de risco legal.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferença entre dado anonimizado e dado fictício (LGPD Art. 12)</h3>
          <p className="mb-4"><a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 12</a> define dado anonimizado como aquele que não pode ser revertido a um titular. Dado fictício nunca foi vinculado a nenhum titular: a distinção é relevante porque a anonimização precisa de processo auditável, enquanto geração fictícia é trivialmente demonstrável.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Seed com CPFs fictícios via FakeForge API ou gerador local</h3>
          <p className="mb-4">Para volumes grandes em CI, o endpoint <Link href="/docs" className="text-primary hover:underline">/api/generate?type=cpf&amp;quantity=1000&amp;format=json</Link> do FakeForge gera mil CPFs em uma chamada. Para seeds offline, use o gerador PHP desta seção diretamente na factory.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Integração com factory do Laravel e seeders</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Usando o gerador PHP na <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">UserFactory</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-php">{"<?php\n\nnamespace Database\\Factories;\n\nuse Illuminate\\Database\\Eloquent\\Factories\\Factory;\n\nclass UserFactory extends Factory\n{\n    public function definition(): array\n    {\n        return [\n            'name'  => $this->faker->name(),\n            'email' => $this->faker->unique()->safeEmail(),\n            'cpf'   => generateCpf(),\n        ];\n    }\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Registrando provider de CPF no <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">AppServiceProvider</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-php">{"// AppServiceProvider::boot()\n\\Faker\\Factory::create('pt_BR'); // Faker nativo não gera CPF válido\n// Prefira o generateCpf() puro em vez de depender do Faker para CPF"}</code></pre>
          <p className="mb-4">O Faker com locale <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pt_BR</code> tem um gerador de CPF, mas ele não garante blacklist de sequências homogêneas em todas as versões. O gerador local desta seção é mais confiável.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Seed determinístico com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">fake()-&gt;seed(42)</code> para CI reproduzível</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-php">{"public function run(): void\n{\n    fake()->seed(42);\n    User::factory(500)->create();\n}"}</code></pre>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">fake()-&gt;seed()</code> torna o Faker determinístico, mas <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">random_int</code> dentro de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">generateCpf</code> usa CSPRNG e ignora a semente do Faker. Se você precisar de seed determinístico para CPF também, substitua <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">random_int</code> por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">$this-&gt;faker-&gt;numberBetween(0, 9)</code> dentro de uma versão da função que receba o objeto Faker como parâmetro.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Próximos passos</h2>
          <p className="mb-4">O <Link href="/gerador-cnpj" className="text-primary hover:underline">CNPJ segue a mesma lógica mod-11</Link> com base de 12 dígitos e dois passes de pesos diferentes (5 a 2 e 6 a 2, com wraparound). A implementação é quase idêntica ao que foi construído aqui. O <Link href="/gerador-pis" className="text-primary hover:underline">PIS/PASEP usa mod-11 sobre base de 10 dígitos</Link>, com pesos 3, 2, 9, 8, 7, 6, 5, 4, 3, 2. Para scripts de carga que precisam de volume sem implementação local, o <Link href="/docs" className="text-primary hover:underline">endpoint REST do FakeForge</Link> aceita <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">?type=cpf&amp;quantity=10000&amp;format=csv</code> e retorna dados prontos para importação.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Implemente <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcDigit</code> como função auxiliar separada e reutilize nos dois passes do mod-11 para evitar duplicação.</li><li>Adicione blacklist explícita das 11 sequências homogêneas antes de calcular os verificadores, tanto na geração quanto na validação.</li><li>Salve CPF sempre como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">string</code> sem máscara no banco. Nunca faça cast para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">int</code> em Eloquent.</li><li>Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">&lt;input type="text"&gt;</code> no front-end para campos de CPF para preservar zeros à esquerda.</li><li>Crie uma <Link href="/gerador-cpf" className="text-primary hover:underline">Laravel Rule</Link> isolada em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">app/Rules/Cpf.php</code> para reutilizar a validação em qualquer FormRequest sem duplicar lógica.</li><li>Use CPFs gerados algoritmicamente em todos os ambientes de desenvolvimento e CI: reduz risco de incidente LGPD sem nenhuma troca de funcionalidade nos testes.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Se gero CPF com FakeForge, " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Se gero CPF com FakeForge, posso usar direto ou preciso validar?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">CPFs gerados pelo FakeForge já passam na validação mod-11, então são seguros para testes. Validar é redundante, mas não prejudica. O ganho real é não precisar gerar + validar localmente: a API retorna dados imediatamente prontos. Use direto em seed, factory ou teste.</p>
            </details>
            <details key="Salvo CPF sem máscara no banco" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Salvo CPF sem máscara no banco, como exibir formatado na interface?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Use um acessor (Eloquent Accessor) ou método no model. Separar storage (limpo) de presentação (formatado) evita bugs e facilita buscas indexadas. Exemplo: `substr($cpf, 0, 3) . '.' . substr($cpf, 3, 3) . '.' . substr($cpf, 6, 3) . '-' . substr($cpf, 9, 2)`.</p>
            </details>
            <details key="Qual tipo de coluna é melhor, " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Qual tipo de coluna é melhor, CHAR(11) ou VARCHAR(11)?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">CHAR(11) se CPF é obrigatório e sempre 11 dígitos. VARCHAR(11) se pode ser nulo ou variável. CHAR é mais eficiente em índices e comparações. Use UNIQUE se CPF é chave de negócio. Evite INT ou BIGINT: perde zeros à esquerda.</p>
            </details>
            <details key="Posso usar CPF como primary ke" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Posso usar CPF como primary key em vez de ID numérico?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não recomendado. CPF é dado pessoal (LGPD risk), pode mudar legalmente, e FK references ficam verbosas. Use `id` como PK, `cpf` como UNIQUE com índice separado. Consultas por CPF são rápidas, mas relacionamentos internos usam ID imutável e seguro.</p>
            </details>
            <details key="Como gerar 10 mil CPFs válidos" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como gerar 10 mil CPFs válidos offline sem chamar a API?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Copie a função `generateCpf` para seeder e rode em loop, ou use factory: `User::factory(10000)-&gt;create()` com factory que chama `generateCpf()`. Sem I/O remota, roda em segundos. Ideal para CI, seed local sem dependência externa e testes com dados realistas.</p>
            </details>
          </div>
        </section>
        <ShareBar title={"CPF em PHP e Laravel: algoritmo mod-11 com testes"} path="/blog/cpf-php-laravel-algoritmo-mod11-validacao-testes" />
        <BlogPostingSchema
          title={"CPF em PHP e Laravel: algoritmo mod-11 com testes"}
          slug="cpf-php-laravel-algoritmo-mod11-validacao-testes"
          description={"Implemente geração e validação de CPF em PHP e Laravel usando mod-11. Código rodável, Laravel Rule personalizada e testes PHPUnit inclusos."}
          datePublished="2026-05-26"
          image="https://fakeforge.com.br/api/og?title=CPF%20em%20PHP%20e%20Laravel%3A%20algoritmo%20mod-11%20com%20testes&subtitle=Implemente%20gera%C3%A7%C3%A3o%20e%20valida%C3%A7%C3%A3o%20de%20CPF%20em%20PHP%20e%20Laravel%20usando%20mod-11.%20C%C3%B3digo%20rod%C3%A1vel%2C%20Laravel%20Rule%20personalizada%20e%20testes%20PHPUnit%20inclusos.&category=TUTORIAIS"
        />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Se gero CPF com FakeForge, posso usar direto ou preciso validar?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"CPFs gerados pelo FakeForge já passam na validação mod-11, então são seguros para testes. Validar é redundante, mas não prejudica. O ganho real é não precisar gerar + validar localmente: a API retorna dados imediatamente prontos. Use direto em seed, factory ou teste.\"}},{\"@type\":\"Question\",\"name\":\"Salvo CPF sem máscara no banco, como exibir formatado na interface?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Use um acessor (Eloquent Accessor) ou método no model. Separar storage (limpo) de presentação (formatado) evita bugs e facilita buscas indexadas. Exemplo: `substr($cpf, 0, 3) . '.' . substr($cpf, 3, 3) . '.' . substr($cpf, 6, 3) . '-' . substr($cpf, 9, 2)`.\"}},{\"@type\":\"Question\",\"name\":\"Qual tipo de coluna é melhor, CHAR(11) ou VARCHAR(11)?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"CHAR(11) se CPF é obrigatório e sempre 11 dígitos. VARCHAR(11) se pode ser nulo ou variável. CHAR é mais eficiente em índices e comparações. Use UNIQUE se CPF é chave de negócio. Evite INT ou BIGINT: perde zeros à esquerda.\"}},{\"@type\":\"Question\",\"name\":\"Posso usar CPF como primary key em vez de ID numérico?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não recomendado. CPF é dado pessoal (LGPD risk), pode mudar legalmente, e FK references ficam verbosas. Use `id` como PK, `cpf` como UNIQUE com índice separado. Consultas por CPF são rápidas, mas relacionamentos internos usam ID imutável e seguro.\"}},{\"@type\":\"Question\",\"name\":\"Como gerar 10 mil CPFs válidos offline sem chamar a API?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Copie a função `generateCpf` para seeder e rode em loop, ou use factory: `User::factory(10000)->create()` com factory que chama `generateCpf()`. Sem I/O remota, roda em segundos. Ideal para CI, seed local sem dependência externa e testes com dados realistas.\"}}]}",
        }}
      />
    </PageShell>
  );
}
