import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";

export const metadata: Metadata = {
  title: "Como Gerar CPF Válido em Python para Testes",
  description: "Aprenda a gerar CPFs válidos em Python do zero e com Faker. Código rodável, fixtures para pytest e orientações LGPD para testes seguros.",
  openGraph: {
    title: "Como Gerar CPF Válido em Python para Testes",
    description: "Aprenda a gerar CPFs válidos em Python do zero e com Faker. Código rodável, fixtures para pytest e orientações LGPD para testes seguros.",
    type: "article",
  },
  alternates: { canonical: "/blog/como-gerar-cpf-valido-python-testes" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Como Gerar CPF Válido em Python para Testes" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Como Gerar CPF Válido em Python para Testes
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>05 de maio de 2026</time>
            <span>·</span>
            <span>9 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">Gerar um CPF para testes parece simples até o validador de produção rejeitar o número. CPFs como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code> passam na regex de formato, mas quebram em qualquer implementação que calcule os dígitos verificadores — e isso derruba formulários, quebra seeds de banco e faz pipelines de CI falharem em silêncio.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">CPF válido não é número qualquer — entenda o que seu teste realmente precisa</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">A diferença entre CPF "formatado" e CPF "válido"</h3>
          <p className="mb-4">Um CPF formatado segue o padrão <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">XXX.XXX.XXX-XX</code>. Um CPF válido, além do formato, tem os dois últimos dígitos calculados com base nos nove primeiros via Módulo 11. Você pode ter um CPF formatado que nunca existiu e que qualquer biblioteca de validação descarta imediatamente.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code> quebra validadores de produção</h3>
          <p className="mb-4">A Receita Federal define que CPFs com todos os dígitos iguais — <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">000.000.000-00</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code>, até <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">999.999.999-99</code> — são inválidos por definição, independentemente do resultado do Módulo 11. Muitos tutoriais ignoram esse caso e produzem geradores que passam em 90% dos testes, mas falham exatamente nos edge cases que importam.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cenários de teste que exigem CPF com dígitos verificadores corretos</h3>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Formulários com biblioteca <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cpf-check</code> ou equivalente no backend</li><li>Seeds de banco com constraints de unicidade e validação em trigger</li><li>Testes de integração contra APIs de terceiros (bancos, processadores de pagamento)</li><li>Testes de carga onde o volume exige CPFs únicos sem colisão</li></ul>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O algoritmo do CPF é determinístico — dois passos, nenhuma magia</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura do CPF: 9 dígitos base + 2 dígitos verificadores</h3>
          <p className="mb-4">Um CPF tem 11 dígitos: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">D1 D2 D3 . D4 D5 D6 . D7 D8 D9 - V1 V2</code>. Os nove primeiros são gerados aleatoriamente (com restrição de sequências repetidas). <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">V1</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">V2</code> são calculados deterministicamente a partir dos anteriores.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Módulo 11 na prática: cálculo do primeiro dígito</h3>
          <p className="mb-4">Multiplique os nove dígitos base pelos pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">10, 9, 8, 7, 6, 5, 4, 3, 2</code>. Some os produtos. Calcule <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto = soma % 11</code>. Se <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto < 2</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">V1 = 0</code>; senão, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">V1 = 11 - resto</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Módulo 11 na prática: cálculo do segundo dígito</h3>
          <p className="mb-4">Repita com os dez dígitos (base + <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">V1</code>) multiplicados pelos pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11, 10, 9, 8, 7, 6, 5, 4, 3, 2</code>. Mesma regra de arredondamento para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">V2</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Casos especiais: sequências repetidas são inválidas pela Receita Federal</h3>
          <p className="mb-4">Antes de retornar qualquer CPF gerado, verifique se todos os dígitos são iguais. Se forem, descarte e gere outro. A probabilidade é baixa, mas num gerador em loop de 10 mil CPFs acontece.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Implementação do zero em Python puro</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">gerar_cpf()</code> sem dependências externas</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"import random\n\ndef _calcular_digito(digitos: list[int], peso_inicial: int) -> int:\n    soma = sum(d * p for d, p in zip(digitos, range(peso_inicial, 1, -1)))\n    resto = soma % 11\n    return 0 if resto < 2 else 11 - resto\n\ndef gerar_cpf(formatado: bool = False) -> str:\n    while True:\n        base = [random.randint(0, 9) for _ in range(9)]\n        if len(set(base)) == 1:\n            continue  # descarta sequências repetidas\n        v1 = _calcular_digito(base, 10)\n        v2 = _calcular_digito(base + [v1], 11)\n        cpf = base + [v1, v2]\n        numero = \"\".join(map(str, cpf))\n        if formatado:\n            return f\"{numero[:3]}.{numero[3:6]}.{numero[6:9]}-{numero[9:]}\"\n        return numero"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">formatar_cpf()</code> para saída <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">XXX.XXX.XXX-XX</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"def formatar_cpf(cpf: str) -> str:\n    c = cpf.replace(\".\", \"\").replace(\"-\", \"\")\n    return f\"{c[:3]}.{c[3:6]}.{c[6:9]}-{c[9:]}\""}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validar_cpf()</code> para smoke-test do próprio gerador</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"def validar_cpf(cpf: str) -> bool:\n    c = cpf.replace(\".\", \"\").replace(\"-\", \"\")\n    if len(c) != 11 or len(set(c)) == 1:\n        return False\n    digitos = [int(x) for x in c]\n    v1 = _calcular_digito(digitos[:9], 10)\n    v2 = _calcular_digito(digitos[:10], 11)\n    return digitos[9] == v1 and digitos[10] == v2"}</code></pre>
          <p className="mb-4">Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">assert validar_cpf(gerar_cpf())</code> como verificação no início da suíte para confirmar que o gerador está correto antes de qualquer teste. Prefere <Link href="/gerador-cpf" className="text-primary hover:underline">gerar CPFs diretamente no navegador</Link> para testes manuais.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Gerar CPF com a biblioteca Faker (locale <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pt_BR</code>)</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Instalação e configuração do <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">faker</code> com locale brasileiro</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"pip install faker"}</code></pre>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"from faker import Faker\n\nfake = Faker(\"pt_BR\")\nprint(fake.cpf())  # ex: 847.231.965-02"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">fake.cpf()</code> versus implementação própria: quando cada uma serve</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Critério</th><th className="text-left px-3 py-2 text-muted-foreground font-medium"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">fake.cpf()</code></th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Implementação própria</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">Configuração</td><td className="px-3 py-2">1 linha</td><td className="px-3 py-2">~20 linhas</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Controle do algoritmo</td><td className="px-3 py-2">Nenhum</td><td className="px-3 py-2">Total</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Auditabilidade</td><td className="px-3 py-2">Depende da versão</td><td className="px-3 py-2">Você decide</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Seed determinístico</td><td className="px-3 py-2">Sim</td><td className="px-3 py-2">Manual</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Geração em lote customizada</td><td className="px-3 py-2">Limitado</td><td className="px-3 py-2">Flexível</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Dependências externas</td><td className="px-3 py-2">Sim</td><td className="px-3 py-2">Nenhuma</td></tr></tbody></table></div>
          <p className="mb-4">Para a maioria dos projetos, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">fake.cpf()</code> é suficiente. Use implementação própria quando precisar de auditabilidade, comportamento customizado ou quando o projeto proíbe dependências externas.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Seed para geração determinística em CI/CD</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"from faker import Faker\n\nfake = Faker(\"pt_BR\")\nFaker.seed(42)  # mesmo seed → mesmos CPFs em toda execução\n\ncpfs = [fake.cpf() for _ in range(10)]\n# lista idêntica em qualquer máquina com seed=42"}</code></pre>
          <p className="mb-4">Fixar o seed garante que snapshots de teste não quebrem por variação aleatória entre runs de CI.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Fixtures de pytest prontas para CPF</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@pytest.fixture</code> com CPF único por teste</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"import pytest\nfrom faker import Faker\n\nfake = Faker(\"pt_BR\")\n\n@pytest.fixture\ndef cpf_valido() -> str:\n    return fake.cpf()\n\ndef test_cadastro_aceita_cpf_valido(cpf_valido):\n    resultado = cadastrar_usuario(cpf=cpf_valido)\n    assert resultado.sucesso is True"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@pytest.fixture(params=[...])</code> para testar múltiplos CPFs em lote</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"@pytest.fixture(params=[fake.cpf() for _ in range(5)])\ndef cpf_parametrizado(request) -> str:\n    return request.param\n\ndef test_validador_aceita_varios_cpfs(cpf_parametrizado):\n    assert validar_cpf(cpf_parametrizado) is True"}</code></pre>
          <p className="mb-4">Essa fixture roda o teste cinco vezes, uma por CPF. Útil para detectar falsos negativos no validador.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Factory fixture para CPFs inválidos (teste de rejeição)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"@pytest.fixture\ndef cpf_invalido() -> str:\n    cpf = fake.cpf().replace(\".\", \"\").replace(\"-\", \"\")\n    # corrompe o primeiro dígito verificador\n    invalido = cpf[:9] + str((int(cpf[9]) + 1) % 10) + cpf[10]\n    return invalido\n\ndef test_cadastro_rejeita_cpf_invalido(cpf_invalido):\n    with pytest.raises(ValueError, match=\"CPF inválido\"):\n        cadastrar_usuario(cpf=cpf_invalido)"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">DICA: teste de rejeição é tão importante quanto teste de aceitação. Um validador que aceita tudo "passa" nos testes positivos, mas falha em produção.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Geração em lote para testes de carga e seeds de banco</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Gerando 10.000 CPFs únicos sem colisão</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"def gerar_cpfs_unicos(quantidade: int) -> list[str]:\n    cpfs: set[str] = set()\n    while len(cpfs) < quantidade:\n        cpfs.add(gerar_cpf())\n    return list(cpfs)\n\nlote = gerar_cpfs_unicos(10_000)\nprint(f\"Gerados: {len(lote)} CPFs únicos\")"}</code></pre>
          <p className="mb-4">O uso de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">set</code> garante unicidade sem comparação explícita. Para 10.000 CPFs, o risco de colisão é negligível dado o espaço de aproximadamente 900 milhões de CPFs válidos possíveis.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Exportando para CSV e SQL INSERT</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"import csv\n\ndef exportar_csv(cpfs: list[str], caminho: str) -> None:\n    with open(caminho, \"w\", newline=\"\", encoding=\"utf-8\") as f:\n        writer = csv.writer(f)\n        writer.writerow([\"cpf\"])\n        writer.writerows([[formatar_cpf(cpf)] for cpf in cpfs])\n\ndef exportar_sql(cpfs: list[str], tabela: str = \"usuarios_teste\") -> str:\n    linhas = [\n        f\"CREATE TABLE IF NOT EXISTS {tabela} (cpf CHAR(14) PRIMARY KEY);\",\n        \"\",\n    ]\n    for cpf in cpfs:\n        linhas.append(f\"INSERT INTO {tabela} (cpf) VALUES ('{formatar_cpf(cpf)}');\")\n    return \"\\n\".join(linhas)"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Evitar duplicatas em suítes paralelas com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">uuid</code>-seed</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"import uuid\n\ndef seed_por_worker(worker_id: str) -> int:\n    return int(uuid.uuid5(uuid.NAMESPACE_DNS, worker_id).int % 2**31)\n\nFaker.seed(seed_por_worker(\"worker-1\"))"}</code></pre>
          <p className="mb-4">Em pytest-xdist, passe o <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">worker_id</code> disponível em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">request.config.workerinput["workerid"]</code> para garantir seeds diferentes por processo paralelo.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">LGPD exige dados fictícios — não é opcional</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">LGPD Art. 7º, IX e o legítimo interesse em ambientes de teste</h3>
          <p className="mb-4">A <a href="https://www.planalto.gov.br/cciv_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">Lei Geral de Proteção de Dados (LGPD, Art. 7º, IX)</a> permite o tratamento de dados pessoais quando baseado em legítimo interesse do controlador — mas esse interesse não cobre ambientes de desenvolvimento e teste com dados reais de titulares sem consentimento explícito. Dados fictícios eliminam a questão na raiz.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O risco de usar CPFs reais capturados em produção para testes</h3>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Ambientes de desenvolvimento têm controles de acesso mais fracos que produção</li><li>Desenvolvedores terceiros (freelancers, agências) acessam dados reais sem necessidade</li><li>Um dump de banco de desenvolvimento vazado expõe dados de titulares reais</li><li>A ANPD aplicou sanções em casos de exposição por ambientes não-produtivos</li></ul>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">AVISO: usar CPFs reais em seeds de banco de teste, fixtures ou dados de CI viola a LGPD independentemente de a base estar em ambiente isolado. A obrigação de minimização de dados (<a href="https://www.planalto.gov.br/cciv_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 6º, III</a>) se aplica a todos os contextos de tratamento.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Pseudonimização vs. anonimização: qual o padrão correto para dados de teste</h3>
          <p className="mb-4"><strong className="text-foreground">Pseudonimização</strong> substitui o CPF real por um identificador que pode ser revertido com uma chave. Ainda é dado pessoal sob a LGPD.</p>
          <p className="mb-4"><strong className="text-foreground">Anonimização</strong> (<a href="https://www.planalto.gov.br/cciv_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 5º, III</a>) transforma o dado de forma que não possa ser revertido. CPFs gerados artificialmente com Módulo 11 são anonimizados desde a origem — não há titular.</p>
          <p className="mb-4">Para dados de teste, gerar do zero é a abordagem correta. Mascarar dados reais cria risco residual de re-identificação.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Validação cruzada: testar se seu gerador está correto</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Comparar saída com a calculadora da Receita Federal</h3>
          <p className="mb-4">O portal da Receita Federal verifica se um CPF existe cadastrado, não se o algoritmo é válido. Para validar o algoritmo, use a função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validar_cpf()</code> implementada acima ou rode <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">assert all(validar_cpf(c) for c in gerar_cpfs_unicos(1000))</code> como smoke-test isolado.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Testar contra o endpoint <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/validar-cpf</code> do FakeForge BR</h3>
          <p className="mb-4">Para uma segunda opinião independente, <Link href="/validar-cpf" className="text-primary hover:underline">valide o CPF gerado contra as regras da Receita Federal</Link> sem instalar nada. O endpoint aceita CPF com ou sem formatação e retorna o resultado da verificação de dígitos.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Propriedades invariantes para testes baseados em propriedade com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">hypothesis</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"from hypothesis import given, settings\nfrom hypothesis import strategies as st\n\n@given(\n    st.integers(min_value=0, max_value=999_999_999).map(\n        lambda n: [int(d) for d in str(n).zfill(9)]\n    )\n)\n@settings(max_examples=500)\ndef test_digitos_calculados_produzem_cpf_valido(base: list[int]):\n    if len(set(base)) == 1:\n        return  # sequência repetida, pular\n    v1 = _calcular_digito(base, 10)\n    v2 = _calcular_digito(base + [v1], 11)\n    cpf = \"\".join(map(str, base)) + str(v1) + str(v2)\n    assert validar_cpf(cpf)"}</code></pre>
          <p className="mb-4">O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">hypothesis</code> gera centenas de combinações de dígitos base e verifica que o cálculo sempre produz um CPF válido. Isso testa o algoritmo, não apenas exemplos fixos.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Alternativa sem código: API REST do FakeForge BR</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">GET /api/generate?type=cpf&quantity=100&format=json</code> — resposta em milissegundos</h3>
          <p className="mb-4">Para times sem Python, lambdas de CI ou pipelines de dados que precisam de CPFs prontos:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=cpf&quantity=100&format=json\"\n# {\"data\":[{\"cpf\":\"382.910.475-06\"}, ...]}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Exportar direto para SQL com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code> e CREATE TABLE incluído</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=cpf&quantity=500&format=sql\"\n# CREATE TABLE cpf (cpf VARCHAR(14));\n# INSERT INTO cpf VALUES ('382.910.475-06');\n# ..."}</code></pre>
          <p className="mb-4">A resposta inclui <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE</code> com a definição de colunas e os <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">INSERT INTO</code> prontos para colar no seu seed de banco. Veja a <Link href="/docs" className="text-primary hover:underline">documentação completa da API REST</Link> para todos os parâmetros disponíveis.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quando usar a API em vez de código próprio</h3>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Times de QA sem ambiente Python configurado</li><li>Pipelines em AWS Lambda ou Google Cloud Functions onde instalar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">faker</code> é overhead</li><li>Projetos multi-linguagem que precisam de uma fonte centralizada de dados de teste</li><li>Necessidade de dados correlacionados: CPF + nome + endereço em um único request via <Link href="/gerador-pessoa" className="text-primary hover:underline">gerador de pessoa completa com CPF e endereço correlacionados</Link></li></ul>
          <p className="mb-4">Para uso em CI/CD com volume alto, veja os <Link href="/pricing" className="text-primary hover:underline">planos para uso da API em times</Link>. O plano gratuito cobre 100 chamadas/dia; o plano Dev (R$29/mês) sobe para 5.000 chamadas/dia. Confira também o <Link href="/comparacao/fakeforge-vs-alternativas" className="text-primary hover:underline">comparativo com outras ferramentas de dados de teste</Link> antes de decidir a abordagem.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li><strong className="text-foreground">Algoritmo</strong>: CPF válido exige Módulo 11 em dois passos e rejeição de sequências repetidas — sem isso, validadores de produção descartam o número.</li><li><strong className="text-foreground">Python puro</strong>: a função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">gerar_cpf()</code> com menos de 20 linhas cobre todos os casos sem dependências externas; inclua <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validar_cpf()</code> como smoke-test do próprio gerador.</li><li><strong className="text-foreground">Faker</strong>: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Faker("pt_BR").cpf()</code> com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Faker.seed(42)</code> é suficiente para a maioria dos projetos e garante reprodutibilidade em CI/CD sem implementar o algoritmo do zero.</li><li><strong className="text-foreground">Pytest</strong>: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@pytest.fixture</code> para CPF único por teste, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@pytest.fixture(params=[...])</code> para cobertura em lote e factory fixture para CPFs inválidos — teste de rejeição é obrigatório.</li><li><strong className="text-foreground">LGPD</strong>: dados gerados artificialmente são a única abordagem segura — pseudonimizar dados reais ainda cria risco residual de re-identificação conforme o Art. 5º, III.</li><li><strong className="text-foreground">Próximo passo</strong>: gere CNPJ, endereço e PIX correlacionados para testes end-to-end com o <Link href="/gerador-cnpj" className="text-primary hover:underline">gerador de CNPJ</Link> e o <Link href="/gerador-pix" className="text-primary hover:underline">gerador de PIX</Link>, ou use a API do FakeForge BR para dados compostos em um único request.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Meu gerador evita CPFs com tod" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Meu gerador evita CPFs com todos os dígitos iguais, mas preciso testar esse edge case?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sim. Crie uma fixture que força `cpf_invalido = '111.111.111-11'` e teste que seu validador o rejeita. O Módulo 11 pode calcular dígitos "tecnicamente corretos", mas a Receita Federal bloqueia por definição. Validadores em produção exploram esse caso para detectar dados fake.</p>
            </details>
            <details key="Qual o risco de um CPF gerado " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Qual o risco de um CPF gerado aleatoriamente já existir em produção?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Negligível: ~900M CPFs válidos possíveis. Gerar 10 mil CPFs tem risco matemático &lt; 0,01%. Porém, se seu BD tem unique constraint, configure retry: ao INSERT falhar por duplicata, gere outro. O endpoint REST do FakeForge já faz isso internamente para volumes grandes.</p>
            </details>
            <details key="Faker ou função própria em Pyt" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Faker ou função própria em Python? Qual é mais rápido para 10 mil CPFs?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Faker (compilado) é ~10x mais rápido: ~1-2 microsegundos/CPF vs. 5-10 microsegundos da função pura. Para volumes &lt; 1000, a diferença é imperceptível. Acima disso, Faker vence. Trade-off: Faker = 1 linha + dependência; função própria = 20 linhas + sem dependência.</p>
            </details>
            <details key="Como testo se meu validador re" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como testo se meu validador rejeita CPFs inválidos, não só aceita os válidos?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Use a factory fixture `cpf_invalido()` do artigo (corrompe um dígito verificador), ou chame `assert not validar_cpf('12345678901')` localmente. Para segunda opinião independente, POST o CPF no endpoint `/validar-cpf` do FakeForge BR — serve como oráculo externo.</p>
            </details>
            <details key="Devo armazenar CPFs em arquivo" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Devo armazenar CPFs em arquivo de seed formatados (XXX.XXX.XXX-XX) ou sem formatação?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sem formatação (11 dígitos puros): mais compacto, mais portável entre linguagens, mais fácil comparar em testes. Aplique formatação apenas na exibição ou antes de enviar para APIs/BD. CSV de 10 mil CPFs: 110 KB sem formatação, 150 KB com.</p>
            </details>
          </div>
        </section>
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Meu gerador evita CPFs com todos os dígitos iguais, mas preciso testar esse edge case?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sim. Crie uma fixture que força `cpf_invalido = '111.111.111-11'` e teste que seu validador o rejeita. O Módulo 11 pode calcular dígitos \\\"tecnicamente corretos\\\", mas a Receita Federal bloqueia por definição. Validadores em produção exploram esse caso para detectar dados fake.\"}},{\"@type\":\"Question\",\"name\":\"Qual o risco de um CPF gerado aleatoriamente já existir em produção?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Negligível: ~900M CPFs válidos possíveis. Gerar 10 mil CPFs tem risco matemático < 0,01%. Porém, se seu BD tem unique constraint, configure retry: ao INSERT falhar por duplicata, gere outro. O endpoint REST do FakeForge já faz isso internamente para volumes grandes.\"}},{\"@type\":\"Question\",\"name\":\"Faker ou função própria em Python? Qual é mais rápido para 10 mil CPFs?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Faker (compilado) é ~10x mais rápido: ~1-2 microsegundos/CPF vs. 5-10 microsegundos da função pura. Para volumes < 1000, a diferença é imperceptível. Acima disso, Faker vence. Trade-off: Faker = 1 linha + dependência; função própria = 20 linhas + sem dependência.\"}},{\"@type\":\"Question\",\"name\":\"Como testo se meu validador rejeita CPFs inválidos, não só aceita os válidos?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Use a factory fixture `cpf_invalido()` do artigo (corrompe um dígito verificador), ou chame `assert not validar_cpf('12345678901')` localmente. Para segunda opinião independente, POST o CPF no endpoint `/validar-cpf` do FakeForge BR — serve como oráculo externo.\"}},{\"@type\":\"Question\",\"name\":\"Devo armazenar CPFs em arquivo de seed formatados (XXX.XXX.XXX-XX) ou sem formatação?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sem formatação (11 dígitos puros): mais compacto, mais portável entre linguagens, mais fácil comparar em testes. Aplique formatação apenas na exibição ou antes de enviar para APIs/BD. CSV de 10 mil CPFs: 110 KB sem formatação, 150 KB com.\"}}]}",
        }}
      />
    </PageShell>
  );
}
