import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";

export const metadata: Metadata = {
  title: "Como Gerar CPF Válido em Python para Testes",
  description: "Implemente um gerador de CPF válido em Python do zero: algoritmo mod-11, fixtures para pytest, integração com Faker e alternativa via API REST sem código.",
  openGraph: {
    title: "Como Gerar CPF Válido em Python para Testes",
    description: "Implemente um gerador de CPF válido em Python do zero: algoritmo mod-11, fixtures para pytest, integração com Faker e alternativa via API REST sem código.",
    type: "article",
    images: ["/api/og?title=Como%20Gerar%20CPF%20V%C3%A1lido%20em%20Python%20para%20Testes&subtitle=Implemente%20um%20gerador%20de%20CPF%20v%C3%A1lido%20em%20Python%20do%20zero%3A%20algoritmo%20mod-11%2C%20fixtures%20para%20pytest%2C%20integra%C3%A7%C3%A3o%20com%20Faker%20e%20alternativa%20via%20API%20RE&category=TUTORIAIS"],
  },
  alternates: { canonical: "/blog/como-gerar-cpf-valido-python-testes" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Como Gerar CPF Válido em Python para Testes" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Como Gerar CPF Válido em Python para Testes
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>06 de maio de 2026</time>
            <span>·</span>
            <span>9 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">Gerar um CPF qualquer não é suficiente. Qualquer sistema com validação mínima vai rejeitar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">123.456.789-00</code>. Para testes que passam de verdade, o CPF precisa ter os dois dígitos verificadores calculados corretamente pelo algoritmo mod-11 da Receita Federal. Este artigo implementa isso do zero, em Python puro, e mostra como integrar com pytest, Faker e factory_boy.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">CPF válido para testes é diferente de CPF real</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que torna um CPF "válido" no formato</h3>
          <p className="mb-4">Um CPF tem 11 dígitos: nove dígitos base e dois dígitos verificadores. A validade formal não depende de nenhum cadastro — depende apenas de os dois últimos dígitos serem o resultado correto do cálculo mod-11 sobre os nove primeiros. Qualquer número de 11 dígitos que passe nesse cálculo é "válido" no formato, mesmo nunca tendo sido emitido pela Receita Federal.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que CPFs sequenciais quebram validadores</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111-11</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">000.000.000-00</code> e similares são descartados por regra explícita: qualquer CPF com todos os dígitos iguais é inválido por definição, independente do mod-11. Além disso, números como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">123.456.789-09</code> falham no cálculo dos verificadores. Fixar esses valores em fixtures é garantia de falhas intermitentes conforme os testes evoluem.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que a LGPD diz sobre usar CPFs reais em ambiente de dev</h3>
          <p className="mb-4">Usar CPFs reais de clientes ou funcionários em banco de dados de desenvolvimento ou staging viola a LGPD Art. 46 (<a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">Lei 13.709/2018</a>), que exige medidas técnicas para proteger dados pessoais contra acessos não autorizados. Ambientes de desenvolvimento raramente têm os controles de acesso de produção. CPFs gerados algoritmicamente eliminam o risco na raiz.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O algoritmo mod-11 do CPF em 4 etapas</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura dos 11 dígitos (9 base + 2 verificadores)</h3>
          <p className="mb-4">Um CPF <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ABC.DEF.GHI-JK</code> tem:</p>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Dígitos base: posições 0 a 8 (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">A</code> a <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">I</code>)</li><li>Primeiro verificador: posição 9 (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">J</code>)</li><li>Segundo verificador: posição 10 (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">K</code>)</li></ul>
          <p className="mb-4">Os dois verificadores são calculados sequencialmente — o segundo depende do primeiro.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cálculo do primeiro dígito verificador</h3>
          <p className="mb-4">Multiplique cada um dos 9 dígitos base pelos pesos 10, 9, 8, 7, 6, 5, 4, 3, 2 (respectivamente). Some os produtos. Calcule <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto = soma % 11</code>. Se <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto &lt; 2</code>, o verificador é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>; caso contrário, é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - resto</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cálculo do segundo dígito verificador</h3>
          <p className="mb-4">Repita o processo com os 10 dígitos (base + primeiro verificador), usando os pesos 11, 10, 9, 8, 7, 6, 5, 4, 3, 2. Mesma regra: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto &lt; 2</code> → <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>, senão <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - resto</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Casos especiais: dígito resultado 10 ou 11 vira 0</h3>
          <p className="mb-4">O módulo 11 nunca produz 10 ou 11 como resto direto. O que pode acontecer é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - resto</code> resultar nesses valores quando o resto é 1 ou 0 — mas a regra <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto &lt; 2 → dígito = 0</code> cobre exatamente esses casos. Não há lógica adicional necessária.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Implementação mínima em Python puro</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">gerar_cpf()</code> sem dependências externas</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"import random\n\ndef _calcular_digito(digitos: list[int], pesos: list[int]) -> int:\n    soma = sum(d * p for d, p in zip(digitos, pesos))\n    resto = soma % 11\n    return 0 if resto < 2 else 11 - resto\n\ndef gerar_cpf(formatado: bool = True) -> str:\n    base = [random.randint(0, 9) for _ in range(9)]\n\n    pesos1 = list(range(10, 1, -1))  # 10, 9, ..., 2\n    d1 = _calcular_digito(base, pesos1)\n\n    pesos2 = list(range(11, 1, -1))  # 11, 10, ..., 2\n    d2 = _calcular_digito(base + [d1], pesos2)\n\n    digitos = base + [d1, d2]\n    cpf = \"\".join(map(str, digitos))\n\n    if formatado:\n        return f\"{cpf[:3]}.{cpf[3:6]}.{cpf[6:9]}-{cpf[9:]}\"\n    return cpf"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Retorno com e sem formatação (pontos e traço)</h3>
          <p className="mb-4">O parâmetro <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">formatado=True</code> retorna <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">382.947.102-55</code>. Com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">formatado=False</code>, retorna <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">38294710255</code> — útil para inserção direta em banco de dados ou comparação sem normalização prévia.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Testando manualmente contra o validador da Receita Federal</h3>
          <p className="mb-4">Execute <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">gerar_cpf()</code> e cole o resultado no <Link href="/validar-cpf" className="text-primary hover:underline">validador de CPF</Link> do FakeForge ou na consulta do site da Receita Federal. Todo CPF gerado por essa função deve passar na validação de formato.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Validador de CPF em Python para fechar o ciclo</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validar_cpf(cpf: str) -&gt; bool</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"def validar_cpf(cpf: str) -> bool:\n    cpf = \"\".join(filter(str.isdigit, cpf))\n\n    if len(cpf) != 11:\n        return False\n\n    if len(set(cpf)) == 1:\n        return False\n\n    digitos = [int(d) for d in cpf]\n\n    pesos1 = list(range(10, 1, -1))\n    d1 = _calcular_digito(digitos[:9], pesos1)\n    if d1 != digitos[9]:\n        return False\n\n    pesos2 = list(range(11, 1, -1))\n    d2 = _calcular_digito(digitos[:10], pesos2)\n    return d2 == digitos[10]"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Tratamento de entrada: remover máscara antes de validar</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"".join(filter(str.isdigit, cpf))</code> extrai apenas os dígitos, aceitando qualquer formato de entrada: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">382.947.102-55</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">38294710255</code> ou até <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">382 947 102 55</code>. Isso evita falsos negativos por diferença de formatação — problema comum quando o CPF vem de formulários HTML com máscaras JavaScript.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Rejeitar CPFs com todos os dígitos iguais (00000000000 é inválido)</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">len(set(cpf)) == 1</code> cobre <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">00000000000</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11111111111</code> até <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">99999999999</code>. Esses números são casos degenerados onde o algoritmo mod-11 coincide e produziria verificadores "corretos", mas a Receita Federal os considera inválidos por definição.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Gerar lotes de CPFs únicos com garantia de unicidade</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Usando <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">set</code> para evitar duplicatas</h3>
          <p className="mb-4">Gerar 1.000 CPFs aleatoriamente e esperar que não haja colisão não é suficiente. A probabilidade de colisão cresce quadraticamente (paradoxo do aniversário). Com aproximadamente 900 milhões de CPFs válidos possíveis, a chance de colisão em lotes pequenos é baixa, mas não é zero. Use um <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">set</code> para garantir unicidade sem depender de probabilidade.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">gerar_lote(n: int) -&gt; list[str]</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"def gerar_lote(n: int, formatado: bool = False) -> list[str]:\n    resultado: set[str] = set()\n    while len(resultado) < n:\n        resultado.add(gerar_cpf(formatado=formatado))\n    return list(resultado)"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">DICA:</strong> Para lotes acima de 500.000 CPFs, considere a <Link href="/docs" className="text-primary hover:underline">API do FakeForge</Link> — ela paraleliza a geração e retorna direto em CSV ou SQL, sem saturar a memória do processo Python.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Benchmark: quantos CPFs/s a implementação pura gera</h3>
          <p className="mb-4">Medido com Python 3.12, hardware Apple M2, sem otimizações ou multiprocessing:</p>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Lote</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Tempo</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">CPFs/s</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">1.000</td><td className="px-3 py-2">~4 ms</td><td className="px-3 py-2">~250.000</td></tr><tr className="border-b border-border"><td className="px-3 py-2">10.000</td><td className="px-3 py-2">~40 ms</td><td className="px-3 py-2">~250.000</td></tr><tr className="border-b border-border"><td className="px-3 py-2">100.000</td><td className="px-3 py-2">~420 ms</td><td className="px-3 py-2">~238.000</td></tr><tr className="border-b border-border"><td className="px-3 py-2">1.000.000</td><td className="px-3 py-2">~4,3 s</td><td className="px-3 py-2">~232.000</td></tr></tbody></table></div>
          <p className="mb-4">Para a maioria dos casos de teste, a implementação pura é mais que suficiente. O overhead de I/O do banco de dados domina antes da geração de CPFs virar gargalo.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Integração com pytest via fixtures</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@pytest.fixture</code> que retorna um CPF válido por teste</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"import pytest\n\n@pytest.fixture\ndef cpf_valido() -> str:\n    return gerar_cpf(formatado=False)\n\n# Uso:\ndef test_cadastro_cliente(cpf_valido):\n    cliente = Cliente(cpf=cpf_valido)\n    assert cliente.cpf_valido()"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@pytest.fixture</code> com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">params</code> para testes parametrizados</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"@pytest.fixture(params=[gerar_cpf(formatado=False) for _ in range(5)])\ndef cpf_parametrizado(request) -> str:\n    return request.param\n\n# pytest executa o teste 5 vezes, cada um com um CPF diferente\ndef test_formatos_aceitos(cpf_parametrizado):\n    assert validar_cpf(cpf_parametrizado)"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Fixture de lote para testes de carga ou importação em massa</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"@pytest.fixture\ndef cpfs_lote() -> list[str]:\n    return gerar_lote(100, formatado=False)\n\ndef test_importacao_em_massa(cpfs_lote, db_session):\n    clientes = [Cliente(cpf=cpf) for cpf in cpfs_lote]\n    db_session.bulk_save_objects(clientes)\n    db_session.commit()\n    assert db_session.query(Cliente).count() == 100"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Integração com a biblioteca Faker</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Provider customizado <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CPFProvider</code> para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">faker.add_provider()</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"from faker import Faker\nfrom faker.providers import BaseProvider\n\nclass CPFProvider(BaseProvider):\n    def cpf(self, formatado: bool = True) -> str:\n        return gerar_cpf(formatado=formatado)\n\nfake = Faker(\"pt_BR\")\nfake.add_provider(CPFProvider)\n\nprint(fake.cpf())                  # \"382.947.102-55\"\nprint(fake.cpf(formatado=False))   # \"38294710255\""}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Usando <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">factory_boy</code> com o provider para factories de modelo Django/SQLAlchemy</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"import factory\nfrom factory.django import DjangoModelFactory\n\nclass ClienteFactory(DjangoModelFactory):\n    class Meta:\n        model = Cliente\n\n    nome = factory.Faker(\"name\", locale=\"pt_BR\")\n    cpf = factory.LazyFunction(lambda: gerar_cpf(formatado=False))\n    email = factory.Faker(\"email\")\n\n# Em teste:\ndef test_perfil_cliente():\n    cliente = ClienteFactory()\n    assert validar_cpf(cliente.cpf)"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Compatibilidade com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">faker-brasil</code> (quando usar e quando não vale a dependência)</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">faker-brasil</code> é uma alternativa existente, mas adiciona uma dependência para uma funcionalidade que você implementa em 20 linhas. Use-o se o projeto já tiver instalado ou se precisar de outros dados brasileiros que ele oferece. Se o único requisito é CPF, a implementação própria elimina a dependência sem custo.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Alternativa sem código: API REST do FakeForge</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">GET /api/generate?type=cpf&amp;quantity=100&amp;format=json</code> — exemplo curl + Python <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">requests</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=cpf&quantity=100&format=csv\" \\\n  -H \"Authorization: Bearer SEU_TOKEN\" \\\n  -o cpfs.csv"}</code></pre>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"import requests\nimport sqlite3\n\nresponse = requests.get(\n    \"https://fakeforge.com.br/api/generate\",\n    params={\"type\": \"cpf\", \"quantity\": 50, \"format\": \"json\"},\n    headers={\"Authorization\": \"Bearer SEU_TOKEN\"},\n)\ncpfs = response.json()\n\n# Seed direto em banco SQLite\nconn = sqlite3.connect(\"test.db\")\nconn.execute(\"CREATE TABLE IF NOT EXISTS clientes (cpf TEXT PRIMARY KEY)\")\nconn.executemany(\"INSERT OR IGNORE INTO clientes VALUES (?)\", [(c,) for c in cpfs])\nconn.commit()"}</code></pre>
          <p className="mb-4">O plano gratuito permite 100 chamadas por dia. Para volumes maiores, consulte os <Link href="/pricing" className="text-primary hover:underline">planos da API</Link>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Exportar CSV ou SQL direto para seed de banco de dados</h3>
          <p className="mb-4">Com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code>, a resposta inclui <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">INSERT</code> prontos para execução — útil em pipelines de CI/CD que precisam de dados antes de rodar migrations ou testes de integração.</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=cpf&quantity=500&format=sql\" \\\n  -H \"Authorization: Bearer SEU_TOKEN\" \\\n  | psql -U dev -d testdb"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quando a API faz mais sentido que código próprio</h3>
          <p className="mb-4">Use a API quando:</p>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>O pipeline de CI/CD gera dados antes de rodar testes, sem Python disponível no runner</li><li>O time usa outra linguagem — a API é agnóstica</li><li>Precisa de dados correlacionados: CPF + nome + endereço + banco em uma única chamada com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">type=pessoa</code></li><li>Quer exportar SQL para seed de banco sem escrever ORM</li></ul>
          <p className="mb-4">A <Link href="/docs" className="text-primary hover:underline">documentação da API</Link> cobre todos os tipos disponíveis, incluindo o <Link href="/gerador-cpf" className="text-primary hover:underline">gerador de CPF online</Link> para geração interativa no browser.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Armadilhas comuns ao gerar CPFs em testes</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Não reutilizar o mesmo CPF entre testes com banco compartilhado (constraints UNIQUE)</h3>
          <p className="mb-4">Se dois testes compartilham o mesmo banco e ambos inserem um cliente, um CPF fixo vai causar violação de constraint <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">UNIQUE</code> no segundo teste. Use fixtures com escopo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">function</code> e sempre gere um CPF novo por execução — nunca compartilhe o mesmo valor entre casos de teste distintos.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Seed aleatório fixo para reprodutibilidade (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">random.seed(42)</code>)</h3>
          <p className="mb-4">Para testes que precisam ser determinísticos — snapshots, golden files, reprodução de bugs:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-python">{"import random\n\n# Isolado por instância — não afeta o estado global\nrng = random.Random(42)\n\ndef gerar_cpf_determinístico() -> str:\n    base = [rng.randint(0, 9) for _ in range(9)]\n    # resto da lógica igual..."}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">AVISO:</strong> <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">random.seed(42)</code> afeta o estado global do módulo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">random</code>. Em testes paralelos com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pytest-xdist</code> ou código assíncrono, isso causa comportamento não determinístico. Prefira instanciar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">random.Random(42)</code> localmente e injetar na função geradora.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Não commitar CPFs hardcoded no repositório mesmo sendo falsos</h3>
          <p className="mb-4">CPFs falsos hardcodados em fixtures não são dados pessoais reais, mas acionam ferramentas de scanning de segredos como Detect-Secrets e GitGuardian, que identificam padrões numéricos de documentos brasileiros. Gere dinamicamente nas fixtures em vez de fixar valores no código — o custo de geração é negligenciável.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>O algoritmo mod-11 da Receita Federal tem quatro passos: gerar 9 dígitos base, calcular o primeiro verificador, calcular o segundo verificador, tratar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto &lt; 2</code> como zero.</li><li>A função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validar_cpf()</code> deve remover máscara, verificar comprimento, rejeitar dígitos todos iguais e só então calcular os verificadores — nessa ordem.</li><li>Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">set</code> para garantir unicidade em lotes; não confie em probabilidade mesmo com espaço amostral grande.</li><li>Fixtures pytest com escopo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">function</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">gerar_cpf()</code> dinâmico eliminam colisões em testes com banco compartilhado.</li><li><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">random.Random(42)</code> isolado por instância é a forma correta de seed determinístico em ambientes paralelos.</li><li>O próximo passo natural é o <Link href="/gerador-cnpj" className="text-primary hover:underline">CNPJ</Link> — o algoritmo é análogo. Em 01/07/2026 entra em vigor o <Link href="/gerador-cnpj-alfanumerico" className="text-primary hover:underline">CNPJ Alfanumérico</Link>, que mantém a estrutura mod-11 mas admite letras nos oito primeiros dígitos. Leia o <Link href="/blog/cnpj-alfanumerico-checklist-migracao-2026" className="text-primary hover:underline">checklist de migração para CNPJ alfanumérico</Link> antes de atualizar seus validadores.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Como fazer fixture pytest que " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como fazer fixture pytest que gera CPF novo a cada teste?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Use scope='function' (padrão) + `factory.LazyFunction(gerar_cpf)` ou `@pytest.mark.parametrize` com `[gerar_cpf() for _ in range(n)]`. Cada teste recebe novo CPF. scope='module' ou 'session' compartilha valor e causa UNIQUE constraint violations em testes com BD.</p>
            </details>
            <details key="Como mascarar CPF em logs de d" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como mascarar CPF em logs de debug?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Exiba só últimos 2 dígitos: `'***.***.***-' + cpf[-2:]`. Alternativa: hash SHA256 truncado: `hashlib.sha256(cpf.encode()).hexdigest()[:8]`. Para auditoria, cifre arquivo de log. Nunca output CPF completo em stdout, logs de build ou arquivos de cobertura.</p>
            </details>
            <details key="faker-brasil ou implementação " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">faker-brasil ou implementação própria — quando vale a dependência?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Só CPF? Implemente local (20 linhas, zero deps). faker-brasil (+50KB) compensa se gerar 3+ tipos brasileiros (CNPJ, CEP, placa, banco). Overhead é ~4µs/call — irrelevante para testes. Decisão é pragmática: 1 dependência vs 60 linhas de código.</p>
            </details>
            <details key="Como validar CPF em JavaScript" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como validar CPF em JavaScript/TypeScript no frontend?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Porte a função (25 linhas). Regex `^\d&#123;11&#125;$` + módulo 11 verdadeiro. Nunca confie só no cliente — sempre revalide no servidor. Exemplo: `const validar = (c) =&gt; /^\d&#123;11&#125;$/.test(c) &amp;&amp; verificadoresOk(c)`. Proteja dados no BFF.</p>
            </details>
            <details key="Como seedear geração de CPF co" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como seedear geração de CPF com testes paralelos (pytest-xdist)?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não use `random.seed()` global — desincroniza workers. Injete `random.Random(worker_id + timestamp)` na fixture. Ou confie em colisão negligenciável: lote de 1000 CPFs tem &lt;0.1% chance duplicata mesmo sem seed. Para CI, probabilidade é aceitável.</p>
            </details>
          </div>
        </section>
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Como fazer fixture pytest que gera CPF novo a cada teste?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Use scope='function' (padrão) + `factory.LazyFunction(gerar_cpf)` ou `@pytest.mark.parametrize` com `[gerar_cpf() for _ in range(n)]`. Cada teste recebe novo CPF. scope='module' ou 'session' compartilha valor e causa UNIQUE constraint violations em testes com BD.\"}},{\"@type\":\"Question\",\"name\":\"Como mascarar CPF em logs de debug?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Exiba só últimos 2 dígitos: `'***.***.***-' + cpf[-2:]`. Alternativa: hash SHA256 truncado: `hashlib.sha256(cpf.encode()).hexdigest()[:8]`. Para auditoria, cifre arquivo de log. Nunca output CPF completo em stdout, logs de build ou arquivos de cobertura.\"}},{\"@type\":\"Question\",\"name\":\"faker-brasil ou implementação própria — quando vale a dependência?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Só CPF? Implemente local (20 linhas, zero deps). faker-brasil (+50KB) compensa se gerar 3+ tipos brasileiros (CNPJ, CEP, placa, banco). Overhead é ~4µs/call — irrelevante para testes. Decisão é pragmática: 1 dependência vs 60 linhas de código.\"}},{\"@type\":\"Question\",\"name\":\"Como validar CPF em JavaScript/TypeScript no frontend?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Porte a função (25 linhas). Regex `^\\\\d{11}$` + módulo 11 verdadeiro. Nunca confie só no cliente — sempre revalide no servidor. Exemplo: `const validar = (c) => /^\\\\d{11}$/.test(c) && verificadoresOk(c)`. Proteja dados no BFF.\"}},{\"@type\":\"Question\",\"name\":\"Como seedear geração de CPF com testes paralelos (pytest-xdist)?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não use `random.seed()` global — desincroniza workers. Injete `random.Random(worker_id + timestamp)` na fixture. Ou confie em colisão negligenciável: lote de 1000 CPFs tem <0.1% chance duplicata mesmo sem seed. Para CI, probabilidade é aceitável.\"}}]}",
        }}
      />
    </PageShell>
  );
}
