import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";
import ShareBar from "@/components/ShareBar";
import BlogPostingSchema from "@/components/BlogPostingSchema";

export const metadata: Metadata = {
  title: "Inscrição Estadual SP: Algoritmo e Gerador TypeScript",
  description: "Entenda o formato e o algoritmo de dígito verificador da IE-SP, implemente gerador e validador em TypeScript com exemplos rodáveis.",
  openGraph: {
    title: "Inscrição Estadual SP: Algoritmo e Gerador TypeScript",
    description: "Entenda o formato e o algoritmo de dígito verificador da IE-SP, implemente gerador e validador em TypeScript com exemplos rodáveis.",
    type: "article",
    images: ["/api/og?title=Inscri%C3%A7%C3%A3o%20Estadual%20SP%3A%20algoritmo%20passo%20a%20passo%20e%20gerador%20em%20TypeScript&subtitle=Entenda%20o%20formato%20e%20o%20algoritmo%20de%20d%C3%ADgito%20verificador%20da%20IE-SP%2C%20implemente%20gerador%20e%20validador%20em%20TypeScript%20com%20exemplos%20rod%C3%A1veis.&category=TUTORIAIS"],
  },
  alternates: { canonical: "/blog/gerador-inscricao-estadual-sp-algoritmo" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Inscrição Estadual SP: algoritmo passo a passo e gerador em TypeScript" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Inscrição Estadual SP: algoritmo passo a passo e gerador em TypeScript
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>29 de maio de 2026</time>
            <span>·</span>
            <span>12 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">A Inscrição Estadual de São Paulo tem dois dígitos verificadores com pesos assimétricos e um prefixo textual que não entra nos cálculos. Implementações incorretas costumam tratar o prefixo "P" como dígito ou copiar o algoritmo de outro estado. Este artigo documenta o formato oficial da SEFAZ-SP, implementa gerador e validador em TypeScript sem dependências externas, e mostra como integrar IEs válidas em pipelines de teste fiscal.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O que é a Inscrição Estadual e por que SP tem seu próprio algoritmo</h2>
          <p className="mb-4">A Inscrição Estadual (IE) identifica o contribuinte no cadastro estadual de ICMS. Cada Unidade Federativa define seus próprios pesos e regras de verificação. A SEFAZ-SP usa dois dígitos verificadores com pesos diferentes entre si, o que distingue o algoritmo paulista dos estados que usam dígito único ou pesos simétricos.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferença entre IE, CNPJ e CNAE</h3>
          <p className="mb-4">CNPJ identifica a pessoa jurídica perante a Receita Federal. IE identifica o estabelecimento no cadastro estadual de ICMS. CNAE classifica a atividade econômica. São documentos complementares: uma NF-e de saída exige tanto o CNPJ do emitente quanto a IE do estabelecimento. Para montar um emissor completo com campos correlacionados, use o <Link href="/gerador-empresa" className="text-primary hover:underline">gerador de empresa</Link>. Para gerar o CNPJ isolado, acesse o <Link href="/gerador-cnpj" className="text-primary hover:underline">/gerador-cnpj</Link>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quem é obrigado a ter IE-SP</h3>
          <p className="mb-4">Contribuintes de ICMS em São Paulo são obrigados a se inscrever no Cadastro de Contribuintes (Decreto-Lei Estadual 45.490/2000, art. 19). Isso inclui industriais, comerciantes, transportadores intermunicipais e produtores rurais. Prestadores de serviços tributados por ISS em geral estão dispensados.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que dados de IE válidos são necessários em testes fiscais</h3>
          <p className="mb-4">Softwares de emissão de NF-e validam o dígito verificador da IE antes de transmitir o XML à SEFAZ. Se o número falha na verificação local, o documento é rejeitado antes de chegar ao servidor de autorização. Ambientes de homologação aceitam IEs sinteticamente válidas, o que torna geradores como este necessários para testes de ponta a ponta.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Anatomia do número: estrutura dos 12 dígitos</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Formato oficial da SEFAZ-SP: P.XXX.XXX.XXX.XXX</h3>
          <p className="mb-4">A SEFAZ-SP formata a IE como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">P.XXX.XXX.XXX.XXX</code>. O número bruto, sem o prefixo e sem pontos, tem exatamente 12 dígitos numéricos distribuídos em quatro grupos de três.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O prefixo "P" e o que ele indica</h3>
          <p className="mb-4">O "P" é um prefixo literal que identifica o tipo de inscrição padrão (pessoa jurídica comercial ou industrial). Ele não é um dígito e não entra em nenhum cálculo de verificação. Aparece na representação textual do Sintegra e nos campos de IE da NF-e.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Posição dos dois dígitos verificadores (D10 e D12)</h3>
          <p className="mb-4">Nos 12 dígitos numéricos, a distribuição é:</p>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Posição</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Conteúdo</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">1 a 8</td><td className="px-3 py-2">Dígitos base, gerados aleatoriamente</td></tr><tr className="border-b border-border"><td className="px-3 py-2">9</td><td className="px-3 py-2">Dígito fixo (0 nesta implementação)</td></tr><tr className="border-b border-border"><td className="px-3 py-2">10</td><td className="px-3 py-2">Primeiro verificador (D10)</td></tr><tr className="border-b border-border"><td className="px-3 py-2">11</td><td className="px-3 py-2">Dígito fixo (0 nesta implementação)</td></tr><tr className="border-b border-border"><td className="px-3 py-2">12</td><td className="px-3 py-2">Segundo verificador (D12)</td></tr></tbody></table></div>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Casos especiais: substitutos tributários e produtores rurais</h3>
          <p className="mb-4">Substitutos tributários de outros estados inscritos em SP e produtores rurais usam prefixos ou formatos diferentes do "P" comercial. O algoritmo descrito aqui cobre o caso mais comum em testes de NF-e: contribuintes comerciais e industriais com inscrição padrão.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Algoritmo do primeiro dígito verificador (D10)</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Pesos aplicados às posições 1 a 8: [1, 3, 4, 5, 6, 7, 8, 10]</h3>
          <p className="mb-4">Cada um dos oito dígitos base recebe um peso fixo na mesma ordem: a posição 1 recebe peso 1, a posição 2 recebe peso 3, e assim até a posição 8, que recebe peso 10. O somatório dos produtos é dividido por 11.</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"function calcD10(digits: number[]): number {\n  const weights = [1, 3, 4, 5, 6, 7, 8, 10];\n  const sum = weights.reduce((acc, w, i) => acc + w * digits[i], 0);\n  const r = sum % 11;\n  return r < 2 ? 0 : r;\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cálculo do somatório e regra do mod 11</h3>
          <p className="mb-4">O resultado de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">sum % 11</code> é o dígito verificador, com uma exceção descrita a seguir.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regra de exceção: resto 0 e resto 1 resultam em dígito 0</h3>
          <p className="mb-4">Tanto o resto 0 quanto o resto 1 produzem D10 = 0. Uma implementação que só trate <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">r === 0</code> gera dígitos incorretos quando o somatório for congruente a 1 (mod 11).</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Exemplo manual com valores reais passo a passo</h3>
          <p className="mb-4">Base: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[1, 2, 3, 4, 5, 6, 7, 8]</code></p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-">{"1×1 + 2×3 + 3×4 + 4×5 + 5×6 + 6×7 + 7×8 + 8×10\n= 1 + 6 + 12 + 20 + 30 + 42 + 56 + 80\n= 247\n247 % 11 = 5  →  D10 = 5"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Algoritmo do segundo dígito verificador (D12)</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Pesos aplicados às posições 1, 3, 4, 5, 6, 7, 8, 10 (subconjunto diferente)</h3>
          <p className="mb-4">D12 não usa todas as posições 1 a 8. Usa as posições 1, 3, 4, 5, 6, 7, 8 mais a posição 10 (o D10 já calculado). As posições 2 e 9 são ignoradas. Os pesos correspondentes são <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[3, 2, 10, 9, 8, 7, 6, 5]</code>.</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"function calcD12(full: number[]): number {\n  const positions = [0, 2, 3, 4, 5, 6, 7, 9]; // 0-indexed (1-indexed: 1,3,4,5,6,7,8,10)\n  const weights   = [3, 2, 10, 9, 8, 7, 6, 5];\n  const sum = weights.reduce((acc, w, i) => acc + w * full[positions[i]], 0);\n  const r = sum % 11;\n  return r < 2 ? 0 : r;\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regra do mod 11 para D12 e sua independência de D10</h3>
          <p className="mb-4">D12 usa o valor de D10 como um dos termos do somatório, mas os dois cálculos são independentes: não há recursão e não existe risco de circularidade. A regra de exceção é idêntica: resto menor que 2 produz dígito 0.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Exemplo manual complementando o caso anterior</h3>
          <p className="mb-4">Com base <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[1, 2, 3, 4, 5, 6, 7, 8]</code> e D10 = 5, o array completo antes de D12 é:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-">{"full = [1, 2, 3, 4, 5, 6, 7, 8, 0, 5, 0, ?]\nposições usadas (0-idx): 0→1, 2→3, 3→4, 4→5, 5→6, 6→7, 7→8, 9→5\npesos:                       3    2   10    9    8    7    6    5\nprodutos:           3 + 6 + 40 + 45 + 48 + 49 + 48 + 25 = 264\n264 % 11 = 0  →  D12 = 0"}</code></pre>
          <p className="mb-4">IE completa: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">P.123.456.780.500</code></p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Implementação do gerador em TypeScript</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">generateIESP()</code>: geração dos 8 dígitos base aleatórios</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"function generateIESP(): string {\n  const base = Array.from({ length: 8 }, () => Math.floor(Math.random() * 10));\n\n  const full = [...base, 0, calcD10(base), 0, 0];\n  full[11] = calcD12(full);\n\n  const n = full.join('');\n  return `P.${n.slice(0, 3)}.${n.slice(3, 6)}.${n.slice(6, 9)}.${n.slice(9, 12)}`;\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Funções <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcD10()</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcD12()</code>: isolamento dos cálculos</h3>
          <p className="mb-4">As duas funções são puras e sem efeitos colaterais. Isolá-las do gerador permite reutilizá-las no validador sem duplicação de lógica.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Montagem final com formatação P.XXX.XXX.XXX.XXX</h3>
          <p className="mb-4">O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">join('')</code> transforma o array de 12 dígitos em string contígua. Os quatro <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">slice()</code> extraem cada grupo de três para compor o formato <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">P.d1d2d3.d4d5d6.d7d8d9.d10d11d12</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Exportar como módulo reutilizável (sem dependências externas)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"// ie-sp.ts\nexport { calcD10, calcD12, generateIESP, validateIESP };"}</code></pre>
          <p className="mb-4">Importável em Node.js, Deno ou Bun sem nenhum pacote adicional.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Implementação do validador em TypeScript</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validateIESP(ie: string): boolean</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"function validateIESP(ie: string): boolean {\n  const clean = ie.replace(/^P\\.?/i, '').replace(/[\\s.]/g, '');\n\n  if (clean.length !== 12 || !/^\\d{12}$/.test(clean)) return false;\n\n  const d = clean.split('').map(Number);\n  return d[9] === calcD10(d.slice(0, 8)) && d[11] === calcD12(d);\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Sanitização da entrada: remover P, pontos, espaços</h3>
          <p className="mb-4">A regex <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">^P\.?</code> remove o prefixo "P" com ou sem ponto. O segundo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">replace</code> remove espaços e pontos restantes. Após a sanitização, a string deve ter exatamente 12 caracteres numéricos.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Verificação de comprimento e caracteres numéricos</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/^\d&#123;12&#125;$/.test(clean)</code> garante que não há letras ou caracteres especiais após a sanitização. Entradas como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"P.111.111.111.111"</code> passam na sanitização mas falham na verificação do dígito.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Reaproveitamento de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcD10()</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcD12()</code> no validador</h3>
          <p className="mb-4">O validador chama as mesmas funções do gerador. Se os cálculos estiverem corretos no gerador, o validador não pode divergir.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">DICA:</strong> Em formulários de NF-e, aplique o validador no evento <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">onBlur</code>, não no <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">onChange</code>. Validação a cada tecla em campos de 12 dígitos gera experiência ruim sem ganho funcional.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Casos de borda que quebram implementações ingênuas</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">IE de produtor rural começa com dígito diferente de P</h3>
          <p className="mb-4">Produtores rurais em SP usam uma faixa de inscrição com prefixo numérico diferente do "P" comercial. Uma regex <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">^P</code> rejeita essas IEs válidas. Separe os dois casos de uso antes de implementar validação de prefixo.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Zeros à esquerda no campo base precisam ser preservados</h3>
          <p className="mb-4">IEs podem ter zeros nos primeiros dígitos base, como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">P.001.234.567.890</code>. Converter a string para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Number</code> antes de processar apaga esses zeros. Sempre use arrays de dígitos ou strings com padding explícito.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Strings como "111.111.111.111" passam na validação de formato mas falham no dígito</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">111.111.111.111</code> tem 12 dígitos e formato sintático válido. Para base <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[1,1,1,1,1,1,1,1]</code> com pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[1,3,4,5,6,7,8,10]</code>: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">1+3+4+5+6+7+8+10 = 44</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">44 % 11 = 0</code> → D10 = 0, não 1. O validador rejeita corretamente.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferença entre IE inválida e IE inexistente no Sintegra</h3>
          <p className="mb-4">Validação local confirma que o número é matematicamente possível. Não confirma que o contribuinte existe e está ativo. Para consulta de situação cadastral real, use a API do Sintegra ou a consulta pública da SEFAZ-SP.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Testes unitários para o gerador e validador</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Suite com casos conhecidos da SEFAZ-SP (valores de referência públicos)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"import { describe, it, expect } from 'vitest';\nimport { generateIESP, validateIESP } from './ie-sp';\n\ndescribe('IE-SP', () => {\n  it('aceita IE do exemplo da documentação', () => {\n    expect(validateIESP('P.123.456.780.500')).toBe(true);\n  });\n\n  it('rejeita IE com comprimento incorreto', () => {\n    expect(validateIESP('P.123.456.780.50')).toBe(false);\n  });\n\n  it('rejeita IE com dígito verificador errado', () => {\n    expect(validateIESP('P.111.111.111.111')).toBe(false);\n  });\n});"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Property-based testing: todo número gerado deve passar no validador</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"it('propriedade: todo generateIESP() retorna IE válida', () => {\n  for (let i = 0; i < 1000; i++) {\n    expect(validateIESP(generateIESP())).toBe(true);\n  }\n});"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Teste de roundtrip: gerar → formatar → validar → true</h3>
          <p className="mb-4">O loop de 1.000 iterações cobre o roundtrip mínimo. Para testes baseados em propriedades com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">fast-check</code>:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"import fc from 'fast-check';\n\nit('fast-check roundtrip', () => {\n  fc.assert(fc.property(fc.constant(null), () => validateIESP(generateIESP())));\n});"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Uso em pipelines de teste fiscal e NF-e</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Seed de banco com IEs válidas para testes de emissão de NF-e</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"-- Generated by FakeForge BR - free Brazilian test data\n-- https://fakeforge.com.br\nCREATE TABLE IF NOT EXISTS empresas_seed (\n  id           SERIAL PRIMARY KEY,\n  razao_social VARCHAR(100),\n  cnpj         CHAR(14),\n  ie_sp        VARCHAR(20)\n);\n\nINSERT INTO empresas_seed (razao_social, cnpj, ie_sp) VALUES\n  ('Distribuidora Teste Ltda', '12345678000195', 'P.123.456.780.500'),\n  ('Comercio Exemplo SA',      '98765432000101', 'P.234.567.891.602');"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Uso com gerador de CNPJ para montar emissor completo</h3>
          <p className="mb-4">Para compor emissor completo (CNPJ + IE + endereço correlacionado), use o <Link href="/gerador-empresa" className="text-primary hover:underline">gerador de empresa</Link>. Para validar o CNPJ antes de associar a IE, use o <Link href="/validar-cnpj" className="text-primary hover:underline">/validar-cnpj</Link>. A partir de 01/07/2026, o formato muda para <Link href="/gerador-cnpj-alfanumerico" className="text-primary hover:underline">CNPJ alfanumérico</Link> (IN RFB 2.229/2024).</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Exportar via API REST com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code> para scripts de seed</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=ie-sp&quantity=10&format=sql\""}</code></pre>
          <p className="mb-4">O endpoint retorna um bloco <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE</code> seguido dos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">INSERT</code> com os registros. Consulte a <Link href="/docs" className="text-primary hover:underline">documentação da API</Link> para parâmetros de autenticação e rate limits.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">LGPD Art. 7º, IX — base legal para uso de dados sintéticos em homologação</h3>
          <p className="mb-4">Dados gerados sinteticamente sem correspondência a pessoas reais não configuram dado pessoal pela <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 5º, I</a>. O uso em homologação pode ser fundamentado em <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 7º, IX</a> (legítimo interesse), mas a ausência de dado pessoal torna desnecessária qualquer base legal para o tratamento.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Comparação com outros estados: quando o algoritmo muda</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">RJ, MG e RS têm pesos diferentes — não reutilize a função SP</h3>
          <p className="mb-4">O Rio de Janeiro usa 8 dígitos base com pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[2, 7, 6, 5, 4, 3, 2, 1]</code> e um único dígito verificador. Minas Gerais tem 13 dígitos com cálculo em duas passagens. O Rio Grande do Sul usa mod 11 com pesos distintos. Reutilizar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcD10()</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcD12()</code> nesses estados produz validações incorretas de forma silenciosa.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Tabela rápida: estados com dígito único vs. dois dígitos verificadores</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">UF</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Dígitos totais</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Verificadores</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Observação</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">SP</td><td className="px-3 py-2">12</td><td className="px-3 py-2">2 (D10, D12)</td><td className="px-3 py-2">Prefixo P na formatação</td></tr><tr className="border-b border-border"><td className="px-3 py-2">RJ</td><td className="px-3 py-2">8</td><td className="px-3 py-2">1</td><td className="px-3 py-2">Mod 11, pesos distintos</td></tr><tr className="border-b border-border"><td className="px-3 py-2">MG</td><td className="px-3 py-2">13</td><td className="px-3 py-2">2</td><td className="px-3 py-2">Duas passagens de cálculo</td></tr><tr className="border-b border-border"><td className="px-3 py-2">RS</td><td className="px-3 py-2">10</td><td className="px-3 py-2">1</td><td className="px-3 py-2">Mod 11 padrão</td></tr><tr className="border-b border-border"><td className="px-3 py-2">PR</td><td className="px-3 py-2">10</td><td className="px-3 py-2">2</td><td className="px-3 py-2">Verificadores ao final</td></tr><tr className="border-b border-border"><td className="px-3 py-2">SC</td><td className="px-3 py-2">9</td><td className="px-3 py-2">1</td><td className="px-3 py-2">Mod 11 simples</td></tr></tbody></table></div>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">AVISO:</strong> Esta tabela é uma referência rápida. Confirme o formato exato no manual de integração da SEFAZ de cada estado antes de usar em produção.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que vale encapsular por estado (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">{`ieValidator(uf)`}</code>)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-typescript">{"const ieValidator: Record<string, (ie: string) => boolean> = {\n  SP: validateIESP,\n  // RJ: validateIERJ,\n  // MG: validateIEMG,\n};\n\nfunction validateIE(uf: string, ie: string): boolean {\n  return ieValidator[uf]?.(ie) ?? false;\n}"}</code></pre>
          <p className="mb-4">Encapsular por UF elimina <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">if/else</code> espalhados no código de emissão de NF-e e torna a adição de novos estados uma questão de inserir uma entrada no objeto.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li><strong className="text-foreground">Gerador:</strong> gera 8 dígitos aleatórios, aplica <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcD10()</code> com pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[1,3,4,5,6,7,8,10]</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcD12()</code> com subconjunto de posições <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[1,3,4,5,6,7,8,10]</code> e pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[3,2,10,9,8,7,6,5]</code>, formata como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">P.XXX.XXX.XXX.XXX</code>.</li><li><strong className="text-foreground">Validador:</strong> sanitiza prefixo P e pontos, verifica comprimento 12, reaplica as mesmas funções de cálculo e compara os resultados com as posições 10 e 12 do número.</li><li><strong className="text-foreground">Armadilhas:</strong> preservar zeros à esquerda, tratar restos 0 e 1 como dígito 0, não confundir validação matemática com consulta de situação cadastral no Sintegra.</li><li><strong className="text-foreground">Testes:</strong> rodar 1.000 iterações de roundtrip <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">generateIESP()</code> seguido de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validateIESP()</code> como smoke test mínimo antes de integrar em qualquer pipeline.</li><li><strong className="text-foreground">Integração fiscal:</strong> compor CNPJ via <Link href="/gerador-cnpj" className="text-primary hover:underline">/gerador-cnpj</Link> com IE e endereço via <Link href="/gerador-empresa" className="text-primary hover:underline">/gerador-empresa</Link>; exportar seed com <Link href="/docs" className="text-primary hover:underline">API REST e format=sql</Link>.</li><li><strong className="text-foreground">Multi-UF:</strong> encapsular validadores por estado em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Record&lt;string, validator&gt;</code> para escalar sem ramificação condicional no código de emissão de NF-e.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Como integrar validação IE-SP " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como integrar validação IE-SP em um form React sem bloquear a experiência?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Validação matemática é síncrona e &lt;1ms. Use onBlur, não onChange para evitar validação a cada tecla. Para consulta real ao Sintegra, faça async via API Route em background com debounce; isso não bloqueia o form. Padrão: validação local imediata + fetch ao Sintegra em paralelo com retry exponencial e timeout de 5s.</p>
            </details>
            <details key="Vale validar IE-SP no cliente " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Vale validar IE-SP no cliente ou é melhor fazer apenas na API?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Validação matemática é O(1) em ambos (&gt;10k/ms). Trade-off é segurança: cliente é rápido mas bypassável; API é seguro. Best practice: validação local no cliente para UX, re-validação na API antes de INSERT obrigatoriamente. Função é pura e &lt;100 bytes minificado, cabe em ambos sem penalidade.</p>
            </details>
            <details key="Como lidar com IEs de produtor" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como lidar com IEs de produtores rurais que começam com número?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Produtores rurais SP usam prefixo numérico em vez de 'P'. O algoritmo D10/D12 é idêntico, mas o sanitizador e validação de prefixo mudam. Crie `validateIESPProdutor()` separada ou parameterize com `&#123; type: 'produtor' &#125;`. Confirme prefixos numéricos válidos na documentação SEFAZ-SP antes de deployar.</p>
            </details>
            <details key="Devo validar IE-SP antes de en" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Devo validar IE-SP antes de enviar a NF-e para a SEFAZ?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sim, é exatamente o caso de uso. No middleware de validação de NF-e XML, aplique `validateIESP()` antes de enviar à SEFAZ. Pega erros de digitação localmente, economiza requisição de autorização e reduz rejeições de protocolo. Combine com `validateCNPJ()` do emissor para garantir coerência.</p>
            </details>
            <details key="Como testar se um IE-SP gerado" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como testar se um IE-SP gerado existe de verdade no Sintegra?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Números gerados têm check digits corretos mas não existem no Sintegra. Para testes end-to-end, use API pública do Sintegra ou consulta de situação cadastral com IEs conhecidas em ambiente de teste da SEFAZ-SP. Alternativamente, mock a resposta e teste integração com Vitest + nock.</p>
            </details>
          </div>
        </section>
        <ShareBar title={"Inscrição Estadual SP: Algoritmo e Gerador TypeScript"} path="/blog/gerador-inscricao-estadual-sp-algoritmo" />
        <BlogPostingSchema
          title={"Inscrição Estadual SP: Algoritmo e Gerador TypeScript"}
          slug="gerador-inscricao-estadual-sp-algoritmo"
          description={"Entenda o formato e o algoritmo de dígito verificador da IE-SP, implemente gerador e validador em TypeScript com exemplos rodáveis."}
          datePublished="2026-05-26"
          image="https://fakeforge.com.br/api/og?title=Inscri%C3%A7%C3%A3o%20Estadual%20SP%3A%20algoritmo%20passo%20a%20passo%20e%20gerador%20em%20TypeScript&subtitle=Entenda%20o%20formato%20e%20o%20algoritmo%20de%20d%C3%ADgito%20verificador%20da%20IE-SP%2C%20implemente%20gerador%20e%20validador%20em%20TypeScript%20com%20exemplos%20rod%C3%A1veis.&category=TUTORIAIS"
        />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Como integrar validação IE-SP em um form React sem bloquear a experiência?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Validação matemática é síncrona e <1ms. Use onBlur, não onChange para evitar validação a cada tecla. Para consulta real ao Sintegra, faça async via API Route em background com debounce; isso não bloqueia o form. Padrão: validação local imediata + fetch ao Sintegra em paralelo com retry exponencial e timeout de 5s.\"}},{\"@type\":\"Question\",\"name\":\"Vale validar IE-SP no cliente ou é melhor fazer apenas na API?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Validação matemática é O(1) em ambos (>10k/ms). Trade-off é segurança: cliente é rápido mas bypassável; API é seguro. Best practice: validação local no cliente para UX, re-validação na API antes de INSERT obrigatoriamente. Função é pura e <100 bytes minificado, cabe em ambos sem penalidade.\"}},{\"@type\":\"Question\",\"name\":\"Como lidar com IEs de produtores rurais que começam com número?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Produtores rurais SP usam prefixo numérico em vez de 'P'. O algoritmo D10/D12 é idêntico, mas o sanitizador e validação de prefixo mudam. Crie `validateIESPProdutor()` separada ou parameterize com `{ type: 'produtor' }`. Confirme prefixos numéricos válidos na documentação SEFAZ-SP antes de deployar.\"}},{\"@type\":\"Question\",\"name\":\"Devo validar IE-SP antes de enviar a NF-e para a SEFAZ?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sim, é exatamente o caso de uso. No middleware de validação de NF-e XML, aplique `validateIESP()` antes de enviar à SEFAZ. Pega erros de digitação localmente, economiza requisição de autorização e reduz rejeições de protocolo. Combine com `validateCNPJ()` do emissor para garantir coerência.\"}},{\"@type\":\"Question\",\"name\":\"Como testar se um IE-SP gerado existe de verdade no Sintegra?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Números gerados têm check digits corretos mas não existem no Sintegra. Para testes end-to-end, use API pública do Sintegra ou consulta de situação cadastral com IEs conhecidas em ambiente de teste da SEFAZ-SP. Alternativamente, mock a resposta e teste integração com Vitest + nock.\"}}]}",
        }}
      />
    </PageShell>
  );
}
