import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";
import ShareBar from "@/components/ShareBar";

export const metadata: Metadata = {
  title: "CNPJ válido para testes: algoritmo mod-11 e API REST",
  description: "Entenda o cálculo mod-11 do CNPJ, implemente o validador em TypeScript e consuma uma API REST pronta para gerar CNPJs válidos em pipelines de teste.",
  openGraph: {
    title: "CNPJ válido para testes: algoritmo mod-11 e API REST",
    description: "Entenda o cálculo mod-11 do CNPJ, implemente o validador em TypeScript e consuma uma API REST pronta para gerar CNPJs válidos em pipelines de teste.",
    type: "article",
    images: ["/api/og?title=CNPJ%20v%C3%A1lido%20para%20testes%3A%20algoritmo%20mod-11%20e%20API%20REST&subtitle=Entenda%20o%20c%C3%A1lculo%20mod-11%20do%20CNPJ%2C%20implemente%20o%20validador%20em%20TypeScript%20e%20consuma%20uma%20API%20REST%20pronta%20para%20gerar%20CNPJs%20v%C3%A1lidos%20em%20pipelines%20d&category=TUTORIAIS"],
  },
  alternates: { canonical: "/blog/gerar-cnpj-valido-testes-algoritmo-mod11-api" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="CNPJ válido para testes: algoritmo mod-11 e API REST" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            CNPJ válido para testes: algoritmo mod-11 e API REST
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>03 de junho de 2026</time>
            <span>·</span>
            <span>11 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">Todo <Link href="/gerador-cnpj" className="text-primary hover:underline">CNPJ válido para testes</Link> tem 14 dígitos que satisfazem um cálculo mod-11 definido pela Receita Federal. Implementar esse cálculo corretamente — e consumi-lo via API quando o volume exige escala — é o que separa fixtures de teste confiáveis de bugs de validação que aparecem em produção.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O que é um CNPJ válido para fins de teste</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura do CNPJ: 14 dígitos e o que cada bloco significa</h3>
          <p className="mb-4">O CNPJ segue o padrão <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">BB.BBB.BBB/FFFF-DD</code>:</p>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Bloco</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Posições</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Significado</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">BB.BBB.BBB</td><td className="px-3 py-2">1–8</td><td className="px-3 py-2">Raiz da empresa (identificador único)</td></tr><tr className="border-b border-border"><td className="px-3 py-2">FFFF</td><td className="px-3 py-2">9–12</td><td className="px-3 py-2">Filial (0001 para matriz)</td></tr><tr className="border-b border-border"><td className="px-3 py-2">DD</td><td className="px-3 py-2">13–14</td><td className="px-3 py-2">Dígitos verificadores</td></tr></tbody></table></div>
          <p className="mb-4">Os oito primeiros dígitos identificam o contribuinte. Os quatro seguintes identificam o estabelecimento. Os dois últimos são calculados a partir dos doze anteriores via mod-11.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que "válido" não significa "real" — a distinção que a LGPD exige</h3>
          <p className="mb-4">Um CNPJ é matematicamente válido quando seus dígitos verificadores conferem com o algoritmo. Ele não precisa estar cadastrado na Receita Federal para isso. Dados gerados por uma ferramenta como o <Link href="/gerador-cnpj" className="text-primary hover:underline">gerador de CNPJ</Link> do FakeForge BR passam em qualquer validador de formato, mas não existem no Cadastro Nacional de Pessoas Jurídicas.</p>
          <p className="mb-4">Essa distinção importa juridicamente. A LGPD Art. 5º, I define dado pessoal como "informação relacionada a pessoa natural identificada ou identificável". Um CNPJ fictício não se relaciona a nenhuma entidade real, portanto sai do escopo de proteção da lei para fins de armazenamento em ambiente de teste.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Casos em que um CNPJ inválido quebra o pipeline de testes</h3>
          <p className="mb-4">Usar sequências como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">12345678000100</code> em fixtures é o erro mais comum. A maioria dos sistemas de ERP, gateways de pagamento e APIs de crédito valida o dígito verificador antes de processar. Um CNPJ inválido retorna erro 400 logo na entrada, mascarando o comportamento real que o teste deveria exercitar.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O algoritmo mod-11 passo a passo</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Pesos da primeira rodada (5 4 3 2 9 8 7 6 5 4 3 2)</h3>
          <p className="mb-4">Multiplicam-se os 12 primeiros dígitos pelos pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[5,4,3,2,9,8,7,6,5,4,3,2]</code> e somam-se os produtos.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cálculo do primeiro dígito verificador</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto = soma % 11</code></p>
          <p className="mb-4">Se <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto &lt; 2</code>, o primeiro dígito verificador é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>. Caso contrário, é <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - resto</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Pesos da segunda rodada (6 5 4 3 2 9 8 7 6 5 4 3 2)</h3>
          <p className="mb-4">Acrescenta-se o primeiro dígito verificador à base e multiplica-se pelos pesos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[6,5,4,3,2,9,8,7,6,5,4,3,2]</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cálculo do segundo dígito verificador</h3>
          <p className="mb-4">A mesma fórmula: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto = soma % 11</code>, com a regra <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto &lt; 2 → 0</code>, caso contrário <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - resto</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regra do resto menor que 2 — o ponto mais esquecido em implementações</h3>
          <p className="mb-4">A Receita Federal exige que qualquer resto 0 ou 1 produza dígito <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0</code>. Implementações que usam diretamente <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11 - resto</code> sem esse condicional geram dígitos <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">10</code>, quebrando a validação. É o bug mais frequente em geradores escritos às pressas.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Implementação do gerador em TypeScript</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Gerar os 12 dígitos base aleatórios</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function gerarBase(): number[] {\n  return Array.from({ length: 12 }, () => Math.floor(Math.random() * 10));\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcularDigitoVerificador</code> reutilizável</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function calcularDigito(digitos: number[], pesos: number[]): number {\n  const soma = digitos.reduce((acc, d, i) => acc + d * pesos[i], 0);\n  const resto = soma % 11;\n  return resto < 2 ? 0 : 11 - resto;\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">gerarCNPJ</code> com opção de formatação</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"export function gerarCNPJ(formatado = false): string {\n  const base = gerarBase();\n\n  const pesos1 = [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2];\n  const d1 = calcularDigito(base, pesos1);\n\n  const pesos2 = [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2];\n  const d2 = calcularDigito([...base, d1], pesos2);\n\n  const cnpj = [...base, d1, d2].join('');\n\n  if (!formatado) return cnpj;\n\n  return `${cnpj.slice(0, 2)}.${cnpj.slice(2, 5)}.${cnpj.slice(5, 8)}/${cnpj.slice(8, 12)}-${cnpj.slice(12)}`;\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validarCNPJ</code> para usar nos testes de regressão</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"export function validarCNPJ(cnpj: string): boolean {\n  const limpo = cnpj.replace(/\\D/g, '');\n  if (limpo.length !== 14) return false;\n  if (/^(\\d)\\1{13}$/.test(limpo)) return false; // bloqueia 00000000000000 etc.\n\n  const digitos = limpo.split('').map(Number);\n\n  const pesos1 = [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2];\n  const d1Esperado = calcularDigito(digitos.slice(0, 12), pesos1);\n  if (digitos[12] !== d1Esperado) return false;\n\n  const pesos2 = [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2];\n  const d2Esperado = calcularDigito(digitos.slice(0, 13), pesos2);\n  return digitos[13] === d2Esperado;\n}"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">CNPJ Alfanumérico vigente a partir de 01/07/2026</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que muda na estrutura com a Instrução Normativa RFB 2.229/2024</h3>
          <p className="mb-4">A IN RFB 2.229/2024 permite que os oito dígitos da raiz contenham letras maiúsculas (A–Z) além de números. O formato passa a ser <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">AA.AAA.AAA/FFFF-DD</code>, onde <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">A</code> pode ser letra ou dígito. A Receita Federal começará a emitir CNPJs nesse formato em 01/07/2026. O <Link href="/gerador-cnpj-alfanumerico" className="text-primary hover:underline">gerador de CNPJ Alfanumérico</Link> do FakeForge BR já implementa o novo padrão.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como o mod-11 se adapta ao novo formato com letras</h3>
          <p className="mb-4">Cada caractere da raiz recebe um valor numérico para o cálculo: dígitos mantêm seu valor, letras são convertidas pelo índice (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">A=10</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">B=11</code>, ..., <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Z=35</code>). Os pesos e a regra do resto permanecem idênticos. O resultado dos dígitos verificadores continua sendo numérico.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Impacto nos sistemas legados e nos testes que já usam regex <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">\d&#123;14&#125;</code></h3>
          <p className="mb-4">Qualquer regex do tipo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">^\d&#123;14&#125;$</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">^\d&#123;2&#125;\.\d&#123;3&#125;\.\d&#123;3&#125;\/\d&#123;4&#125;-\d&#123;2&#125;$</code> vai rejeitar CNPJs alfanuméricos. A correção é substituir <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">\d</code> por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[A-Z0-9]</code> na raiz. Sistemas de ERP, ERPs fiscais e bibliotecas de validação precisarão de patch antes de julho de 2026.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">AVISO:</strong> Se o seu pipeline de CI usa fixtures CNPJ em formato numérico e seu produto processa notas fiscais após 01/07/2026, adicione ao menos um caso de teste com CNPJ alfanumérico antes dessa data.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Geração em lote via API REST</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Endpoint GET <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/api/generate?type=cnpj&amp;quantity=50&amp;format=json</code></h3>
          <p className="mb-4">A <Link href="/docs" className="text-primary hover:underline">documentação da API REST</Link> descreve todos os parâmetros. Para gerar 50 CNPJs em JSON:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"# JSON\ncurl \"https://fakeforge.com.br/api/generate?type=cnpj&quantity=50&format=json\"\n\n# CSV com watermark de atribuição\ncurl \"https://fakeforge.com.br/api/generate?type=cnpj&quantity=50&format=csv\"\n\n# SQL com CREATE TABLE pronto\ncurl \"https://fakeforge.com.br/api/generate?type=cnpj&quantity=50&format=sql\""}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Export em CSV com cabeçalho e em SQL com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE</code> pronto</h3>
          <p className="mb-4">O output SQL da API inclui a declaração da tabela e os <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">INSERT</code>s prontos para executar:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"-- Generated by FakeForge BR - free Brazilian test data\n-- https://fakeforge.com.br\n-- Generated at: 2026-06-03T14:00:00Z\n-- License: CC0 (public domain test data)\n\nCREATE TABLE IF NOT EXISTS cnpj_data (\n  id SERIAL PRIMARY KEY,\n  cnpj VARCHAR(18) NOT NULL\n);\n\nINSERT INTO cnpj_data (cnpj) VALUES\n  ('12.345.678/0001-95'),\n  ('98.765.432/0001-10');"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Autenticação e rate limit: 100 chamadas/dia no plano gratuito</h3>
          <p className="mb-4">O <Link href="/pricing" className="text-primary hover:underline">plano gratuito com 100 chamadas/dia</Link> não exige cadastro. Para volumes maiores, inclua o header <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Authorization: Bearer SEU_API_KEY</code>. A chave é gerada no painel após criar conta.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Exemplo com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">fetch</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">axios</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">curl</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// fetch (Node 18+)\nconst response = await fetch(\n  'https://fakeforge.com.br/api/generate?type=cnpj&quantity=10&format=json'\n);\nconst { data } = await response.json();\n// data: string[]\n\n// axios\nimport axios from 'axios';\nconst { data: { data: cnpjs } } = await axios.get(\n  'https://fakeforge.com.br/api/generate',\n  { params: { type: 'cnpj', quantity: 10, format: 'json' } }\n);"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Integrar CNPJs gerados no pipeline de CI</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Fixture em Jest: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">beforeAll</code> chamando a API e populando o banco de teste</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// cnpj.fixture.ts\nlet cnpjs: string[] = [];\n\nbeforeAll(async () => {\n  const res = await fetch(\n    'https://fakeforge.com.br/api/generate?type=cnpj&quantity=20&format=json'\n  );\n  const body = await res.json();\n  cnpjs = body.data;\n  await db.cnpj.createMany({ data: cnpjs.map(cnpj => ({ cnpj })) });\n});\n\nafterAll(async () => {\n  await db.cnpj.deleteMany();\n});"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Seed com o export SQL direto no <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">docker-compose</code> de teste</h3>
          <p className="mb-4">Salve o output SQL em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">./seed/cnpj.sql</code> e monte o arquivo no container do banco:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-yaml">{"services:\n  db:\n    image: postgres:16\n    volumes:\n      - ./seed/cnpj.sql:/docker-entrypoint-initdb.d/cnpj.sql"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Variáveis de ambiente e segredos — onde não guardar o API key</h3>
          <p className="mb-4">Nunca coloque o API key no <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">docker-compose.yml</code> comitado. Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">docker-compose.override.yml</code> (no <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">.gitignore</code>) ou um secret manager. Em GitHub Actions, use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">$&#123;&#123; secrets.FAKEFORGE_API_KEY &#125;&#125;</code> injetado via <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">env:</code>.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Validar CNPJs no código antes de persistir</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Middleware de validação em Next.js (App Router, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">route.ts</code>)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// app/api/empresa/route.ts\nimport { NextRequest, NextResponse } from 'next/server';\nimport { validarCNPJ } from '@/lib/validators/cnpj';\n\nexport async function POST(req: NextRequest) {\n  const body = await req.json();\n  if (!validarCNPJ(body.cnpj)) {\n    return NextResponse.json({ error: 'CNPJ inválido' }, { status: 422 });\n  }\n  // ...\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Schema Zod com refinamento mod-11</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import { z } from 'zod';\nimport { validarCNPJ } from '@/lib/validators/cnpj';\n\nexport const EmpresaSchema = z.object({\n  cnpj: z\n    .string()\n    .regex(/^[\\dA-Z]{14}$|^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}-\\d{2}$/, 'Formato inválido')\n    .refine(validarCNPJ, { message: 'Dígitos verificadores inválidos' }),\n  razaoSocial: z.string().min(3),\n});"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferença entre validar formato e validar existência na Receita Federal</h3>
          <p className="mb-4">A função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validarCNPJ</code> confirma que os dígitos batem com o algoritmo. Ela não consulta se o CNPJ está ativo na Receita Federal. Para isso existe a API pública do CNPJ (sem SLA e com rate limit baixo). Na maioria dos sistemas de teste, validação de formato é suficiente. Para sistemas fiscais em produção, a consulta à Receita é obrigatória.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Conformidade com a LGPD ao usar CNPJs fictícios</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Dado fictício não é dado pessoal — LGPD Art. 5º, I</h3>
          <p className="mb-4">A <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 5º, I</a> define dado pessoal como informação relacionada a pessoa natural identificada ou identificável. Um CNPJ gerado por algoritmo que não existe na Receita Federal não se relaciona a nenhuma entidade. Não há titular. Não há obrigação de base legal para tratamento.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quando o CNPJ aparece junto de nome real e vira dado pessoal — Art. 7º, IX</h3>
          <p className="mb-4">Se o fixture combina um CNPJ fictício com o nome real de um sócio (extraído de uma base de produção, por exemplo), o conjunto pode identificar uma pessoa natural via cruzamento com o Quadro de Sócios e Administradores. Nesse caso, o tratamento precisa de base legal conforme o <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 7º, IX</a>. Use o <Link href="/gerador-cpf" className="text-primary hover:underline">gerador de CPF</Link> e dados de pessoa fictícios para evitar o problema pela raiz.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Boas práticas de descarte de fixtures após o ciclo de teste</h3>
          <p className="mb-4">Pipelines que gravam fixtures em banco devem incluir teardown explícito (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">afterAll</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">docker-compose down -v</code>). Fixtures em arquivo devem ter TTL no storage (S3 lifecycle policy, por exemplo). Dados fictícios sem vínculo a pessoa real têm risco baixo, mas manter fixtures acumuladas por meses é dívida técnica sem benefício.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Erros comuns e como diagnosticar</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Dígito verificador errado por off-by-one no array de pesos</h3>
          <p className="mb-4">O erro mais frequente é usar o array de pesos com um índice a mais ou a menos. Valide a implementação contra o CNPJ <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11.222.333/0001-81</code>, que é um dos exemplos didáticos da Receita Federal com dígitos verificadores conhecidos (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">8</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">1</code>).</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">CNPJs com sequência repetida passando em validadores fracos</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">00000000000000</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11111111111111</code> e similares satisfazem o algoritmo mod-11 (o resto é sempre consistente com o dígito). Todo validador de produção deve rejeitar explicitamente CNPJs com todos os dígitos iguais. A função <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validarCNPJ</code> acima inclui essa verificação.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regex que rejeita o novo formato alfanumérico</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// Antes (rejeita CNPJ alfanumérico após 01/07/2026)\nconst regex = /^\\d{14}$/;\n\n// Depois (aceita ambos os formatos)\nconst regex = /^[A-Z0-9]{14}$|^[A-Z0-9]{2}\\.[A-Z0-9]{3}\\.[A-Z0-9]{3}\\/\\d{4}-\\d{2}$/;"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li>Implemente <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">calcularDigito</code> com a regra <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">resto &lt; 2 → 0</code> antes de qualquer outra coisa; esse condicional é o ponto de falha mais comum.</li><li>Use o <Link href="/validar-cnpj" className="text-primary hover:underline">validador de CNPJ</Link> do FakeForge para checar sua implementação contra casos de borda (sequências repetidas, CNPJ alfanumérico).</li><li>Para gerar volume em CI, prefira a API REST com export SQL e monte o arquivo no <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">docker-entrypoint-initdb.d</code> do container de banco.</li><li>Atualize todas as regex <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">\d&#123;14&#125;</code> para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[A-Z0-9]&#123;14&#125;</code> antes de 01/07/2026.</li><li>Nunca combine CNPJ fictício com nome real de pessoa; use <Link href="/gerador-empresa" className="text-primary hover:underline">dados de empresa completos</Link> gerados juntos para manter consistência e conformidade.</li><li>Descarte fixtures com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">afterAll</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">docker-compose down -v</code>; acúmulo silencioso é dívida técnica.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Qual é a latência para gerar 1" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Qual é a latência para gerar 10.000 CNPJs via API? Vale a pena cachear localmente em desenvolvimento?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">A API gera ~5.000 CNPJs/segundo em v16 Node. Uma chamada com `quantity=10000` retorna em ~200ms. Cachear localmente (arquivo JSON) só vale se roda testes &gt;50x/dia. Para CI unitário, preferir chamada direta. Para staging que roda 100+ vezes, cache em Redis com TTL de 1h reduz latência.</p>
            </details>
            <details key="Como testo CNPJ alfanumérico h" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como testo CNPJ alfanumérico hoje se a Receita só emite em 01/07/2026?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">O gerador de CNPJ alfanumérico do FakeForge já produz formatos como `A1.B2C.3D4/5678-EF`. Seu teste pode gerar amostra agora com `?format=json&amp;sample_alfanumerico=true` (simulação). Atualize regex antes de julho; use `[A-Z0-9]` na raiz.</p>
            </details>
            <details key="Posso fazer teste reproduzível" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Posso fazer teste reproduzível se a API gera valores aleatórios? Preciso hardcodar CNPJs?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sim, hardcode para testes críticos (integração, pagamento). Gere fixture estática em setup (`beforeAll`) e reutilize nos testes. Para testes de formato, use seed determinístico (seed=1234 → mesma sequência). Aleatoriedade vale em smoke tests; determinismo em regressão.</p>
            </details>
            <details key="Como mostrar erro amigável em " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como mostrar erro amigável em PT-BR quando validação Zod rejeita CNPJ do formulário?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Catch do `ZodError` e mapeie `.errors[0].code` para mensagem: `'invalid_string'` → 'Formato inválido', `'custom'` → 'Dígitos verificadores não conferem'. Use i18n (`next-intl`) para cada error.message. No handler, retorne `&#123; error: &#123; field: 'cnpj', message: msg &#125; &#125;` e renderize no input.</p>
            </details>
            <details key="Se meu CI roda 50 testes paral" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Se meu CI roda 50 testes paralelos cada um chamando a API, vou estourar limite de 100/dia?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sim. Estratégias: (1) Gere fixture bulk antes dos testes, salve em arquivo, use no beforeAll global. (2) Mock a API para testes unitários, API real só em E2E. (3) Ative plano pago (500/dia) em CI=true com variável de env. (4) Batch chamadas em worker separado.</p>
            </details>
          </div>
        </section>
        <ShareBar title={"CNPJ válido para testes: algoritmo mod-11 e API REST"} path="/blog/gerar-cnpj-valido-testes-algoritmo-mod11-api" />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Qual é a latência para gerar 10.000 CNPJs via API? Vale a pena cachear localmente em desenvolvimento?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"A API gera ~5.000 CNPJs/segundo em v16 Node. Uma chamada com `quantity=10000` retorna em ~200ms. Cachear localmente (arquivo JSON) só vale se roda testes >50x/dia. Para CI unitário, preferir chamada direta. Para staging que roda 100+ vezes, cache em Redis com TTL de 1h reduz latência.\"}},{\"@type\":\"Question\",\"name\":\"Como testo CNPJ alfanumérico hoje se a Receita só emite em 01/07/2026?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"O gerador de CNPJ alfanumérico do FakeForge já produz formatos como `A1.B2C.3D4/5678-EF`. Seu teste pode gerar amostra agora com `?format=json&sample_alfanumerico=true` (simulação). Atualize regex antes de julho; use `[A-Z0-9]` na raiz.\"}},{\"@type\":\"Question\",\"name\":\"Posso fazer teste reproduzível se a API gera valores aleatórios? Preciso hardcodar CNPJs?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sim, hardcode para testes críticos (integração, pagamento). Gere fixture estática em setup (`beforeAll`) e reutilize nos testes. Para testes de formato, use seed determinístico (seed=1234 → mesma sequência). Aleatoriedade vale em smoke tests; determinismo em regressão.\"}},{\"@type\":\"Question\",\"name\":\"Como mostrar erro amigável em PT-BR quando validação Zod rejeita CNPJ do formulário?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Catch do `ZodError` e mapeie `.errors[0].code` para mensagem: `'invalid_string'` → 'Formato inválido', `'custom'` → 'Dígitos verificadores não conferem'. Use i18n (`next-intl`) para cada error.message. No handler, retorne `{ error: { field: 'cnpj', message: msg } }` e renderize no input.\"}},{\"@type\":\"Question\",\"name\":\"Se meu CI roda 50 testes paralelos cada um chamando a API, vou estourar limite de 100/dia?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sim. Estratégias: (1) Gere fixture bulk antes dos testes, salve em arquivo, use no beforeAll global. (2) Mock a API para testes unitários, API real só em E2E. (3) Ative plano pago (500/dia) em CI=true com variável de env. (4) Batch chamadas em worker separado.\"}}]}",
        }}
      />
    </PageShell>
  );
}
