import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";

export const metadata: Metadata = {
  title: "CNPJ Alfanumérico: checklist para migrar antes de 01/07/2026",
  description: "CNPJ alfanumérico entra em vigor em 01/07/2026. Veja o checklist técnico completo: validação, máscaras, banco de dados e APIs que precisam mudar agora.",
  openGraph: {
    title: "CNPJ Alfanumérico: checklist para migrar antes de 01/07/2026",
    description: "CNPJ alfanumérico entra em vigor em 01/07/2026. Veja o checklist técnico completo: validação, máscaras, banco de dados e APIs que precisam mudar agora.",
    type: "article",
  },
  alternates: { canonical: "/blog/cnpj-alfanumerico-checklist-migracao-2026" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="News" title="CNPJ Alfanumérico: checklist para migrar antes de 01/07/2026" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            CNPJ Alfanumérico: checklist para migrar antes de 01/07/2026
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>05 de maio de 2026</time>
            <span>·</span>
            <span>9 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">A partir de 01/07/2026, todo CNPJ emitido pela Receita Federal pode conter letras. Não é uma mudança opcional — é uma alteração estrutural no formato do cadastro que afeta validação, banco de dados, APIs e formulários. Este checklist cobre o que precisa mudar e em que ordem.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O que muda no CNPJ a partir de 01/07/2026</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Formato atual vs. formato novo</h3>
          <p className="mb-4">O CNPJ atual tem 14 posições numéricas: 8 dígitos de raiz, 4 de ordem e 2 verificadores, exibidos como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">00.000.000/0000-00</code>. O novo formato mantém as 14 posições e a máscara visual, mas os 12 primeiros caracteres (antes dos verificadores) passam a aceitar letras maiúsculas de A a Z além de 0 a 9.</p>
          <p className="mb-4">Os dígitos verificadores (posições 13 e 14) continuam sendo numéricos. Um CNPJ como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">AB.CDE.FGH/0001-AB</code> é inválido por esse motivo.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Base legal — IN RFB nº 2.229/2024 e cronograma da Receita Federal</h3>
          <p className="mb-4">A Instrução Normativa RFB nº 2.229, de 3 de setembro de 2024, estabelece o novo formato e o cronograma de implementação. A Receita Federal definiu 01/07/2026 como data de início da emissão de CNPJs alfanuméricos.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">AVISO: A IN RFB 2.229/2024 não define prazo para migração forçada dos CNPJs existentes. A base numérica permanece válida indefinidamente. O impacto imediato é nos sistemas que precisam aceitar os novos CNPJs emitidos a partir de julho.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quem é afetado primeiro</h3>
          <p className="mb-4">CNPJs emitidos após 01/07/2026 já nascem alfanuméricos. CNPJs existentes permanecem numéricos. Qualquer sistema que receba, armazene ou valide CNPJ precisará suportar ambos os formatos simultaneamente a partir dessa data.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Validação de CNPJ precisa mudar</h2>
          <p className="mb-4">O algoritmo atual usa módulo 11 sobre os 12 primeiros dígitos numéricos para calcular os dois verificadores. Com letras, esse algoritmo quebra imediatamente — <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">'A'</code> não é um dígito válido para a fórmula atual.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Novo algoritmo oficial: conversão posicional A=17…Z=44</h3>
          <p className="mb-4">A Receita Federal define a seguinte conversão: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0–9</code> mantêm seus valores; <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">A=17, B=18, C=19, ..., Z=44</code>. O cálculo dos verificadores usa módulo 11 sobre os valores convertidos, com os mesmos pesos da fórmula atual.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Código TypeScript: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">validateCNPJ()</code> compatível com ambos os formatos</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"function charValue(c: string): number {\n  const code = c.charCodeAt(0);\n  if (code >= 48 && code <= 57) return code - 48;       // '0'–'9'\n  if (code >= 65 && code <= 90) return code - 65 + 17;  // 'A'=17 … 'Z'=44\n  throw new Error(`Caractere inválido: ${c}`);\n}\n\nfunction calcDigit(cnpj: string, weights: number[]): number {\n  let sum = 0;\n  for (let i = 0; i < weights.length; i++) {\n    sum += charValue(cnpj[i]) * weights[i];\n  }\n  const rem = sum % 11;\n  return rem < 2 ? 0 : 11 - rem;\n}\n\nexport function validateCNPJ(raw: string): boolean {\n  const cnpj = raw.replace(/[.\\-\\/]/g, '').toUpperCase();\n  if (cnpj.length !== 14) return false;\n\n  // Rejeita sequências homogêneas (ex.: \"00000000000000\")\n  if (/^(.)\\1+$/.test(cnpj)) return false;\n\n  try {\n    const w1 = [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2];\n    const w2 = [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2];\n\n    const d1 = calcDigit(cnpj, w1);\n    if (d1 !== Number(cnpj[12])) return false;\n\n    const d2 = calcDigit(cnpj, w2);\n    if (d2 !== Number(cnpj[13])) return false;\n\n    return true;\n  } catch {\n    return false;\n  }\n}"}</code></pre>
          <p className="mb-4">Para <Link href="/validar-cnpj" className="text-primary hover:underline">validar CNPJ</Link> manualmente durante o desenvolvimento, use a ferramenta do FakeForge que já suporta o novo formato.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Casos-limite que derrubam validações ingênuas</h3>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">00.000.000/0000-00</code> — rejeitar sequências de um único caractere repetido</li><li>Letras minúsculas — normalizar para maiúsculas antes de validar</li><li>Caracteres especiais além da máscara — rejeitar na entrada</li><li>Letras nas posições 13–14 — verificadores sempre numéricos</li></ul>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Máscaras e formatação de input</h2>
          <p className="mb-4">A máscara <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">00.000.000/0000-00</code> está hardcoded em bibliotecas que assumem dígitos. Com letras nas primeiras 12 posições, ela precisa aceitar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[A-Z0-9]</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Regex de validação de formato</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"const CNPJ_FORMAT = /^[A-Z0-9]{2}\\.[A-Z0-9]{3}\\.[A-Z0-9]{3}\\/[A-Z0-9]{4}-[0-9]{2}$/;"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Bibliotecas populares afetadas</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Biblioteca</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Status</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Ação necessária</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cpf-cnpj-validator</code></td><td className="px-3 py-2">Usa regex <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">\d</code></td><td className="px-3 py-2">Aguardar PR ou substituir</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">react-input-mask</code></td><td className="px-3 py-2">Padrão <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">9</code> aceita só dígitos</td><td className="px-3 py-2">Trocar padrão por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">*</code> + regex externa</td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">IMask</code></td><td className="px-3 py-2">Configurável via <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">definitions</code></td><td className="px-3 py-2">Atualizar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">mask</code> para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">AA.AAA.AAA/AAAA-00</code></td></tr><tr className="border-b border-border"><td className="px-3 py-2"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">vue-the-mask</code></td><td className="px-3 py-2">Hardcoded numérico</td><td className="px-3 py-2">Substituir por solução customizada</td></tr></tbody></table></div>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Código TypeScript: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">formatCNPJ()</code> agnóstico ao tipo</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"export function formatCNPJ(raw: string): string {\n  const cnpj = raw.replace(/[^A-Z0-9]/gi, '').toUpperCase().slice(0, 14);\n  if (cnpj.length !== 14) return cnpj;\n  return `${cnpj.slice(0,2)}.${cnpj.slice(2,5)}.${cnpj.slice(5,8)}/${cnpj.slice(8,12)}-${cnpj.slice(12)}`;\n}"}</code></pre>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Banco de dados: colunas e índices</h2>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(14)</code> com letras maiúsculas funciona tecnicamente, mas coloca pressão na collation. Em PostgreSQL com collation padrão (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">en_US.UTF-8</code>), ser explícito evita surpresas em comparações e índices.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Migration PostgreSQL segura e não-destrutiva</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"-- Migration: suporte a CNPJ alfanumérico\n-- Compatível com CNPJs numéricos existentes\n\nBEGIN;\n\n-- 1. Alterar tipo da coluna (CHAR → VARCHAR não quebra dados existentes)\nALTER TABLE empresas\n  ALTER COLUMN cnpj TYPE VARCHAR(14) COLLATE \"C\";\n\n-- 2. Remover constraint numérica antiga (se existir)\nALTER TABLE empresas\n  DROP CONSTRAINT IF EXISTS empresas_cnpj_numerico_check;\n\n-- 3. Adicionar nova constraint compatível com ambos os formatos\nALTER TABLE empresas\n  ADD CONSTRAINT empresas_cnpj_formato_check\n  CHECK (cnpj ~ '^[A-Z0-9]{14}$');\n\n-- 4. Normalizar valores existentes para maiúsculas\nUPDATE empresas SET cnpj = UPPER(cnpj) WHERE cnpj ~ '[a-z]';\n\nCOMMIT;"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">DICA: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">COLLATE "C"</code> no PostgreSQL faz comparação byte a byte — elimina ambiguidade de case em índices únicos e garante que <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">AB1234</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ab1234</code> são tratados como valores distintos. O índice único existente herda a collation da coluna, então não precisa ser recriado.</blockquote>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">APIs internas e contratos de integração</h2>
          <p className="mb-4">O ajuste mais esquecido em migrações é o contrato de API. Sistemas upstream começam a enviar CNPJs alfanuméricos e o consumer rejeita silenciosamente por causa de validação de schema.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">OpenAPI/Swagger e JSON Schema</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-yaml">{"# Antes\ncnpj:\n  type: string\n  pattern: '^\\d{14}$'\n\n# Depois\ncnpj:\n  type: string\n  pattern: '^[A-Z0-9]{14}$'\n  description: 'CNPJ sem máscara, 14 caracteres alfanuméricos maiúsculos'"}</code></pre>
          <p className="mb-4">Esse ajuste impacta clientes gerados por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">openapi-generator</code>, validações <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">zod</code> (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">z.string().regex(...)</code>) e schemas <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">yup</code>. Procure pelo pattern <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">\d&#123;14&#125;</code> em todo o repositório.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Webhooks e filas</h3>
          <p className="mb-4">Antes de produzir eventos com CNPJs alfanuméricos, confirme que todos os consumidores das filas suportam string alfanumérica. Um consumer que deserializa o campo para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">number</code> vai quebrar em runtime.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Integrações com terceiros</h2>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Sistema</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Status (Maio/2026)</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Ação</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">SEFAZ NF-e/NFS-e</td><td className="px-3 py-2">Schema XSD não atualizado</td><td className="px-3 py-2">Monitorar Portal da NF-e</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Open Finance BACEN</td><td className="px-3 py-2">Aguardando versão 3.x do padrão</td><td className="px-3 py-2">Monitorar changelog da API</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Cielo / Stone / Adyen BR</td><td className="px-3 py-2">Sem confirmação de suporte</td><td className="px-3 py-2">Abrir chamado de suporte agora</td></tr><tr className="border-b border-border"><td className="px-3 py-2">SAP / TOTVS / Oracle</td><td className="px-3 py-2">Campos numéricos hardcoded</td><td className="px-3 py-2">Abrir chamado com fornecedor agora</td></tr></tbody></table></div>
          <p className="mb-4">Para integrações via <Link href="/docs" className="text-primary hover:underline">API REST do FakeForge</Link>, o parâmetro <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">type=cnpj-alfanumerico</code> já está disponível.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Frontend: formulários e UX</h2>
          <p className="mb-4"><strong className="text-foreground">Placeholder e label:</strong> troque <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">00.000.000/0000-00</code> por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">AB.CDE.FGH/0001-00</code> para orientar o novo formato visualmente.</p>
          <p className="mb-4"><strong className="text-foreground">inputmode mobile:</strong> <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">inputmode="numeric"</code> abre teclado numérico e bloqueia letras. Troque para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">inputmode="text"</code> em qualquer campo que aceite CNPJ. Meça o impacto em conversão com analytics — a mudança afeta o comportamento do usuário em mobile.</p>
          <p className="mb-4"><strong className="text-foreground">Lookup por CNPJ em APIs públicas:</strong> BrasilAPI e ReceitaWS ainda não têm data confirmada de suporte ao formato alfanumérico. Não dependa de lookup automático por CNPJ alfanumérico antes de confirmar com o provedor.</p>
          <p className="mb-4"><strong className="text-foreground">Feedback de erro:</strong> "CNPJ inválido" precisa de contexto. Adicione: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">"Formato esperado: XX.XXX.XXX/XXXX-00 (letras A–Z maiúsculas e números)"</code>.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Testes automatizados</h2>
          <p className="mb-4">Seeds e fixtures com CNPJs hardcoded são a fonte mais comum de falhas silenciosas. Um teste que usa <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">11.222.333/0001-81</code> continua passando — mas o sistema pode quebrar com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">AB.CDE.FGH/0001-XX</code>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Tabela de casos de teste TypeScript</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// vitest / jest\nimport { validateCNPJ } from './cnpj';\n\nconst cases: { input: string; expected: boolean }[] = [\n  { input: '11.222.333/0001-81', expected: true  }, // numérico válido\n  { input: 'AB.CDE.FGH/0001-35', expected: true  }, // alfanumérico válido (fictício)\n  { input: '00.000.000/0000-00', expected: false }, // sequência homogênea\n  { input: '11.222.333/0001-99', expected: false }, // dígito verificador errado\n  { input: 'AB.CDE.FGH/0001-AB', expected: false }, // verificadores com letra\n  { input: '11.222.333/0001-8',  expected: false }, // tamanho errado\n];\n\ntest.each(cases)('validateCNPJ($input) → $expected', ({ input, expected }) => {\n  expect(validateCNPJ(input)).toBe(expected);\n});"}</code></pre>
          <p className="mb-4">Para gerar CNPJs alfanuméricos válidos em massa para seeds, use o <Link href="/gerador-cnpj-alfanumerico" className="text-primary hover:underline">gerador de CNPJ alfanumérico</Link> ou a <Link href="/docs" className="text-primary hover:underline">API REST</Link> com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">type=cnpj-alfanumerico</code>. Para <Link href="/gerador-cnpj" className="text-primary hover:underline">gerar CNPJs numéricos</Link> paralelos, o gerador padrão continua disponível.</p>
          <p className="mb-4">Se você usa Pact ou Dredd, adicione pelo menos um exemplo alfanumérico nos testes de contrato. Testes que só têm exemplos numéricos não cobrem o novo formato.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Checklist executivo — o que fazer por semana</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Semana 1–2: diagnóstico</h3>
          <p className="mb-4">Inventarie toda ocorrência de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cnpj</code> no código:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"grep -rn \"cnpj\" --include=\"*.ts\" --include=\"*.js\" --include=\"*.py\" --include=\"*.java\" ."}</code></pre>
          <p className="mb-4">Procure também por regex com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">\d&#123;14&#125;</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[0-9]&#123;14&#125;</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(14)</code> em migrations SQL, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pattern: '^\d&#123;14&#125;$'</code> em OpenAPI e JSON Schema, e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">inputmode="numeric"</code> em campos de CNPJ.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Semana 3–4: lib e validação</h3>
          <p className="mb-4">Atualize ou substitua a biblioteca de validação. Cubra com os casos de teste da seção anterior. Não avance sem cobertura dos casos-limite.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Semana 5–6: banco e API</h3>
          <p className="mb-4">Execute a migration. Atualize schemas OpenAPI e contratos. Atualize clientes gerados automaticamente.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Semana 7–8: integrações e frontend</h3>
          <p className="mb-4">Alinhe parceiros externos — especialmente SEFAZ e processadoras. Ajuste máscaras, placeholders e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">inputmode</code> nos formulários.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Semana 9–10: homologação</h3>
          <p className="mb-4">Execute smoke tests com CNPJs alfanuméricos gerados. Monitore erros em staging com o <Link href="/gerador-cnpj-alfanumerico" className="text-primary hover:underline">gerador de CNPJ alfanumérico</Link> para criar dados realistas.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">LGPD e dados de teste — atenção redobrada</h2>
          <p className="mb-4">CNPJ de MEI (Microempreendedor Individual) identifica uma pessoa natural, não apenas uma pessoa jurídica. Dependendo do contexto, o CNPJ alfanumérico de um MEI pode ser dado pessoal nos termos da <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 5º, I</a>.</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">AVISO: LGPD Art. 7º, IX permite tratamento de dados para legítimo interesse, mas seeds de banco de desenvolvimento não se enquadram nesse fundamento. Use dados fictícios gerados por ferramentas como o FakeForge BR. Para comparar as <Link href="/comparacao/fakeforge-vs-alternativas" className="text-primary hover:underline">alternativas de gerador de dados</Link> disponíveis, veja o artigo de comparação.</blockquote>
          <p className="mb-4">Nunca use CNPJs reais em seeds de banco de dados de desenvolvimento ou homologação — numéricos ou alfanuméricos.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li><strong className="text-foreground">01/07/2026</strong> é a data de emissão dos primeiros CNPJs alfanuméricos; sem prazo para migração forçada da base existente — mas qualquer sistema que receba CNPJ precisa suportar ambos os formatos a partir dessa data.</li><li><strong className="text-foreground">Validação</strong> exige novo algoritmo: converta <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">A=17...Z=44</code> antes do módulo 11; os dois dígitos verificadores continuam numéricos e precisam ser tratados como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">Number</code>, não <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">charValue</code>.</li><li><strong className="text-foreground">Banco de dados:</strong> migre <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(14)</code> para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">VARCHAR(14) COLLATE "C"</code>, atualize constraints e normalize para maiúsculas antes de aplicar a nova constraint.</li><li><strong className="text-foreground">APIs e contratos:</strong> substitua <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">\d&#123;14&#125;</code> por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">[A-Z0-9]&#123;14&#125;</code> em patterns OpenAPI, JSON Schema, Zod e Yup — e confirme que todos os consumidores de filas suportam string alfanumérica antes de produzir eventos.</li><li><strong className="text-foreground">Terceiros:</strong> SEFAZ, Open Finance e processadoras ainda sem prazo confirmado — monitore o Portal NF-e e o changelog do BACEN ativamente; abra chamados com SAP, TOTVS e Oracle agora.</li><li><strong className="text-foreground">Testes:</strong> adicione casos alfanuméricos a toda tabela de fixtures e use o <Link href="/gerador-cnpj-alfanumerico" className="text-primary hover:underline">gerador de CNPJ alfanumérico</Link> para seeds de homologação — nunca use CNPJs reais de MEIs em ambientes de desenvolvimento.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Índices únicos em CNPJ ficam m" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Índices únicos em CNPJ ficam mais lentos depois de migrar CHAR(14) para VARCHAR?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">PostgreSQL maneja índices em VARCHAR normalmente. A chave é collation: sempre use `COLLATE "C"` para garantir comparação determinística byte-a-byte. Sem `COLLATE "C"`, o SO pode tratar minúsculas/maiúsculas como equivalentes, quebrando a constraint de unicidade. Com `COLLATE "C"`, performance é idêntica à CHAR(14). Teste em staging antes.</p>
            </details>
            <details key="Como gerar CNPJ alfanumérico v" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como gerar CNPJ alfanumérico válido para fixtures sem chamar a API?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sorteie 12 caracteres de [A-Z0-9] via `crypto.getRandomValues()`, calcule os 2 dígitos verificadores com o algoritmo do artigo (charValue + módulo 11), concatene. Exemplo: `randomString(12) → calcDigit() → calcDigit() → resultado válido`. Não é mais complexo que gerar CPF — implementação é literal.</p>
            </details>
            <details key="Descobrimos um CNPJ inválido s" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Descobrimos um CNPJ inválido salvo no banco. Como fazer rollback sem quebrar foreign keys?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Antes de deletar, valide toda a tabela com `validateCNPJ()`. Registros inválidos: migre-os para tabela staging usando UUID de rastreamento, nunca delete silencioso. Use transação explícita com BEGIN/COMMIT. Se integrado com NF-e/SEFAZ, consulte antes pois pode haver certificado associado. Notifique stakeholders do impacto.</p>
            </details>
            <details key="Regex sozinho é suficiente par" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Regex sozinho é suficiente para validar CNPJ ou preciso de checksum também?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Regex `[A-Z0-9]&#123;14&#125;` valida só formato; qualquer 14 caracteres passam. Checksum (módulo 11) garante que é CNPJ emitido legalmente. Um atacante gera strings válidas no regex mas inválidas no checksum. Em entrada de usuário, sempre valide checksum. Regex é suficiente só para máscaras internas/display.</p>
            </details>
            <details key="Como validar campo CNPJ que ac" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como validar campo CNPJ que aceita formato numérico e alfanumérico em Zod?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Use `z.string().regex(/^[A-Z0-9]&#123;14&#125;$/).refine(validateCNPJ, &#123; message: 'CNPJ inválido' &#125;)` — regex valida formato, refine valida checksum. Ou `superRefine()` para mensagens contextualizadas. Ambos aceitam numérico e alfanumérico. Importante: nunca confie só em regex; sempre aplique checksum na entrada. Type-safe end-to-end.</p>
            </details>
          </div>
        </section>
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Índices únicos em CNPJ ficam mais lentos depois de migrar CHAR(14) para VARCHAR?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"PostgreSQL maneja índices em VARCHAR normalmente. A chave é collation: sempre use `COLLATE \\\"C\\\"` para garantir comparação determinística byte-a-byte. Sem `COLLATE \\\"C\\\"`, o SO pode tratar minúsculas/maiúsculas como equivalentes, quebrando a constraint de unicidade. Com `COLLATE \\\"C\\\"`, performance é idêntica à CHAR(14). Teste em staging antes.\"}},{\"@type\":\"Question\",\"name\":\"Como gerar CNPJ alfanumérico válido para fixtures sem chamar a API?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sorteie 12 caracteres de [A-Z0-9] via `crypto.getRandomValues()`, calcule os 2 dígitos verificadores com o algoritmo do artigo (charValue + módulo 11), concatene. Exemplo: `randomString(12) → calcDigit() → calcDigit() → resultado válido`. Não é mais complexo que gerar CPF — implementação é literal.\"}},{\"@type\":\"Question\",\"name\":\"Descobrimos um CNPJ inválido salvo no banco. Como fazer rollback sem quebrar foreign keys?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Antes de deletar, valide toda a tabela com `validateCNPJ()`. Registros inválidos: migre-os para tabela staging usando UUID de rastreamento, nunca delete silencioso. Use transação explícita com BEGIN/COMMIT. Se integrado com NF-e/SEFAZ, consulte antes pois pode haver certificado associado. Notifique stakeholders do impacto.\"}},{\"@type\":\"Question\",\"name\":\"Regex sozinho é suficiente para validar CNPJ ou preciso de checksum também?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Regex `[A-Z0-9]{14}` valida só formato; qualquer 14 caracteres passam. Checksum (módulo 11) garante que é CNPJ emitido legalmente. Um atacante gera strings válidas no regex mas inválidas no checksum. Em entrada de usuário, sempre valide checksum. Regex é suficiente só para máscaras internas/display.\"}},{\"@type\":\"Question\",\"name\":\"Como validar campo CNPJ que aceita formato numérico e alfanumérico em Zod?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Use `z.string().regex(/^[A-Z0-9]{14}$/).refine(validateCNPJ, { message: 'CNPJ inválido' })` — regex valida formato, refine valida checksum. Ou `superRefine()` para mensagens contextualizadas. Ambos aceitam numérico e alfanumérico. Importante: nunca confie só em regex; sempre aplique checksum na entrada. Type-safe end-to-end.\"}}]}",
        }}
      />
    </PageShell>
  );
}
