import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";
import ShareBar from "@/components/ShareBar";

export const metadata: Metadata = {
  title: "FakeForge vs Mockaroo vs Faker.js para Dados Brasileiros",
  description: "Compare FakeForge, Mockaroo e Faker.js para CPF, CNPJ, PIX e endereços BR. Veja qual valida checksums, exporta SQL e respeita a LGPD.",
  openGraph: {
    title: "FakeForge vs Mockaroo vs Faker.js para Dados Brasileiros",
    description: "Compare FakeForge, Mockaroo e Faker.js para CPF, CNPJ, PIX e endereços BR. Veja qual valida checksums, exporta SQL e respeita a LGPD.",
    type: "article",
    images: ["/api/og?title=FakeForge%20vs%20Mockaroo%20vs%20Faker.js%3A%20qual%20gera%20dados%20brasileiros%20de%20verdade%3F&subtitle=Compare%20FakeForge%2C%20Mockaroo%20e%20Faker.js%20para%20CPF%2C%20CNPJ%2C%20PIX%20e%20endere%C3%A7os%20BR.%20Veja%20qual%20valida%20checksums%2C%20exporta%20SQL%20e%20respeita%20a%20LGPD.&category=COMPARATIVOS"],
  },
  alternates: { canonical: "/blog/fakeforge-vs-mockaroo-vs-fakerjs-dados-brasileiros" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Comparativos" title="FakeForge vs Mockaroo vs Faker.js: qual gera dados brasileiros de verdade?" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            FakeForge vs Mockaroo vs Faker.js: qual gera dados brasileiros de verdade?
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>20 de maio de 2026</time>
            <span>·</span>
            <span>9 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">Escolher a ferramenta errada para gerar dados de teste custa horas de debug. Um CPF com dígito verificador inválido quebra a validação no back-end antes do primeiro <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">console.log</code>. Um endereço onde o CEP não corresponde à cidade derruba o formulário de checkout no step de entrega. Este artigo compara FakeForge BR, Mockaroo e Faker.js em critérios objetivos: checksum, coerência geográfica, suporte a PIX e CNPJ Alfanumérico, export SQL e LGPD.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O que cada ferramenta faz — e para quem foi feita</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">FakeForge BR — gerador focado no mercado brasileiro</h3>
          <p className="mb-4"><a href="https://fakeforge.com.br" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">FakeForge BR</a> é uma aplicação web e API REST construída especificamente para o mercado brasileiro. Gera CPF, CNPJ, CEP, PIX, cartões com Luhn, RG, CNH, CIN, PIS/PASEP, Título de Eleitor e dados de pessoa, empresa e endereço — tudo com validação de formato embutida na geração. A API está disponível em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/api/generate</code> com saída em JSON, CSV ou SQL.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Mockaroo — plataforma SaaS de dados genéricos</h3>
          <p className="mb-4">Mockaroo é uma plataforma SaaS americana para geração de dados tabulares em qualquer domínio. Suporta mais de 180 tipos de campo, mas nenhum deles é CPF ou CNPJ nativo. A interface web serve bem times não-técnicos que precisam de planilhas de teste. A API custa a partir de USD 50/mês para volume relevante.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Faker.js — biblioteca open-source para Node/browser</h3>
          <p className="mb-4">Faker.js é uma biblioteca JavaScript/TypeScript open-source com suporte a múltiplos locales, incluindo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pt_BR</code>. Roda no seu próprio processo, sem dependência de rede. O locale brasileiro existe, mas a manutenção é comunitária — e os gaps para dados financeiros e documentos são conhecidos.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">CPF e CNPJ com dígito verificador correto</h2>
          <p className="mb-4">Dado inválido em teste não é dado de teste — é ruído. Um formulário que valida CPF no front-end vai rejeitar qualquer número gerado sem o algoritmo mod-11 correto, interrompendo o fluxo antes de chegar ao back-end.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que checksum mod-11 é obrigatório em testes reais</h3>
          <p className="mb-4">O CPF usa dois dígitos verificadores calculados por multiplicação dos nove primeiros algarismos por pesos decrescentes, módulo 11. O CNPJ usa sequência similar com pesos 2–9 aplicados duas vezes. Qualquer número gerado por string aleatória falha nesse cálculo em 99% dos casos.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Faker.js <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">br</code> locale gera CPF válido? (resultado do teste)</h3>
          <p className="mb-4">Sim — <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">faker.br.cpf()</code> calcula o dígito corretamente. O código abaixo é um ponto de comparação real:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import { faker } from '@faker-js/faker/locale/pt_BR';\n\nconst cpf = faker.br.cpf(); // ex: \"123.456.789-09\"\nconsole.log(cpf);"}</code></pre>
          <p className="mb-4">O problema aparece fora do CPF. Faker.js não tem <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">faker.br.cnpj()</code> com checksum verificável na versão estável, não tem PIX, não tem Luhn para BINs brasileiros (Elo, Hipercard) e não tem endereço correlacionado.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Mockaroo não possui tipo CPF nativo — o workaround e seus limites</h3>
          <p className="mb-4">Mockaroo não tem campo CPF. O workaround comum é usar "Custom List" com uma lista pré-gerada de CPFs válidos ou uma fórmula no campo "Formula". Ambas as abordagens exigem trabalho manual e não escalam — ninguém vai manter uma lista de 50 mil CPFs válidos atualizada.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">FakeForge valida o dígito na geração e expõe <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/validar-cpf</code></h3>
          <p className="mb-4">O <Link href="/gerador-cpf" className="text-primary hover:underline">gerador de CPF</Link> da FakeForge calcula os dígitos verificadores no servidor antes de retornar o resultado. O round-trip abaixo confirma isso:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// Round-trip test: gera CPF e valida na mesma API\nasync function roundTripCPF(): Promise<void> {\n  const gen = await fetch(\n    'https://fakeforge.com.br/api/generate?type=cpf&quantity=1'\n  );\n  const { data } = await gen.json();\n  const cpf: string = data[0].cpf;\n\n  const val = await fetch(\n    `https://fakeforge.com.br/api/validar-cpf?cpf=${cpf}`\n  );\n  const { valid } = await val.json();\n\n  console.log(`CPF: ${cpf} | válido: ${valid}`); // sempre true\n}\n\nroundTripCPF();"}</code></pre>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">CNPJ Alfanumérico: suporte antes da vigência de 01/07/2026</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que muda na Instrução Normativa RFB 2.237/2024</h3>
          <p className="mb-4">A Instrução Normativa RFB 2.237/2024 altera o formato do CNPJ para aceitar letras nas oito primeiras posições, mantendo os dois dígitos verificadores no final. A vigência obrigatória começa em 01/07/2026. Sistemas que fazem <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">parseInt()</code> ou validam com regex <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">^\d&#123;14&#125;$</code> vão quebrar na primeira empresa com CNPJ alfanumérico.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estado atual de cada ferramenta</h3>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li><strong className="text-foreground">Faker.js</strong>: sem suporte a CNPJ Alfanumérico na versão estável. O locale <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pt_BR</code> gera apenas o formato numérico.</li><li><strong className="text-foreground">Mockaroo</strong>: sem tipo CNPJ nativo, muito menos alfanumérico.</li><li><strong className="text-foreground">FakeForge</strong>: o <Link href="/gerador-cnpj-alfanumerico" className="text-primary hover:underline">gerador de CNPJ Alfanumérico</Link> já está disponível, com cálculo correto dos dígitos verificadores no novo formato.</li></ul>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">DICA: Se você tem sistemas que vão receber CNPJ Alfanumérico após 01/07/2026, comece os testes de regressão agora. O FakeForge já gera o formato novo — não espere a vigência para descobrir o bug em produção.</blockquote>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Endereços brasileiros correlacionados vs campos independentes</h2>
          <p className="mb-4">Formulários de endereço no Brasil dependem de coerência entre CEP, bairro, cidade e estado. Um CEP com prefixo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">01</code> pertence a São Paulo-SP. Um com prefixo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">40</code> pertence a Salvador-BA. Se esses campos não forem gerados juntos, seus testes de formulário vão passar com dados que nenhum sistema de validação real aceitaria.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como Faker.js gera endereço BR (campos soltos, sem coerência geográfica)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import { faker } from '@faker-js/faker/locale/pt_BR';\n\nconst endereco = {\n  cep:    faker.location.zipCode('########'), // sem correlação geográfica\n  cidade: faker.location.city(),              // cidade aleatória\n  estado: faker.location.state(),             // pode não bater com a cidade\n  bairro: faker.location.street(),            // retorna rua, não bairro\n};\n\n// Resultado possível:\n// { cep: '83729-041', cidade: 'São Paulo', estado: 'Minas Gerais', bairro: 'Rua das Flores' }\n// CEP de PR, cidade SP, estado MG — incoerente para qualquer validação"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Mockaroo com dataset importado: funciona, mas exige setup manual</h3>
          <p className="mb-4">Mockaroo permite importar um dataset CSV com CEPs reais e configurar joins entre colunas para garantir coerência. O resultado final é válido — mas você precisa manter o dataset, atualizá-lo quando cidades mudam de nome e reconfigurar as relações a cada schema novo.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">FakeForge: CEP, bairro, cidade e estado do mesmo estado por design</h3>
          <p className="mb-4">O <Link href="/gerador-pessoa" className="text-primary hover:underline">gerador de endereço</Link> da FakeForge garante que todos os campos de endereço pertencem à mesma região geográfica. CEP prefix, bairro, cidade e estado são selecionados de um conjunto de referência coerente para os estados cobertos — sem configuração manual.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">PIX, cartão de crédito e dados financeiros com formato BACEN</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Chaves PIX nos quatro formatos</h3>
          <p className="mb-4">O BACEN define quatro tipos de chave PIX: CPF/CNPJ, email, telefone (E.164) e chave aleatória (UUID v4). Testes de integração com gateways de pagamento precisam dos quatro formatos. O <Link href="/gerador-pix" className="text-primary hover:underline">gerador de PIX</Link> da FakeForge entrega todos eles:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=pix&quantity=5&format=json\"\n\n# Saída esperada (campos anotados):\n# {\n#   \"data\": [\n#     { \"type\": \"cpf\",       \"key\": \"123.456.789-09\"          }, # CPF válido mod-11\n#     { \"type\": \"cnpj\",      \"key\": \"12.345.678/0001-90\"      },\n#     { \"type\": \"email\",     \"key\": \"joao.silva@gmail.com\"    },\n#     { \"type\": \"telefone\",  \"key\": \"+5511987654321\"          }, # E.164 com DDD válido\n#     { \"type\": \"aleatoria\", \"key\": \"a1b2c3d4-e5f6-7890-...\"  } # UUID v4\n#   ]\n# }"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Cartões com algoritmo de Luhn e BINs reais (Visa, Mastercard, Elo, Hipercard, Amex)</h3>
          <p className="mb-4">O <Link href="/gerador-cartao" className="text-primary hover:underline">gerador de cartão</Link> usa BINs reais das bandeiras brasileiras e aplica o algoritmo de Luhn para o último dígito. Elo e Hipercard — inexistentes no Faker.js <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pt_BR</code> — estão incluídas.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que Mockaroo e Faker.js entregam nesse domínio</h3>
          <p className="mb-4">Mockaroo tem um campo "Credit Card Number" genérico com Luhn, mas sem BINs brasileiros. Faker.js tem <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">faker.finance.creditCardNumber()</code> com Luhn, mas sem Elo ou Hipercard. PIX como conceito não existe em nenhum dos dois.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">API REST vs biblioteca vs interface web — o modelo certo para cada caso de uso</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">CI/CD e seed de banco: quando uma API com endpoint <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/api/generate</code> é a resposta mais simples</h3>
          <p className="mb-4">Em pipelines de CI, você quer uma chamada HTTP que retorna dados prontos — sem instalar dependências, sem manter código de geração no repositório. A <Link href="/docs" className="text-primary hover:underline">API REST</Link> da FakeForge aceita GET com query params ou POST com JSON body:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// Seed de banco com a API FakeForge — format=sql entrega schema + INSERTs prontos\nasync function seedDatabase(db: { query: (sql: string) => Promise<void> }): Promise<void> {\n  const res = await fetch(\n    'https://fakeforge.com.br/api/generate?type=pessoa&quantity=50&format=sql',\n    { headers: { Authorization: `Bearer ${process.env.FAKEFORGE_API_KEY}` } }\n  );\n  if (!res.ok) throw new Error(`FakeForge API: ${res.status}`);\n  const sql = await res.text();\n  await db.query(sql); // CREATE TABLE + 50 INSERTs em uma chamada\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Faker.js no código: controle total, mas manutenção do locale BR é sua responsabilidade</h3>
          <p className="mb-4">Faker.js é a escolha certa quando você quer zero dependência externa e aceita manter o código de geração. O risco: o locale <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pt_BR</code> tem contribuidores esporádicos — bugs como nome de bairro em inglês ou DDD inválido existem no histórico do repositório.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Mockaroo API: plano pago a partir de USD 50/mês para volume razoável</h3>
          <p className="mb-4">O plano gratuito do Mockaroo limita a 200 linhas por download e não inclui acesso à API. O plano Developer (USD 50/mês) libera a API com até 100 mil linhas/mês. Para times brasileiros, isso representa aproximadamente R$ 280/mês na cotação de maio de 2026.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">FakeForge freemium: 100 chamadas/dia grátis, plano Dev R$29</h3>
          <p className="mb-4">A FakeForge oferece 100 chamadas de API por dia no plano gratuito. O <Link href="/pricing" className="text-primary hover:underline">plano Dev</Link> custa R$29/mês para uso individual. O plano Team custa R$79/mês para times com volume maior.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Export SQL com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE</code> pronto — diferencial para seed de banco</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como o parâmetro <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code> da FakeForge gera schema + INSERT em uma chamada</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"-- Output de /api/generate?type=cpf&quantity=3&format=sql\n\nCREATE TABLE IF NOT EXISTS cpf_data (\n  id        SERIAL PRIMARY KEY,\n  cpf       VARCHAR(14) NOT NULL,\n  cpf_limpo VARCHAR(11) NOT NULL\n);\n\nINSERT INTO cpf_data (cpf, cpf_limpo) VALUES\n  ('123.456.789-09', '12345678909'),\n  ('987.654.321-00', '98765432100'),\n  ('456.789.123-87', '45678912387');"}</code></pre>
          <p className="mb-4">O schema é gerado automaticamente com base no tipo solicitado e funciona para todos os 16 tipos disponíveis.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Mockaroo também tem SQL export — comparação lado a lado</h3>
          <p className="mb-4">Mockaroo gera SQL export com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">INSERT INTO</code>. A diferença: você configura o schema manualmente na interface antes de exportar. Para dados genéricos o Mockaroo é competitivo nessa funcionalidade. Para CPF, CNPJ ou PIX, o schema precisa ser construído com campos customizados — sem garantia de checksum.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Faker.js não exporta SQL nativamente (você monta o script)</h3>
          <p className="mb-4">Com Faker.js, você escreve o template SQL manualmente. Isso não é um problema — é uma biblioteca, não um serviço de export — mas o custo de manutenção do template e do schema fica no seu repositório.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">LGPD Art. 7º, IX e o uso de dados fictícios em testes</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que dados reais de produção em ambiente de dev violam a base legal</h3>
          <p className="mb-4">A <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">LGPD Art. 7º, IX</a> permite o tratamento de dados pessoais quando necessário para atender aos interesses legítimos do controlador — mas usar base de clientes reais em ambiente de desenvolvimento não se enquadra nessa base legal. Ambientes de dev tipicamente têm controles de segurança menores, mais pessoas com acesso e logs não auditados.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que "LGPD-safe" significa na prática: nenhum dado real armazenado ou processado</h3>
          <p className="mb-4">Ferramentas de dados fictícios são LGPD-safe quando não coletam, armazenam nem processam dados pessoais reais. A FakeForge gera dados algoritmicamente — não existe banco de dados com CPFs reais sendo "amostrados". O mesmo vale para Faker.js (execução local) e Mockaroo (sem input de dados reais do usuário).</p>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic">AVISO: "Anonimizar" dados de produção com substituição simples de campos — por exemplo, trocar o nome por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">faker.person.firstName()</code> mantendo o CPF original — não é suficiente para fins de LGPD. O CPF sozinho é dado pessoal diretamente identificável (LGPD Art. 5º, I). Use dados inteiramente sintéticos, sem nenhuma correlação com titulares reais.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Como documentar a escolha da ferramenta de dados fictícios no RIPD</h3>
          <p className="mb-4">O Relatório de Impacto à Proteção de Dados (RIPD) deve registrar que o ambiente de teste usa dados inteiramente fictícios, gerados por ferramenta específica (nome, versão, URL), sem correlação com titulares reais. Uma linha de justificativa adequada: "Dados de teste gerados pela API FakeForge BR (fakeforge.com.br), algoritmo determinístico sem base em dados reais, em conformidade com LGPD Art. 7º."</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Tabela de decisão: critérios objetivos lado a lado</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Matriz de funcionalidades</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Critério</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">FakeForge BR</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Mockaroo</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Faker.js</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">CPF com mod-11</td><td className="px-3 py-2">Sim</td><td className="px-3 py-2">Não nativo</td><td className="px-3 py-2">Sim (<code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pt_BR</code>)</td></tr><tr className="border-b border-border"><td className="px-3 py-2">CNPJ com checksum</td><td className="px-3 py-2">Sim</td><td className="px-3 py-2">Não nativo</td><td className="px-3 py-2">Parcial</td></tr><tr className="border-b border-border"><td className="px-3 py-2">CNPJ Alfanumérico (2026)</td><td className="px-3 py-2">Sim</td><td className="px-3 py-2">Não</td><td className="px-3 py-2">Não</td></tr><tr className="border-b border-border"><td className="px-3 py-2">PIX (4 formatos BACEN)</td><td className="px-3 py-2">Sim</td><td className="px-3 py-2">Não</td><td className="px-3 py-2">Não</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Elo / Hipercard + Luhn</td><td className="px-3 py-2">Sim</td><td className="px-3 py-2">Não</td><td className="px-3 py-2">Não</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Endereço correlacionado BR</td><td className="px-3 py-2">Sim</td><td className="px-3 py-2">Setup manual</td><td className="px-3 py-2">Não</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Export SQL com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE</code></td><td className="px-3 py-2">Sim</td><td className="px-3 py-2">Sim</td><td className="px-3 py-2">Não nativo</td></tr><tr className="border-b border-border"><td className="px-3 py-2">API REST</td><td className="px-3 py-2">Sim</td><td className="px-3 py-2">Sim (pago)</td><td className="px-3 py-2">N/A (biblioteca)</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Preço da API</td><td className="px-3 py-2">R$ 29/mês</td><td className="px-3 py-2">~R$ 280/mês</td><td className="px-3 py-2">Grátis</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Zero dependência externa</td><td className="px-3 py-2">Não</td><td className="px-3 py-2">Não</td><td className="px-3 py-2">Sim</td></tr></tbody></table></div>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quando usar Faker.js mesmo assim (projeto open-source, sem dependência externa)</h3>
          <p className="mb-4">Se o projeto é open-source, não pode ter dependência de serviço externo e os dados necessários são cobertos pelo locale <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pt_BR</code> (CPF, nomes, emails básicos), Faker.js é a escolha correta. O custo de manter o locale é menor do que justificar uma dependência de rede em um projeto público.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quando Mockaroo ainda faz sentido (times com dados não-BR e orçamento em dólar)</h3>
          <p className="mb-4">Mockaroo é competitivo para times multinacionais que precisam de dados de múltiplos países em um único schema, com interface visual para usuários não-técnicos. Se o time já paga em dólar e precisa de dados americanos, europeus e brasileiros no mesmo dataset, o Mockaroo unifica isso — mesmo que os dados BR sejam mais limitados.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Migração prática de Faker.js para a API FakeForge em 15 linhas</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Antes: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">faker.helpers.fake()</code> com locale pt_BR</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import { faker } from '@faker-js/faker/locale/pt_BR';\n\n// Geração local com Faker.js — sem PIX, sem endereço correlacionado, sem CNPJ alfanumérico\nconst pessoas = Array.from({ length: 50 }, () => ({\n  nome:  `${faker.person.firstName()} ${faker.person.lastName()}`,\n  cpf:   faker.br.cpf(),\n  email: faker.internet.email(),\n}));"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Depois: fetch para <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/api/generate</code> com tipagem TypeScript</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"interface Pessoa {\n  nome:     string;\n  cpf:      string;\n  email:    string;\n  pix:      string;\n  endereco: string;\n}\n\nasync function gerarPessoas(quantidade: number): Promise<Pessoa[]> {\n  const url = new URL('https://fakeforge.com.br/api/generate');\n  url.searchParams.set('type', 'pessoa');\n  url.searchParams.set('quantity', String(quantidade));\n  url.searchParams.set('format', 'json');\n\n  const res = await fetch(url.toString(), {\n    headers: { Authorization: `Bearer ${process.env.FAKEFORGE_API_KEY}` },\n  });\n  if (!res.ok) throw new Error(`FakeForge API: ${res.status}`);\n  const { data } = await res.json();\n  return data as Pessoa[];\n}\n\nconst pessoas = await gerarPessoas(50);\n// dados com CPF válido, PIX, endereço correlacionado e tipagem garantida"}</code></pre>
          <p className="mb-4">A mudança remove a dependência do pacote <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">@faker-js/faker</code> do pipeline e centraliza a lógica de geração. Usando <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code> no lugar de <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">json</code>, você elimina também o passo de montar o <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">INSERT</code> manualmente.</p>
          <p className="mb-4">---</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li><strong className="text-foreground">CPF e CNPJ com checksum correto</strong> são obrigatórios para testes reais; Faker.js cobre CPF, mas falha em dados financeiros BR e no novo formato de CNPJ.</li><li><strong className="text-foreground">CNPJ Alfanumérico entra em vigor em 01/07/2026</strong> — apenas o <Link href="/gerador-cnpj-alfanumerico" className="text-primary hover:underline">FakeForge</Link> já suporta o novo formato; sistemas que validam com regex <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">\d&#123;14&#125;</code> precisam de testes de regressão agora.</li><li><strong className="text-foreground">Endereços correlacionados</strong> (CEP + cidade + estado coerentes) só existem no FakeForge por design; Faker.js gera campos independentes sem garantia geográfica.</li><li><strong className="text-foreground">LGPD Art. 7º, IX</strong> exige dados inteiramente sintéticos em ambientes de teste — anonimização parcial de dados reais não é suficiente.</li><li>Para <strong className="text-foreground">projetos open-source sem dependência externa</strong>, Faker.js é a escolha válida; para <strong className="text-foreground">APIs, pipelines de CI e seed de banco com dados BR completos</strong>, a <Link href="/docs" className="text-primary hover:underline">API FakeForge</Link> é mais direta com custo menor que o Mockaroo.</li><li>A <Link href="/comparacao/fakeforge-vs-alternativas" className="text-primary hover:underline">comparação completa de alternativas</Link> cobre outros geradores além dos três analisados aqui.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Como o FakeForge garante CPFs " className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como o FakeForge garante CPFs únicos ao gerar lotes grandes?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">O FakeForge gera CPFs aleatoriamente no espaço de 10^11 valores válidos. Colisões em lotes de até 10 mil são estatisticamente irrelevantes (probabilidade é ~10^-7). Se seu banco tem UNIQUE constraint, raros duplicados retornarão erro — capture-os e regenere o lote específico.</p>
            </details>
            <details key="Como usar a API FakeForge em C" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como usar a API FakeForge em CI/CD sem expor a API key?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Configure a chave como secret no GitHub Actions (Settings &gt; Secrets), acesse via `$&#123;&#123; secrets.FAKEFORGE_API_KEY &#125;&#125;`. Passe ao script via variável de ambiente. A chave não aparece em logs ou artifacts — é mascarada automaticamente pelo GitHub.</p>
            </details>
            <details key="Qual a latência esperada ao so" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Qual a latência esperada ao solicitar 10.000 registros da API FakeForge?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Geração de 10 mil itens leva ~500ms–2s dependendo do tipo. Pessoa com endereço é mais lenta que CPF puro. Para volumes maiores, chunque em blocos de 5 mil com rate limit de 1 chamada/s. Timeout recomendado: 10s.</p>
            </details>
            <details key="Se gero 100 mil CPFs em testes" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Se gero 100 mil CPFs em testes, qual risco de colisão com dados reais?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">CPF tem 11 dígitos (~10^11 valores). Colisão acidental é improvável. Risco real é cruzamento com produção. Solução: use ranges específicos para testes (ex: CPFs iniciando com 999), valide antes de importar. LGPD: dados fictícios são obrigatórios.</p>
            </details>
            <details key="FakeForge suporta seed determi" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">FakeForge suporta seed determinístico como Faker.js?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não — a API gera dados aleatórios a cada chamada. Para testes reprodutíveis, exporte JSON na primeira execução, comite no repositório e reutilize. Ou mantenha Faker.js com seed fixo para cenários que exigem replay determinístico absoluto.</p>
            </details>
          </div>
        </section>
        <ShareBar title={"FakeForge vs Mockaroo vs Faker.js para Dados Brasileiros"} path="/blog/fakeforge-vs-mockaroo-vs-fakerjs-dados-brasileiros" />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Como o FakeForge garante CPFs únicos ao gerar lotes grandes?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"O FakeForge gera CPFs aleatoriamente no espaço de 10^11 valores válidos. Colisões em lotes de até 10 mil são estatisticamente irrelevantes (probabilidade é ~10^-7). Se seu banco tem UNIQUE constraint, raros duplicados retornarão erro — capture-os e regenere o lote específico.\"}},{\"@type\":\"Question\",\"name\":\"Como usar a API FakeForge em CI/CD sem expor a API key?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Configure a chave como secret no GitHub Actions (Settings > Secrets), acesse via `${{ secrets.FAKEFORGE_API_KEY }}`. Passe ao script via variável de ambiente. A chave não aparece em logs ou artifacts — é mascarada automaticamente pelo GitHub.\"}},{\"@type\":\"Question\",\"name\":\"Qual a latência esperada ao solicitar 10.000 registros da API FakeForge?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Geração de 10 mil itens leva ~500ms–2s dependendo do tipo. Pessoa com endereço é mais lenta que CPF puro. Para volumes maiores, chunque em blocos de 5 mil com rate limit de 1 chamada/s. Timeout recomendado: 10s.\"}},{\"@type\":\"Question\",\"name\":\"Se gero 100 mil CPFs em testes, qual risco de colisão com dados reais?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"CPF tem 11 dígitos (~10^11 valores). Colisão acidental é improvável. Risco real é cruzamento com produção. Solução: use ranges específicos para testes (ex: CPFs iniciando com 999), valide antes de importar. LGPD: dados fictícios são obrigatórios.\"}},{\"@type\":\"Question\",\"name\":\"FakeForge suporta seed determinístico como Faker.js?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não — a API gera dados aleatórios a cada chamada. Para testes reprodutíveis, exporte JSON na primeira execução, comite no repositório e reutilize. Ou mantenha Faker.js com seed fixo para cenários que exigem replay determinístico absoluto.\"}}]}",
        }}
      />
    </PageShell>
  );
}
