import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import BlogFeaturedImage from "@/components/BlogFeaturedImage";

export const metadata: Metadata = {
  title: "Popular MySQL com dados brasileiros falsos no staging",
  description: "Aprenda a popular um banco MySQL de staging com CPF, CNPJ, endereços e PIX falsos e válidos usando FakeForge API — sem violar a LGPD.",
  openGraph: {
    title: "Popular MySQL com dados brasileiros falsos no staging",
    description: "Aprenda a popular um banco MySQL de staging com CPF, CNPJ, endereços e PIX falsos e válidos usando FakeForge API — sem violar a LGPD.",
    type: "article",
  },
  alternates: { canonical: "/blog/popular-mysql-dados-brasileiros-fake-staging" },
};

export default function Post() {
  return (
    <PageShell>
      <article className="max-w-2xl">
        <Link href="/blog" className="text-xs text-primary hover:underline mb-4 inline-block">
          ← Voltar ao blog
        </Link>
        <BlogFeaturedImage category="Tutoriais" title="Popular MySQL com dados brasileiros falsos no staging" className="mb-6" />
        <div className="mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight leading-tight">
            Popular MySQL com dados brasileiros falsos no staging
          </h1>
          <div className="flex items-center gap-3 text-xs text-muted mt-3">
            <time>20 de maio de 2026</time>
            <span>·</span>
            <span>12 min de leitura</span>
          </div>
        </div>

        <div className="prose-custom space-y-2 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">Usar dados reais de clientes no banco de staging é uma prática comum — e um passivo jurídico real. Este guia mostra como popular um banco MySQL de staging com CPF, CNPJ, endereços e chaves PIX estruturalmente válidos, sem tocar em nenhum dado de produção, usando a <Link href="/docs" className="text-primary hover:underline">FakeForge API</Link>.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Dados reais em staging violam a LGPD</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">O que diz o Art. 7º, IX da LGPD sobre bases de teste</h3>
          <p className="mb-4">A <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">Lei 13.709/2018 (LGPD)</a> exige base legal para qualquer tratamento de dado pessoal. O Art. 7º, IX autoriza tratamento para "proteção do crédito" e finalidades legítimas — não para popular bancos de teste. Ao copiar um dump de produção para staging, você está tratando CPF, e-mail e endereço sem base legal, em ambiente sem os controles de segurança do prod.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Riscos concretos: vazamento de PII em ambientes não-produtivos</h3>
          <p className="mb-4">Ambientes de staging têm superfície de ataque maior: credenciais menos protegidas, acesso liberado para terceiros (QA externo, parceiros, devs freelancers) e logs menos monitorados. Uma credencial de banco de staging comprometida expõe dados reais de clientes com as mesmas consequências legais de um vazamento em produção. A ANPD pode aplicar multas de até 2% do faturamento bruto do grupo, limitado a R$ 50 milhões por infração (LGPD Art. 52).</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Por que anonimização parcial não basta</h3>
          <p className="mb-4">Mascarar apenas CPF e e-mail enquanto mantém nome completo + endereço + histórico de compras cria um conjunto re-identificável. Estudos de re-identificação mostram que três atributos quase-identificadores (CEP de 8 dígitos, data de nascimento, sexo) são suficientes para identificar mais de 87% dos registros em bases populacionais. Anonimização eficaz exige geração sintética desde a origem — não truncamento de dados reais.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">O que são dados falsos estruturalmente válidos</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Diferença entre dado aleatório e dado válido (dígitos verificadores)</h3>
          <p className="mb-4">Um CPF gerado como sequência aleatória de 11 dígitos falha em qualquer validador. Sistemas de cadastro, gateways de pagamento e ERPs rejeitam na hora. Dado falso útil para teste é aquele que passa pelas mesmas validações que o dado real — dígitos verificadores corretos, DDD existente, CEP com prefixo válido para o estado informado.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">CPF com módulo 11, CNPJ com dois dígitos verificadores</h3>
          <p className="mb-4">O <Link href="/gerador-cpf" className="text-primary hover:underline">CPF</Link> usa dois dígitos verificadores calculados por módulo 11 sobre os nove primeiros dígitos. O <Link href="/gerador-cnpj" className="text-primary hover:underline">CNPJ</Link> aplica o mesmo algoritmo duas vezes com pesos diferentes. Gerar esses números na mão é viável, mas manter a lógica atualizada (a Receita Federal já alterou regras de validação) e garantir ausência de colisões com CPFs reais exige cuidado extra — daí o valor de uma API dedicada.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Endereço correlacionado: CEP, município, UF e DDD coerentes</h3>
          <p className="mb-4">Um endereço com CEP <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">01310-100</code> (Av. Paulista, SP) e DDD <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">71</code> (Brasília) é tecnicamente inválido para testes de sistemas que validam coerência geográfica. A FakeForge gera endereços onde CEP, bairro, município, UF e DDD estão correlacionados — útil para testar sistemas de frete, cálculo de ICMS interestadual e cobertura de entrega.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Arquitetura da solução: API + seed script + MySQL</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Visão geral do fluxo (FakeForge API → Node.js → MySQL)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-">{"FakeForge API (/api/generate)\n        │\n        ▼\n  Node.js seed script (TypeScript)\n   ├── fetchFakeData()      ← chama a API em lotes\n   ├── mapToRow()          ← transforma resposta em objeto plano\n   └── insertBatch()       ← INSERT parametrizado via mysql2\n        │\n        ▼\n   MySQL staging (usuarios, empresas, transacoes)"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Dependências necessárias: mysql2, node-fetch (ou fetch nativo Node 18+)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"npm install mysql2\nnpm install --save-dev tsx dotenv"}</code></pre>
          <p className="mb-4">Node 18+ inclui <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">fetch</code> nativo. Se usar Node 16, adicione <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">node-fetch@3</code>. O <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">tsx</code> permite rodar TypeScript diretamente sem compilar para CI.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Estrutura de pastas do projeto de seed</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-">{"seed/\n├── .env               # DATABASE_URL e FAKEFORGE_API_KEY\n├── schema.sql         # CREATE TABLE dos três domínios\n├── seed.ts            # script principal\n└── types.ts           # interfaces TypeScript dos payloads da API"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Configurar a FakeForge API para geração em lote</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Endpoint <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">/api/generate</code> — parâmetros type, quantity e format</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-">{"GET https://fakeforge.com.br/api/generate?type=pessoa&quantity=500&format=json"}</code></pre>
          <p className="mb-4">Os tipos relevantes para este seed: <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pessoa</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cep</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">empresa</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">pix</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">cartao</code>. A documentação completa de parâmetros está em <Link href="/docs" className="text-primary hover:underline">/docs</Link>.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Autenticação com API key (header <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">x-api-key</code>)</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"const response = await fetch(\n  `https://fakeforge.com.br/api/generate?type=${type}&quantity=${quantity}&format=json`,\n  {\n    headers: {\n      \"x-api-key\": process.env.FAKEFORGE_API_KEY ?? \"\",\n    },\n  }\n);"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Limites do plano gratuito (100 chamadas/dia) e quando usar o plano Dev</h3>
          <div className="my-6 rounded-xl bg-card border border-border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-card-hover"><tr><th className="text-left px-3 py-2 text-muted-foreground font-medium">Plano</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Chamadas/dia</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Batch máximo</th><th className="text-left px-3 py-2 text-muted-foreground font-medium">Preço</th></tr></thead><tbody><tr className="border-b border-border"><td className="px-3 py-2">Grátis</td><td className="px-3 py-2">100</td><td className="px-3 py-2">100 itens</td><td className="px-3 py-2">R$ 0</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Dev</td><td className="px-3 py-2">ilimitado</td><td className="px-3 py-2">10.000 itens</td><td className="px-3 py-2">R$ 29/mês</td></tr><tr className="border-b border-border"><td className="px-3 py-2">Team</td><td className="px-3 py-2">ilimitado</td><td className="px-3 py-2">10.000 itens</td><td className="px-3 py-2">R$ 79/mês</td></tr></tbody></table></div>
          <p className="mb-4">Para um seed de 500 registros por tabela, são ao menos 5 chamadas por tipo. Se o seed rodar diariamente no CI, o plano gratuito esgota rapidamente. O <Link href="/pricing" className="text-primary hover:underline">plano Dev</Link> cobre a maioria dos pipelines de staging individuais.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Criar o schema MySQL compatível com os campos gerados</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Tabela <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">usuarios</code>, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">empresas</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">transacoes</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"CREATE TABLE IF NOT EXISTS usuarios (\n  id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,\n  cpf           CHAR(11)        NOT NULL UNIQUE,  -- sem pontuação\n  nome          VARCHAR(120)    NOT NULL,\n  email         VARCHAR(200)    NOT NULL,\n  telefone      VARCHAR(20),\n  cep           CHAR(8)         NOT NULL,\n  logradouro    VARCHAR(200),\n  bairro        VARCHAR(100),\n  municipio     VARCHAR(100),\n  uf            CHAR(2)\n);\n\nCREATE TABLE IF NOT EXISTS empresas (\n  id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,\n  cnpj          CHAR(14)        NOT NULL UNIQUE,  -- sem pontuação\n  razao_social  VARCHAR(200)    NOT NULL,\n  cep           CHAR(8),\n  municipio     VARCHAR(100),\n  uf            CHAR(2),\n  banco_codigo  CHAR(3),\n  agencia       VARCHAR(10),\n  conta         VARCHAR(20)\n);\n\nCREATE TABLE IF NOT EXISTS transacoes (\n  id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,\n  usuario_id    INT UNSIGNED    NOT NULL,\n  chave_pix     VARCHAR(100),\n  valor         DECIMAL(12, 2)  NOT NULL,\n  banco_nome    VARCHAR(80),\n  cartao_numero CHAR(16),\n  cartao_bandeira VARCHAR(20),\n  created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (usuario_id) REFERENCES usuarios(id)\n);"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Tipos de coluna adequados</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(11)</code> para CPF e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(14)</code> para CNPJ armazenam sem pontuação — a pontuação é responsabilidade da camada de apresentação. <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">DECIMAL(12,2)</code> evita arredondamentos em valores monetários. Nunca use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">FLOAT</code> para dinheiro.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Script de seed completo em TypeScript</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Tipos e função de fetch</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// types.ts\nexport interface PessoaGerada {\n  nome: string;\n  cpf: string;        // \"12345678901\" — sem máscara\n  email: string;\n  telefone: string;\n}\n\nexport interface CepGerado {\n  cep: string;        // \"01310100\"\n  logradouro: string;\n  bairro: string;\n  municipio: string;\n  uf: string;\n}"}</code></pre>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"// seed.ts — fetchFakeData\nimport \"dotenv/config\";\n\nasync function fetchFakeData<T>(type: string, quantity: number): Promise<T[]> {\n  const url = new URL(\"https://fakeforge.com.br/api/generate\");\n  url.searchParams.set(\"type\", type);\n  url.searchParams.set(\"quantity\", String(quantity));\n  url.searchParams.set(\"format\", \"json\");\n\n  const res = await fetch(url.toString(), {\n    headers: { \"x-api-key\": process.env.FAKEFORGE_API_KEY ?? \"\" },\n  });\n\n  if (!res.ok) {\n    throw new Error(`FakeForge API error: ${res.status} ${await res.text()}`);\n  }\n\n  const json = await res.json();\n  return json.data as T[];\n}"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Script de seed completo com mysql2</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"import mysql from \"mysql2/promise\";\nimport type { PessoaGerada, CepGerado } from \"./types\";\n\nconst BATCH_SIZE = 100;\nconst TOTAL = 500;\n\nasync function seedUsuarios(conn: mysql.Connection) {\n  for (let offset = 0; offset < TOTAL; offset += BATCH_SIZE) {\n    const qty = Math.min(BATCH_SIZE, TOTAL - offset);\n\n    const [pessoas, enderecos] = await Promise.all([\n      fetchFakeData<PessoaGerada>(\"pessoa\", qty),\n      fetchFakeData<CepGerado>(\"cep\", qty),\n    ]);\n\n    const rows = pessoas.map((p, i) => [\n      p.cpf,\n      p.nome,\n      p.email,\n      p.telefone,\n      enderecos[i]?.cep ?? null,\n      enderecos[i]?.logradouro ?? null,\n      enderecos[i]?.bairro ?? null,\n      enderecos[i]?.municipio ?? null,\n      enderecos[i]?.uf ?? null,\n    ]);\n\n    const results = await Promise.allSettled(\n      rows.map((row) =>\n        conn.execute(\n          `INSERT IGNORE INTO usuarios\n             (cpf, nome, email, telefone, cep, logradouro, bairro, municipio, uf)\n           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,\n          row\n        )\n      )\n    );\n\n    const failed = results.filter((r) => r.status === \"rejected\").length;\n    if (failed > 0) console.warn(`Lote ${offset}: ${failed} falhas ignoradas`);\n\n    console.log(`Inseridos ${offset + qty} / ${TOTAL} usuários`);\n\n    // backoff linear simples entre lotes\n    await new Promise((r) => setTimeout(r, 200));\n  }\n}\n\nasync function main() {\n  const conn = await mysql.createConnection(process.env.DATABASE_URL ?? \"\");\n  try {\n    await seedUsuarios(conn);\n  } finally {\n    await conn.end();\n  }\n}\n\nmain().catch((err) => {\n  console.error(err);\n  process.exit(1);\n});"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">DICA:</strong> <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">INSERT IGNORE</code> descarta silenciosamente duplicatas de CPF, tornando o script idempotente sem precisar de lógica extra. Se quiser atualizar registros existentes em vez de ignorar, troque por <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ON DUPLICATE KEY UPDATE nome = VALUES(nome), email = VALUES(email)</code>.</blockquote>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Exportar direto em SQL com CREATE TABLE pronto</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Usar <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code> na API</h3>
          <p className="mb-4">Para volumes pequenos ou onboarding rápido, a FakeForge gera um arquivo <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">.sql</code> completo com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CREATE TABLE</code> e todos os <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">INSERT</code>s:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl -s \\\n  -H \"x-api-key: $FAKEFORGE_API_KEY\" \\\n  \"https://fakeforge.com.br/api/generate?type=pessoa&quantity=200&format=sql\" \\\n  -o seed_pessoas.sql\n\nmysql -h \"$DB_HOST\" -u \"$DB_USER\" -p\"$DB_PASS\" \"$DB_NAME\" < seed_pessoas.sql"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Quando preferir SQL direto vs script Node.js</h3>
          <p className="mb-4">Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code> para seeds pontuais, demos ou quando o ambiente não tem Node.js disponível. Use o script TypeScript quando precisar de lotes acima de 10 mil registros, correlação entre tabelas (foreign keys), ou transformações customizadas no dado antes de inserir.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Automatizar o seed no pipeline de CI/CD</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">GitHub Actions: job <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">seed-staging</code></h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-yaml">{"name: Seed Staging\n\non:\n  push:\n    branches: [main]\n\njobs:\n  seed-staging:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n\n      - uses: actions/setup-node@v4\n        with:\n          node-version: \"20\"\n          cache: \"npm\"\n\n      - name: Instalar dependências\n        run: npm ci --prefix seed\n\n      - name: Truncar tabelas e rodar seed\n        env:\n          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}\n          FAKEFORGE_API_KEY: ${{ secrets.FAKEFORGE_API_KEY }}\n        run: npx tsx seed/seed.ts\n\n      - name: Rodar testes e2e\n        run: npm run test:e2e"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Variáveis de ambiente como secrets</h3>
          <p className="mb-4"><code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">STAGING_DATABASE_URL</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">FAKEFORGE_API_KEY</code> vivem em <strong className="text-foreground">Settings → Secrets and variables → Actions</strong> no GitHub. Nunca coloque valores reais no <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">yaml</code> ou no repositório.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Idempotência</h3>
          <p className="mb-4">Adicione um step antes do seed para garantir tabelas limpas:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-ts">{"await conn.execute(\"SET FOREIGN_KEY_CHECKS = 0\");\nawait conn.execute(\"TRUNCATE TABLE transacoes\");\nawait conn.execute(\"TRUNCATE TABLE usuarios\");\nawait conn.execute(\"TRUNCATE TABLE empresas\");\nawait conn.execute(\"SET FOREIGN_KEY_CHECKS = 1\");"}</code></pre>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Validar a integridade dos dados inseridos</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Query de sanidade pós-seed</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-sql">{"-- Contagem por tabela\nSELECT 'usuarios'   AS tabela, COUNT(*) AS total FROM usuarios\nUNION ALL\nSELECT 'empresas',              COUNT(*)          FROM empresas\nUNION ALL\nSELECT 'transacoes',            COUNT(*)          FROM transacoes;\n\n-- Campos obrigatórios nulos\nSELECT COUNT(*) AS cpf_nulo    FROM usuarios  WHERE cpf IS NULL OR cpf = '';\nSELECT COUNT(*) AS cnpj_nulo   FROM empresas  WHERE cnpj IS NULL OR cnpj = '';\nSELECT COUNT(*) AS valor_zero  FROM transacoes WHERE valor <= 0;\n\n-- Faixa de valores monetários\nSELECT MIN(valor), MAX(valor), AVG(valor) FROM transacoes;"}</code></pre>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Checar CPF com a API</h3>
          <p className="mb-4">Para validar uma amostra dos CPFs inseridos, use o endpoint <Link href="/validar-cpf" className="text-primary hover:underline">/validar-cpf</Link>:</p>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"curl \"https://fakeforge.com.br/api/generate?type=validar-cpf&cpf=12345678901\""}</code></pre>
          <p className="mb-4">O mesmo vale para CNPJ via <Link href="/validar-cnpj" className="text-primary hover:underline">/validar-cnpj</Link>. Em produção, faça essa validação no seed script antes do INSERT — não depois.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Boas práticas de segurança no ambiente de staging</h2>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Nunca commitar API key</h3>
          <pre className="rounded-lg bg-background border border-border p-4 font-mono text-xs leading-6 my-4 overflow-x-auto"><code className="language-bash">{"# .gitignore\n.env\n.env.local\n*.env"}</code></pre>
          <blockquote className="border-l-4 border-accent pl-4 my-4 text-muted-foreground italic"><strong className="text-foreground">AVISO:</strong> Uma API key de FakeForge exposta no repositório pode ser usada por terceiros para esgotar sua cota ou gerar cobranças no seu plano. Ferramentas como <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">git-secrets</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">gitleaks</code> detectam esse tipo de vazamento antes do push.</blockquote>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Restringir acesso ao banco de staging</h3>
          <p className="mb-4">Configure o security group (AWS) ou firewall do MySQL para aceitar conexões apenas do range de IP do CI (GitHub Actions publica a lista de IPs em <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">https://api.github.com/meta</code>) e de VPN corporativa. Evite <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">0.0.0.0/0</code> mesmo em staging.</p>
          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Rotacionar dados falsos a cada ciclo de release</h3>
          <p className="mb-4">Dados sintéticos envelhecem: testes ficam acoplados a IDs fixos, seeds tornam-se fixtures implícitas. A cada release, execute <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">TRUNCATE + seed</code> para garantir que os testes e2e cubram combinações novas de dados.</p>
          <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Resumo</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 my-4"><li><strong className="text-foreground">Schema primeiro:</strong> defina <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(11)</code> para CPF, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">CHAR(14)</code> para CNPJ e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">DECIMAL(12,2)</code> para valores antes de rodar qualquer seed — tipos errados geram truncamentos silenciosos.</li><li><strong className="text-foreground">Use <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">INSERT IGNORE</code> ou <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">ON DUPLICATE KEY UPDATE</code></strong> para tornar o script idempotente e seguro para re-execução no CI.</li><li><strong className="text-foreground">Separe segredos do código:</strong> <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">DATABASE_URL</code> e <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">FAKEFORGE_API_KEY</code> como GitHub Secrets, nunca hardcoded ou commitados.</li><li><strong className="text-foreground">Valide após inserir:</strong> execute a query de sanidade e cheque CPFs com <Link href="/validar-cpf" className="text-primary hover:underline">/validar-cpf</Link> para detectar falhas de mapeamento antes dos testes e2e rodarem.</li><li><strong className="text-foreground">Para volumes pequenos, <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">format=sql</code> basta:</strong> baixe o arquivo e importe com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">mysql &lt;</code>; para seeds com correlação entre tabelas, use o script TypeScript com <code className="text-xs bg-background border border-border px-1.5 py-0.5 rounded">mysql2</code>.</li><li><strong className="text-foreground">Próximos geradores úteis:</strong> <Link href="/gerador-cartao" className="text-primary hover:underline">cartão de crédito com Luhn válido</Link>, <Link href="/gerador-pis" className="text-primary hover:underline">PIS/PASEP para sistemas de RH</Link> e <Link href="/gerador-titulo-eleitor" className="text-primary hover:underline">Título de Eleitor</Link> cobrem os tipos restantes em sistemas financeiros e de RH.</li></ul>
        </div>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-foreground mb-4">Perguntas frequentes</h2>
          <div className="space-y-3">
            <details key="Posso reutilizar o script de s" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Posso reutilizar o script de seed se meu database já tem dados?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Sim, com INSERT IGNORE ou ON DUPLICATE KEY UPDATE. Exemplo: `INSERT IGNORE INTO usuarios (cpf, nome, email...) VALUES (?, ?, ?)` descarta silenciosamente CPFs duplicados. Se quiser atualizar campos existentes, use `ON DUPLICATE KEY UPDATE nome = VALUES(nome)`. Backups automáticos recomendados.</p>
            </details>
            <details key="O que fazer se a API FakeForge" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">O que fazer se a API FakeForge retornar erro 429 (rate limit)?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Implemente backoff exponencial no script. Exemplo: comece com 1s, dobre a cada tentativa (1s, 2s, 4s, 8s). A biblioteca `p-retry` (npm) automação isso. Para plano gratuito, reduza batch de 100 para 50 ou migre para plano Dev se seed roda diariamente no CI.</p>
            </details>
            <details key="Como garantir que telefone e C" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Como garantir que telefone e CEP estão correlacionados corretamente?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">A API FakeForge retorna DDD válido baseado no CEP — não precisa validação extra. Mas se misturar `pessoa` + `cep` de lotes separados (como no artigo), ordem fica aleatória. Use um seed com `empresa` (que retorna pessoa + cep correlacionados) ou indexe por nome para casar manualmente.</p>
            </details>
            <details key="É seguro rodar seed em paralel" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">É seguro rodar seed em paralelo com testes e2e contra o mesmo DB?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Não. Use TRUNCATE antes do seed atomicamente. Melhor: rode seed em banco limpo antes dos testes (GitHub Actions: `seed-staging` → `test-e2e`). Se precisa testar dados dinâmicos, crie um usuário fixture por teste (INSERT com dados únicos do teste, limpe com `teardown`).</p>
            </details>
            <details key="Quanto custa gerar 10 mil regi" className="group border border-border rounded-lg">
              <summary className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-card-hover transition-colors">
                <span className="text-sm font-medium text-foreground">Quanto custa gerar 10 mil registros por mês no plano Dev?</span>
                <span className="text-muted group-open:rotate-45 transition-transform text-lg leading-none">+</span>
              </summary>
              <p className="px-4 pb-3 text-sm text-muted-foreground">Plano Dev é R$ 29/mês com limite de até 10 mil itens por request (ilimitado número de requests). 10 mil registros = 1 chamada. Custo fixo R$ 29/mês independente do volume. Economicamente viável para staging contínuo. Team é R$ 79/mês com features extras (suporte, SLA).</p>
            </details>
          </div>
        </section>
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"Posso reutilizar o script de seed se meu database já tem dados?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Sim, com INSERT IGNORE ou ON DUPLICATE KEY UPDATE. Exemplo: `INSERT IGNORE INTO usuarios (cpf, nome, email...) VALUES (?, ?, ?)` descarta silenciosamente CPFs duplicados. Se quiser atualizar campos existentes, use `ON DUPLICATE KEY UPDATE nome = VALUES(nome)`. Backups automáticos recomendados.\"}},{\"@type\":\"Question\",\"name\":\"O que fazer se a API FakeForge retornar erro 429 (rate limit)?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Implemente backoff exponencial no script. Exemplo: comece com 1s, dobre a cada tentativa (1s, 2s, 4s, 8s). A biblioteca `p-retry` (npm) automação isso. Para plano gratuito, reduza batch de 100 para 50 ou migre para plano Dev se seed roda diariamente no CI.\"}},{\"@type\":\"Question\",\"name\":\"Como garantir que telefone e CEP estão correlacionados corretamente?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"A API FakeForge retorna DDD válido baseado no CEP — não precisa validação extra. Mas se misturar `pessoa` + `cep` de lotes separados (como no artigo), ordem fica aleatória. Use um seed com `empresa` (que retorna pessoa + cep correlacionados) ou indexe por nome para casar manualmente.\"}},{\"@type\":\"Question\",\"name\":\"É seguro rodar seed em paralelo com testes e2e contra o mesmo DB?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Não. Use TRUNCATE antes do seed atomicamente. Melhor: rode seed em banco limpo antes dos testes (GitHub Actions: `seed-staging` → `test-e2e`). Se precisa testar dados dinâmicos, crie um usuário fixture por teste (INSERT com dados únicos do teste, limpe com `teardown`).\"}},{\"@type\":\"Question\",\"name\":\"Quanto custa gerar 10 mil registros por mês no plano Dev?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Plano Dev é R$ 29/mês com limite de até 10 mil itens por request (ilimitado número de requests). 10 mil registros = 1 chamada. Custo fixo R$ 29/mês independente do volume. Economicamente viável para staging contínuo. Team é R$ 79/mês com features extras (suporte, SLA).\"}}]}",
        }}
      />
    </PageShell>
  );
}
